.github/CODEOWNERS
.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md

The useful change here is adding CODEOWNERS, which should make the CCF team a reviewer for every PR by default.
I've also added our CODE_OF_CONDUCT and CONTRIBUTING guidelines under .github - they're already in the README, but having them in a standard location makes them accessible to automated tools.

Add GitHub standards files

---

src/genesisgen/main.cpp
tests/start_network.py

Add general `start_network.py`. This uses the e2e Python infrastructure to spin up a network, then leaves it alive until a KeyboardInterrupt. The following will start a 2-node network running the logging app:
```
$ python ../tests/start_network.py -p libloggingenc -q
```
GenesisGen's slurp_certs becomes optional like the slurps in `files.h` - `ra_ca.pem` is really optional, the default sample ca is copied by the other e2e tests but can be omitted.

Add start_network.py

---

check-format.sh
src/apps/logging/logging.cpp
src/clients/logging_client.cpp
src/crypto/hash.cpp
src/crypto/symmkey.cpp
src/host/test/ledger.cpp
src/kv/test/kv_bench.cpp
src/kv/test/kv_contention.cpp
src/kv/test/kv_serialisation.cpp
src/kv/test/kv_test.cpp
src/luainterp/test/luakv.cpp
src/node/test/history.cpp
src/node/test/history_bench.cpp
src/node/test/merkle_bench.cpp
src/tls/test/bench.cpp
src/tls/test/main.cpp

Our check_format script wasn't actually running on .cpp files (due to the missing `-or` before the `"*.c"` arg). Now it is.
Also needed to remove the suffix for `--assume-filename`. Formatting `kv.h.cpp` seems to be fine, but `symmkey.cpp.cpp` isn't (`symmkey.h` is no longer recognised as the special header that gets its own line).

Check cpp format

---

src/raft/raft.h
src/raft/test/main.cpp

send_append_entries() will be called when the collective transaction size exceeds the byte limit, but entries will be batched based on the tx_threshold which is calculated each time based on the number of transactions and their average size.

Send append entries batched by tx count instead of byte count

---

CMakeLists.txt
src/host/ledger.h
src/node/test/merkle_bench.cpp

Segfaults were caused by linking liboecore.a, which results in rather unaligned memory being allocated when running outside an enclave it seems (not entirely sure why that's the case). This causes the aes asm implementation to fail on movdqu in turn.
As discussed @wintersteiger, it is possible that some stricter pre-conditions could be added in the merkle tree impl, in the future.

Fix Merkle Tree benchmark

---

src/kv/kv.h

Small tweak to clear the KV store's rollback counter when `clear()` is called on the whole store.

Clear new rollback counter in store clear()

---

cmake/common.cmake
src/host/main.cpp
tests/infra/remote.py
tests/quote_verification.py

While investigating the issue with large hanging RPCs (fixed in https://github.com/microsoft/CCF/pull/41), I've noticed that very large (10kB) all-zero quotes were dumped to disk by the virtual host (`cchost.virtual`) and passed around in the genesis transaction, etc. This PR removes quotes altogether when using virtual enclaves.
I've also moved the quote file dump before the quote verification so that we can hopefully debug what is wrong with the quote (e.g. `OE_MISSING_CERTIFICATE_CHAIN`) if the verification fails.

No quotes with virtual

---

CMakeLists.txt
cmake/common.cmake
cmake/crypto.cmake
cmake/secp256k1.cmake
src/raft/test/driver.h

This adds a VIRTUAL_ONLY flag to cmake, to allow building virtual enclaves only and running only the corresponding tests. The ulterior motive for this change is to have a fully public CI, which can run on public executors.
Note that this does not allow for a completely OpenEnclave-free build, because we still require the oeedger8r, the files it produces from the EDL and some OpenEnclave headers. What is does allow though, importantly, is builds against the binary release of OpenEnclave (.deb packages), on a machine without SGX.

"Virtual only" build

---

.vsts-ci-templates/build_and_test.yml
.vsts-ci-templates/build_and_test_with_san.yml
.vsts-ci.yml
cmake/common.cmake
src/host/main.cpp
tests/tests.sh

Allows replacing:
```
python -m venv env
source env/bin/activate
pip install -r ../tests/requirements.txt
ctest ARGS
```
with
```
./tests.sh ARGS
```

A simple test wrapper for ctest

---

.gitignore
src/host/dns.h
src/host/tcp.h

Our e2e tests stopped working on some machines, as `start_network` requests were being sent before the  nodes are listening. We could add paths to check each connection's status, and only dump the cert files (indicating we're ready) inside the uv loop once we're _actually_ listening. This fix is simpler - when we `listen` for incoming TCP connections, resolve and bind synchronously rather than asynchronously, so the return code indicates the complete result.

TCP listens resolve synchronously

---

tests/coverage/add_perf_summary.py
tests/coverage/generate_coverage.sh

Adds a line at the end of the perf summary csv file, so overall line coverage percentage will be displayed as a graph along with the performance graphs

Adding coverage to perf summary csv

---

src/enclave/tlsendpoint.h
tests/e2e_logging.py

Fixed issue with large outbound messages. If they where larger than mbedtls_ssl_get_max_frag_len then the full message would not be sent but part of it would remain in the pending_write vector. Thanks @eddyashton for the help with this.

large outbound messages

---

src/kv/kv.h
src/kv/kvtypes.h
src/kv/replicator.h
src/node/nodestate.h
src/node/rpc/forwarder.h
src/node/rpc/frontend.h
src/node/rpc/test/frontend_test.cpp
src/node/test/history.cpp
src/node/test/history_bench.cpp
src/raft/raft.h
tests/infra/ccf.py
tests/recovery.py

I have added some unit tests for the new frontend forwarding capability in `frontend_test.cpp`.
In the process, I had to change `raft` in `frontend.h` to be of type `kv::Replicator` which involved defining a bunch of virtual methods in all sub-classes that derive from `kv::Replicator`. We also found out an issue with the `NullReplicator` used in the very first stage of the recovery - which I have now removed as it was not used anyway.

Add unit test for forwarder and remove NullReplicator

---

.codecov.yml
.vsts-ci-templates/build_and_test.yml
README.md
tests/coverage/generate_coverage.sh

This PR adds support for Codecov as a code coverage tool, which has a nice integration with GitHub. 
For each PR, there should be a code coverage report automatically published as a comment on GitHub. I've also added a badge at the top of `README.md`.

Adding support for Codecov

---

.codecov.yml

It turns out, the new `.codecov.yml` file was not valid (my bad!). It meant that [the default style was being used](https://docs.codecov.io/docs/codecov-yaml#section-do-i-need-a-codecov-yml-file-).

Fix .codecov.yml as it is not currently valid

---

src/enclave/enclave.h
src/enclave/rpcendpoint.h
src/enclave/rpchandler.h
src/enclave/rpcmap.h
src/enclave/tlsendpoint.h
src/enclave/tlsframedendpoint.h
src/node/entities.h
src/node/rpc/forwarder.h
src/node/rpc/frontend.h
src/node/rpc/nodefrontend.h
tests/e2e_logging.py

Only the `USERS` frontend used to be forwarded. This PR adds support for forwarding all frontends (i.e. `MEMBERS`, `MANAGEMENT` and `NODES`) by passing a new `ActorsType` enum (indicating which frontend to forward to) to the forwarded command.
I've added a new `RpcMap` class that handles the conversion between a string (`host` in `rpcendpoint.h`) and the `ActorsType` enum that uniquely identifies each frontend. Please let me know if there's a better way to do this.
**Also:**
- Changed some logs to `LOG_TRACE` as they are too verbose for a debug build.
- Simplified some things in `nodefrontend.h` as 1) we don't need to check whether we are leader (it is handled at the generic `frontend.h` level) and 2) the joining node's id is already passed in the `args` to the handler.

Support for forwarding for all frontends

---

.vsts-ci-templates/build_and_test.yml
CMakeLists.txt
cmake/common.cmake
tests/coverage/generate_coverage.sh
tests/infra/remote.py

Code coverage from end to end tests, tagged accordingly (so we can display only unit coverage or only end to end coverage). This should help us find any dead code we may have.
At the moment, this is only for one end to end test, a bit more file mangling is necessary to aggregate the rest of them (recovery and election mainly).

End to end coverage

---

.codecov.yml

As it will be very hard to achieve 100% code coverage (because of different types of curve, etc.), this reduces the threshold for the green code coverage badge to 85%.

Coverage badge is now green if coverage > 85%

---

CMakeLists.txt
cmake/common.cmake

The end-to-end tests get coloured logs thanks to loguru, but through CTest they must additionally go through unbuffer. This makes that support more widely available (from common.cmake), and enables it for the small_bank perf tests.

Use unbuffer for perf tests

---

.vsts-ci.yml
tests/e2e_logging.py

If the static_checks fail, the build will fail. This change causes static_check failures to kill the build _early_, rather than after ~7 minutes when another test has failed and an agent is free.
I think this is the behaviour we want for PRs, and don't think its too strong a restriction on other builds.

Static checks first

---

src/apps/logging/logging.cpp
src/node/rpc/frontend.h
src/node/rpc/test/frontend_test.cpp

Roll schema generation/provision into `install`, rather than requiring a separate `register` call with the same method name.

Install with schema

---

Dockerfile
getting_started/setup_vm/D-oe.yml
getting_started/setup_vm/local_skip_dependencies

This is for #101, and also to hopefully dispatch some of the jobs in the private CI to public executors and relieve our overloaded VMs.
https://hub.docker.com/r/ccfciteam/ccf-ci-18.04/tags

Add docker file for public CI

---

src/ds/champmap.h
src/ds/rbmap.h
src/ds/test/map_bench.cpp
src/kv/kv.h

I noticed our kv map foreach implementations were taking copies of the functor, with potentially expensive copy of the captured args. I've changed these to use universal forwarding, and added a benchmark of foreach.
Sample of new benchmark before:
```
foreach:
===============================================================================
Name (baseline is *)   |   Dim   |  Total ms |  ns/op  |Baseline| Ops/second
===============================================================================
bench_rb_map_foreach * |     512 |     9.366 |   18292 |      - |    54667.0
bench_champ_map_foreach |     512 |     0.328 |     641 |  0.035 |  1559074.3
bench_rb_map_foreach * |    1024 |    37.663 |   36780 |      - |    27188.6
bench_champ_map_foreach |    1024 |     1.007 |     983 |  0.027 | …
```

Avoid unnecessary copies of lambda capture - universal forwarding

---

CMakeLists.txt
src/host/tcp.h

If node removal happens before an on_resolve() callback has fired, we can be trying to use a deleted object.
This was caught by the UBSan: https://circleci.com/gh/microsoft/CCF/198
```
../src/host/tcp.h:309:41: runtime error: member call on address 0x613000002a40 which does not point to an object of type 'asynchost::TCPImpl'
34: 0x613000002a40: note: object has invalid vptr
34:  27 00 80 19  29 00 00 20 00 00 00 00  40 2a 00 00 30 61 00 00  e0 37 de 16 be 7f 00 00  0c 00 00 00
34:               ^~~~~~~~~~~~~~~~~~~~~~~
34:               invalid vptr
34: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/host/tcp.h:309:41 in 
34: 
```
Long term it would be preferable to introduce a ref counting scheme to avoid this while retaining async resolve, but for now this fixes the …

Workaround resolve race

---

src/node/rpc/frontend.h
src/node/rpc/memberfrontend.h
src/node/rpc/test/frontend_test.cpp
tests/schema.py

Noticed a bug caused by my schema changes.
In `install(MemberProcs::ACK, ack, Write, false);`, the false is converted to `json` and used as the params schema. The fix is to use an enum rather than bool for the forwardability status. All the calls to `install` should be unambiguous now.
This also extends schema.py to fetch schemas from all frontends, though currently only the common RPCs have defined schemas.

Fix forwarding status for non-forwardable RPCs

---

cmake/common.cmake

Follow up from https://github.com/microsoft/CCF/pull/152: we also need to tell python to ignore quotes for real enclaves when OE was not build with SGX.

Disable quote for non-sgx machines with real enclaves

---

samples/apps/smallbank/smallbank.cmake
samples/apps/smallbank/tests/verify_small_bank_short.json

The iterations count with performance test with signature used to be very low for historical reasons. I have bumped this up to `50000` so that we get more accurate performance results.

Increase tx count for performance test with signature

---

tests/infra/remote.py

When builds are interrupted on DevOps, we sometimes end up with zombie cchost processes running on the executors. That seems to be caused by the Python orchestration being killed in a way that does not give it the opportunity to terminate its children.
This change configures children to set themselves a SIGTERM if their parent dies (SET_PR_PDEATHSIG), which should fix the problem. Another solution may be to run the tests (or indeed the whole job) in a container. This seems to be very slow on DevOps at the moment though.

Send SIGTERM to cchost if parent dies

---

src/node/rpc/frontend.h
src/node/rpc/test/membervoting_test.cpp

According to the [JSON-RPC 2.0 Spec](https://www.jsonrpc.org/specification#parameter_structures), `params` may be omitted, but if present it must be an object or list. We did not match this spec. We allowed `"params": null`, and if `params` was _missing_ we returned an error (`"[INVALID_REQUEST}: Invalid params."`).
The error was caused by a notable gotcha in `nlohmann::json`: when using `operator[]` on a const object, a missing key results in [undefined behaviour](https://github.com/nlohmann/json/blob/1126c9ca74fdea22d2ce3a065ac0fcb5792cbdaf/single_include/nlohmann/json.hpp#L15984). This is subtly different from calling on a non-const object, where this would return `null` (and modify the object).
This PR modifies `RpcFrontend::process_json()` to use method `at()` rather than …

Params are optional

---

CMakeLists.txt
cmake/common.cmake

This PR adds support for PBFT with real enclave (it was previously only supporting virtual enclaves). 
The changes are:
- Change in the linking order for real enclaves. Otherwise, PBFT will try to use Open Enclave's mbedtls for its underlying crypto function (which we don't want, as we need the functions in `evercrypt.enclave`).
- Move the new `addnode` end-to-end test so that it is only built when PBFT is disabled (as it makes use of dynamic configuration).

CCF + PBFT in real enclave

---

sphinx/source/logging_lua.rst
src/apps/luageneric/luageneric.cpp
src/apps/luageneric/luageneric_test.cpp
src/node/scripts.h

Previously we supported 2 ways of implementing lua handlers for the luageneric app. This simplifies things by removing the older method.
We no longer support a special script at key `__default` which handles all RPCs, instead we require entries in the `APP_SCRIPTS` table for each supported method.
As a concrete example, if we previously had an app with `get` and `set` RPCs like this:
```
return {
__default = [[
tables, gov_tables, caller_id, method, params = ...
env = {
error_codes = {
INVALID_PARAMS = -32602
}
}
function env.jsucc (result)
return {result = result}
end
function env.jerr (code, message)
return {error = {code = code, message = message}}
end
handler = {}
function handler.get()
msg = tables.pub0:get(params.id)
if not msg then
return env.jerr(env.error_codes.INVALID_PARAMS, …
```

Remove special lua __default script

---

sphinx/source/logging_lua.rst
src/apps/logging/logging.lua
src/apps/luageneric/luageneric.cpp
src/apps/luageneric/luageneric_test.cpp
src/clients/logging_client.cpp
src/luainterp/luaargs.h
src/luainterp/luainterp.h
src/luainterp/luajson.h
src/luainterp/luauserdata.h
src/luainterp/luautil.h
src/node/rpc/frontend.h
src/node/scripts.h
tests/loggingclient.py

Previously if we changed the arguments passed to Lua method handlers then existing apps would likely return obscure errors. Either they'd try to access a `nil` parameter, or try to use a parameter of the wrong type.
This change mitigates that. Lua arguments are passed in a named table, and looking up any missing keys in that table will result in a readable error.
For example if we changed the arguments from `(int a, string b)` to `(string c)`, under the old scheme:
```
tables, gov_tables, a, b = …
x = a + 5 // ERROR: attempt to perform arithmetic on a string value
s = b + "_foo" // ERROR: attempt to perform arithmetic on a nil value
```
Under the new
```
tables, gov_tables, args = …
x = args.a + 5 // ERROR: 'a' is not a lua argument
s = args.b + "_foo" // ERROR: 'b' is not a lua argument …
```

Harden Lua handler API

---

.github/CONTRIBUTING.md
README.md
getting_started/setup_vm/D-oe.yml
sphinx/source/getting_started.rst

Added brief description of CI requirements + advice on passing static_checks to our contributing guidelines.
Update links to OE repo, which has moved to the [openenclave org](https://github.com/openenclave) on GitHub.

Update contributing guide and OpenEnclave links

---

src/node/rpc/test/membervoting_test.cpp
src/runtime_config/gov.lua

Hi!
I realized that gov.lua was wrongly considering the non-existing table `scripts` as sensitive; should be `govscripts` instead. 
Added a corresponding test.

Fix sensitive table name in gov.lua

---

.vsts-ci.yml

This is now done in CircleCI, no reason to do it twice.

Remove static_checks from VSTS

---

.vsts-ci.yml

Using [yaml schedules](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers) to start CI builds every morning, Monday to Friday, shortly after the CI machines have started. This ensures we get regular perf results and early warning when external dependencies are broken.

Scheduled CI build

---

.vsts-ci.yml

The CI `cron` time is currently fixed to UTC, whereas the CI pool is restarted in London time. Scheduling it earlier means it will be queued, and should then run when the VMs start, regardless of daylight savings.

Schedule morning CI earlier

---

.vsts-gh-pages.yml
sphinx/source/rpc_api.rst
sphinx/source/start_network.rst
src/clients/client.cpp
tests/infra/ccf.py

Update `--req` options to the client binary with curl-style syntax, allowing load-from-file or specify-on-command-line.
So you can write:
```
$ ./client --pretty-print userrpc --req @listMethods.json
```
or
```
$ ./client --pretty-print userrpc --req '{"id": 1, "jsonrpc": "2.0", "method": "listMethods"}'
```

Allow RPC body to be given on command line

---

cmake/common.cmake

Because the patched library was build with `add_custom_target`, we were running it every time we call ninja, even when there's no changes.
This changes to `add_custom_command`, so the patched library is only reproduced when its dependencies change.
```
$ touch ../src/apps/logging/logging.cpp
$ ninja -vvvv -d explain
ninja explain: output CMakeFiles/loggingenc.dir/src/apps/logging/logging.cpp.o older than most recent input ../src/apps/logging/logging.cpp (1562149069 vs 1562149257)
ninja explain: CMakeFiles/loggingenc.dir/src/apps/logging/logging.cpp.o is dirty
ninja explain: libloggingenc.so is dirty
ninja explain: libloggingenc.patched.so is dirty
ninja explain: libloggingenc.patched.so.signed is dirty
ninja explain: CMakeFiles/loggingenc.patched_signed is dirty
ninja explain: …
```

Don't patch unnecessarily

---

src/node/rpc/memberfrontend.h
tests/addnode.py
tests/infra/ccf.py

#208 We prevent adding nodes with a host:port combination that already exists.

Not allowing adding nodes with a host:port combination that already exists

---

sphinx/source/governance.rst
sphinx/source/index.rst
sphinx/source/ledger.rst

I noticed that we did not have any user documentation for governance. This PR adds a page of sphinx documentation for it. 
Only the most basic governance operations are described for now (using `memberclient`) but we should plan to add more documentation for this soon (e.g. how to add a new code version, how to run any arbitrary proposal).

Adding basic documentation for governance

---

src/ds/champmap.h
src/ds/test/map_bench.cpp
src/ds/test/map_test.cpp
src/genesisgen/genesisgen.h
src/kv/kv.h
src/kv/test/kv_test.cpp
src/luainterp/luakv.h
src/node/nodestate.h
src/node/rpc/frontend.h
src/node/rpc/memberfrontend.h

KV foreach callback functions can now control whether to continue iterating by returning true (continue) or false (stop).

Allowing to break KV foreach loops

---

src/node/nodestate.h

Follow-up on this is #226. Part of that is making the max tree size customistable (probably a cli argument), so we can make sure we've done at least one in each recovery.

Compact the right history where recovering private ledger

---

src/tls/keypair.h
tests/votinghistory.py

Recovering the public key from the signature is extremely inefficient, so we revert to using the public key from the PEM.
The recoverable public key verification will still be tested the voting history test.

Reverted secp256k1 verification to use public key from cert

---

src/node/networksecrets.h
src/node/nodestate.h
src/node/rpc/memberfrontend.h
src/node/seal.h
src/tls/context.h
src/tls/entropy.h
src/tls/intel_drng.h
src/tls/keyexchange.h
src/tls/keypair.h

Choosing the random number generator during compilation does creates a problem running the code on hardware that is different than the one that the code was compiled on (RDRAND and RDSEED instructions must be supported).
The ideal solution is to have this behavior handled by mbedtls, therefore, this solution should be temporary.
There are now two implementation of the pure virtual Entropy class, and the correct one can be retrieved using the _tls::create_entropy_ function.
Note: _tls::create_entropy_ returns a shared_ptr since the IntelDRNG implementation (which is the commonly used one) is stateless, and there is no need to instantiate it for each call.

Entropy detection during runtime

---

CMakeLists.txt
src/clients/client.cpp
src/clients/memberclient.cpp
src/ds/msgpack_adaptor_nlohmann.h
src/kv/msgpackserialise.h
src/node/members.h
src/node/proposals.h
src/node/rawsignature.h
src/node/rpc/memberfrontend.h
src/node/rpc/test/membervoting_test.cpp
src/node/script.h
src/node/signatures.h
src/node/test/msgpack_serialization.cpp
tests/tests.sh

Some of our uses of `MSGPACK_DEFINE` were not serialising members inherited from the base type. In particular we were not fully serialising `OpenProposal`s, resulting in differences in the KV across replicas. This resulted in #214.
The fix is simple - adding `MSGPACK_BASE(T)` entries. In the case of `OpenProposal` I decided it was simpler to remove the inheritance (the fields it shares with `Proposal::In` are coincidental, not a logical hierarchy). To serialise the `nlohmann::json` field I needed to define msgpack-c's `pack` and `convert` structs, and using _that_ we can replace the special case handling of json objects in `msgpackserialise.h`.
I've added `msgpack_serialization_test` which roundtrips examples of all these types, but we don't have a way to enforce that new fields are …

Serialise base members and nlohmann::json with msgpack-c

---

src/tls/entropy.h

We pass &drbg to mbedtls_ctr_drbg_random, while &drbg used to be == this when there was no vtable on the class, but now it is not.
The rng function on line 51 expects the callback data that was passed on line 45, which in the old case, MbedtlsEntropy == &MbedtlsEntropy::drbg, so the cast would succeed. Now it obviously can't.

Fix mbedtls callback argument cast

---

tests/addnode.py
tests/code_update.py
tests/infra/ccf.py
tests/recovery.py

We previously used the C++ client app for most `joinNetwork` requests, relying on the `joinNetwork.json` file written during genesis. If we have any additional elections during the test then these joins will fail. This replaces the use of `joinNetwork.json` with a direct RPC from the Python client, retrieving the current leader just before sending a freshly populated join request.
`networkcert.pem` is read once when the network is created, then stored on the Python `Network` instance. If we called `startNetwork` in the same way (directly from Python) we could simplify this even further and store the contents from the RPC response, but we probably still want to dump the resulting cert to file and need to re-examine how we generate the initial node's ID.
This fixes #256.

Query network for current leader before sending joinNetwork

---

sphinx/source/logging_lua.rst
src/apps/logging/logging.lua
src/apps/luageneric/luageneric.cpp
src/apps/luageneric/luageneric_test.cpp
src/luainterp/txscriptrunner.h

Rather than manually repeating the possible RPC errors in every lua app, and trying to keep these up-to-date, we automatically fill in the `env.error_codes` field from `luageneric`. This also means the `env` table is created from C++, and should not be created by apps.
While doing this I added access to the logging macros in Lua, with the same names they have in C++.
Resolves #265, though ignores the similar duplication in Python.

Automatically populate error codes in Lua

---

check-format.sh
samples/perf_client/perf_client.h
sphinx/source/recovery.rst
sphinx/source/rpc_api.rst
sphinx/source/schemas/add_node_params.json
sphinx/source/schemas/setRecoveryNodes_params.json
sphinx/source/start_network.rst
src/clients/client.cpp
src/clients/logging_client.cpp
src/clients/memberclient.cpp
src/ds/cli_helper.h
src/genesisgen/main.cpp
src/host/main.cpp
src/node/nodes.h
src/node/nodestate.h
src/node/rpc/frontend.h
src/node/rpc/memberfrontend.h
tests/e2e_scenarios.py
tests/infra/ccf.py
tests/infra/remote.py
tests/infra/remote_client.py
tests/infra/runner.py
tests/loggingclient.py
tests/start_network.py

As we now use the node-to-node connections for more than just raft (i.e. PBFT, forwarding), the CLI options and documentation are no longer raft-specific.

Raft host/port rename

---

.vsts-ci-no-sgx.yml
.vsts-ci.yml
tests/requirements.txt

It seems that our builds (except for the GitHub pages) were not triggered for commits on `master`. I guess there was something manually configured on the old jobs that made it build on `master`? 
This should also be the first PR since the performance tests on `master` have run. Let's see how `cimetrics` display the report below! :point_down:

Build SGX and non-SGX for every commit on master

---

.azure-pipelines.yml
docker/Dockerfile.nosgx
docker/Dockerfile.sgx
getting_started/setup_vm/D-oe.yml

This had been dropped from the 0.6 upgrade, along with the custom mbedtls build. I've also made a small change to the dockerfiles that should reduce the image size somewhat.

Remove Spectre mitigations from OE build

---

tests/infra/remote.py

This completes #303.
For example, if a node comes under the influence of supernatural forces, we should see something like this:
```
42: 2019-08-19 14:44:23.615 | INFO     | infra.jsonrpc:log_request:216 - [127.45.115.244:53293] #1 getSchema {'method': 'LOG_get'} (node 0 (user))
42: 2019-08-19 14:44:24.725 | INFO     | infra.remote:stop:408 - [127.45.115.244] closing
42: 2019-08-19 14:44:24.732 | ERROR    | infra.remote:log_errors:70 - /data/src/CCF/build/workspace/schema_tests_0/out: 2019-08-19 14:44:23.538558        [fail ] ../src/host/rpcconnections.h:179     | Cannot close id 4: does not exist
42: 2019-08-19 14:44:24.733 | ERROR    | infra.remote:log_errors:70 - /data/src/CCF/build/workspace/schema_tests_0/out: 2019-08-19 14:44:23.625556        [fatal] ../src/host/enclave.h:120 …
```

Log end of output when nodes crash

---

src/enclave/enclavetypes.h
src/enclave/rpcclient.h
src/enclave/rpcsessions.h
src/node/nodestate.h

https://github.com/microsoft/CCF/pull/318 removed the need for the feature introduced in https://github.com/microsoft/CCF/pull/100 since the join protocol is no longer triggered by an RPC (it happens automatically when a node starts up in `join`).
As such, I have removed this feature from the `RPCClient` class as it is no longer needed/wouldn't be tested anymore. If we need it again at some point in the future, it will be a quick job to introduce it back.

RPC Client no longer needs to be synchronous

---

.azure-pipelines.yml

Testing the fixed AzureCLI step from https://github.com/microsoft/azure-pipelines-tasks/issues/11137#issuecomment-526057911

Remove container workaround to test newly uploaded AzureCLI

---

.clang-format
.dockerignore
cmake/common.cmake
getting_started/setup_vm/roles/ccf_dependencies/tasks/install.yml
sphinx/source/getting_started.rst
tests/coverage/generate_coverage.sh

CCF doesn't depend on Boost - remove it from ansible playbooks, and references elsewhere.

Remove boost dependency

---

tests/infra/ccf.py
tests/infra/remote.py

When manually spinning up CCF nodes via our e2e python infra, the files created at node startup (node certificate, network certificate) were only copied over to the local directory for clients to use when using non-debug nodes. This PR fixes the behaviour so that the files are also copied over when manually spinning up debug nodes (i.e. `-d <node_id>`).

Fix debug e2e test issue

---

src/node/nodestate.h
src/node/rpc/frontend.h

The changes brought by the light-genesis mean that 1) the user connections are only opened once the service table changes from `OPENING` to `OPEN` are globally committed and 2) we now use the member frontend (requiring signed requests) to open the network. 
We actually do not use global hooks in PBFT yet (see https://github.com/microsoft/CCF/issues/373) so for now, we hard code the opening of the user frontend in `setup_pbft()`.

Fix e2e ePBFT test

---

tests/e2e_logging.py

The notifications checker currently fails on the no-sgx CI as the notifications are not properly formatted/framed yet. 
As the plan is to support libcurl on the host to send these notifications and since CCF does not rely on the notifier feature yet, I've disabled the only test we have for this for now.

Disable notifications e2e check

---

cmake/common.cmake
getting_started/setup_vm/roles/ccf_dependencies/vars/common.yml
sphinx/source/getting_started.rst
src/host/main.cpp
src/host/notifyconnections.h
tests/e2e_logging.py
tests/infra/notification.py

In cchost, when sending notifications, we now send them as individual HTTP POST requests rather than raw over TCP. This uses libcurl. We create a single multi-handle, create individual easy-handles for each request, add those to the multi-handle, and then perform/pump/advance the multi-handle once each uv loop.
There's probably some improvements still to be made here:
- fiddling with `CURLOPT`s to limit the amount of work done in each `curl_multi_perform`
- adding more appropriate headers to the notifications
And relatedly, possible extensions to the notification system:
- app dictating target address, per-notification
- handling HTTP response to our notifications, with retries or informing the app or at least detailed logging
The Python changes to run a simple HTTP server are …

Use libcurl on the host to send HTTP notifications

---

src/enclave/enclave.h
src/node/nodestate.h
src/node/notifier.h
tests/e2e_logging.py
tests/e2e_logging_pbft.py
tests/governance.py
tests/infra/ccf.py

To avoid duplicate notifications while offering some robustness against node failure, this sends notifications only from the leader node.
Some associated changes to the Python tests:
- only `e2e_logging` actually uses the notification server, so other tests don't create one unnecessarily
- a notifications-enabled `Checker` confirms that it receives increasing commit numbers

Only send notifications from leader

---

src/clients/tls_client.h
src/enclave/rpcsessions.h
src/enclave/tlsendpoint.h
src/host/proxy.h
src/host/rpcconnections.h
src/tls/msg_types.h

Resolves https://github.com/microsoft/CCF/issues/387. 
Connections between the host and the enclave are now properly terminated, even when the TLS client terminates the connection gracefully. Note that when the TCP socket is invalidated, no more messages are written to and from the enclave.
Sequence diagram of new behaviour:
Note that when the TCP connection is closed from the host, no more messages are written to the enclave (there might still be messages to write out to the peer) and the following logic applies:

Fix spurious fail log messages

---

src/node/nodestate.h

Since https://github.com/microsoft/CCF/pull/405, the KV store is now compacted by PBFT. It is no longer necessary to open the user frontend as soon as PBFT is setup. 
Resolves #405.

Remove hardcoded accept_user_connections with PBFT

---

samples/apps/smallbank/app/smallbank.cpp
src/kv/test/stub_consensus.h
src/node/clientsignatures.h
src/node/rpc/frontend.h
src/node/rpc/test/frontend_test.cpp
tests/infra/rates.py

Resolves https://github.com/microsoft/CCF/issues/417.
These changes result from switching the `balance` endpoint of our small bank app from `Write` to `Read`:
- The primary (and only the primary) now stores the signed client request.
- For a forwarded command, the primary stores the signed client request without validating it, trusting that the forwarder backup has verified it.
I added the corresponding unit tests in `frontend_test.cpp`. 
Plus some minor changes:
- Moved some functions from `public:` to `private:` in `frontend.h`.
- Added curly braces under if/else statements in `frontend.h`.

Small bank balance as a Read handler

---

.azure-pipelines-no-sgx.yml

This test is still failing unpredictably, so we should disable it in the PR-gating CI until this is resolved.

Disable test_TCP_with_delay

---

tests/infra/remote.py

If we run the end-to-end tests with `TRACE` logging level, then OE gives us its `verbose` logs. These include [direct dumps of the CRL data in DER format](https://github.com/openenclave/openenclave/blob/3a25e82565493522eeb8a103354bcf1f5f51ec55/host/sgx/sgxquoteprovider.c#L125) - this is non-printable non-UTF8 binary. When our Python infra scans the output for errors it fails to decode these lines, and previously this raised an exception and crashed the test.
Now we just ignore these decode errors, replacing unparseable bytes with a placeholder character.

Ignore failures when decoding logs

---

ePBFT/src/pbft/bft-simple/test/replica_test.cpp
ePBFT/src/pbft/libbyz/LedgerReplay.cpp
ePBFT/src/pbft/libbyz/LedgerReplay.h
ePBFT/src/pbft/libbyz/LedgerWriter.cpp
ePBFT/src/pbft/libbyz/LedgerWriter.h
ePBFT/src/pbft/libbyz/Replica.cpp
ePBFT/src/pbft/libbyz/Replica.h
ePBFT/src/pbft/libbyz/keypair.h
ePBFT/src/pbft/libbyz/libbyz.cpp
ePBFT/src/pbft/libbyz/libbyz.h
ePBFT/src/pbft/libbyz/receive_message_base.h
ePBFT/src/pbft/libbyz/test/test_ledger_replay.cpp
src/consensus/pbft/pbft.h

Resolves #458 
- `LedgerWriter` will not register callbacks and a generic ctx pointer to write to the ledger 
- Replica will have the `LedgerEnclave` object passed to it during construction and it will in turn initialize `LedgerWriter` with the `LedgerEnclave` object
- `LedgerReplay` will use `LedgerWriter`'s `LedgerEnclave` to put entries into it's own ledger, same way as Raft does now. The entry will be returned to `LedgerReplay` without the frame. Then we will go on to deserializing the entry into a pre-prepare and executing it
- `test_ledger_replay` doesn't need to write to files anymore
- removed ledger initialization from `replica_test` since we don't check the ledger in e2e tests now

LedgerEnclave in epbft

---

tests/infra/jsonrpc.py

Looks like the latest version of `black` (`black-19.10b0`), that has automatically been picked up by the latest `master` build, does not like this.

Fix jsonrpc.py format

---

src/node/nodestate.h

That was somehow missing, meaning that enclave with debug on would not start.

Add current state to advance log

---

src/ds/logger.h

Minor feature that was lost in a previous refactor. Lines up the actual log messages (from the `|`), regardless of the length of the path+linenumber.
Before:
```
2019-11-01T16:39:47.328568Z        [info ] ../src/host/main.cpp:323             | Creating new node: new network (with 3 initial member(s))
2019-11-01T16:39:47.339420Z        [info ] ../src/consensus/pbft/libbyz/Node.cpp:85 |  max faulty (f): 0 num replicas: 1
2019-11-01T16:39:47.339465Z        [info ] ../src/consensus/pbft/libbyz/Node.cpp:127 | Adding principal with id:0
2019-11-01T16:39:47.339490Z        [info ] ../src/consensus/pbft/libbyz/Node.cpp:157 | Added principal with id:0
2019-11-01T16:39:47.339496Z        [info ] ../src/consensus/pbft/libbyz/Node.cpp:101 | My id is 0
```
After:
```
2019-11-01T16:48:57.282875Z …
```

Truncate long filenames in logger

---

sphinx/source/quickstart/index.rst
sphinx/source/users/deploy_app.rst
tests/infra/ccf.py
tests/infra/path.py
tests/infra/remote.py
tests/recovery.py

So that you can run, from the `build` directory: `$ ../start_test_network.sh ./libloggingenc.so.signed`.
Also moved `wait_for_state` from `recovery.py` to `ccf.py` as it is a general feature of CCF and not test-specific.

start_test_network.sh accepts full enclave package path

---

src/ds/cli_helper.h
src/host/main.cpp

Tweaked the descriptions and behaviour of some options.
#515: Each `--member-certs` arg must be an existing file.
```
$ ./cchost start --help
Start new network
Usage: ./cchost start [OPTIONS]
Options:
-h,--help                   Print this help message and exit
--network-cert-file PATH=networkcert.pem
Destination path where fresh network certificate will be created
--gov-script FILE=gov.lua REQUIRED
Path to Lua file that defines the contents of the gov_scripts table
--member-cert FILE=[] ... REQUIRED
Certificate files of the initial consortium members
```
#516: The address arguments show a type (`HOST:PORT`). `--public-rpc-address` is not a required argument, if not provided it will default to `--rpc-address`.
```
$ ./cchost --help
ccf
Usage: ./cchost [OPTIONS] SUBCOMMAND
Options: …
```

Clarify options to cchost

---

src/node/rpc/frontend.h
src/node/rpc/memberfrontend.h
tests/infra/ccf.py

Make error message for certs not found in user table clearer

---

CMakeLists.txt
cmake/common.cmake
samples/apps/smallbank/smallbank.cmake
src/consensus/pbft/libbyz/Big_req_table.cpp
src/consensus/pbft/libbyz/Big_req_table.h
src/consensus/pbft/libbyz/Client_proxy.h
src/consensus/pbft/libbyz/Log_allocator.h
src/consensus/pbft/libbyz/Message.cpp
src/consensus/pbft/libbyz/Pre_prepare.cpp
src/consensus/pbft/libbyz/Replica.cpp
src/consensus/pbft/libbyz/test/replica_test.cpp
tests/e2e_args.py
tests/e2e_logging_pbft.py
tests/infra/ccf.py
tests/infra/runner.py

- Get smallbank to work with the pbft backend
- Create a python pbft flag and then use that to make  network.start_and_join work for both raft and pbft
- bug fix where we do not return the KV version properly
- change to use the standard allocator for pbft message allocations

ePBFT - smallbank and other things

---

src/host/main.cpp

Resolves https://github.com/microsoft/CCF/issues/555 and https://github.com/microsoft/CCF/issues/556.

Document and set default raft timeout

---

samples/apps/txregulator/tests/txregulatorclient.py
sphinx/source/schemas/getQuotes_result.json
src/node/nodestate.h
src/node/rpc/nodecalltypes.h
tests/governance.py
tests/infra/jsonrpc.py

Our partially recursive failed to decode strings in lists and key-values, causing inconsistent behaviour depending on whether the `format` chosen was `"json"` or `"msgpack"`.
```
>>> o
{'abc': 'def', 'ghi': {'jkl': ['a', 'b', 'c'], 'mno': {}}}
>>> json.loads(json.dumps(o))
{'abc': 'def', 'ghi': {'jkl': ['a', 'b', 'c'], 'mno': {}}}
>>> msgpack.unpackb(msgpack.packb(o))
{b'abc': b'def', b'ghi': {b'jkl': [b'a', b'b', b'c'], b'mno': {}}}
```
Ideally they would be identical, and they are if we call `msgpack.unpackb(..., raw=False)`.
As an associated change, the raw quote is passed as a byte-vector rather than a string. This does mean it appears as a long int list when looking at the raw JSON/Python, so its a prime candidate to be hex-encoded (#278).

Decode msgpack and json consistently

---

CMakeLists.txt
src/apps/batched/batched.lua
src/apps/batched/oe_sign.conf
tests/e2e_batched.py
tests/e2e_logging.py
tests/infra/jsonrpc.py
tests/infra/node.py
tests/suite/test_requirements.py

This adds a basic batched app so we can stress test large requests (#557).
I see 3 potential issues we need to investigate:
- Large incoming transaction messages
- Expensive transaction execution (occupying our only thread for `O(raft timeout)`, causing #557)
- Large write sets
So far I've only looked at the first, and discovered that we close connections for any request larger than 2MB (verified that this also occurs with the logging app, where we currently test up to only 512KB). I don't have a fix for this yet, but submitting this test app for discussion/exploration. Some light tweaks should make this app suitable for testing all 3 cases.

Add basic batched app load test

---

src/apps/luageneric/luageneric.cpp
src/node/rpc/frontend.h
tests/e2e_batched.py
tests/e2e_logging.py
tests/reconfiguration.py
tests/suite/test_requirements.py

Our `listMethods` RPC previously just returned the names of all registered handlers. Since the generic lua app (and presumably future similar generic interpreters) use the _default_ endpoint, they don't actually report the supported methods (ie - they don't include `LOG_record` for the lua logging app). This fixes that.
While doing this I also fiddled with the `test_requirements` to generate parameterised variants, so we can easily say "this test requires exactly these methods", rather than looking for a specific app. I also added the `ensure_reqs` meta-decorator to remove some of the boilerplate (ie - to consistently skip if `enforce_reqs` is False). I'm sure there's some way to reduce the boilerplate even further, but I don't see it straight away.

Implement listMethods for lua generic app

---

src/enclave/rpcendpoint.h
src/enclave/tlsendpoint.h
src/enclave/tlsframedendpoint.h
src/host/tcp.h
tests/infra/jsonrpc.py

`tlsframedendpoint` imposes a maximum message size of 2MB, but previously did so by closing connections with no logging. I've tried to improve this by logging a failure when we close these connections, logging more clearly when we're ignoring messages for closed connections, and trying to send a reasonable message back over the connection before we close it.
I made the `e2e_logging` tests deliberately increase message sizes until it hit this error, but have removed as this didn't work - the error is reported for seqno 0 so we need to fetch from the stream manually, and still we sometimes get a closed session without any preceding error message.

Improve error reporting on oversized messages

---

src/apps/batched/batched.lua
src/kv/genericserialisewrapper.h
src/kv/kv.h
src/kv/kvtypes.h
src/kv/test/kv_serialisation.cpp
tests/e2e_batched.py

As discussed in #338, we currently have no way to safely recover from serialisation failures. This PR adds some more tests which will trigger serialisation failures, and ensures that they all produce a consistent response - currently aborting the executing node.
There are a few other recovery methods we could investigate here, in particular having the executing node rollback its KV, with an associated election to rollback consensus state. This may let the network recover with all nodes still alive, but needs some further thought. We hope to mitigate this risk in future with verified serialisers and increased enclave memory limits.

Generalise handling of serialisation errors

---

src/enclave/http.h
src/enclave/tlsendpoint.h
tests/e2e_logging.py

`HTTPEndpoint` now reads all available data from TLS connection before trying to parse. We could do this more efficiently by converting `read(size...)` to `read_into(vector, size...)`, but I don't think its necessary at the moment (and `read()` is already pretty complicated).
I actually need this to run any e2e HTTP tests on my VM, as the quote pushes the join request over the previous 4k limit.
Resolves #548.

Support large messages over HTTP

---

src/enclave/http.h
src/enclave/http_builder.h
src/enclave/test/http.cpp

This adds an `on_url` callback to our `http_parser`, where we extract the path and query. These are forwarded, along with the http method, to the `MsgProcessor`.
I've also moved our "format a HTTP request" util functions into `http_builder.h`, where it should be easier to extend with headers etc if needed,
This is the first stage of #582.

Extend HTTP parsing to include path and query

---

src/host/dns.h
src/host/main.cpp
src/tls/asn1_san.h

**Host-side**: DNS resolution does not specify IPv4 hint
**Enclave-side**: Support writing IPv6 as well as IPv4 to SAN in node certificate
Also provide default-value for consensus option to `cchost`.
Resolves https://github.com/microsoft/CCF/issues/587

Support for IPv6

---

cmake/common.cmake

Adding flabuffers dependency to unit_tests targets. Will add more dependencies on other targets when it is needed.

add flatbuffers dependency

---

src/enclave/httpendpoint.h

Replacing several TODOs in `httpendpoint.h`. Where previously we had a `LOG_FAIL` but no response to the client, we now send HTTP errors for various kinds of parsing failure at the HTTP level.

Report parsing errors as HTTP status codes

---

src/enclave/httpbuilder.h
src/enclave/httpendpoint.h
src/enclave/httpparser.h
src/enclave/test/http.cpp

- Adds header-related callbacks to our `HTTPParser`
- Builds map of headers
- Passes this to (renamed) `handle_message`
- Adds test that, even with dreadful chunking at the transport level, headers are processed correctly

HTTP header parsing

---

src/node/rpc/frontend.h
tests/infra/checker.py

When running in pbft mkSign was returning an error that was not being caught by the checker
- made checker.py raise an error if we were unable to sign
- pbft return success after emit_signature

pbft mkSign to return success on emit_signature

---

CMakeLists.txt
cmake/common.cmake
samples/apps/smallbank/smallbank.cmake
samples/perf_client/scenario_perf_client.cpp
samples/perf_client/scenario_perf_client.h
tests/infra/remote_client.py
tests/infra/runner.py
tests/perf_logging_scenario_100txs.json
tests/perfclient.py

We have a user-extensible perf client, but it requires transactions to be generated in C++. Since we expect to support systems where no client code is written in C++ this isn't always appropriate. This PR adds a new perf client which, instead of generating transactions at run-time, simply loads a set of static transactions (another 'scenario') from file.
There's a new test using this client with a simple scenario for the logging app. We don't actually care about the performance result from this, its simply to ensure the new `scenario_perf_client` is regularly built and run.

Add generic JSON-scenario perf client

---

src/consensus/pbft/libbyz/Pre_prepare.cpp
src/consensus/pbft/libbyz/Pre_prepare.h
src/consensus/pbft/libbyz/Replica.cpp
src/consensus/pbft/libbyz/test/replica_main.cpp
src/consensus/pbft/libbyz/test/replica_test.cpp
src/consensus/pbft/libbyz/test/test_ledger_replay.cpp
src/consensus/pbft/libbyz/types.h
src/consensus/pbft/pbftconfig.h
src/enclave/rpchandler.h
src/kv/kv.h
src/kv/kvtypes.h
src/kv/test/stub_consensus.h
src/node/history.h
src/node/nodestate.h
src/node/rpc/frontend.h
src/node/test/history.cpp
src/node/test/history_bench.cpp
tests/infra/checker.py

Regarding #539 (item 4, 5c, 5d)
- added second merkle tree to be updated when we are running in pbft and have replicated data (replicated tables). The original merkle tree continues to be updated due to all of the maps on both of the consensuses
- second merkle tree root (r_merkle_root) is added to the pre-prepare
- history will append, rollback, and compact the replicated merkle tree only when the consensus is pbft, otherwise it ignores it
We only use the replicated merkle tree root in the pre-prepare. Everything else still relies only on the all-data merkle tree (but can be updated when/if needed to use the `r_root()` too):
- `receipts` are issued and verified over the all-data merkle tree
- `history->emit_signature()` is done over the all-data merkle tree root
- `history->verify()` is …

Two merkle trees

---

CMakeLists.txt
cmake/common.cmake
src/enclave/httpendpoint.h
src/enclave/httpsig.h
start_test_network.sh
tests/infra/clients.py
tests/keygenerator.sh
tests/scurl.sh

Resolves https://github.com/microsoft/CCF/issues/612 
Introduces the friendly `scurl.sh` script that can be used just like `curl` (arguments are forwarded to curl) and will automagically sign HTTP requests with the private key passed to `curl` to authenticate the client over the TLS connection (via `--key`). 
The signed header fields are very much hard-coded for now but I will address that in a further PR.

Friendly HTTP signatures with curl

---

src/host/main.cpp
src/node/nodeinfonetwork.h
src/node/nodestate.h
src/node/rpc/nodefrontend.h

Noticed that we assume that the rpc hostname and node hostname are the same and we are using the rpc hostname when we do `add_node`.
Fixed to use node hostname

Use node hostname with node port instead of rpc hostname

---

src/clients/sig_rpc_tls_client.h
src/enclave/httpendpoint.h
src/enclave/httpsig.h
tests/infra/clients.py

Adds support for parsing `(request-target)` field as it does not follow the rules of other headers (see https://tools.ietf.org/html/draft-cavage-http-signatures-12#section-2.3).

Support for (request-target) in HTTP client signatures 

---

tests/infra/ccf.py

We used to have to wait before issuing command to a starting node with HTTP. This is no longer the case so this PR removes the last sleep we have in our test infra.

Remove sleep when creating a new node (test infra)

---

src/consensus/pbft/libbyz/Client_proxy.h
src/consensus/pbft/pbft.h

resolves #617 => This would have ended up re-creating only once semantics. This is something that the application is responsible for.
So all we should do is make the client_proxy's re-transmit configurable

make client_proxy retransmit timeout configurable

---

src/enclave/httpbuilder.h
src/enclave/httpendpoint.h
src/enclave/httpparser.h
src/enclave/httpsig.h
src/enclave/wsupgrade.h
tests/infra/clients.py
tests/requirements.txt

Resolves item 2 in https://github.com/microsoft/CCF/issues/629. 
This PR adds support for the WebSocket handshake. 
Typically, the (websocket) client sends a handshake request over HTTP, specifying the upgrade protocol and a random key, e.g.:
```
GET / HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: 127.237.61.243:46920
Origin: http://127.237.61.243:46920
Sec-WebSocket-Key: tuCthd5nFUGth+AnhtfWCQ==
Sec-WebSocket-Version: 13
```
To complete the upgrade, the server should reply with:
```
HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Sec-WebSocket-Accept: +y6XCTIDNuuThvP3OSUoiAUA+UY=
Upgrade: websocket
```
The `Sec-Websocket-Accept` string is constructed by 1) concatenating the client's key with a well-known string, 2) SHA1 it, 3) Base 64 encode the result. 
- Added a websocket …

Support for WebSocket handshake

---

src/consensus/ledgerenclave.h
src/ds/logger.h
src/ds/nonblocking.h
src/ds/oversized.h
src/ds/pending_queue.h
src/ds/ringbuffer.h
src/ds/ringbuffer_types.h
src/ds/test/messaging.cpp
src/ds/test/oversized.cpp
src/enclave/clientendpoint.h
src/enclave/enclave.h
src/enclave/tlsendpoint.h
src/host/handle_ringbuffer.h
src/host/ledger.h
src/host/main.cpp
src/host/nodeconnections.h
src/host/rpcconnections.h
src/host/sigterm.h
src/host/ticker.h
src/node/nodestate.h
src/node/nodetonode.h
src/node/notifier.h
src/node/seal.h

This is a proposed fix for #628.
This adds a new implementation of `ringbuffer::AbstractWriter` which avoids blocking indefinitely - if the underlying ringbuffer is full, it will add messages to an internal queue. This queue can be flushed later, periodically, when the ringbuffer should have space, to write the queued messages. This has less knock-on effects on the calling code than making them call `try_write` and handle failures individually, at each calling point. Instead each write-point can stick with their looks-like-a-blocking-call call, and the details are handled beneath their feet.
There are 2 new unit tests for this. One in `messaging.cpp` which checks this lets us write past a full ringbuffer, and one in `oversized.cpp` which checks this integrates nicely with our existing …

Avoid deadlock by queuing message writes on the host

---

tests/e2e_args.py

ccf.io exists and is assigned, replacing with example.com, reserved for this kind of purpose (https://tools.ietf.org/html/rfc2606)

Remove ccf.io domain

---

sphinx/source/developers/build_app.rst
sphinx/source/developers/index.rst
sphinx/source/developers/kv/kv_serialisation.rst
sphinx/source/developers/ledger.rst
sphinx/source/members/common_member_operations.rst
sphinx/source/members/constitution.rst
sphinx/source/members/index.rst
sphinx/source/members/member_rpc_api.rst
sphinx/source/members/open_network.rst
sphinx/source/members/proposals.rst
sphinx/source/operators/operator_rpc_api.rst
sphinx/source/operators/recovery.rst
sphinx/source/operators/start_network.rst
sphinx/source/quickstart/build.rst
sphinx/source/quickstart/index.rst
sphinx/source/quickstart/requirements.rst
sphinx/source/users/client.rst
sphinx/source/users/deploy_app.rst
sphinx/source/users/index.rst
sphinx/source/users/issue_commands.rst

Add docs for rekeying ledger encryption key (following https://github.com/microsoft/CCF/pull/699). 
I also fixed the docs referencing issue we had by specifying the full path of each section title (half an hour well spent!). 
**This should be merged after https://github.com/microsoft/CCF/pull/699 is merged.**

Add rekey docs and fix broken links in docs

---

.azure-pipelines-templates/cimetrics.yml
.azure-pipelines-templates/common.yml

Component detection currently executes on every job and adds a minute every time. That's quite unnecessary.

Only detect components once

---

src/apps/logging/logging.cpp
tests/e2e_batched.py
tests/e2e_logging.py
tests/e2e_suite.py
tests/infra/ccf.py
tests/infra/logging_app.py
tests/receipts.py
tests/reconfiguration.py
tests/recovery.py
tests/rekey.py
tests/suite/test_requirements.py

This is the last step to guarantee that our end-to-end test suite works correctly. 
There is now a new `txs` object that is passed to the `infra.ccf.network` and records all the transactions executed on the network during the test suite. Whenever we recover the network, the test suite will automatically issue some transactions prior to recovery and guarantee that they are correctly recovered post recovery.
This can be added to any of our tests via the `@reqs.recovery` decorator. I have refactored the `e2e_logging.py` test accordingly.

Add new transaction object to test suite 

---

src/node/history.h

Resolve #724 
This removes 2 calls to get_full_state_root() that are not needed in the Raft case.
  | before | after
-- | -- | --
  | 54957.4 | 61590.5
  | 55383.4 | 59255.6
  | 55322.7 | 61837.1
  | 54537.9 | 61819.2
  | 54345.3 | 61231.4
  |   |  
average | 54909.34 | 61146.76
  |   |  
  |   |  
Improvement | 10.20% |  
"python3" "/home/alexsha/CCF/samples/apps/smallbank/tests/small_bank_client.py" "-b" "." "-c" "./small_bank_client" "--ignore-quote" "-l" "info" "-g" "/home/alexsha/CCF/src/runtime_config/gov.lua" "--consensus" "raft" "--worker_threads" "0" "--default-curve" "secp384r1" "--write-tx-times" "--label" "SB_^" "--transactions" "200000" "--max-writes-ahead" "5000" "--metrics-file" "small_bank_metrics.json" -n 10.190.228.230 -n 10.190.228.232 -n 10.190.228.234 --sig-max-tx …

Do not call get_full_state_root() when it is not needed

---

src/consensus/pbft/pbft.h

AFAICT, [this failure](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=4272&view=logs&j=13585137-c2dd-56f2-c63b-09854f0e18f7&t=3ce5bd4c-ff15-5db3-bb2c-95e75b76f8f8&l=213) started with #735. If we don't resize downwards, then the `serialized_msg` will still contain old data at the end, and it seems this is causing occasional test failures.

Resize to avoid trailing data

---

sphinx/source/concepts.rst
sphinx/source/developers/api.rst
sphinx/source/developers/index.rst
sphinx/source/developers/logging_cpp.rst
sphinx/source/glossary.rst
sphinx/source/introduction.rst
sphinx/source/members/common_member_operations.rst
sphinx/source/members/open_network.rst
sphinx/source/members/proposals.rst
sphinx/source/operators/recovery.rst
sphinx/source/operators/start_network.rst
sphinx/source/users/issue_commands.rst
sphinx/source/users/rpc_api.rst

Updating docs to describe current state, in particular HTTP-by-default. Replacing all `./client` and `./memberclient` sample commands with curl equivalents. Have removed some since I think we're repeating ourselves (don't need to show a sample vote for every proposal).
Most of these edits were done by hand and untested, so please read carefully for dumb mistakes. Doing raw proposals by hand in curl rather than by `memberclient` is still a little awkward (in particular things like "turn this binary file into a JSON array and put that in the correct field of this JSON object") - this should be mitigated once we support non-JSON-RPC payloads.
Opening as a draft for early review while I rewrite the remaining sections.

Updating sphinx docs

---

.devcontainer/devcontainer.json

Seems like Dockerfile.sgx is replaced with Dockerfile

Fixing Dockerfile path typo

---

src/node/rpc/memberfrontend.h
src/node/rpc/test/membervoting_test.cpp
src/runtime_config/default_whitelists.h

Follow up from https://github.com/microsoft/CCF/issues/778
It should not be possible to trust a node that is already retired. Also, the `ccf.nodes` tables should not be writable from Lua - we really want to limit what members can change in that table (i.e. only trust and retire nodes, via C++ functions).

Cannot trust or retire a retired node

---

src/consensus/pbft/libbyz/parameters.h
src/enclave/httpsig.h
src/node/genesisgen.h
src/node/history.h
src/node/rpc/frontend.h
src/node/rpc/test/nodefrontend_test.cpp
src/tls/curve.h
src/tls/hash.h
src/tls/keypair.h
src/tls/test/main.cpp
src/tls/verifier.h

Resolves https://github.com/microsoft/CCF/issues/785
`keypair.h` is now split into `keypair.h`, `curve.h`, `verifier.h` and `hash.h` (all under `tls/`).

Split keypair.h

---

src/consensus/pbft/libbyz/Big_req_table.cpp
src/consensus/pbft/libbyz/Big_req_table.h
src/consensus/pbft/libbyz/Client_proxy.h
src/consensus/pbft/libbyz/Replica.cpp
src/consensus/pbft/libbyz/Request.cpp
src/consensus/pbft/libbyz/Request.h
src/consensus/pbft/libbyz/request_id_gen.cpp
src/consensus/pbft/libbyz/request_id_gen.h
src/ds/thread_messaging.h

Fix the client proxy so that it can run on multiple threads

---

src/consensus/pbft/libbyz/Pre_prepare.cpp
src/consensus/pbft/libbyz/Pre_prepare.h
src/consensus/pbft/libbyz/Replica.cpp
src/consensus/pbft/libbyz/test/replica_test.cpp
src/consensus/pbft/libbyz/test/test_ledger_replay.cpp
src/consensus/pbft/libbyz/types.h
src/consensus/pbft/pbftconfig.h
src/enclave/rpchandler.h
src/node/rpc/frontend.h

Part of #762 and #774
We do not need the full state Merkle tree. It does not give us enough goodness to outweigh the performance overhead. This PR only remove the Merkle root from PBFT, there will be followup remove this from the KV.

Remove full Merkle root from PBFT

---

tests/ledger.py
tests/votinghistory.py

msgpack-python released v1.0.0 yesterday, which has some breaking changes causing our `voting_history_test` to fail. This resolves those, following the notes [here](https://github.com/msgpack/msgpack-python#major-breaking-changes-in-msgpack-10).

Compatibility with msgpack-1.0.0

---

tests/infra/notification.py

Resolves #659.
We were getting occasional CI failures reporting out-of-order notifications. We believe these notifications are always _sent_ in-order, but this simple Python HTTP server is spawning new threads for each request so potentially _processing_ them out-of-order. This server now runs on a single thread instead.

Single threaded notification processing

---

tests/infra/clients.py

Attaching a session object with the post requests in Python RequestClient. Improves throughput.
Signed-off-by: prakashngit <prakash.narayana.moorthy@intel.com>

adding a session to the python request client

---

tests/infra/ccf.py
tests/infra/consortium.py
tests/infra/e2e_args.py
tests/infra/node.py

Added arguments to adjust initial member/client count on network start
--initial-member-count
--initial-user-count
Changed default value of member_id to 0 in calls for cases when there is one member. 
Addressing issue #889 
Signed-off-by: Daniel Peroni <daperoni@microsoft.com>

Adjustable initial member/client

---

src/consensus/pbft/libbyz/Big_req_table.cpp
src/consensus/pbft/libbyz/Big_req_table.h
src/consensus/pbft/libbyz/Replica.cpp
src/consensus/pbft/libbyz/Req_queue.cpp
src/consensus/pbft/libbyz/Req_queue.h

If a request is in the `rqueue` it means that it is pending for execution (view change timer has been started) so it should not be removed from the big req table.

Dont remove pending requests from big request table

---

sphinx/source/quickstart/index.rst
sphinx/source/users/deploy_app.rst
start_test_network.sh
tests/K6.md
tests/infra/ccf.py
tests/infra/remote.py

The new `common/` directory broke our `start_test_network.sh` script because the governance script was not copied properly. This PR fixes it and also removes the expectation that the first argument to the script was the path to the enclave application - we should use the existing `--package` option instead.
https://github.com/microsoft/CCF/issues/493 will need a little more thought to get the script working out of the box so I propose that we defer it until after v0.8.

Fix start_test_network gov script issue

---

samples/apps/smallbank/app/smallbank.cpp
src/apps/jsgeneric/jsgeneric.cpp
src/apps/logging/logging.cpp
src/apps/luageneric/luageneric.cpp
src/enclave/appinterface.h
src/node/rpc/frontend.h
src/node/rpc/userfrontend.h

Resolves #786.
This was a minor TODO we noticed a while ago - User apps should really be inheriting from `UserRpcFrontend` (ensuring standard user-cert lookup is followed), rather than from the more abstract RpcFrontend. This PR makes that the case, renaming the return type from `get_rpc_handler` and fixing some related includes.

get_rpc_handler returns UserRpcFrontend

---

.azure-pipelines-templates/common_test.yml
.azure-pipelines-templates/download_build.yml
CMakeLists.txt
cmake/common.cmake
samples/apps/smallbank/smallbank.cmake

In #922 I recommended naming replacing `SB` with `SB_${CONSENSUS}` in the call to `add_perf_test`. My concern was that the `pbft` and `raft` variants would produce identical labels, so use the same workspace dir in local builds. This caused our CIMetrics labels to no longer match the old values, and to duplicate the consensus (`SB_pbft_SGX_BFT`). I believe this should resolved both issues - we construct the full label in CMake rather than trying to pass it from the CI yaml. The local labels should match the labels produced on the CI, the tests should get unique names, and they should match the _old_ names so we keep our full history.

Construct perf TESTS_SUFFIX in cmake

---

src/consensus/pbft/libbyz/Big_req_table.cpp
src/consensus/pbft/libbyz/Big_req_table.h
src/consensus/pbft/libbyz/Checkpoint.cpp
src/consensus/pbft/libbyz/Replica.cpp
src/consensus/pbft/libbyz/Req_queue.cpp
src/consensus/pbft/libbyz/Req_queue.h
src/ds/dllist.h
src/node/rpc/metrics.h

- big request table will use an intrusive linked list so when an item is removed it can be done in O(1)
- the checkpoint in pbft is now only used for marking stable and therefore does not need to be signed
- the request queue will now have a queue per thread. This allows us to maintain session consistency while ensuring that we have enough work for all execution threads 
- bring the intrusive double linked list from snmalloc
- print a request time series (second granularity) when collecting other metrics

Fix some performance related issues

---

src/consensus/pbft/libbyz/Client_proxy.h
src/consensus/pbft/libbyz/Pre_prepare.cpp
src/consensus/pbft/libbyz/Pre_prepare.h
src/consensus/pbft/libbyz/Prepare.cpp
src/consensus/pbft/libbyz/Replica.cpp
src/consensus/pbft/libbyz/Status.h
src/consensus/pbft/libbyz/parameters.h
src/ds/messaging.h
src/ds/thread_messaging.h

- larger max number of requests in a pre-prepare
- updated what we sign as proof that a pre-prepare was accepted

More PBFT perf changes

---

src/consensus/pbft/libbyz/Node.cpp
src/consensus/pbft/libbyz/Prepare.cpp
src/consensus/pbft/libbyz/Rep_info.cpp
src/consensus/pbft/libbyz/Rep_info_exactly_once.cpp
src/consensus/pbft/libbyz/Rep_info_exactly_once.h
src/consensus/pbft/libbyz/Replica.cpp
src/consensus/pbft/libbyz/Replica.h
src/consensus/pbft/libbyz/Reply.cpp
src/consensus/pbft/libbyz/Reply.h
src/consensus/pbft/libbyz/test/replica_test.cpp
src/consensus/pbft/libbyz/test/test_ledger_replay.cpp
src/consensus/pbft/libbyz/types.h
src/consensus/pbft/pbftconfig.h
src/consensus/pbft/pbftrequests.h
src/consensus/raft/raft.h
src/consensus/raft/test/driver.cpp
src/consensus/raft/test/driver.h
src/consensus/raft/test/main.cpp
src/consensus/test/stub_consensus.h
src/enclave/main.cpp
src/enclave/rpchandler.h
src/kv/kv.h
src/kv/kvtypes.h
src/kv/test/kv_bench.cpp
src/node/history.h
src/node/rpc/frontend.h
src/node/test/history.cpp

- Reduce the cost of the roll data structure in the KV
- Reply's do not need a digest in addition to the node-to-node integrity check
- for PBFT do not add to the Merkle tree at the same time as commit, do this on another thread
- other misc PBFT optimizations

Performance

---

CMakeLists.txt
cmake/secp256k1.cmake
src/tls/main.cpp

Fix https://github.com/microsoft/CCF/issues/948
This fixes two issues:
- `$<BUILD_INTERFACE:${EVERCRYPT_INC}>` was used without " " for the `ccf.enclave` and `ccf.host` targets, which means that the CCF source directory got exported as an installed include directory.
- The install prefix `${CMAKE_INSTALL_PREFIX}` was hardcoded in the `INSTALL_INTERFACE`, which means that it was only possible to install CCF in one given location (`/tmp/install-ccf`, as per the CI Release build).
I will create v0.8.2 when this is merged.

Fix hardcoded paths in CCF install

---

CMakeLists.txt
samples/apps/smallbank/smallbank.cmake
tests/code_update.py
tests/connections.py
tests/e2e_logging.py
tests/e2e_scenarios.py
tests/governance.py
tests/infra/ccf.py
tests/infra/logging_app.py
tests/receipts.py
tests/recovery.py
tests/schema.py
tests/suite/test_requirements.py

Resolves #934 
Tests that are still not enabled are the recovery, reconfiguration related tests, code update test.
- `lua_end_to_end_batched` messages exceed `Max_message_size` so still can't be enabled
Tests that can't be enabled because they raise issues that need to be investigated and addressed separately (will open tickets) are:
- `lua_txregulator_test` and `js_end_to_end_logging` tests trigger a pbft view change which causes the replicas to roll back before the last checkpoint which in turn crashes the nodes #951 
- `lua_end_to_end_logging` and `end_to_end_scenario` are unstable (tagging them along with the above issue)
- `member_clients` test makes merkle roots between replicas un-matched #952
- `governance_history` test fails because it checks the ledger for governance results, …

Enable more pbft tests

---

sphinx/source/developers/logging_cpp.rst
src/apps/logging/logging.cpp
src/node/rpc/commonhandlerregistry.h
src/node/rpc/frontend.h
src/node/rpc/handlerregistry.h
src/node/rpc/memberfrontend.h
src/node/rpc/nodefrontend.h
src/node/rpc/test/frontend_test.cpp
src/node/rpc/userfrontend.h

Resolves #914.
We have several parameters to tweak the behaviour of installed RPC handlers, and we're likely to add more. Rather than needing to specify all of these in the call to `install` (with signficant overload complications), they should be set manually on the few handlers they actually affect.
This PR lets you set those parameters in 2 ways. Manually:
```
auto& foo_handler = install("FOO", foo_func, Read);
foo_handler.execute_locally = true;
foo_handler.params_schema = ...;
```
Or with chaining methods:
```
install("FOO", foo_func, Read)
.set_execute_locally(true)
.set_params_schema(...);
```
I prefer the second, but I think its worth keeping both in general.

Simplify signature of handler install

---

cmake/common.cmake
samples/apps/smallbank/smallbank.cmake
samples/apps/txregulator/tests/txregulatorclient.py
tests/e2e_logging.py
tests/infra/ccf.py
tests/infra/e2e_args.py
tests/memberclient.py

The performance tests now use the fast bitcoin curve when generating users' identities (and members).  Note that there is no need to recompile CCF for this. Also renamed `args.default_curve` to `args.participants_curve`.

Fast curve for users for performance tests with signatures

---

cmake/pbft.cmake
src/kv/kv.h
tests/coverage/generate_coverage.sh
tests/infra/libbyz/node.py
tests/late_joiners.py

Most of our unit tests are `_test`, this renames the few exceptions that were `test_` (so now `./te[TAB]` will auto-complete to `./tests.sh`).
++Some other renames that were bothering me.

Minor renames for consistency

---

.azure-pipelines-templates/matrix.yml

Consolidating on DC_v2, DC_v1 is slower and of limited interest at this point.

Deco DC_v1 pool

---

cmake/common.cmake
getting_started/create_vm/destroy_vm.sh
getting_started/create_vm/make_vm.sh
getting_started/create_vm/vm.json

Install getting started

---

.azure-pipelines-gh-pages.yml
.azure-pipelines.yml
cmake/common.cmake
docker/Dockerfile
getting_started/setup_vm/roles/openenclave/tasks/install.yml
getting_started/setup_vm/roles/openenclave/vars/common.yml

Update Open Enclave for 0.9 to enable snmalloc use.
fix #980

Upgrade Open Enclave

---

src/consensus/pbft/libbyz/governance_update_tracking.h
src/consensus/pbft/libbyz/pre_prepare.cpp
src/consensus/pbft/libbyz/pre_prepare.h
src/consensus/pbft/libbyz/replica.cpp
src/consensus/pbft/libbyz/replica.h
src/consensus/pbft/libbyz/types.h
src/consensus/pbft/pbft_config.h
src/enclave/rpc_handler.h
src/node/rpc/frontend.h
src/node/rpc/member_frontend.h

related to #953
This change creates a "chain" of pre-prepares that contain requests that performed some kind of governance operation.  What this means that when a user gets their receipt (which covers a pre-prepare) they can make a determination if they want to audit the log and if they do they do not need to look into every pre-prepare.

In pbft keep tracks of the last pre-prepare that performed a governance request

---

.azure-pipelines-templates/daily-matrix.yml
.daily.yml

I think we want:
1. SAN
2. Coverage
3. Release build and tests
4. TLS compliance test
5. Randomised test "suite", aka end to end fuzzing (probably over the SAN build)
This only adds the first two, will do the rest after the release.

Daily build

---

src/ds/logger.h

Spent a while trying to work out how we were printing logs out-of-order:
```
2020-03-30T16:55:02.998596Z ...
2020-03-30T16:55:02.998613Z ...
2020-03-30T16:55:02.998634Z ...
2020-03-30T16:55:03.704000Z ...
2020-03-30T16:55:03.942000Z ...
2020-03-30T16:55:03.957000Z ...
2020-03-30T16:55:03.977000Z ...
2020-03-30T16:55:03.106200Z ...
2020-03-30T16:55:03.108100Z ...
2020-03-30T16:55:03.110100Z ...
2020-03-30T16:55:03.111800Z ...
2020-03-30T16:55:03.114100Z ...
2020-03-30T16:55:03.285500Z ...
2020-03-30T16:55:03.312000Z ...
2020-03-30T16:55:03.313600Z ...
2020-03-30T16:55:03.315800Z ...
2020-03-30T16:55:03.329600Z ...
2020-03-30T16:55:03.331900Z ...
2020-03-30T16:55:03.334000Z ...
```
Turns out the timestamp was just aligned to the wrong end (suffixing 0s rather than prefixing them).

Right-align logging timestamp ns

---

CMakeLists.txt

It looks like the election-timeout-halving of #1011 wasn't as safe as hoped:
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=6861&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=efdbc34d-c6b6-5dc6-e05c-1751d4c47c20&l=10624
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=6860&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=efdbc34d-c6b6-5dc6-e05c-1751d4c47c20&l=10073
These are the only tests that set custom election timeouts, it seems they really do need them to be this large, so I've doubled them to match their old values :(

Redouble election timers

---

src/consensus/pbft/libbyz/nv_info.cpp
src/consensus/pbft/libbyz/pre_prepare.cpp
src/consensus/pbft/libbyz/pre_prepare.h
src/consensus/pbft/libbyz/prepare.cpp
src/consensus/pbft/libbyz/prepare.h
src/consensus/pbft/libbyz/receive_message_base.h
src/consensus/pbft/libbyz/rep_info.cpp
src/consensus/pbft/libbyz/rep_info.h
src/consensus/pbft/libbyz/replica.cpp
src/consensus/pbft/libbyz/replica.h
src/consensus/pbft/libbyz/reply.cpp
src/consensus/pbft/libbyz/reply.h
src/consensus/pbft/libbyz/test/replica_test.cpp
src/consensus/pbft/libbyz/test/test_ledger_replay.cpp
src/consensus/pbft/libbyz/types.h
src/consensus/pbft/libbyz/view_info.cpp
src/consensus/pbft/pbft_config.h
src/tls/entropy.h
src/tls/intel_drng.h

Each pre-prepare and prepare are given a hash of a nonce and then in the reply we send the plain text nonce to the client-proxy.
To get two-round-trips latency, replicas would return a reply to the client-proxy after getting a pre-prepare and 2f matching prepares. The client-proxy will get its reply and receipt before the request is committed in the ledger, but we guarantee that the request is eventually committed to the ledger or we can prove that some replicas are malicious.

Enable 2 round trip receipts

---

CMakeLists.txt

#1001 doesn't seem to be stable yet, it's failed twice on master.

Late joiner test is not stable yet

---

src/apps/js_generic/js_generic.cpp
src/apps/logging/logging.cpp
src/consensus/pbft/libbyz/replica.cpp
src/host/tcp.h
src/tls/verifier.h
tests/e2e_batched.py
tests/infra/ccf.py
tests/infra/node.py
tests/infra/remote.py

Daily build was failing on `logging_scenario_perf_test`, with what looked like a SAN-found memory violation. Actually this test was only failing because it timed out (SAN build is O(100)x slower, so we blow past the 90s limit). But _all_ of the SAN builds were reporting a memory leak in std err, and we were ignoring it _because there were no other errors_.
- If we find anything in std err, we log it, regardless of `[fail]`s or `[fatal]`s in std out
- If we have std error content on shutdown, we fail the test (resolves #938). NB: This is only done in `stop_all_nodes`, at the end of a test. Mid-test, we often manually shut down nodes, and sometimes we expect them to contain errors. We don't change the behaviour for those, but I believe we should expect all the final surviving nodes to …

Fail on SAN errors, and fix SAN errors

---

src/host/main.cpp

`std::map`s are ordered by key, so if we pass these to CLI11 our enum options get lexicographically sorted. I think its more readable if we maintain the enum-order.
Before:
`-l,--host-log-level ENUM:value in {debug->1,fail->3,fatal->4,info->2,trace->0} OR {1,3,4,2,0}=2`
After:
`-l,--host-log-level ENUM:value in {trace->0,debug->1,info->2,fail->3,fatal->4} OR {0,1,2,3,4}=2`

Maintain ordering of enum CLI options

---

src/consensus/pbft/libbyz/digest.cpp
src/consensus/pbft/libbyz/node.cpp
src/consensus/pbft/libbyz/parameters.h
src/consensus/pbft/libbyz/pre_prepare.cpp
src/consensus/pbft/libbyz/principal.cpp
src/consensus/pbft/libbyz/rep_info.cpp
src/consensus/pbft/libbyz/rep_info.h
src/consensus/pbft/libbyz/rep_info_exactly_once.cpp
src/consensus/pbft/libbyz/rep_info_exactly_once.h
src/consensus/pbft/libbyz/replica.cpp
src/consensus/pbft/libbyz/reply.cpp
src/consensus/pbft/libbyz/request.cpp
src/consensus/pbft/libbyz/state.cpp
src/consensus/pbft/pbft_config.h

- remove unused stats info
- increase batch size
- when we have less than 10 pending tx to run in a batch always write to the Merkle tree instead of waiting.

Some PBFT cleanup

---

sphinx/requirements.txt

Sphinx 3.0.0 was released today (https://www.sphinx-doc.org/en/master/changes.html#release-3-0-0-released-apr-06-2020) but our GitHub Pages job now fails with:
```
Running Sphinx v3.0.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 45 source files that are out of date
updating environment: [new config] 45 added, 0 changed, 0 removed
reading sources... [  2%] concepts
reading sources... [  4%] design/index
reading sources... [  6%] design/integration_progress
reading sources... [  8%] developers/api
Exception occurred:
File "/__w/1/s/sphinx/env/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 60, in parse_definition
parser = cpp.DefinitionParser(namestr, self)
TypeError: __init__() takes 2 …
```

Set sphinx version to 2.4.4

---

src/consensus/pbft/pbft.h
src/consensus/pbft/pbft_types.h
src/node/channels.h
src/node/node_to_node.h
src/node/rpc/forwarder.h
src/node/test/channel_stub.h

- Encryption/Decryption should be done across multiple threads
- If USE_NULL_ENCRYPTOR=ON do not encrypt the messages

encrypt PBFT request and response messages

---

.github/workflows/automerge.yml

It turns out, I think GitHub Actions are the solution to what we've been discussing for a while now. This PR introduces our first GitHub Action that will take care of (based on https://github.com/pascalgn/automerge-action): 
- Auto-merging a PR if the `automerge` label has been set on a PR (and if the other CI/reviewers requirements are met). Note that the `wip` label would explicitly disable this and no label has no effect.
- Auto-updating all PRs if the `sync` label has been set on a PR.

Keep PR up-to-date and merge automatically

---

sphinx/requirements.txt

Breathe 4.15 has been [released](https://github.com/michaeljones/breathe/pull/491#issuecomment-610543065), which is compatible with Sphinx 3.0, so we can remove the pinned version requirement.

Unpin sphinx version

---

cmake/ccf_app.cmake
cmake/common.cmake
cmake/preproject.cmake

Expose add_enclave_library_c in ccf_app.cmake for applications that want to build and bring in C libraries.

Expose add_enclave_library_c in ccf_app.cmake

---

samples/perf_client/perf_client.h
src/clients/tls_client.h

The `--transaction-rate` flag allows one to specify the transaction rate (tx/s) of the client. If a transaction rate is specified, the client computes the interval between writes needed to maintain this rate, and waits this amount between writes.

Add transaction rate setting to perfclient

---

tests/governance_history.py
tests/infra/consortium.py
tests/infra/member.py
tests/infra/proposal.py
tests/memberclient.py

Fixes #1075.
The problem was the default value of `state` in the `Proposal` constructor - we should read this state from the response, can't assume it is `Open`.
Then the logic in `vote_using_majority` is mostly sound, except for trying to return the last response, which may not exist. Instead, it now returns the `proposal`. This changes the return type of a bunch of functions which `return vote_using_majority(...)`, but it looks like nothing was using _their_ return values so this has no impact.

Handle proposals correctly with single member

---

.azure-pipelines-templates/cmake.yml
.azure-pipelines.yml
cmake/common.cmake
getting_started/setup_vm/roles/ccf_dependencies/vars/common.yml
tests/sgxinfo.sh

fix #639 
Sample output:
```
DRIVER INFO:
filename:       /lib/modules/5.0.0-1036-azure/kernel/ubuntu/sgx/intel_sgx.ko
version:        1.22
license:        Dual BSD/GPL
author:         Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
description:    Intel SGX Driver
srcversion:     B01FB72C0AB4B8EA7883F6E
alias:          acpi*:INT0E0C:*
depends:        
retpoline:      Y
intree:         Y
name:           intel_sgx
vermagic:       5.0.0-1036-azure SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4
PSW INFO:
libsgx-ae-pce/unknown,now 2.9.100.2-bionic1 amd64 [installed,upgradable to: 2.9.101.2-bionic1]
libsgx-ae-qe3/unknown,now 1.5.100.2-bionic1 amd64 [installed,upgradable to: 1.6.100.2-bionic1]
libsgx-ae-qve/unknown,now 1.5.100.2-bionic1 amd64 …
```

Add and install Platform Info script

---

src/consensus/pbft/libbyz/pre_prepare.cpp
src/consensus/pbft/libbyz/pre_prepare.h
src/consensus/pbft/libbyz/replica.cpp

Resolves problem described in #839 
The problem here is that the no-op pre-prepare digests were not being calculated consistently during view changes (no-op pre-prepares are created per-replica vs created by one replica and broadcasted to other replicas as is done in normal execution) and so the no-op pre-prepares would never complete.
This fixes that and also puts the no-op pre-prepares into the ledger during view changes. In order for the no-op pp's to go into the ledger, we need them to not be signed, as each no-op pre-prepare will be signed by the replica that created it, leading eventually to an inconsistent merkle tree. 
These pre-prepares will be signed _eventually_ as part of the next pre-prepare.

Fix no-op pre prepare

---

cmake/common.cmake
tests/infra/e2e_args.py

Fallout from #1083:
If you're in a `-CMAKE_BUILD_TYPE=Debug` folder, you may still want to run (and debug!) the virtual enclaves. But since we appended `-e debug` to the test argument, and your override option (env var `TEST_ENCLAVE`) is only used as the _default for --enclave-type_, this is not possible.
This fixes that. Rather than appending to the command line, a `Debug` or virtual-only build sets another env var, which is used as the default of `TEST_ENCLAVE` is unset. If `ctest` let us append args at runtime, without a rebuild, this would look a lot less weird (our manual override could be an additional arg, rather than an env var).

Set default enclave type by env var, not Python arg

---

samples/apps/smallbank/fbs/tests/small_bank_serdes_bench.cpp
src/consensus/pbft/pbft_types.h
src/crypto/hash.cpp
src/crypto/hash.h
src/crypto/test/crypto.cpp
src/node/history.h
src/node/signatures.h

`evercrypt_sha256` only worked for data sizes that were a multiple of 64, or less than 64. We missed this because our tests did not cover it, and our runtime hashing is all of 64-byte aligned data.
This fixes that, based on the [docs](https://hacl-star.github.io/EverCryptHash.html?highlight=evercrypt_hash_update_last#block-based-api) and some trial and error. I've also removed the `initializer_list` from the constructor, since we only ever use a single `CBuffer`. If we need to hash non-contiguous data in future, its possible but awkward with evercrypt (all but the last block _must_ be 64-byte aligned, or we must copy). We can re-implement this slow path on demand.

Fix how evercrypt hashing is called

---

edl/ccf.edl
src/ds/messaging.h
src/enclave/ccf_v.h
src/enclave/enclave.h
src/enclave/enclave_time.h
src/enclave/main.cpp
src/host/enclave.h
src/host/main.cpp
src/host/time_updater.h
src/host/timer.h

Opening as a draft to see how this affects performance.
We have worker threads inside the enclave, and sometimes they want to idle because there is no work today. Currently they busy-wait with `__mm_pause`, which may do nothing, and wastes processor time. To actually idle, they need some concept of time, and a way to sleep. This PR adds that concept of time (with a uv job on the host writing time to a known memory location, which the enclave reads), and a sketch of backoff behaviour (busy-wait for a while, then start sleeping for chunks of time). If this works, I'll look at a more precise idle notification system (OCalling to wait on a `condition_variable` in host-space).

Get time in enclave from host memory, not OCall

---

.azure-pipelines-templates/checks.yml
tests/connections.py
tests/e2e_batched.py
tests/e2e_suite.py
tests/infra/ccf.py
tests/infra/clients.py
tests/infra/consortium.py
tests/infra/logging_app.py
tests/infra/member.py
tests/infra/node.py
tests/late_joiners.py
tests/schema.py
tests/suite/test_requirements.py
tests/suite/test_suite.py

Fixes failed CI with new pylint version:
```
************* Module tests
1,0,fatal,parse-error:error while code parsing: Unable to load file tests/__init__.py:
[Errno 2] No such file or directory: 'tests/__init__.py'
```

Fix for pylint 2.5.0

---

.azure-pipelines-gh-pages.yml
.azure-pipelines.yml
.daily.yml
docker/app_ci
getting_started/setup_vm/roles/openenclave/vars/common.yml

I've rebuilt the perf CI machines on OE 0.9 as well.

Use 0.9 release of OpenEnclave

---

tests/infra/remote.py
tests/sgxinfo.sh

Failing to run one of these steps shouldn't halt the entire script. Changes output on driverless boxes from
```
$ ./tests/sgxinfo.sh 
DRIVER INFO:
libkmod: ERROR ../libkmod/libkmod.c:586 kmod_search_moddep: could not open moddep file '/lib/modules/4.4.0-18362-Microsoft/modules.dep.bin'
modinfo: ERROR: Module alias intel_sgx not found.
```
to
```
$ ./tests/sgxinfo.sh 
DRIVER INFO:
libkmod: ERROR ../libkmod/libkmod.c:586 kmod_search_moddep: could not open moddep file '/lib/modules/4.4.0-18362-Microsoft/modules.dep.bin'
modinfo: ERROR: Module alias intel_sgx not found.
PSW INFO:
...
DCAP CLIENT INFO:
...
SGX INFO:
./tests/sgxinfo.sh: line 23: /opt/openenclave/bin/oesgx: No such file or directory
```

sgxinfo should run on driverless machines

---

src/ds/files.h
src/host/main.cpp

Resolves https://github.com/microsoft/CCF/issues/1097
Note that we can't use `CLI11`'s `NonexistentPath` validation as the `ledger_file` _should_ be specified when a node starts in `recover` mode.

Check that ledger file does not exist on start/join

---

src/http/http_endpoint.h
src/node/rpc/forwarder.h
tests/e2e_logging.py

Close connection on malformed input, test. When forwarding, catch invalid requests

---

sphinx/source/conf.py

The CI didn't run on these changes in the PR, because it was purely under Sphinx. But it does run on master, and fails. We should probably remvoe the exceptions, but here's a quick fix.

Fix formatting

---

sphinx/source/conf.py
src/node/quote.h

Resolves https://github.com/microsoft/CCF/issues/1086
`crypto::Sha256Hash::SIZE` is `32` while `parsed_quote.report_data_size` is `64`.

Fix report size 

---

.azure-pipelines-templates/install.yml
check-cmake-version-vs-tag.sh
cmake/ccf_app.cmake

2-part fix for #1120:
- When building install folder in ADO, include the current OE installed dir
- When trying to find the OE package in CMake, prefer a local instance if found
Sample release available here until I delete it: https://github.com/microsoft/CCF/releases/tag/untagged-bfa184e16a4d52090092
This only increases the size of our install package slightly - from 55.4MB in 0.9.3 to 63.5MB on current master with OE.

Copy OE into install dir

---

.devcontainer/devcontainer.json

Making this change as OpenEnclave 0.9 release is being installed in new setups due to #1103

Update devcontainer.json to use oe-0.9.0 container

---

src/node/rpc/common_handler_registry.h
src/node/rpc/test/tx_status_test.cpp
src/node/rpc/tx_status.h

The assumption in the removed tests is incorrect: after we win an election, there is a period where we can serve RPCs (producing valid new `Pending` Tx IDs) but the highest committed Tx ID is still in the previous view. So this case shouldn't throw an error, it should fall through to `views_match => Pending`.
This RPC should also not be `execute_locally` (this was my misunderstanding - the common case of `getCommit` still requires consensus, so `tx` does as well).
These should resolve some of our transient CI failures.

Remove incorrect error on tx status RPC

---

cmake/pbft.cmake

Replacing all `CMAKE_SOURCE_DIR` to `CMAKE_CURRENT_SOURCE_DIR` in `pbft.cmake` as cmake breaks on using CCF as a subfolder in other repos.

Switching to CMAKE_CURRENT_SOURCE_DIR in pbft.cmake

---

tests/e2e_suite.py

This fixes a bug in #1146 which caused a failure in the Daily CI. The `recovery_test_suite` should only be running the declared subset of tests, but since it appends to the default argument it always included `all` tests.

Don't run all tests in recovery-specific suite

---

src/apps/lua_generic/test/lua_generic_test.cpp
src/consensus/pbft/libbyz/client_proxy.h
src/consensus/pbft/libbyz/replica.cpp
src/consensus/pbft/libbyz/req_queue.cpp
src/consensus/pbft/libbyz/req_queue.h
src/consensus/pbft/libbyz/request.cpp
src/consensus/pbft/libbyz/test/replica_unit_tests.cpp
src/consensus/pbft/pbft.h
src/consensus/pbft/pbft_config.h
src/crypto/symmetric_key.cpp
src/crypto/symmetric_key.h
src/ds/logger.h
src/ds/messaging.h
src/ds/test/messaging.cpp
src/ds/thread_ids.h
src/ds/thread_messaging.h
src/enclave/enclave.h
src/enclave/main.cpp
src/enclave/thread_local.cpp
src/enclave/tls_endpoint.h
src/http/http_endpoint.h
src/node/channels.h
src/node/test/channels.cpp

Fix for #1162. I believe this leak could only happen in the unit test, so this _removes_ the unrelated thread-messaging from this unit and adds some checks to make sure we don't trigger a similar issue in real nodes.
There's a few aspects to this fix:
- Rather than accessing the `thread_ids` map directly by `operator []`, call `get_current_thread_id` which uses `find` and throws an error if the thread hasn't been registered yet
- Move thread-message handling into the `IdleHandler`, so it doesn't need to be initialised in the messaging unit tests or benchmarks
Separately I've moved these from `enclave::` to `threading::`. There's still an awkward case around startup where we may access the thread ID (eg - for logging) before we've initialised the map (in the `enclave_run` ECALL). Here I …

Safe read access to thread_ids

---

src/consensus/pbft/libbyz/new_view.cpp
src/consensus/pbft/libbyz/new_view.h
src/consensus/pbft/libbyz/node.cpp
src/consensus/pbft/libbyz/node.h
src/consensus/pbft/libbyz/nv_info.cpp
src/consensus/pbft/libbyz/pre_prepare.cpp
src/consensus/pbft/libbyz/prepared_cert.h
src/consensus/pbft/libbyz/view_change.cpp
src/consensus/pbft/libbyz/view_change.h

Regarding #459 
- Add `View_change` message digest signatures in `New_view` 
- Verify those signatures in `New_view::pre_verify()` and check that we have at least `2 * f + 1` of them, and if not verification fails
- Remove redundant signing over the contents of `View_change` messages, since we already sign over the digest of the contents
- Added a helper method to copy signatures when needed
Next: process new view messages during playback

Add and verify view change signatures in new view message

---

src/ds/cli_helper.h
src/host/main.cpp
src/host/node_connections.h
src/host/rpc_connections.h
src/host/tcp.h
tests/infra/node.py
tests/infra/remote.py

This PR adds support in a CCF node for specifying port 0 (or, equivalently, not giving a port at all), in which case a port is automatically assigned by the OS, for the RPC and node-to-node listen addresses. The bound address (whether assigned or specified explicitly) and DNS-resolved IP address are logged, and optionally dumped to a file for automated parsing.
The Python infra uses this automatic assignment for all nodes, rather than probing for a free port (and hoping both that this is released by the OS before the node gets there, and not rebound by something else).
Fixes #1164.

Support automatic port assignment

---

.azure-pipelines-templates/install.yml
doc/index.rst
doc/members/accept_recovery.rst
doc/users/deploy_app.rst
src/host/main.cpp
tests/infra/ccf.py
tests/infra/consortium.py
tests/infra/e2e_args.py
tests/infra/member.py
tests/infra/node.py
tests/infra/remote.py
tests/memberclient.py
tests/recovery.py
tests/start_network.py

Resolves https://github.com/microsoft/CCF/issues/1095
This add a new feature to the `start_test_network.sh` script and underlying Python infra so that it is possible to recover a defunct service, i.e.:
```
$ ../start_test_network.sh -p liblogging.virtual.so
...
[2020-05-14 12:00:15.144]   Node [ 0] = 127.144.227.254:35945
[2020-05-14 12:00:15.144]   Node [ 1] = 127.29.10.59:44623
[2020-05-14 12:00:15.144]   Node [ 2] = 127.69.86.53:46645
...
^C
$ cp ./workspace/test_network_0/0.ledger .
$ cp ./workspace/test_network_0/network_enc_pubk.pem .
$ ../start_test_network.sh -p liblogging.enclave.so.signed --recover --ledger 0.ledger --network-enc-pubk network_enc_pubk.pem --common-dir ./workspace/test_network_common/ 
[2020-05-14 12:01:36.367] Starting 3 CCF nodes...
[2020-05-14 12:01:36.368] …
```

Use start_test_network.sh for recovery

---

docker/ccf_ci

Also renamed old container to ccfciteam/ccf-ci-18.04-oe-0.9.0:az-dcap-1.4, built and pushed ccfciteam/ccf-ci-18.04-oe-0.9.0:az-dcap-1.5 which latest now points to as well.
There should be a nicer, automated way to do this. It's not totally obvious what that is.

Switch to new playbook name

---

docker/ccf_ci
src/host/node_connections.h
tests/infra/member.py

fix #1147 
The gist of the problem is that when a node joins a network, and become a tie-breaker for the consensus (eg. an 8th node joining a 7 node network where 3 nodes are dead, in the case of the code update), there is a race between the join rpc poll and the waiting for the vote to be globally committed.
The new dcap client, which results in faster quote verification seems to have triggered this by making the initial delay shorter in the join RPC, which leads to the vote happening sooner, and the timeout sooner too, before the join RPC has time to poll again.
The code update test is a useful corner case test but not an accurate representation of what we expect a vanilla code update to look like. We ought to refactor it in a similar way to the reconfiguration test, modify it to …

Fix race condition in the code update test

---

tests/ws_scaffold.py

The PBFT version takes a particularly long time, because a full consensus round trip happens for each of the 1k requests (>1 minute), so making this test a bit more lightweight in requests.

Shorten WS tests

---

src/kv/experimental.h
src/kv/map.h
src/kv/test/kv_test.cpp
src/kv/tx_view.h
src/node/node_state.h

Fixes #1208.
The value type in a `Write` is now `std::optional<V>` instead of `VersionV<V>`. The version was supposed to be `NoVersion` to indicate a deletion, but all of our own hooks were ignoring `version` and accessing `value` directly. assuming it was a real written value. This is a breaking API change - even if you want to ignore the possibility of deletions, you now need to access the actual values by `.value()` (preferably gated by a check to `.has_value()`,) not `.value`.
Our hooks don't expect deletions and don't have anything sensible to do if they do occur, so they all simply throw an exception. It would be nice to have this expectation statically enforced (some kind of `NoRemovals` modifier type for a `kv::Map`, which returned `TxView`s with no `remove` method, and whose …

Make it harder to mistake deletions for legitimate writes in commit hooks

---

src/kv/experimental.h
src/kv/test/kv_test.cpp
src/kv/tx_view.h

Noticed as part of #1221 (and one need manually merging when the other goes in, due to similar changes in `tx_view.h`):
`TxView::foreach` takes a visitor lambda, and returning false is supposed to mean "I'm done, don't call me again". We need to run this twice, for both the original state and the current write set. The early-out-on-false behaviour only applied to the writes - if you decided you were done after looking at something in the state, you still get called with something in the write set. This fixes that - return false means you won't get called again at all.
On a related point, `foreach` itself returned a bool with no meaning. It could return "the lambda returned false at some point", or "you saw everything", but none of these seem particularly clear or useful. For clarity, I've …

Make the foreach early-exit semantics consistent

---

notice-check.py
src/consensus/pbft/libbyz/governance_update_tracking.h

Single pass for all headers, to allow moving code around, like in #1238. Coincidentally caught a missing header that the old code didn't.

Unify header check

---

src/consensus/pbft/libbyz/certificate.h
src/consensus/pbft/libbyz/client_proxy.h
src/consensus/pbft/libbyz/digest.cpp
src/consensus/pbft/libbyz/message.cpp
src/consensus/pbft/libbyz/node.cpp
src/consensus/pbft/libbyz/nv_info.cpp
src/consensus/pbft/libbyz/pre_prepare.cpp
src/consensus/pbft/libbyz/rep_info.cpp
src/consensus/pbft/libbyz/replica.cpp
src/consensus/pbft/libbyz/request.cpp
src/consensus/pbft/libbyz/state.cpp
src/consensus/pbft/libbyz/status.cpp
src/consensus/pbft/libbyz/view_info.cpp
src/consensus/pbft/pbft.h
src/ds/ccf_assert.h
src/host/main.cpp
src/http/http_endpoint.h
src/kv/store.h
src/kv/tx.h
src/node/node_state.h
src/node/rpc/forwarder.h
src/node/rpc/frontend.h

- remove any data that should not be printed on a prod service that has a log level of Info+
- change to use LOG_*_FMT for fatal, fail, and info.
resolves #1239 
part of #691

Clean up logging

---

tests/e2e_logging.py
tests/e2e_scenarios.py

We were not waiting for the other replicas to catchup properly. Since there are tests that validate catchup these tests do not need to do that so only use 3 replicas.
This also resolves the issue of a replica crashing and us not seeing the crash because recovery masks the failure.

Fix e2e test

---

.azure-pipelines-templates/daily-matrix.yml

This test takes a long time to run with SAN turned on. It is on in all other configurations.
this is related to #1244

turn off the replay_new_view_pbft for SAN builds

---

src/node/historical_queries.h
src/node/test/historical_queries.cpp

Following #1267 and #1273, enable the intended merkle tree verification.

Historical queries - verify that expected hash is in signature's merkle tree

---

src/apps/logging/logging.cpp
src/apps/logging/logging_schema.h
src/apps/lua_generic/test/lua_generic_test.cpp
src/lua_interp/lua_args.h
src/node/historical_queries_interface.h
src/node/rpc/handler_registry.h
src/node/rpc/json_handler.h
src/node/rpc/test/frontend_test.cpp
tests/e2e_logging.py

Follow up to #1267.
Pulls some common functionality that will be required for many historical queries (find out what transaction it is asking for, find out whether the transaction is valid, find out whether we have that transaction cached) into `ccf::historical::adapter`. I think this is a useful simplification; the body of `get_historical` in `logging.cpp` is now far more readable.
Remaining TODOs, currently aimed at future PRs:
- Finish verification of historical stores (#1278)
- Handle range queries

Build common helper/adapter for historical queries

---

src/enclave/enclave.h
src/node/history.h
src/node/test/merkle_bench.cpp

Daily SAN build caught an issue, fixed in `enclave.h`. Accessing members inside a constructor's initializer list is dodgy, and in this case hit UB that the SAN noticed (space for the objects is allocated, but they've not actually been constructed, so accessing any of their fields is frowned upon). To break this circular dependency, we construct the `NodeState` _after_ the initializer list has completed, when it can safely access `context.notifier`.
The `Receipt` change is probably unnecessary, but just for safety, disabling its copy constructor.

Fix recently introduced SAN errors

---

src/node/history.h
tests/receipts.py

In #1278 I changed our compaction behaviour, to compact all the way to the requested index rather than maintaining `MAX_HISTORY_LEN` old entries. I've worked out why that was a mistake - we can only generate receipts for the in-memory, non-flushed tree. We could look at using the historical state cache to serve arbitrarily old receipts instead, but for now I'm restoring the old behaviour.

Restore historical receipts

---

tests/e2e_logging.py
tests/e2e_scenarios.py
tests/infra/checker.py
tests/infra/clients.py
tests/infra/member.py
tests/reconfiguration.py
tests/rekey.py

Transactions that contain no KV reads nor writes effectively have no position in the total order. We should never rely on the seqno they current return (pending removal) for anything.

Remove usage of NoKV transaction seqnos

---

src/enclave/enclave.h
src/enclave/interface.h
src/host/handle_ring_buffer.h
src/host/ledger.h
src/host/sig_term.h

Locally solves the CI issue experienced on #1274 
We were calling `uv_stop()`, which is not [async-signal-safe](https://github.com/libuv/libuv/issues/2173#issuecomment-460566756), from the signal handler for `SIGTERM`. This PR adds another `enclave -> host` ring buffer message so that the uv loop is only closed once the enclave has acknowledged to the host that it has stopped, leaving the `SIGTERM` handler very short.
It is not 100% clear to me whether the double free issue was caused by this but it seems like a necessary change anyway. Fixing #1274 will hopefully be confirmed once this PR is merged.

Do not stop uv loop from signal handler

---

.azure-pipelines-templates/checks.yml
.azure-pipelines-templates/matrix.yml
.azure-pipelines-templates/release_checks.yml
CMakeLists.txt
check-cmake-version-vs-tag.sh

We used to run `check-cmake-version-vs-tag` on every CI run. It checked that the most recent git tag specified a version <= the cmake version. The idea was to stop us releasing 0.42 with binaries that claimed they were 0.41. This didn't support pre-release identifiers.
Now we can specify pre-release identifiers in CMake (via `CCF_PROJECT_NAME_SUFFIX`), the script looks for exact equality, and it only runs in the release CI. So master's VERSION, as specified in CMake, can jump backwards and forwards as much as we like, but at the point we produce a _tag_  it must exactly match the tag's version.

Only compare versions in release, and support pre-release identifiers

---

src/ds/champ_map.h
src/ds/test/map_test.cpp
src/kv/kv_types.h
src/kv/map.h
src/kv/store.h
src/kv/test/kv_test.cpp
src/kv/untyped_map.h

- serialize all the maps
- only lock the maps when taking a copy of the required champ map
- add key and value serializers to enable serializing complex types
part of #1299

Serialize the Maps

---

src/ds/json_schema.h
src/ds/nonstd.h
src/ds/ring_buffer_types.h
src/ds/serializer.h
src/kv/serialise_entry_blit.h

I keep finding reasons to redefine `dependent_false`. This moves it, and some other potentially generally useful trait helpers, to a single location.

Add ds/nonstd.h with some useful type traits

---

cmake/ccf_app.cmake
cmake/common.cmake

Install the virtual, debug, and release variants of js_generic, so they are part of our releases.

Install JS Generic

---

doc/developers/api.rst
doc/developers/logging_cpp.rst
doc/members/accept_recovery.rst
doc/members/adding_member.rst
doc/members/common_member_operations.rst
doc/members/member_rpc_api.rst
doc/members/open_network.rst
doc/members/proposals.rst
doc/schemas/user_id_params.json
doc/schemas/user_id_result.json
doc/users/issue_commands.rst
doc/users/rpc_api.rst
samples/apps/txregulator/clients/loader.py
samples/apps/txregulator/tests/txregulatorclient.py
samples/perf_client/perf_client.h
src/consensus/pbft/pbft_config.h
src/enclave/enclave.h
src/enclave/rpc_map.h
src/http/http_endpoint.h
src/node/entities.h
src/node/node_state.h
src/node/rpc/call_types.h
src/node/rpc/common_endpoint_registry.h
src/node/rpc/endpoint_registry.h
src/node/rpc/forwarder.h
src/node/rpc/serialization.h
tests/governance_history.py
tests/infra/node.py
tests/submit_recovery_share.sh

Fixes #1322.
Renames:
- `/users` => `/app`
- `/members` => `/gov`
- `/nodes` => `/node`
If the old names are used, returns a `308 Permanent Redirect` response pointing to the new prefix. We only do this check on the first node, which I think is safe? Perhaps a mismatch (between "what prefix did they give me" and "what prefix would I like to see") in the pbft or forwarded cases should be an error?

Rename URI prefixes

---

.gitattributes

An odd diversion. This is wrong:
[This](https://github.com/github/linguist#overrides) is the system that builds this, and how it is overridden.
Before:
```
$ github-linguist --breakdown
83.44%  C++
11.33%  Python
2.34%   CMake
1.32%   Objective-C
0.73%   Shell
0.48%   Lua
0.22%   C
0.10%   XSLT
0.03%   JavaScript
...
C:
src/consensus/pbft/libbyz/bits.h
src/consensus/pbft/libbyz/ledger.h
src/consensus/pbft/libbyz/partition.h
src/consensus/pbft/libbyz/time_types.h
src/enclave/consensus_type.h
src/kv/kv_serialiser.h
src/tls/random_bytes.h
src/tls/tls.h
Objective-C:
src/ds/ccf_deprecated.h
src/ds/test/siphash_known_hashes.h
...
```
After:
```
$ github-linguist 
85.03%  C++
11.28%  Python
2.36%   CMake
0.73%   Shell
0.47%   Lua
0.10%   XSLT
0.03%   JavaScript
```

Correct language statistics via linguist gitattributes

---

doc/developers/kv/api.rst
doc/developers/kv/kv_how_to.rst
doc/developers/kv/kv_serialisation.rst
doc/developers/ledger.rst
src/kv/map.h
src/kv/test/kv_serialisation.cpp

Moved from `kv_how_to` to `kv_serialisation`, added current detail with snippets from unit test.
Fixes #531.

Add docs on custom KV serialisers

---

CMakeLists.txt
doc/developers/ledger.rst

Before:
```
$ cmake .. -UCMAKE_INSTALL_PREFIX
-- CCF version=ccf-0.11.1
-- CCF release version=0.11.1
-- CMAKE_INSTALL_PREFIX is '/opt/ccf/ccf-ccf-0.11.1'
```
After:
```
$ cmake .. -UCMAKE_INSTALL_PREFIX
-- CCF version=ccf-0.11.1-3-g99e8c55a
-- CCF release version=0.11.1
-- CMAKE_INSTALL_PREFIX is '/opt/ccf/ccf-0.11.1'
```

Don't double-prefix the install directory

---

getting_started/setup_vm/app-dev.yml
getting_started/setup_vm/app-run.yml
getting_started/setup_vm/ccf-dev.yml
getting_started/setup_vm/roles/ccf_build/tasks/install.yml
getting_started/setup_vm/roles/ccf_build/vars/common.yml
getting_started/setup_vm/roles/ccf_run/vars/common.yml
getting_started/setup_vm/roles/llvm_repo/tasks/install.yml
getting_started/setup_vm/roles/llvm_repo/vars/common.yml

Recent run containers are missing libc++ and libc++abi, this is adding them explicitly.
Also adding clang-format as a convenience in ccf_build/ccf-app-ci, not strictly required but quite useful when building native apps, and consistent with our inclusion of tools serving similar purposes such as doxygen.
```
root@c4a0ab881a02:/# /usr/bin/cchost -v
CCF host: ccf-0.11.1
root@c4a0ab881a02:/# ldd /usr/bin/cchost | grep libc++
libc++.so.1 => /usr/lib/x86_64-linux-gnu/libc++.so.1 (0x00007fa01ba8c000)
libc++abi.so.1 => /usr/lib/x86_64-linux-gnu/libc++abi.so.1 (0x00007fa01b85c000)
```
Edit: I intend to cut 0.11.2, to avoid leaving the app_run container broken.

Update container dependencies

---

src/node/rpc/frontend.h
src/node/rpc/test/frontend_test.cpp

Now that we drop all views when a transaction conflicts (rightly so!), we need to make sure that the client signature is not dropped if the execution of our RPC endpoint conflicts.

Do not drop client signature if transaction conflict

---

src/node/node_state.h

Resolves #83
Fixes a very old issue that can now be fixed trivially now that they way we manager TLS connection endorsement/opening of frontends has changed.
The member frontend is now only opened _after_ the public ledger has been recovered. The node frontend can still be used to check on the progress of the public recovery.

Move opening to after public ledger is recovered

---

tests/infra/remote.py
tests/infra/remote_client.py

For some time our perf runs have been failing to retrieve `perf_summary.csv`. This fixes that.

Respect relative path in LocalRemote.get

---

scripts/notice-check.py

Previously if I ran `ci-checks.sh` locally, I'd get lots of failures from `notice-check.py`:
```
...
Copyright notice missing from ./build.debug/cmake_install.cmake
...
```
because I have a lot of builds in directories not called `build/`. These are listed in `.gitignore`, so I've updated `notice-check.py` to ignore anything which Git is going to ignore. I was going to add this more generally to `ci-checks.sh`, but everything else runs on specific folders (`src/` and friends) so this was only a problem with `notice-check.py`, since it does `os.walk(".")`

Use gitignore in notice-check.py

---

doc/users/rpc_api.rst

As noted in #1375, if users try to use this sample command from our docs they'll get a non-obvious error message. The quotes around `"tx"` are actually being swallowed by the terminal so we send a query string `?method=tx`, and then we try to parse the right-hand side as JSON and fail.
This is an unfortunate knock-on of trying to retain our JSON parsers for query-string arguments, which we actually use in very few places. I plan to remove this, so endpoints can accept the more obvious `method=tx` if they wish. A slight extension to this is that we're discussing removing `json_handler` from the public API entirely, since it introduces obscure requirements like this which only complicate app development.

Update curl sample line so quotes aren't swallowed by terminal

---

CMakeLists.txt
cmake/common.cmake
doc/developers/demo.rst

One of our most thorough tests is `end_to_end_logging_`. This often picks things up in the CI that other tests miss, as it tests all the obscure variants of our endpoints.
However, it is also one of the most difficult to run in isolation, because `ctest` is useless. The usual way to run a single `ctest` is with a regex, but:
```
$ ctest -N -R end_to_end_logging_raft
Test project /data/src/2.CCF/build
Test #58: js_end_to_end_logging_raft
Test #61: lua_end_to_end_logging_raft
Test #66: end_to_end_logging_raft
Total Tests: 3
```
I don't want the `js_` and `lua_` variants which do a subset of the work. So previously I needed to run some `-N` that would include this good test, then the devil-summoning `ctest -VV -I 66,66`. (NB: You can't add `-I 66,66` to the previous command, because even …

Give the C++ e2e logging test a uniquely regexable name

---

src/kv/msgpack_serialise.h

Fixes daily SAN `kv_test` failure: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=10660&view=logs&j=383d248c-4494-5797-d98f-6cef5140601e&t=bbcdfa66-260b-5619-96df-9537b476c35e&l=195
We should not serialise a raw entry if its size is 0 - which happens in the case of snapshots when a map is empty.
Daily build run for this PR (in progress): https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=10670&view=results

Do not serialise if length of vector is 0

---

cmake/common.cmake

Before:
```
$ find /opt/ccf-0.11.7-31-g89ccf662/ -type f -regex ".*\.sh$"
/opt/ccf-0.11.7-31-g89ccf662/BIN/keygenerator.sh
/opt/ccf-0.11.7-31-g89ccf662/BIN/submit_recovery_share.sh
/opt/ccf-0.11.7-31-g89ccf662/BIN/scurl.sh
/opt/ccf-0.11.7-31-g89ccf662/getting_started/setup_vm/run.sh
/opt/ccf-0.11.7-31-g89ccf662/getting_started/create_vm/destroy_vm.sh
/opt/ccf-0.11.7-31-g89ccf662/getting_started/create_vm/pre_make_vm.sh
/opt/ccf-0.11.7-31-g89ccf662/getting_started/create_vm/make_vm.sh
/opt/ccf-0.11.7-31-g89ccf662/bin/keygenerator.sh
/opt/ccf-0.11.7-31-g89ccf662/bin/submit_recovery_share.sh
/opt/ccf-0.11.7-31-g89ccf662/bin/scurl.sh
/opt/ccf-0.11.7-31-g89ccf662/bin/sgxinfo.sh
```
After:
```
$ find /opt/ccf-0.11.7-33-g3baa6444/ -type f -regex ".*\.sh$" …
```

Install utils in bin, not BIN

---

src/ds/champ_map.h
src/ds/test/map_test.cpp

Noticed this when plugging the new snapshot mechanism into the rest of CCF. The size of the pre-insertion serialised K,V pair returned by `put_mut()` was actually the size of the post-insertion serialised K,V. This worked so far in our unit tests because we use same keys and values but didn't in the case of the `ccf.member_acks` table which changes in size as members ack.

Snapshot size calculation fix

---

tests/infra/e2e_args.py
tests/infra/network.py
tests/start_network.py

Fix daily build failure, caused by the code changes in [#1415](https://github.com/microsoft/CCF/pull/1415/files#diff-797fc5ba90a3fcd2d165899c4b735d24). We don't need a normalised abs path (what the previous code did), just an abs path. Additionally, we can't make it required because its actually _not_ required for the `--recover` case. ~~This sadly means it is not required for anything apart from `start_network.py`, but if its ever missing we'll get ugly errors later...~~ Instead, we assert its set just before use, at least getting a clear error.

Fix --gov-script requirements

---

tests/e2e_batched.py

`lua_e2e_batched` is failing occasionally in the CI. Looks like the "wait 3 seconds for dying node to terminate" is not always long enough. This extends the timeout to 10s, but polls more rapidly, so we should wait _less_ time when the node actually terminates straight away.

Allow longer for e2e_batched timeout

---

.azure-pipelines-gh-pages.yml

[This run](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=11041&view=logs&j=f1fd332c-cd58-5ba4-fc7d-3c1d3a3f0cd3&t=2dc3064a-1eab-55f1-840a-179a38037e58) is a failure with the debugging from #1438, and it looks like `git rev-parse HEAD` is the correct current commit hash even when `BUILD_SOURCEVERSION` is wrong.
Its possible that `git checkout -b master` is sufficient here (we're trying to create a branch from the current state, called master, to satisfy `sphinx-multiversion`), but this is hard to reproduce or verify so going with the safer option.

Optimistic fix for GH Pages CI failures

---

python/ccf/clients.py
src/node/rpc/endpoint_registry.h
src/node/rpc/frontend.h
src/node/rpc/node_frontend.h
tests/e2e_logging.py

As requested by @syhamza, for load balancing purposes, this adds a `/node/primary` which will either return 200 if the node is primary, or 308 and attempt to redirect to the primary if possible.

Primary endpoint

---

.azure-pipelines-templates/release.yml
python/README.md
python/setup.py
tests/requirements.txt

Automated PyPi releases (this time, to the real PyPi!)
The version number is hardcoded to `0.12` for now. A further PR will address that so that it is derived from the git tag/cmake version.

PyPi releases

---

doc/members/open_network.rst
doc/members/proposals.rst
doc/schemas/log/private/admin_only_POST_params.json
doc/schemas/log/private/admin_only_POST_result.json
src/apps/logging/logging.cpp
tests/e2e_logging.py
tests/suite/test_suite.py
tests/ws_scaffold.py

Fixes #1397.
- Adds `/app/log/private/admin_only` to the C++ logging app, using user-data as a very primitive ACL
- Expands documentation on `set_user_data` proposals
- Adds test case in `e2e_logging.py`

Test and document set_user_data

---

python/ccf/clients.py
tests/suite/test_requirements.py

While trying to repro a failure in `full_test_suite`, I noticed we've been silently skipping one of the tests for a while:
```
2020-07-29 10:14:06.413 | WARNING  | __main__:run:141 - Test #25:
{
"name": "election.test_kill_primary",
"status": "skipped",
"elapsed (s)": 0.07,
"reason": "Could not check if test requirements were met: Request client failed with unexpected error"
}
```
The error is trivial, a missing `/` prefix when constructing a requirement-checking request. Now we enforce that all request paths include this prefix. Open to suggestions if anyone sees a neater way to handle requirement failures to ensure these skips are louder in future.

Require / prefix on URL paths in Python

---

doc/quickstart/index.rst

VS Code has added a new and excellent tutorial page for the SSH extension.

Add link to remote SSH tutorial

---

cmake/ccf_app.cmake
cmake/common.cmake
src/apps/js_generic/oe_sign.conf
src/apps/logging/oe_sign.conf

Fixed #1466 
Mostly moving LVI CMake machinery from `common.cmake` to `ccf_app.cmake`. Also installing the LVI cmake files.
While testing I noticed something else:
`oesign` now throws an error if it sees multiple `Debug=X` entries in an `oe_sign.conf` (previously it happily used the latter). This means our old approach of appending `Debug=1` or `Debug=0` for `.debuggable`/`.signed` builds no longer works if apps have an explicit `Debug=X` in their `.conf`. So now the CMake trickery says "sed replace if its already there, else append". Getting this ternary command through CMake's command mangling was surprisingly awkward, so the resulting (formatted) CMake is _ugly_.

Support LVI when building from installed CCF

---

scripts/check-cmake-format.sh

Since the last release (0.6.11) of `cmake-format`, it dumps the contents of correctly formatted files to std out in `--check` mode. This fills our CI `Checks` output [with CMake](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=11520&view=logs&j=435ca956-9126-505f-566f-fff31072e2ba&t=fd2f8e8e-b3a5-5d78-5a6a-df40f62a292a).
For now we pipe the results to `/dev/null` to ignore them.

Redirect cmake-format --check output to /dev/null

---

tests/connections.py

Our `connections_test` e2e test is intended to test the behaviour of a CCF node when the file descriptor cap is reached. It does this by setting a low cap, and then creating many connections to the CCF node. However, creating our Python client connection doesn't necessarily claim a fd - this is only done lazily, at the first message on that connection.
This PR updates the test to send logging messages from the create connections, and asserts that once the cap is reached any future connections will receive errors.

Ensure connections_test actually creates and exhausts fds

---

python/ccf/proposal_generator.py

I noticed that `trust_node` and `retire_node` proposals generated by `proposal_generator` weren't actually useable, because they placed strings into the proposals rather than the int we require. Luckily we now have type annotations, so we can pass them to `argparse` and get the correct result (with an extra hack to load json dicts).

Add inspected types to proposal_generator CLI args

---

src/ds/serialized.h
src/ds/test/ring_buffer.cpp

Fixes #799.
The assignments in the generic templates of `serialized::read` and `serialized::write` are technically UB, since they can (and do!) result in misaligned loads/stores. All the platforms and compilers we care about will do the correct thing here, but to be safe I've replaced the problematic lines with explicit `memcpy`s. I believe these should compile to the same things, and a quick [godbolt experiment](https://godbolt.org/z/KhdfjG) seems to back that up.

Remove misalignment UB

---

python/ccf/proposal_generator.py
src/apps/lua_generic/test/lua_generic_test.cpp
src/node/genesis_gen.h
src/node/rpc/member_frontend.h
src/node/rpc/test/frontend_test.cpp
src/node/rpc/test/member_voting_test.cpp
tests/governance.py
tests/infra/consortium.py

Previously users needed to be added by a `"new_user"` proposal, and then could have user data set by `"set_user_data"`. This requires finding the assigned user ID (which is hard to do, and should be easier!), and enforces a period of time where the user has no user data.
This changes the expected data for `"new_user"`s from just a cert to a full `UserInfo` object, potentially including an initial `user_data` value.

Allow user_data to be set during new_user proposal

---

.azure-pipelines-gh-pages.yml
python/setup.py.in

Looks like I broke the generation of Python docs in https://github.com/microsoft/CCF/pull/1474 as `setup.py` is only generated after cmake is run (for automated versioning).

Generate setup.py before installing docs

---

src/enclave/main.cpp
src/enclave/oe_shim.h

When our `oe_is_within_enclave` checks fail, it is possible for speculative execution to reveal enclave data past the execution point. While we run these checks at initialisation and are unlikely to have any interesting secrets at this time, its best to be sure. So I'm adding lfences to prevent speculative execution over these boundaries.

lfence after memory validation

---

CMakeLists.txt
doc/operators/ledger.rst
src/host/main.cpp
start_test_network.sh
tests/infra/e2e_args.py
tests/infra/network.py
tests/infra/remote.py

The `cchost` option to specify the chunking threshold (in bytes) was named `--ledger-chunk-max-bytes` but the description was `"Minimum size (bytes) at which a new ledger chunk is created"`. The description is right: we create a new chunk only if the threshold has been passed _and_ a signature transaction has been issued so the size of a ledger chunk will always be slightly above the threshold. 
The option is now named `--ledger-chunk-min-bytes` for consistency.

The cchost ledger-chunk-max-bytes option was badly named

---

src/host/main.cpp
src/host/timer.h

Suggestion from @achamayou to make the times specified in `host/main.cpp` more readable.

Add ms units to Timer repeat argument

---

python/ccf/proposal_generator.py
tests/infra/consortium.py

#1493 has exposed that our `ProposalGenerator`'s dynamically set attributes make it hard for mypy to typecheck. After further thought its not clear that this functionality is worth exposing in our public API. If users want to dump the proposals to file (as `consortium.py` does), they can do so themselves.
This PR deletes `ProposalGenerator`.

Remove ProposalGenerator

---

src/kv/store.h
src/kv/test/kv_dynamic_tables.cpp
src/kv/test/kv_test.cpp
src/kv/tx.h

Follow up to #1507 implementing 2 suggestions:
- Indicate that the new KV APIs are experimental, unstable, and should not be used.
- Test `swap_private_maps` with dynamically created tables (and partially rewrites to support this). This actually removes an existing test of `Invalid map swaps` - it is now perfectly valid to have additional or missing tables in the target store, all we do is copy in those from the source store.

Dynamic map swaps

---

src/consensus/raft/raft.h
tests/e2e_logging.py

The way we used to build the term history on backup was buggy when we had signatures _across different terms_ in the same append entries batch. As we didn't have any tests that compared the term history between nodes, we didn't see that small difference. This is now fixed and the `test_view_history` end-to-end test now compares the view history between all nodes active in the network.
**Details:**
The fix is to call `commit_if_possible(r.leader_commit_idx)` early after we've passed a signature in the append entries batch (which will update `commit_idx` to the index of that first signature). That way, the call to `term_history.update(commit_idx + 1, sig_term)` after the next signature (in the new term) will create a new term in the term history, starting at the index right after the …

Fix Raft term history on backup

---

scripts/check-format.sh
scripts/ci-checks.sh

`-f` was broken for clang-format.
This also adds `-U` to `pip install` to avoid using old dependency versions and potentially formatting/linting files differently than in CI.

Fix ci-checks scripts

---

.azure-pipelines-templates/release.yml

Otherwise, `setup.py` will not be generated (cmake generates `setup.py` with the right version from `setup.py.in`).

Run cmake before release

---

CMakeLists.txt
cmake/common.cmake
src/tls/asn1_san.h
src/tls/key_pair.h
src/tls/test/cert.cpp
tests/certs.py

`x509write_crt_set_subject_alt_name()` does not support adding multiple subject alternative names to a cert, so this adds a `x509write_crt_set_subject_alt_names()` which does.

Extend asn1_san to support multiple entries

---

src/enclave/main.cpp
src/enclave/oe_shim.h

Adjustment to #1492, which introduced range checks that weren't quite right. We want to check that the entire buffer subject to user_check is strictly outside enclave memory (https://github.com/openenclave/openenclave/blob/b9ae53c1e580fd1af4760f914d53cba1650068ae/include/openenclave/enclave.h#L105) and fail if it's not.
Current code instead checks for strictly in-enclave buffers, and would therefore be satisfied by a partially in-enclave buffer.

Fix memory range check on ecall

---

python/ccf/proposal_generator.py
src/node/rpc/member_frontend.h
tests/code_update.py
tests/infra/consortium.py
tests/infra/network.py

It is currently possible to retire code with a `raw_puts` proposal, but this is slightly more obvious. We were also missing a test for this.

Add retire_node_code proposal

---

python/ccf/proposal_generator.py
src/runtime_config/gov.lua
tests/modules.py

Update collections of JS modules in one proposal

---

cmake/ccf_app.cmake
cmake/common.cmake

This option doesn't play nicely with the SAN builds. I got a lucky combination on a local build that gave a huge amount of errors:
```
/data/src/CCF/build.san/../src/enclave/thread_local.cpp:(.text.startup+0x2d): undefined reference to `__asan_before_dynamic_init'
/data/src/CCF/build.san/../src/enclave/thread_local.cpp:(.text.startup+0x34): undefined reference to `__asan_option_detect_stack_use_after_return'
/data/src/CCF/build.san/../src/enclave/thread_local.cpp:(.text.startup+0x43): undefined reference to `__asan_stack_malloc_0'
/data/src/CCF/build.san/../src/enclave/thread_local.cpp:(.text.startup+0x10e): undefined reference to `__asan_after_dynamic_init'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
It …

Remove --no-undefined in SAN builds

---

tests/reconfiguration.py

When running the full suite, we would run the `test_retire_primary` test case with as few as 3 nodes. This is insufficient - with 3 nodes, if we retire the primary, we don't have quorum to find a new primary and we're stuck. Instead the requirement is that we have at least 1 killable node.
This should fix some of the recent instability in our daily CI.
There's a followup task to find something I'm missing - if we run the reconfiguration suite as written, we're actually skipping this test:
```
42: 2020-09-04 17:03:49.316 | SUCCESS  | __main__:run:126 - Full suite passed. Ran 9/9
42: 2020-09-04 17:03:49.316 | SUCCESS  | __main__:run:141 - Test #0:
42: {
42:     "name": "reconfiguration.test_add_node",
42:     "status": "success",
42:     "elapsed (s)": 5.12
42: }
42: 2020-09-04 17:03:49.316 …
```

test_retire_primary requires at least 1 killable node

---

src/lua_interp/lua_kv.h
src/lua_interp/test/lua_kv.cpp

Spotted while debugging something else. When calling `tx:foreach( foo )` in Lua, any errors in foo would be silently ignored (they're invoked from a separate `lua_pcall`, and we were ignoring the return code from this). Errors in these functors are now raised as exceptions, the same as we do with any other lua error.

Propagate errors from foreach functors called in Lua

---

python/ccf/proposal_generator.py

When we made it possible to specify the user data at creation (ie - in the `new_user` proposal), we broke the CLI as this `user_data` argument was required (but unparseable) on the CLI.
Before:
```
$ python -m ccf.proposal_generator new_user --help
usage: proposal_generator.py new_user [-h] user_cert_path user_data
$ python -m ccf.proposal_generator new_user bob_cert.pem 
usage: proposal_generator.py new_user [-h] user_cert_path user_data
proposal_generator.py new_user: error: the following arguments are required: user_data
```
After
```
$ python -m ccf.proposal_generator new_user --help
usage: proposal_generator.py new_user [-h] user_cert_path [user_data]
$ python -m ccf.proposal_generator new_user bob_cert.pem
[2020-09-10 16:25:08.973] SUCCESS | Writing proposal to …
```

Support optional arguments when creating proposals via the CLI

---

src/kv/store.h
src/node/history.h

When a BFT backup receives a signature append entry it will validate the signature and compare it to its own merkle root (same as with cft).

AFT: verify signature on the backups

---

tests/e2e_logging.py

Fix the following warning
SyntaxWarning: "is not" with a literal. Did you mean "!="? verify=args.package is not "libjs_generic",

Fix python warning

---

CHANGELOG.md
getting_started/setup_vm/roles/ccf_build/vars/common.yml
src/ds/thread_messaging.h

Fixes a memory growth issue, where messages would be queued indefinitely for inactive threads.
The real fix is to loop `< thread_count` rather than `: tasks`. The rest of the diff is from pulling the inline lambda into `tick_cb`.

Only send Tick messages to live threads

---

src/ds/test/messaging.cpp
src/ds/thread_messaging.h

Always call get_task when getting and task queue and then have an assert in said function to ensure the queue we are returning will eventually be polled

Ensure that we cannot send message to an "unused" threads queue

---

doc/members/accept_recovery.rst
doc/members/member_rpc_api.rst
doc/schemas/gov_openapi.json
doc/schemas/recovery_share/submit_POST_params.json
doc/schemas/recovery_share/submit_POST_result.json
doc/schemas/recovery_share_POST_params.json
doc/schemas/recovery_share_POST_result.json
python/utils/submit_recovery_share.sh
src/node/rpc/member_frontend.h
src/node/rpc/test/member_voting_test.cpp

Rename `POST gov/recovery_share/submit` to `POST gov/recovery_share` to be more RESTful.

Rename submit recovery share endpoint

---

doc/schemas/gov_openapi.json
src/ds/openapi.h

As discussed in recent PRs:
```
[
{ ... Schema A ... },
{ ... Schema B ... }
]
```
is valid JSON schema, describing a 2-element tuple (which is how nlohmann converts entries in a non-string-keyed `std::map`). However it is not valid in OpenAPI 3.0. So we replace this with:
```
"oneOf":
[
{ ... Schema A ... },
{ ... Schema B ... }
],
"minItems": 2,
"maxItems": 2
```
This is _slightly_ less precise (it accepts `[B, A]` when we really only want `[A, B]`). But it looks close-enough, and gives us compliant OAPI 3.0. Hopefully we can revert this when we have OAPI 3.1 support.

Document nlohmann's tuple maps as oneOf, rather than a tuple

---

CMakeLists.txt
src/consensus/aft/raft.h
src/consensus/aft/raft_consensus.h
src/consensus/aft/raft_types.h
src/ds/logger.h
src/ds/logger_formatters.h
src/kv/kv_types.h
src/kv/store.h
src/kv/test/kv_test.cpp
src/kv/test/stub_consensus.h
src/node/history.h
src/node/node_signature.h
src/node/progress_tracker.h
src/node/signatures.h
src/node/test/history.cpp
src/node/test/progress_tracker.cpp

Part of #1655, #1627
In this PR AFT backup nodes will send their signatures of the primary signed merkle root to the other replicas and propagate their their acks of receiving said signatures.
The next PR will involve writing this info to the ledger. This should allow for a node to catchup that is behind the 2f+1 up to date bft nodes.

Aft: In BFT mode propagate backup signatures and backups to signatures 

---

tests/committable.py
tests/infra/network.py

Quick fix: `committable_suffix_test` is failing sporadically in the CI. It looks like we don't wait long enough for a new primary when the nodes are coming out of suspension. So in this special case, we wait longer.

Wait longer in committable_suffix_test

---

CMakeLists.txt
tests/committable.py

More accurate wait for the non suspended backup to have the last tx be committable.

Make committable test more robust

---

python/ccf/clients.py

I meant to use the standard Python `re` library, but we have a (very similar!) pip package named `regex` through some dependency. This code worked in some `venv`s but not all.

regex is not re

---

doc/schemas/app_openapi.json
doc/schemas/gov_openapi.json
doc/schemas/node_openapi.json
python/ccf/proposal_generator.py
src/node/rpc/endpoint_registry.h

As noted in #1735, we were failing to document a few endpoints which had no schema defined. These are now included in the OpenAPI document, with the minimal fields to create a valid document. This requires a response code, so we assume they are all capable of returning a 200. To be more accurate, we could be injecting some system error codes in here that we know they may return, but we don't currently have documentation for those.

Document all endpoints, even those with no schema

---

src/apps/js_generic/js_generic.cpp
tests/modules.py
tests/npm-app/app.json
tests/npm-app/src/endpoints/crypto.ts
tests/npm-app/src/types/ccf.ts
tests/npm-tsoa-app/src/types/ccf.ts

Later on this may be exposed as [SubtleCrypto.generateKey](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey) using the same underlying C++ function.

Expose AES key generation to JS

---

.azure-pipelines-templates/daily-matrix.yml
samples/apps/smallbank/smallbank.cmake
src/ds/spin_lock.h
src/ds/thread_messaging.h
src/enclave/enclave.h
src/kv/kv_types.h
src/kv/store.h
src/node/history.h
src/node/node_state.h
src/node/rpc/frontend.h
src/node/test/historical_queries.cpp
src/node/test/history.cpp
src/node/test/history_bench.cpp
src/node/test/snapshot.cpp

Resolves #1736, #48
Links: #1737
There is a long held desire to move the instigation of signatures from the frontends. This change address this by moving the issuance of signatures to history. Please review this carefully, not much code changes here but this is a more fundamental change where bugs can be harder to find later.

Issue signatures from history

---

src/enclave/rpc_sessions.h
src/tls/context.h

Noticed while stress testing. If clients try to create too many connections at the same time, we'll eventually exhaust enclave memory. The most obvious place was `mbedtls_ssl_setup`, since this SSL context is pretty expensive. I've capped it at 1000 connections for now, which seems like a plausible place for a HTTP server to say "I'm busy", but in practice we may want it much lower while we're extremely memory constrained in-enclave.

Add an upper limit on the number of active sessions allowed in the enclave

---

tests/npm-tsoa-app/tsoa-support/postprocess.js
tests/npm-tsoa-app/tsoa-support/routes.ts.tmpl

In tsoa, there are controllers and actions. A controller has a route "users" and an action may have an appended route as well, e.g. "{id}". Previously, the helper code didn't handle the extra route of actions. This PR fixes that.

Fix tsoa route handling

---

src/consensus/aft/test/logging_stub.h
src/kv/tx.h
src/node/progress_tracker_types.h

Thanks to the recent changes to `ProgressTracker`, we no longer need the old (unsafe!) `Tx` constructor any more, so this removes it.

Remove old Store-less Tx constructor

---

tests/infra/e2e_args.py
tests/infra/network.py
tests/infra/node.py
tests/infra/path.py
tests/sandbox/sandbox.sh
tests/start_network.py

Backwards compatible changes to the infra code to fix an issue with launching sandbox.sh from arbitrary folders.
This also uses `exec` to launch python so that signals are forwarded when using the script programmatically.

Fix sandbox

---

src/apps/js_generic/js_generic.cpp
src/kv/test/kv_test.cpp
src/kv/tx_view.h
src/kv/untyped_tx_view.h

Adds a native `.has()` method. This is more efficient than `.get()` as it doesn't deserialise/copy the value.

Implement has(k) on TxView

---

tests/generate_vegeta_targets.py
tests/vegeta_stress.py

Followup to #1763.
I had a bash script for generating Vegeta target streams, but that was rewritten in Python. I've now pulled that generation logic into a separate Python file so we can use it as a CLI tool for manually stressing a network. Its ugly, but removes some of the grunt work, and should be easy to extend if we start using this more often.
Example (command formatted for readability):
```
$ python ../tests/generate_vegeta_targets.py
targets
--uri-path /app/hello
targets
--uri-path '/app/foo/{i}/bar'
--range-start 5
--range-end 9
--method "GET"
--hostname 127.1.2.3:1234
--body '{"Key {i}": ["A message about {i}", NaN]}'
{"method": "POST", "url": "https://127.0.0.1:8000/app/hello", "header": {"Content-Type": ["application/json"]}}
{"method": "GET", "url": …
```

Vegeta CLI target generator

---

.daily.yml
tests/test_install.sh

The recent `--library-dir` means that relative package paths must be relative to the binary dir, not the working directory. For simplicity, the path in `test_install.sh` is now an absolute path.
Unrelated tweak in the same script - wait for `network_info.txt` to appear as a sign the network is open.

Fix Daily CI - pass absolute package path

---

CHANGELOG.md
src/kv/test/kv_test.cpp
src/kv/untyped_tx_view.h

Opening this as a draft as there's still discussion around whether these are the semantics we want.
We want to avoid errors when the functor in a `foreach` calls `put` or `remove`.
ie, if we have a map:
```
{
1: 'a',
2: 'b'
}
```
and we call:
```
view->foreach([&view](const auto& key, const auto& value)
{
LOG_INFO_FMT("{} {};", key, value);
view->remove(2);
}
);
```
Since iteration order is undefined, we may be removing 2 before we've called the functor. We _could_ try and get to a point where this example may print _either_ `2 b; 1 a;` _or_ `1 a;`, and does so safely, but I don't think this 'randomness' is useful behaviour.
We could guide users towards only `foreach`ing on `ReadOnly` views, and building their own collection of keys to iterate over. This is slower and hard to enforce (I …

Make foreach iteration over TxViews operate over a copy, to avoid invalidated iterators caused by modifications

---

src/consensus/aft/impl/execution.cpp
src/consensus/aft/impl/execution.h
src/consensus/aft/impl/request_tracker.h
src/consensus/aft/raft.h
src/consensus/aft/raft_consensus.h
src/consensus/aft/test/driver.cpp
src/consensus/aft/test/driver.h
src/consensus/aft/test/main.cpp
src/enclave/enclave.h
src/enclave/forwarder_types.h
src/kv/kv_types.h
src/kv/test/stub_consensus.h
src/node/node_state.h
src/node/node_types.h
src/node/request_tracker.h
src/node/rpc/forwarder.h
src/node/rpc/frontend.h
src/node/rpc/test/frontend_test.cpp
src/node/test/channel_stub.h
src/node/test/progress_tracker.cpp
src/tls/hash.h

Part of #1709
When a replica forwards a request it will send a hash of the forwarded request to all the other backup nodes. If said request is not executed within a specific period if time we will issue a view-change. This PR introduces the RequestTracker class which is responsible for matching up the hashes which are sent to the requests that are seen by the backups.

AFT: Send request hash when forwarding request

---

src/apps/js_generic/js_generic.cpp
tests/content_types.py

As noted in #1772, we are sometimes returning `403` from JS apps when we should really be returning `404`. This happens if we send an anonymous request to a non-existent path, because the default handler is selected and has all of the normal endpoint properties including a `require_client_identity = true`.
I'd like to remove the default_handler entirely in favour of the dynamic dispatch, but this is slightly more involved (we have multiple proposals for creating JS apps, but only `deploy_js_app` sidesteps the default_handler - I think we should remove the others) so I'll leave it for a future PR.

Return 404s from js_generic

---

CHANGELOG.md
doc/developers/demo.rst
doc/quickstart/test_network.rst

Helps with #1700, but isn't complete. We should talk about JS app bundles, and we will once 0.14.2 is out of the door.

Update documentation related to start_test_network.sh to talk about sandbox.sh instead

---

src/http/http_endpoint.h

#1783 introduced a significant perf regression.
While exploring the `modules_test` failures I'd fiddled with some hardcoded limits to see if I could reduce queuing on large requests. I thought I'd reverted all of these but I missed this one, which makes a significantly larger allocation than it used to. I believe this is the cause of the perf regression - opening as a draft to confirm. If this _is_ responsible for such a significant slowdown, its worth seeing if we can reduce the allocation/copying here, and actually get a speed-up.

Fix perf regression: Restore old read_block_size

---

tests/start_network.py

Some of our request logging had leaked into `sandbox.sh`. All other requests are suppressed by `LOG.disable("ccf")`, but this is called directly from `start_network.py` so is not caught. Instead, if we're not verbose, we dump these messages to an ignored list.
Then:
```
$ ../tests/sandbox/sandbox.sh -p liblogging
Setting up Python environment...
Python environment successfully setup
[09:26:52.885] Starting 1 CCF nodes...
[09:26:52.885] Virtual mode enabled
[09:26:58.146] [0|user0] GET /app/commit
[09:26:58.146] 200 @2.8 {"seqno":8,"view":2}
[09:26:58.146] Started CCF network with the following nodes:
[09:26:58.146]   Node [0] = https://127.0.0.1:8000
```
Now:
```
$ ../tests/sandbox/sandbox.sh -p liblogging
Setting up Python environment...
Python environment successfully setup …
```

In non-verbose start_network, don't log request status

---

CHANGELOG.md
cmake/common.cmake

`tools.cmake` was created in #1757, and `ccf_app.cmake` depends on it (it includes `enable_san`) but it wasn't added to install files and so is missing from release packages.

Install tools.cmake

---

cmake/common.cmake
cmake/cpack_settings.cmake
getting_started/setup_vm/roles/ccf_build/vars/common.yml
getting_started/setup_vm/roles/ccf_run/vars/common.yml

Spotted by @jumaffre, this dramatically shortens the size of `ldd cchost.virtual` :)

Libcurl is not needed anymore now that the notification server is gone

---

CMakeLists.txt
src/consensus/aft/impl/state.h
src/consensus/aft/impl/view_change_tracker.h
src/consensus/aft/raft.h
src/consensus/aft/raft_types.h
src/consensus/aft/test/logging_stub.h
src/crypto/hash.cpp
src/crypto/hash.h
src/crypto/test/crypto.cpp
src/node/history.h
src/node/node_signature.h
src/node/node_state.h
src/node/node_to_node.h
src/node/progress_tracker.h
src/node/progress_tracker_types.h
src/node/test/progress_tracker.cpp
src/node/view_change.h
tests/election.py

Part of #1709 
When running in BFT mode we sometimes decide to send view change messages (#1770, #1813). This PR picks up at the point when we are ready to send a view change message. It includes:
- Create a view-change message will all the relevant evidence and send it to all the other replicas
- Receiving replicas validates the incoming message
- Receiving replicas update their progress tracker with the new evidence
- Rate limit how often a replica will send a view-change message

AFT: Send view change messages

---

src/kv/serialise_entry_json.h
src/kv/store.h
src/kv/test/kv_serialisation.cpp
src/kv/tx.h

We say "you can bring your own serialiser", and have a test that defines a few custom nonsense serialisers to confirm that. We _also_ say "here's a few serialisers for you", via msgpack, JSON, and blitting-a-few-primitive-types, but we were only actually testing the msgpack serialiser (since its used everywhere).
At some point these have rotted, and dropping in `JsonSerialisedMap` for `Map` stopped working! This fixes that, and adds use of these serialisers to the `kv_serialisation` test.

Test non-msgpack serialisers

---

src/apps/js_generic/js_generic.cpp

Currently, in JS, all data is queried/stored as msgpack-encoded `std::vector<uint8_t>`. This is clearly a mistake and should query/store data as-is.

Use raw serialiser instead of msgpack when accessing tables from js

---

doc/conf.py

Running a Sphinx documentation server locally is super useful to check the formatting of local doc edits, etc.. However, running doxygen on every edit means that it takes a few seconds to render doc changes in the browser. The `SKIP_DOXYGEN` environment variable can now be set to skip this slow process, e.g. `$ SKIP_DOXYGEN=ON ./livehtml.sh`.

Skip doxygen generation based on env var

---

CMakeLists.txt
src/consensus/aft/impl/state.h
src/consensus/aft/impl/view_change_tracker.h
src/consensus/aft/raft.h
src/consensus/aft/raft_consensus.h
src/consensus/aft/raft_types.h
src/consensus/aft/test/driver.h
src/consensus/aft/test/main.cpp
src/kv/store.h
src/node/progress_tracker.h
src/node/progress_tracker_types.h
src/node/test/progress_tracker.cpp

Part of #1709
This is still a work in progress and there will be follow-up PRs. In this PR we do the following:
- A backup checks the validity of the NewViewConfirmation append entry before it applies it
- Every time an append entry arrives a backup will check that it comes from a "valid" primary
- If the validity of a primary cannot be established from the information that the backup already has it will look at the append entry to see if it is a NewViewConfirmation entry that contains said proof.

AFT: Verify append entry validity

---

src/consensus/aft/impl/state.h
src/consensus/aft/impl/view_change_tracker.h
src/consensus/aft/raft.h
src/consensus/aft/raft_types.h
src/node/test/progress_tracker.cpp

resolves #1709
This is closing a hole that exists in view-changes where: if there is a network partition a replica that is considerably behind the primary and did receive any of the view-change messages could receive append entries from the new primary and no evidence that supports this new primary is the actual primary.

AFT: New primary send evidence extremely delayed backup

---

src/tls/cert.h

Related to https://github.com/microsoft/CCF/pull/1882
The `tls::Cert` should _optionally_ take our own certificate/private key. This wasn't possible with the `tls::Cert` constructor and is now fixed.

Improved interface for tls::Cert context

---

src/consensus/aft/raft.h

part of #1601
I am fixing some of the locking issues, additional PRs will follow-up on this work
- In replicate raft.h:404, on the BFT backup we would go through the committed tx and put them on the ledger. This actually results in double adding ledger entries, raft.h:452, does this already
- There was a re-entrant lock issue if we ended up having to append the ViewChangeConfirmation message to the ledger, we solve this by release the lock for a short period of time. This is safe because there is no concurrency dependency by adding the view and propagating the ledger which would occur next.

AFT: locking issues

---

src/kv/store.h
src/kv/test/kv_test.cpp

Related to #1539 
On join, when a node has verified the authenticity of a snapshot (i.e. proof in the ledger that evidence is globally committed), it can safely clear its state so far and join from there. 
Clearing the store at this point is safer than re-creating a store object that may have already been passed to other objects (i.e. frontends) when the node was created.

Add clear method to KV store

---

src/node/jwt_key_auto_refresh.h

Fixes https://github.com/microsoft/CCF/issues/1916.

check host of tls cert during jwt key auto-refresh

---

src/http/http_jwt.h

This is essentially a false positive, but it's inexpensive to silence in a way that makes the code slightly more robust to further changes.

Address warning flagged by CodeQL

---

tests/reconfiguration.py
tests/suite/test_suite.py

I was trying to work out what failed in this test (a specific seed for `full_test_suite`):
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=16059&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded&l=11078
I thought maybe we had a bug where we're not able to retire the final backup, as the special case progress for a single-node network wasn't triggered? But that's not the case - I tried retiring all backups and the final lone primary is happy to proceed.
The actual fix is much simpler. This seed had previously run the test which _kills_ the primary, without retiring it. So the configuration currently contains 3 nodes, 1 of whom is not participating, and sure enough the primary can't reach consensus if the sole live backup is retired. So we …

Only retire backup when test suite can progress

---

scripts/notice-check.py
src/ds/ccf_assert.h
src/ds/stacktrace_utils.h

All the contents of this file except for a few squiggly brackets has been replaced (*), none of the code to which the original notice applied still exists.
(*) See file history in git, but mostly #1261, #1309 and #1633
This change simplifies the notice check, and removes the sole MIT-licensed file from the otherwise all-Apache 2.0 `src/`.

Remove pbft notice

---

tests/e2e_suite.py

Print memory usage on each live node at the end of each test in the suite.
Not useful to debug a bad_alloc this time, but could be in the future.

Add memory stats in suite

---

getting_started/setup_vm/roles/nodejs/vars/common.yml
samples/apps/forum/package.json

Recently nodejs 12.20 was released which broke `ts-node` (used by the forum app). The new version of `ts-node` contains fixes that only work on nodejs >= 14, and since this is an LTS as well, the easiest path forward is to bump to that version.

Bump nodejs to 14 LTS to fix ts-node issues

---

.azure-pipelines-templates/install.yml
src/host/main.cpp
tests/reconfiguration.py
tests/sandbox/sandbox.sh
tests/test_install.sh

When testing a new release on the CI, the CCF Python package won't be published until `test_install.sh` has passed. However, `test_install.sh`, which now uses `sandbox.sh`, assumed that `pip install ccf=<version>` works. To fix this, we can now pass a `PYTHON_PACKAGE_PATH` env var to both `test_install.sh` and `sandbox.sh` so that the Python package is installed from there instead.

Fix test_install.sh when testing a new CCF release

---

src/node/rpc/member_frontend.h
src/node/rpc/test/member_voting_test.cpp

Spotted by @eddyashton 
On recovery, when a threshold of member shares have been submitted and one (or more) of the recovery shares was bogus, the share combination fails and the endpoint returns an error. In this scenario, we want to clear all the submitted recovery shares from the `ccf.gov.submitted_shares` table to let members try again (and because it is hard to find out which share was bogus). 
Because the endpoint returned an error, the write set wasn't actually applied, which meant the submitted recovery shares weren't cleared. This is now the case, via `ctx->set_apply_writes(true)`.

Clear member submitted shares on error

---

samples/apps/forum/test/poll.test.ts

Fixes https://github.com/microsoft/CCF/issues/2042.
This works around an issue related to the experimental ESM support used with mocha. By not importing the (runtime) constant from the ccf app code it doesn't try to import the module and its dependencies which caused the issue (NOTE: the error message in the issue is not the real error because that's swallowed by mocha, see also mocha/lib/esm-utils.js::requireOrImport).

Fix forum app test

---

doc/schemas/app_openapi.json
doc/schemas/gov_openapi.json
doc/schemas/node_openapi.json
src/ds/openapi.h
src/ds/test/openapi.cpp
src/http/authentication/authentication_types.h
src/http/authentication/cert_auth.h
src/http/authentication/jwt_auth.h
src/http/authentication/sig_auth.h
src/node/rpc/endpoint_registry.h

Part of #2032.
Adds `components/securitySchemes` and per-path-operation `security` fields to generated OpenAPI documents.

Document auth policies in OpenAPI

---

doc/build_apps/logging_cpp.rst
doc/schemas/app_openapi.json
samples/apps/logging/logging.cpp
tests/e2e_logging.py

Part of #2032.
Adds a sample custom policy + identity + endpoint in `logging.cpp`, an e2e test case, and a section in the docs describing it.

Add example of custom auth policy, and documentation of new auth types

---

python/ccf/clients.py
src/http/authentication/sig_auth.h
src/node/rpc/frontend.h
src/tls/pem.h
tests/memberclient.py
tests/suite/test_suite.py

In the auth refactor, we lost the step of actually verifying HTTP signatures. There is validation of the structure of the headers and the digest to construct a `SignedReq` object, but we weren't verifying that signed req against the expected caller cert.

Fix signature verification

---

cmake/ccf_app.cmake

Non-LVI-mitigated enclaves did not link to OE's openssl yet.

Add missing openenclave::oecryptoopenssl 

---

doc/build_apps/kv/kv_serialisation.rst
python/ccf/ledger.py
src/kv/generic_serialise_wrapper.h
src/kv/kv_types.h
src/kv/snapshot.h
src/kv/store.h
src/kv/tx.h
src/kv/untyped_map.h
src/kv/view_containers.h

part of #2055
To allow parallelism on the backup we need to know where conflict could occur. Step 1 is tracking the max version that a transaction reads from.

Track the max version a transaction would conflict with

---

src/ds/thread_messaging.h
src/node/snapshotter.h

Fixes issues related to multithreading (see #2069)
Asynchronous snapshot generation used its own round robin function which wasn't correct in a multi-threading setting (it would dispatch snapshots to the last thread + 1). Instead, use the one from `thread_messaging.h` directly.

Use thread messaging round robin for snapshot generation

---

doc/schemas/node_openapi.json
src/consensus/aft/impl/execution.cpp
src/consensus/aft/impl/execution.h
src/consensus/aft/impl/view_change_tracker.h
src/consensus/aft/raft.h
src/consensus/aft/raft_consensus.h
src/enclave/rpc_context.h
src/host/ledger.h
src/http/http_rpc_context.h
src/http/ws_rpc_context.h
src/kv/kv_types.h
src/kv/test/stub_consensus.h
src/node/rpc/call_types.h
src/node/rpc/frontend.h
src/node/rpc/node_frontend.h
src/node/rpc/serialization.h
tests/election.py
tests/infra/network.py

Resolves #1601
Part of #2055
This resolves 2 issues:
- The "primary_info" endpoint should run outside of BFT consensus on the node that receives the request
- After executing a transaction the frontend returns the last global commit. This change adds a check to see if this value has been set and only sets it in the frontend if it has not been set. This allows for BFT to set this value at an appropriate time.
Minor: Change log level for a info log in ledger.h

AFT: Resolve recursive lock issues with BFT

---

src/ds/nonstd.h
src/host/ledger.h
src/host/test/ledger.cpp

Adding some resilience to corrupted (i.e. invalid names, empty files, wrong format) files in the host's ledger. 
This should fix some errors seen on multithreaded end-to-end scenarios (because we now snapshot aggressively by default in CI, we generate many ledger chunks, which sometimes result in a node resuming from an empty ledger file).

Host ledger resilience to corrupted files

---

tests/e2e_logging.py

`test_view_history` makes loads of requests, which quickly fill up the logs but don't show useful progress:
```
60: 10:19:31.794 | INFO     | __main__:test_view_history:503 - [0|user0|] GET /node/tx?view=1&seqno=15
60: 10:19:31.794 | INFO     | __main__:test_view_history:503 - 200 {"status":"INVALID"}
60: 10:19:31.798 | INFO     | __main__:test_view_history:503 - [0|user0|] GET /node/tx?view=2&seqno=15
60: 10:19:31.798 | INFO     | __main__:test_view_history:503 - 200 {"status":"COMMITTED"}
60: 10:19:31.800 | INFO     | __main__:test_view_history:503 - [0|user0|] GET /node/tx?view=1&seqno=16
60: 10:19:31.800 | INFO     | __main__:test_view_history:503 - 200 {"status":"INVALID"}
```
This is unnecessary since we already print a summary of the results, on success _or_ failure:
```
60: …
```

Don't log every request in test_view_history

---

CHANGELOG.md
doc/schemas/gov_openapi.json
src/node/rpc/endpoint_registry.h
src/node/rpc/json_handler.h
src/node/rpc/member_frontend.h
src/node/rpc/test/member_voting_test.cpp
tests/e2e_logging.py
tests/infra/member.py

Addresses first point of https://github.com/microsoft/CCF/issues/1944.

Return 204 on /ack success instead of JSON true

---

CHANGELOG.md
doc/schemas/gov_openapi.json
python/utils/submit_recovery_share.sh
src/node/rpc/call_types.h
src/node/rpc/error.h
src/node/rpc/member_frontend.h
src/node/rpc/serialization.h
src/node/rpc/test/member_voting_test.cpp
tests/infra/member.py

Addresses the second point of https://github.com/microsoft/CCF/issues/1944.
GET /recovery_share now returns `{"encrypted_share": "..base64"}` while POST /recovery_share has as input `{"share": "..base64"}` and returns `{"message": "status message..."}`.

Change schemas of /recovery_share GET/POST endpoints

---

.daily_canary
CMakeLists.txt
src/node/ledger_secrets.h

At the end of the public recovery, the store is rolled back to discard any unsigned entries. The rollback propagates to the ledger secrets which haven't yet been set, which caused a SAN error as we were accessing the first ledger secret.

Fix SAN error on rollback during recovery

---

src/node/history.h
src/node/node_state.h

That store is a pure replay construct to recover private state, emitting signatures over it neither makes sense nor works.

Do not start the signature timer on the recovery store

---

CMakeLists.txt
doc/operations/ledger_snapshot.rst
src/host/ledger.h
src/host/test/ledger.cpp
tests/infra/e2e_args.py
tests/infra/network.py
tests/infra/remote.py
tests/ledger_operation.py

We didn't use to test what happened when a _committed_ ledger file was moved out of the main ledger directory (`--ledger-dir`) to another location, hopefully accessible via `--read-only-ledger-dir`. 
This is now done in the ledger unit test as well as in a new `ledger_operation` end-to-end test.
This actually worked fine as it was but found out an interesting point: the ledger keeps track of a few committed ledger files in its read cache (specified via the `max_read_cache_files` constructor argument and hardcoded to 5 in CCF). Even if these files are deleted, the node process still holds a reference to the underlying inode and the ledger entries in those files can still be read. Once more recent committed ledger files are read by the node, the node will drop the reference to these files …

Unit and end-to-end tests for moving committed ledger files out of main ledger dir

---

src/apps/js_generic/js_generic.cpp

CodeQL scanning warning raised [potential use of this uninitialized variable](https://github.com/microsoft/CCF/security/code-scanning/707). That's a false positive - we actually set all of these or none, and throw in the latter case. But its simple to silence the error, so we do that.

Silence uninitialized local variable warning

---

src/kv/store.h

Store::rollback() acquires and holds the maps lock for its entire execution, and the version lock several times (twice explicitly, one or two more times indirectly via current_version()). The term is updated under the first acquisition, but the version (and other elements of state) are only updated in the final acquisition.
As a result, a transaction starting in the middle of a rollback() could when it captures current_txid() grab an incorrect (term, version) pair. Making all store state changes atomically under a single acquisition of the version lock fixes that.

Fix locking in store rollback

---

src/consensus/aft/raft.h
src/kv/kv_types.h
src/kv/store.h
src/node/history.h

Next part of #2087
This is necessary so the frontend can atomically capture a (term, version, root) and initialise the Tx with an up to date (term, read_version) and the corresponding merkle tree root.

Keep accurate term in history on the primary

---

src/consensus/aft/impl/execution.cpp
src/consensus/aft/raft.h
src/consensus/aft/raft_types.h
src/consensus/aft/request.h
src/consensus/aft/test/driver.h
src/consensus/aft/test/logging_stub.h
src/consensus/aft/test/main.cpp
src/crypto/symmetric_key.h
src/kv/deserialise.h
src/kv/encryptor.h
src/kv/kv_types.h
src/kv/store.h
src/kv/test/kv_bench.cpp
src/kv/test/kv_dynamic_tables.cpp
src/kv/test/kv_serialisation.cpp
src/kv/test/kv_snapshot.cpp
src/kv/test/kv_test.cpp
src/kv/view_containers.h
src/libmerklecpp/merklecpp.h
src/node/historical_queries.h
src/node/history.h
src/node/node_state.h
src/node/secret_broadcast.h
src/node/share_manager.h
src/node/test/encryptor.cpp
src/node/test/history.cpp
src/node/test/snapshot.cpp

Part of #2055
This is the first set step of parallel execution on the backup. This PR does a bit of ground work in separating append entry deserialization & execution. There are also moved the deserialization logic out of store.h in deserialise.h this makes things a bit cleaner :)

AFT: Async execution on backup

---

python/ccf/ledger.py

Fixing Signatures table name as defined in CCF here: https://github.com/microsoft/CCF/blob/master/src/node/entities.h#L96

Fix Signatures Table Name in Python Ledger module

---

src/kv/untyped_map.h

This `Check` namespace and associated template machinery must have done something a long time ago (when we were potentially comparing maps of different types?), but is now unnecessary. This PR deletes it.

Remove unnecessary type

---

.azure-pipelines-templates/checks.yml
.azure-pipelines-templates/matrix.yml
.github/workflows/ci-checks.yml

I did this because I thought I could add a path exclude on the AZP CI, and save the CI runs on PRs that only touch documentation and .md files. Then I realised it wouldn't help, because deciding which checks are gating is very much a Settings checkbox and not something that's decided by the config. Bummer.
Still, I think it's marginally nicer that way, it's fewer clicks to get the error, to re-run etc.

Move format and license checks to GH actions

---

tests/infra/runner.py
tests/upload_pico_metrics.py

Since we're renaming our CIMetrics labels and losing all history, take this opportunity to also:
- Remove `secp256k1`, since we don't care about its signing rate enough any more (and have the full picobench when we do)
- Move the `mem` decorator to suffix rather than prefix, so we get the memory use of each test adjacent to the throughput, rather than all mem followed by all throughput
I'm also wondering if `ls` is too brief and opaque a name for what was `logging_scenario`, is `log` better? Scream if you want to go longer.

Reorder and cull perf metrics

---

CHANGELOG.md
src/node/rpc/json_handler.h
tests/e2e_logging.py

fix #2185 
Longer term, we need to get to #2153

Fix '/node/network/nodes' endpoint to return all nodes when no filter is used

---

src/node/channels.h
src/node/node_to_node.h

There is a race that exists on a backup where the primary can create a connection from 2 different source, a connection from a client and a connection to another node (if CFT then only the primary). If these 2 things happened at the same time then an unordered_map in the ChannelManager is concurrently modified.

fix race in NodeToNode

---

src/node/history.h

We have had a couple of places in the code where we access the history without a lock, version or term lock. This causes issues when there is multi-threading. Discussed this with @achamayou  and we decided to convert the term_lock in history to protect more than just the term.

History lock

---

tests/jwt_test.py

Mostly guessing that the replacement calls+flags, but this seems to work.

Remove deprecated ssl.wrap_context - fix pylint failure

---

src/apps/js_generic/js_generic.cpp
src/ds/openapi.h
tests/js-app-bundle/app.json
tests/npm-app/app.json

Latest update to the OpenAPI validator we use requires descriptions in responses. Fair enough - we can add default descriptions to the places where we didn't have them (OpenAPI snippets in JS app bundles).
This also exposed another issue, where those snippets weren't correctly inserted. Because we previously added at least an _empty_ `"responses"` object for every `path_operation`, we failed to insert any real response objects from the JSON endpoint definition (we just insert any new fields, but don't try and merge if the key is already present). Work around this by not inserting that empty `"responses"`.

Fix modules_test in CI

---

doc/requirements.txt
doc/use_apps/verify_tx.rst
tests/e2e_logging.py

Noticed while exploring #2224 with @jumaffre. We'd previously thought that a TxID could not transition from `PENDING` back to `UNKNOWN`, but this is not true - it can happen after an election. Updating the docs, and fixing a related occasional CI failure from this assumption.

Correct Tx status transitions

---

cmake/version.cmake

If the current tag is not a valid release tag (ie. doesn't start with "ccf-"), things will go wrong during release, and in particular the install prefix will be broken.
fix #2253

Do not attempt to use invalid tags for releases

---

CMakeLists.txt

Missing CMake install that broke the attempted 0.18.5 release.

Install public headers

---

.multi-thread.yml

Similar to the daily canary, this is so we can (more) easily kick off threading build runs on PRs that make changes related to threading.

Create threading canary

---

CHANGELOG.md
include/ccf/tx_id.h
python/ccf/clients.py
src/enclave/rpc_context.h
src/http/http_consts.h
src/http/http_rpc_context.h
src/http/ws_parser.h
src/http/ws_rpc_context.h
src/node/historical_queries_adapter.h
src/node/rpc/frontend.h
src/perf_client/perf_client.h
src/perf_client/timing.h
tests/infra/logging_app.py

Closes #2256.
The format of this header is `{view}.{seqno}`, with no other decoration. Any decoration we do add to aid parsing should be safe to insert as a URL query parameter.
Also creates public header file for this `ccf::TxID`. This should be used more broadly within CCF, replacing a few similar duplicated structs, but I don't want that to pollute this PR.
There are other places in the API (notably `/tx`) where we still talk about view and seqno separately. These could be consolidated into a single field, but they're not directly tied to this change.

Combine view and seqno into single HTTP header

---

.daily_canary
src/node/node_state.h
src/node/rpc/node_frontend.h
tests/infra/node.py

The recent node ID changes (#2241) introduced a memory misalignment with BFT. This PR fixes the issue by padding the monotic node ID in this case. Note that this is a quick fix and that the BFT node ID scheme will eventually be unified with CFT (see #1852).

Fix SAN error from recent node ID changes and BFT

---

tests/suite/test_suite.py

Issue: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=20114&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded
The current tests are not robust to:
1. view changes
2. recovery
The first problem can be resolved by keeping track of the node_id -> local_id mapping for the lifetime of a network, which is only a minor change. The second problem needs a slightly larger change, where recovered networks need to endorse the previous identity, and receipt verification logic needs to find that (potential sequence) of endorsements and the node identities of previous nodes.
I am not planning to look at this until JS governance is complete.

Remove receipts from suite

---

.daily_canary
tests/infra/consortium.py
tests/infra/network.py

Fixes two issues in the Daily following the member/user IDs changes in #2279:
- https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=20234&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded&l=10388: The users weren't recovered by the infra recovery network.
- https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=20231&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=fe98d859-2537-5570-75af-de67d4290f3a&l=745: In a recovery sandbox, the member IDs were recovered only from the service. However, the service isn't aware of the members' local IDs, so the infra now recovers the members from the `common_dir` and only asks the service for their status.

Fix test install and full test suite in Daily

---

.cg.yml

This adds a separate pipeline for component governance checks, so that we're not dependant on auto-injection anymore. The way it is set up in this PR, it produces 5 correct alerts and I'm working with CELA to get those resolved (problems on their end).

Add component governance CI job

---

src/apps/js_generic/js_generic.cpp

Fixes the warning reported [CodeQL #434](https://github.com/microsoft/CCF/actions/runs/643355581)

Fix CodeQL warning about uninitialized variable

---

doc/conf.py
doc/requirements.txt

~~The doc-building CI pipeline is broken this morning. I haven't found an immediate fix - in fact trying to repro locally I got a completely different error than the one seen on the CI. As an optimistic temporary fix, try pinning to an older version of Sphinx while I investigate further, maybe this unblocks other PRs.~~
We tracked the failure down to [this new release](https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.5.0), which isn't happy building our docs between versions `ccf-0.14.1` and `ccf-0.16.2`. We have a lot of very old versions that we don't want to support for ever, so taking this opportunity to cull some of the oldest and only build the docs since `ccf-0.16.3`. Its unfortunate that this needs to be expressed as a regex, but that's what we have. Please have a …

Only build recent versions of docs

---

3rdparty/stub/mem.c

Once was a dependency for the evercrypt code, no longer necessary.

Remove unnecessary stub

---

src/crypto/mbedtls/key_pair.cpp
src/crypto/openssl/key_pair.cpp

Fix #2190 for now.
Longer term, we probably want to add the following features:
1. Make node and network cert validity ranges user-configurable
2. Add a mechanism allowing a periodic refresh of the self-signed network certificate without creating a new identity

Extend certificate validity range

---

.daily_canary
tests/infra/consortium.py

Fixes daily build which [is broken](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=20791&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=fe98d859-2537-5570-75af-de67d4290f3a)

Python infra: fix MemberStatus enum parsing

---

samples/apps/forum/src/error_handler.ts

Previously, `@Response` accepted `number` as status code type, now it's literals only.

Forum sample: adapt to tsoa type changes

---

python/ccf/proposal_generator.py
src/crypto/hash_provider.h
src/ds/hex.h
src/endpoints/common_endpoint_registry.cpp
src/kv/serialise_entry_blit.h
src/node/blit.h
src/node/code_id.h
src/node/genesis_gen.h
src/node/node_state.h
src/node/quote.h
src/node/rpc/member_frontend.h
src/node/rpc/node_call_types.h
src/node/rpc/node_frontend.h

The trusted node code ID were still serialised as raw bytes in the ledger and in the associated proposals.

Serialise code ID as hex string

---

.azure-pipelines-templates/install.yml
.azure-pipelines-templates/matrix.yml
CMakeLists.txt
cmake/common.cmake
src/enclave/main.cpp
src/host/main.cpp
tests/test_install.sh

As BFT support is still experimental, this PR disables it for CCF releases via a new CMake `ENABLE_BFT` flag (defaults to `ON`), which is set to `OFF` in our release CI job (tested in `test_install.sh`). 
The fact that BFT is enabled or not is captured at compile time so that it is part of the enclave measurement, so that operators cannot enable BFT for an already-trusted measurement.

Disable BFT in CCF releases

---

src/host/main.cpp
tests/infra/node.py
tests/infra/remote.py
tests/reconfiguration.py

Removing the annoying failure log when starting a join/recovery node without a snapshot.

Remove failure log message when starting a node without a snapshot

---

src/crypto/mbedtls/key_pair.cpp
src/node/test/channels.cpp

ECDSA signatures are non-deterministic/randomized, i.e. signing the same message twice produces different signatures (and both verify correctly). Our implementations of signing with mbedTLS and OpenSSL don't agree on that; mbedTLS is deterministic and OpenSSL is not. mbedTLS makes it hard to sign non-deterministically (see code changes here), while OpenSSL doesn't support deterministic signatures (work in progress: https://github.com/openssl/openssl/pull/9223). 
I believe we should be using non-deterministic signatures because we have a good enough source of randomness, at least in enclaves, via the Intel DRNG (see also https://tools.ietf.org/html/rfc6979), so that's what I opted to implement. Our tests tolerate either, so I can be convinced otherwise (and perhaps help out with the …

Non-deterministic/randomized ECDSA

---

.daily_canary
src/consensus/aft/test/logging_stub.h
src/crypto/symmetric_key.h
src/kv/encryptor.h
src/node/channels.h
src/node/node_to_node.h
src/node/node_types.h
src/node/test/channels.cpp

This adds the facilities to trigger key exchanges for node-to-node channels when the message limits have been reached. This is item 3 of #2092.

Add N2N channel key rotation

---

src/ds/logger_formatters.h

I noticed these custom formatters while investigating something else. This PR removes the unnecessary copy when formatting `std::array`s, generalises to any length of array, and decorates the types so its easier to grep where the hexification has come from.
```
std::vector<uint8_t> v{0xde, 0xad, 0xbe, 0xef};
LOG_INFO_FMT("{}", v);
std::array<uint8_t, 7> a{1, 2, 3, 4, 5, 6, 7};
LOG_INFO_FMT("What about my keys? {}!", a);
```
```
[info ] ... | <vec[4]: de ad be ef>
[info ] ... | What about my keys? <arr[7]: 01 02 03 04 05 06 07>!
```

Decorate vectors and arrays through libfmt

---

src/js/wrap.cpp
src/node/jwt.h
src/node/rpc/member_frontend.h
src/runtime_config/actions.js
tests/jwt_test.py

Note that I didn't move over the code of `set_jwt_public_signing_keys` / `remove_jwt_public_signing_keys` since those are still used in C++ for JWT auto-refresh and I didn't want to duplicate the code. Apart from that, `set_jwt_public_signing_keys` is quite complex, involving OE and cert parsing etc.

js gov: ca cert and jwt proposals

---

python/ccf/proposal_generator.py

JS has no built-in object equality. This should work, because the fields in the object are defined in the same order (coming from the same Python `args` object).

In JS proposal generator, use JSON.stringify for object equality

---

src/host/node_connections.h
src/node/channels.h
src/node/node_to_node.h

Fixes at least one more part of #2378. Attempting to send on a channel that has previously been closed is now allowed and triggers a new key exchange.
Also, less `[fail]` logging.

Fix N2N channel destruction/recreation and logging

---

CHANGELOG.md
doc/governance/index.rst
doc/governance/js_gov.rst
doc/governance/proposals.rst
doc/overview/constitution.rst
tests/sandbox/sandbox.sh

Not a complete docs rewrite. Instead a warning on the most deprecated pages, with a link to a transitionary doc describing the basics of the JS constitution and how to migrate from Lua to JS.

Add 0.99.0 release notes and docs on upgrading from Lua to JS governance

---

.azure-pipelines-templates/matrix.yml
CHANGELOG.md

Now that JS governance is the default for the tests, it shouldn't be disabled at compile time in Release builds.

Fix for Release pipeline

---

python/ccf/ledger.py
python/ccf/read_ledger.py

As suggested in a comment on original PR, I think this aids navigation of large ledgers. I've also changed the formatting of bytes (to avoid using non-printable characters, make enum values more readable) and removed all the info logging from `ledger.py`. Current output looks like this:

Add indentation to make read_ledger.py collapsible

---

cmake/ccf_app.cmake

I added these CMake bodges a while ago to work around `oesign`. `oesign` insisted on a fixed output path. We want debuggable and non-debuggable variants of our enclaves, so I needed to create a temp directory to sign both, otherwise every build would overwrite its own files and cause unnecessary rebuilds. Additionally, I added a `grep|sed|echo` pipe to add a `Debug=0` or `Debug=1` to the `.conf` files used to sign, regardless of what the original `.conf` said.
`oesign` now takes a custom output path as an argument, so we can create the `.debuggable` enclave without overwriting any other files. Additionally, I realised my pipe was unnecessarily complicated - rather than trying to overwrite an existing line, we can just delete any existing `Debug=` lines and add our own at the end. This has …

Remove oesign shenanigans from CMake

---

src/host/proxy.h

This adds another (necessary) check on uv_handles to avoid double-`uv_close`s. Pertains to #2378.

Add check for double uv_close

---

js/ccf-app/DEVELOPMENT.md

As noticed by @eddyashton it is not actually required to have a debug build with verbose logging enabled to dump uncaught exceptions and `console.log` to the node's logs.

js: remove mention of debug/verbose requirement

---

CHANGELOG.md
doc/schemas/node_openapi.json
src/host/main.cpp
src/host/snapshot.h
src/host/test/ledger.cpp
src/node/node_state.h
src/node/rpc/error.h
src/node/rpc/node_call_types.h
src/node/rpc/node_frontend.h
src/node/rpc/node_interface.h
src/node/rpc/serialization.h
src/node/rpc/test/node_stub.h
tests/infra/network.py
tests/reconfiguration.py
tests/start_network.py
tests/suite/test_requirements.py

Resolves item 2. in https://github.com/microsoft/CCF/issues/2020 
The snapshot used by new nodes to join the network shouldn't be older than the snapshot that was used by the current primary to join (either on recovery, or a previous join). Otherwise, if the snapshot used to join is older, the new joiner may not be given ledger secrets recent enough to decrypt ledger entries. 
Note that this may be too strict (ledger rekeys may not have happened between an old and a new snapshot), so this PR gives a clear and early error message for operators starting new nodes from snapshots.

Join shouldn't be allowed from stale snapshots

---

src/consensus/aft/raft.h
src/node/channels.h
src/node/node_to_node.h

This reverts part of a previous change to the N2N channel exception behaviour. There is a bug in `Node2Node::recv_authenticated`; it should not return `t` when a message is dropped. This caused outdated (and potentially unauthenticated) messages to be delivered, which is likely the only reason for #2456. 
The ugly part is that this brings back failure log messages that aren't really failures; for instance:
```
43: 17:39:49.084 | ERROR    | infra.remote:log_errors:70 - /data/cwinter/CCF/build/workspace/rotation_test_3/out: 2021-04-13T17:39:48.114058Z -0.005 0   [fail ] ../src/consensus/aft/raft.h:678      | Exception in void aft::Aft<consensus::LedgerEnclave, ccf::NodeToNode, ccf::Snapshotter>::recv_message(const ccf::NodeId &, OArray &&) [LedgerProxy = consensus::LedgerEnclave, …
```

Fix N2N channel exception behaviour

---

cmake/ccf_app.cmake
src/node/entities.h

resolves #2167 
The table ccf.internal.consensus.requests has all the client sent requests, since some of them may be private and we do not differentiate which requests are stored in this table we need to encrypt all of them

BFT - Encrypt append entries

---

doc/build_apps/js_app_bundle.rst
samples/apps/forum/app.tmpl.json
samples/apps/forum/tsoa-support/postprocess.js
samples/apps/logging/js/app.json
src/apps/batched/app.json
tests/js-app-bundle/app.json
tests/js-authentication/app.json
tests/js-content-types/app.json
tests/js-custom-authorization/app.json
tests/js-limits/app.json
tests/js-modules/basic-module-import/app.json
tests/npm-app/app.json

Also, remove the non-functional `"execute_outside_consensus"` field from all the `app.json` files and the docs.

Document forwarding_required & mode in app.json

---

src/enclave/ccf_v.h
src/host/enclave.h

Swallow the OE logging so it doesn't log "logging is not enabled" in the wrong format.
Goodbye forever to this message:
```
2021-04-16T16:39:20+0100.498499Z [(H)WARN] tid(0x7ff6502ee600) | In-enclave logging is not supported. To enable, please add 
from "openenclave/edl/logging.edl" import *;
in the edl file.
[/source/openenclave/host/sgx/create.c:oe_create_enclave:1178]
```

Remove OE logging

---

doc/schemas/gov_openapi.json
src/ds/json_schema.h
src/ds/nonstd.h
src/ds/openapi.h
src/ds/ring_buffer_types.h
src/kv/map.h
src/kv/serialise_entry_json.h

Our generated OpenAPI document should now match the actual serialisation for map types with stringifiable keys (ie - `EntityID`), describing these as objects.
Includes some vaguely related cleanup:
- Prefer to gives these objects names like `EntityId_to_Failure` rather than `named_Failure`. Even if the key _is_ just a string, we'd prefer `string_to_Foo`.
- Give an earlier, clearer error when creating `kv::Map`s with non-serialisable types.

Fix detection of object vs list-of-pairs JSON serialisation

---

python/ccf/ledger.py
python/ccf/read_ledger.py
python/ledger_tutorial.py
tests/governance_history.py
tests/infra/node.py
tests/infra/remote.py
tests/ledger_operation.py
tests/suite/test_suite.py

Fix for Daily CI. When a node's ledger is split across multiple directories, we should read from all of them to reconstruct the full ledger.

Read multiple directories to construct Python ledger

---

CHANGELOG.md
doc/build_apps/kv/api.rst
src/kv/map_handle.h
src/kv/test/kv_test.cpp
src/kv/untyped_map_handle.h
src/node/rpc/member_frontend.h

Same motivation as #2493 - create this API so it can be used now, and maybe we'll improve the implementation in future.
Note the second test `SUBCASE` - `clear()` actually needs to introduce a read dependency in the current implementation, since if its ordered after another operation it may miss new keys. If we find a different way to express the clear in the underlying implementation then we may not need to introduce this read dependency (ie - an app endpoint that just says `clear()` and does no reads _can_ be ordered before or after any other), but we'd need to ensure that we remove all keys which are present at _commit_ time.

Add `MapHandle::clear()`

---

python/ccf/ledger.py

Format check is failing on `main` because somehow this was checked in unformatted.

Fix python format

---

src/host/enclave.h

Followup to a comment on #2478.

Retain OE logging when `VERBOSE_LOGGING` is on

---

CMakeLists.txt
src/host/main.cpp
src/node/identity.h
src/node/node_state.h
tests/governance_history.py
tests/infra/e2e_args.py
tests/infra/network.py
tests/infra/remote.py
tests/memberclient.py
tests/membership.py

NB: This still doesn't support _mixed curves_ within a service. If a node tries to join with an identity generated on a different curve, it will currently be unable to form channels with other nodes.

Add test for `secp256r1` as service and node identities curve

---

.daily_canary
src/consensus/aft/raft.h
src/node/channels.h
tests/rotation.py

Resolves #2492 
The investigation of the rogue "_Invalid nonce, possible replay attack_" log message (see https://github.com/microsoft/CCF/issues/2492#issuecomment-826838601) has led to the conclusion that this is currently a legitimate scenario that may arise around election time, and that there's no immediate fix for this.
Changing the level of the log to `TRACE` so that the message doesn't appear in CCF releases.

Change log message to TRACE for replayed node-to-node nonces

---

doc/conf.py

An ugly fix, causes a second page reordering, but seems to work. Hopefully temporary - there are several issues around this, so maybe they'll add a better configuration option?
The other proposed fix was using `mermaid-cli`, but I think installing this (in our images) and testing it (at arms length through `sphinxcontrib-mermaid`) seems more difficult?

Fix Mermaid diagram whitespace by rewriting height attribute

---

.azure-pipelines.yml

Fixes the issue which blocked [this](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=24259&view=logs&j=e2a2669a-638d-5159-fc94-d9196412c4a4&s=d654deb9-056d-50a2-1717-90c08683d50a) release.
We didn't previously run the perf tests in the release pipeline (they were gated on `perf_or_release`). We don't wait for them to pass before doing the release:
```
- template: release.yml
parameters:
env: ${{ parameters.env.Hosted }}
depends_on:
- Checks
- SGX_Release
```
But now they run, and if they fail before the release happens they may upload artifacts (logs from the failing tests) that we try to upload in the release.
We should probably be more precise about what we want to upload in the release - we currently do everything in the `ArtifactStagingDirectory`, which may include logs/junk …

Don't run perf tests in release pipeline

---

.azure-pipelines-templates/install.yml
doc/build_apps/install_bin.rst
getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml
getting_started/setup_vm/roles/ccf_install/tasks/install.yml
samples/apps/forum/README.md

This is expected to fix the issue that cropped up during the release of 1.0.0-rc1.

Rename debian packages containing tildes to underscores to avoid GitHub's auto-replace

---

.azure-pipelines-templates/install.yml
doc/build_apps/install_bin.rst
getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml
getting_started/setup_vm/roles/ccf_install/tasks/install.yml
samples/apps/forum/README.md

Same as main but on 1.x branch.

Rename debian packages containing tildes to underscores to avoid GitHub's auto-replace (#2539)

---

CHANGELOG.md
src/kv/kv_types.h
src/kv/store.h
src/kv/test/kv_contention.cpp
src/kv/test/kv_test.cpp

Renamed Store::commit_version() to the more accurate compacted_version()

---

include/ccf/base_endpoint_registry.h
samples/apps/nobuiltins/nobuiltins.cpp
src/endpoints/base_endpoint_registry.cpp
tests/nobuiltins.py

Resolves #2523.
Adds the API `get_untrusted_host_time_v1`, which returns the host-written (UTC) time as a `timespec`.
Also adds an example endpoint using this in the `nobuiltins` app, and a few test calls to confirm the reported time is close enough to the true time.

Add C++ API to get untrusted host time

---

tests/e2e_logging.py

https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=24676&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded
It doesn't look like setting the curve name is necessary or useful on client sockets though: https://docs.python.org/3/library/ssl.html
Re-run with the same seed (SHUFFLE_SUITE_SEED=1620028147) successfully.

Fix unknown curve error

---

CHANGELOG.md
include/ccf/base_endpoint_registry.h
samples/apps/nobuiltins/nobuiltins.cpp
src/endpoints/base_endpoint_registry.cpp
tests/nobuiltins.py

Completes #2206.
Opening as a draft for now because I think this API needs a little more thought. This initial version includes _all known_ node quotes directly from the KV, with no indication as to the node's current status. If the aim is to allow apps to build their own status endpoints, they will need to see node status (and perhaps other node data, like public RPC address?). I'm tempted to just make a `get_status_for_node_v1`, to keep these queries cleanly separated, and perhaps even make this `get_quote_for_node_v1` with a separate `get_ids_for_all_nodes_v1`, but the core question remains - what do we mean by "all nodes"? The current behaviour, where all historic nodes happen to remain in the KV, is supposed to be temporary. So maybe this API should ignore `Retired` nodes already? Do …

Add `get_quotes_for_all_trusted_nodes_v1` API

---

doc/conf.py

Ordering `-rc`s and `-dev` releases with the _real_ release is hard. Instead we just drop docs for pre-1.0.0 releases, and we'll modify this regex to march boldly into the future as we get to future releases.

Drop docs for pre-1.0.0 releases

---

include/ccf/json_handler.h
samples/apps/logging/logging.cpp
src/apps/js_generic/js_generic.cpp
src/apps/smallbank/app/smallbank.cpp
src/apps/tpcc/app/tpcc.cpp
src/endpoints/common_endpoint_registry.cpp
src/endpoints/endpoint_registry.cpp
src/node/rpc/test/frontend_test.cpp

As outlined in #2345, our samples have got a mix of old and new styles in many places. In particular still using the old generic `args` variable name for the `EndpointContext` object. This replaces those with `ctx`, and removes some string duplication.
EDIT: Resolves #2345.

Sample consistency pass

---

CMakeLists.txt
samples/apps/logging/js_perf/app.json
samples/apps/logging/js_perf/src/logging.js

The perf drop in #2569 has shown that our JS perf numbers are very sensitive to changes in the JS app size. This means they're unduly affected when we're just trying to add functional changes to the JS interpreter, that are unused by the perf test. This splits the JS app used for functional testing (`logging/js`) from the minimal app that only has the endpoints used by the perf test (`logging/js_perf`). We now run perf tests on both, but the number for `ls_js_sgx_cft` should only be affected by changes to the interpreter, not a (largely unrelated) app.

Add a minimal JS logging app for perf testing

---

doc/schemas/app_openapi.json
doc/schemas/gov_openapi.json
doc/schemas/node_openapi.json
samples/apps/logging/logging.cpp
src/node/rpc/member_frontend.h
src/node/rpc/node_frontend.h
tests/schema.py

Resolves #2559.
These APIs are now stable enough that we should give them real versions, so they're now 1.0.0. To try and ensure that we change the version when we change the API, `schema_test` is now stricter - it will only overwrite the existing OpenAPI document if the fetched version is newer. This may turn out to be very annoying, as it will flag some minor things (adding docs) that don't need a version bump, and breaks an existing helpful flow ("Schema changed? Oh I'll just run that test and check in the file").

Update doc versions of `/gov` and `/node` OpenAPI

---

CHANGELOG.md
src/consensus/aft/raft.h
src/consensus/aft/test/logging_stub.h
src/node/node_state.h
src/node/snapshotter.h
src/node/test/snapshotter.cpp
tests/infra/logging_app.py

Resolves #2491 
I'd been tracking down this bug for a while, [without success](https://github.com/microsoft/CCF/pull/2526), but activating JWT auto-refresh for the test suites (see https://github.com/microsoft/CCF/pull/2600) triggers the bug much more consistently.
This is the proposed fix for it. This issue was that, while we record "snapshottable" `seqno`s as we replicate entries (on both primary and backups) based on the value of `snapshot_tx_interval`, nodes would generate snapshots on (global) commit at the `seqno` of that commit. However, commits can happen at any signature `seqno`, and don't necessarily match the "snapshottable" `seqno` which was record on the replication code path. In other words, for a `snapshot_tx_interval` of `10`, we may have recorded `seqnos` 10, 20 and 30 as …

Fix for ledger chunking and snapshot out-of-sync

---

src/node/rpc/frontend.h

Noticed this while looking at the forwarding/redirect logic. We should use the same transaction object to lookup the primary address in the store, rather than creating a new one.

Remove extra transaction in redirect logic

---

tests/infra/network.py
tests/infra/node.py

Small fix to the test infra, the status is set externally in network right now, which makes get_joined_nodes() somewhat unreliable.

Set joined status in the node

---

src/node/node_state.h
src/node/rpc/error.h
src/node/rpc/node_frontend.h
tests/reconfiguration.py

Fix #2610 
This change modifies the join endpoint to:
1. Never forward, but...
2. Execute locally when possible (`add_node` when primary, return Trusted status and secrets when applicable regardless of consensus role)
3. Redirect to the new primary otherwise
This typically wouldn't have been a problem under the old governance, which did not allow multiple actions in the same proposal. It is one of (several) problems spotted by #2606.

Make join robust to primary retirement

---

.azure-pipelines-gh-pages.yml
.azure-pipelines.yml
.daily.yml
.github/workflows/ci-checks.yml
.multi-thread.yml
.stress.yml
CHANGELOG.md
cmake/ccf_app.cmake
cmake/cpack_settings.cmake
getting_started/setup_vm/roles/openenclave/vars/common.yml

Apply #2622 (issue #2609) to 1.x LTS.
Picking up some minor CI changes along the way that have no impact but will make merging easier in the future.

Upgrade to OpenEnclave 0.16.1 (1.0.3)

---

doc/conf.py
js/ccf-app/package.json

Doc build is hitting https://github.com/TypeStrong/typedoc/issues/1589: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=26075&view=logs&j=f1fd332c-cd58-5ba4-fc7d-3c1d3a3f0cd3&t=31418c00-d4df-5619-e99a-3cbbc8fcc481
Pinning TypeScript until TypeDoc adds support for 4.3

Pin TypeScript to a version TypeDoc supports

---

include/ccf/entity_id.h
src/apps/js_generic/js_generic.cpp
src/endpoints/base_endpoint_registry.cpp
src/node/blit.h
src/node/rpc/test/frontend_test.cpp

`EntityID`s are currently printed as long hex strings, and it can be hard to identify them in the output and hard to distinguish what domain they're in. This adds decoration to make grepping and domain-distinction easier.
So rather than a line in the node output saying:
```
012345 has voted to add 123456 on 234567
```
we'd see
```
=[012345]= has voted to add -[123456]- on <[234567]>
```
and (hopefully) learn to quickly recognise `=[members]=`, `-[users]-` and (most commonly) `<[nodes]>`.
This distinction relies on the strong typing of (now-distinct) `EntityID`s, so it won't work in places that see these IDs as raw strings (ie - in JS, or for ProposalIDs, or in places where we deliberately support any kind of `EntityID`).

Add decoration around EntityID in node output

---

include/ccf/endpoint_registry.h
src/consensus/aft/impl/state.h
src/consensus/aft/raft.h
src/ds/messaging.h
src/ds/spin_lock.h
src/enclave/main.cpp
src/enclave/rpc_sessions.h
src/endpoints/common_endpoint_registry.cpp
src/endpoints/endpoint_registry.cpp
src/http/authentication/sig_auth.h
src/kv/store.h
src/kv/untyped_map.h
src/node/channels.h
src/node/historical_queries.h
src/node/history.h
src/node/ledger_secrets.h
src/node/node_state.h
src/node/progress_tracker.h
src/node/request_tracker.h
src/node/rpc/frontend.h
src/node/snapshotter.h

We no longer have multiple implementations of `SpinLock`, its always a `std::mutex`, so remove the obfuscating typedef.

Remove unnecessary `SpinLock` typedef

---

CMakeLists.txt
tests/rotation.py

BFT still relies on the rotation tests and has not been ported to suspension-based rotation tests. So this change in-part undoes https://github.com/microsoft/CCF/pull/2650

BFT rotation tests

---

doc/conf.py

As noticed by @jumaffre, my hack to strip the `height` attribute (removing excess whitespace from our mermaid diagrams) was no longer working. Turns out this doesn't work since `sphinxcontrib-mermaid 0.7` (released [15 days ago](https://github.com/mgaitan/sphinxcontrib-mermaid/releases/tag/0.7)), as suggested in the comment. Removing the `<script>` tags fixes this.

Fix mermaid diagram whitespace (again)

---

tests/infra/github.py
tests/infra/remote.py
tests/lts_compatibility.py

As pointed in https://github.com/microsoft/CCF/pull/2643#issuecomment-859715259, we now use the constitution JS scripts from the LTS rather than from our local checkout, so that we don't break the test by adding new features to the constitution (e.g. addition of JS KV map's `clear()` function).

Use LTS version of JS constitution

---

doc/audit/python_library.rst
python/ccf/ledger.py
python/ccf/read_ledger.py

As discussed with @msftsettiy:
- Added docstrings for the `signature_count` and `last_verified_txid` functions
- Make `read_ledger.py` resilient to corrupted ledger files (the latest verified signature will still be displayed if any ledger file is corrupted)

Python ledger tweaks

---

tests/infra/github.py
tests/lts_compatibility.py

(To be backported to `release/1.x` branch).
This PR should hopefully contain the last tweaks required to get the LTS compatibility test working with all branches:
- Fixes an issue with branches off the release branch (e.g. `release/1.0.4`) which were considered as releases branches (but they're not!)
- Add a `--dry-run` option to run the test quickly, without spinning up networks.
- Retrieve the major version of the local checkout from the local branch name (or use `None` if we're not on a release branch). 
- Only consider tags that have a release (to avoid race conditions when release job is running)

LTS compatibility test latest tweaks

---

tests/lts_compatibility.py

LTS major release detection doesn't seem to work quite as expected, so hardcoding to get release pipeline working for now.

Hardcode compatibility check

---

src/apps/tpcc/app/tpcc_tables.h
src/apps/tpcc/tpcc.cmake

resolves #2662
fixed sized arrays can store content of a variable size so we need to zero them to remove non-determinism

Remove non-determinism from TPCC implementation

---

doc/contribute/design/index.rst
doc/contribute/index.rst

This PR adds a new "Design" section under the "Contribute" page. The aim will be to move all useful design documentation there. 
The first instance is the design of the node-to-node channel protocol, which was already briefly outline in https://github.com/microsoft/CCF/issues/2092.

Node-to-node design documentation

---

src/ubsan.blacklist

Resolves #2702.
The recently added JS module bytecode cache exposed another instance of undefined behaviour in QuickJS. Calling `JS_WriteObject` on a module with no debug information eventually calls `dbuf_put(&s->dbuf, b->debug.pc2line_buf, b->debug.pc2line_len)` with a null second argument, and _that_ calls `memcpy(P, null, 0)`, which is technically UB. We already blacklist `quickjs`'s other sources for similar reasons, so I think it sensible to blacklist `cutils` as well and ignore these SAN errors.

Add quickjs/cutils.c to UBSAN blacklist

---

tests/lts_compatibility.py

Fix issue in Daily that causes LTS compatibility check to break: the jwt_issuer wait implementation relies on an endpoint that isn't available in the 1.x LTS.

Fix LTS compat check

---

CMakeLists.txt
tests/rotation.py

This test is unstable at the moment, turning it off until it can be made more stable, hopefully using the partition tooling instead.
Sample failure: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=27624&view=results
```
80: 10:59:44.290 | INFO     | infra.network:stop_all_nodes:536 - All nodes stopped
80: Traceback (most recent call last):
80:   File "/mnt/build/1/s/tests/rotation.py", line 85, in <module>
80:     run(args)
80:   File "/mnt/build/1/s/tests/rotation.py", line 62, in run
80:     test_suspend_primary(network, args)
80:   File "/mnt/build/1/s/tests/suite/test_requirements.py", line 20, in wrapper
80:     return func(*args, **kwargs)
80:   File "/mnt/build/1/s/tests/suite/test_requirements.py", line 43, in wrapper
80:     return func(network, args, *nargs, **kwargs) …
```

Disable rotation test for BFT

---

tests/infra/network.py

Catch up in multi-threaded mode is slower (no parallelisation, additional dispatch costs), so recovery at the end of a `full_test_suite` in the Threading CI takes longer than expected, occasionally longer than the 10s timeout. This doubles that timeout.

Extend timeout in recovery.test

---

doc/build_apps/js_app_ts.rst
doc/build_apps/js_app_tsoa.rst

Although the text suggested using a different version, its a little confusing that these docs reference an unpublished version of the `ccf-app` NPM package. This updates those to a safe-enough version (`1.0.0`), while clarifying that the actual choice should be determined by the version of the other CCF code.

Minor: Point at recent version of ccf-app in docs

---

include/ccf/tx_id.h
src/consensus/aft/impl/view_change_tracker.h
src/consensus/aft/raft.h
src/consensus/aft/raft_consensus.h
src/ds/messaging.h
src/kv/deserialise.h
src/kv/kv_types.h
src/kv/store.h
src/kv/test/stub_consensus.h
src/node/history.h
src/node/progress_tracker.h
src/node/progress_tracker_types.h
src/node/test/progress_tracker.cpp

Currently, the ProgressTracker will combine message for the same seqno regardless of view or configuration and depends on rollback on view-changes. This will not work in the reconfiguration scenario so in this PR it will not combine messages from different views and also take a configuration (if deciding thresholds have been reached) to ensure messages are filtered correctly by configuration.

BFT: filter consensus messages on view and configuration

---

tests/infra/crypto.py

A new pylint came out yesterday ([v2.9.0](https://github.com/PyCQA/pylint/releases/tag/v2.9.0)), and doesn't like this specific line:
```
************* Module infra.crypto
191,19,error,no-value-for-parameter:No value for argument 'algorithm' in method call
```
~Quick fix looks like adding this parameter, though its presumably unused in this ECDSA signing path.~
Looks like this error is totally spurious, and adding the parameter actually breaks the call when we execute it (in `modules_test`). Ignoring the warning instead, will see if I can make a minimal repro and raise an issue.

Fix pylint: Disable warning

---

src/http/http_status.h

Noticed in passing, low priority.
The status line "203 Non - Authoritative Information" _should_ be acceptable to any parser, but is a little odd and not what we were actually trying to do (comes from our formatter). We'd prefer "203 Non-Authoritative Information", with no extra whitespace.

Stringify HTTP status Reason-Phrases without extra spaces

---

.azure-pipelines-gh-pages.yml
.azure-pipelines.yml
.daily.yml
.github/workflows/ci-checks.yml
.multi-thread.yml
.stress.yml
CHANGELOG.md
cmake/ccf_app.cmake
cmake/cpack_settings.cmake
getting_started/setup_vm/roles/openenclave/vars/common.yml

Targeting 1.0.5 at Open Enclave 0.15.1, to provide a low-disruption upgrade path for users on 1.0.2 who need to pick up https://github.com/openenclave/openenclave/commit/b6dcbdf39521c41f34e7c9d4299b50da2512f879 in emergency.
The next release, 1.0.6, will upgrade to Open Enclave 0.17.0 as soon as it becomes available.

Open Enclave 0.15.1

---

tests/jwt_test.py

This is turning off two of the JWT tests that use attestation-based-validation, because they depend on an Open Enclave release-specific certificate, which needs a custom build to produce, and for which there isn't time.
It's worth noting that this issue is resolved on `main`, which is using 0.17-rc and calls the new `oeutil` CLI to avoid this issue.

Disable SGX JWT tests

---

cmake/cpack_settings.cmake

Forgotten during #2758, already fixed in the release branch.

Fix cpack dependency for OE 0.17.0 final

---

doc/governance/accept_recovery.rst
doc/use_apps/issue_commands.rst
doc/use_apps/verify_tx.rst

Update documentation to use x-ms-ccf-transaction-id everywhere

---

doc/overview/consensus.rst

This adds the latest changes to the 2-tx reconfiguration protocol to the documentation. Also includes a diagram for the 2-tx leader retirement. Addresses #2721.

2-tx reconfiguration protocol updates

---

src/consensus/aft/impl/view_change_tracker.h
src/node/progress_tracker_types.h
src/node/test/progress_tracker.cpp

We used to only sign the new-view-confirmation message just before the new primary wrote it to the ledger. That if it was requested by a replica that has not seen the version on the ledger the message was not signed.

Sign new-view-confirmation message earlier

---

tests/election.py
tests/infra/network.py
tests/infra/node.py

BFT view-changes are not timeout for a heartbeat based like CFT but require a timeout of a pending request. In this change the test will wait for a new primary to be elected (when appropriate) and if the consensus protocol is bft it will issue requests.

Fix network.wait_for_new_primary for BFT

---

src/consensus/aft/async_execution.h
src/consensus/aft/raft.h
src/consensus/aft/raft_consensus.h
src/consensus/aft/test/logging_stub.h
src/kv/kv_types.h
src/kv/test/stub_consensus.h
src/node/node_state.h
src/node/node_to_node.h
src/node/test/channels.cpp

Noticed as part of #2775:
We pass incoming messages in some places as `OArray&&`, despite never using the abstraction it provides (a _long-lived_ projection onto owned data). We can replace the ownership points with a plain `std::vector<uint8_t>`, and where we pass it we can pass `(data, size)` (these could be refs if we had a pattern of read-modification that needed it, but we don't). The advantage of this is that when we're reading directly from an existing buffer (eg - we had `(data, size)` already pointing somewhere on the ringbuffer), we don't create an unnecessary copy into an `OArray`.

Remove unnecessary copies into OArray

---

src/ds/state_machine.h
src/node/node_state.h

We have a simple `StateMachine` class in `NodeState`. This moves it to `ds/` where it can be reused by other systems (eg - node-to-node channels). Eventually I'd like to add a restricted set of transitions to this implementation, so we can check that we're only transitioning through states in the expected order.

Move `StateMachine` to standalone ds header

---

doc/audit/builtin_maps.rst
src/consensus/aft/raft.h
src/consensus/aft/raft_consensus.h
src/kv/kv_types.h
src/kv/test/stub_consensus.h
src/node/entities.h
src/node/genesis_gen.h
src/node/hooks.h
src/node/network_configurations.h
src/node/network_tables.h
src/node/node_state.h
src/node/nodes.h
src/node/reconfig_id.h
src/node/rpc/member_frontend.h
src/node/rpc/node_frontend.h

This adds a table of network configurations that assigns unique reconfiguration IDs and a hook on that table that will trigger ORC RPCs in the next reconfiguration PR.

Add table of network configurations

---

edl/ccf.edl
src/consensus/consensus_types.h
src/enclave/ccf_v.h
src/enclave/enclave.h
src/enclave/main.cpp
src/host/enclave.h
src/host/main.cpp
src/node/node_state.h
src/node/rpc/forwarder.h

Another part of #2775. The forwarder and node-to-node channels were owned by the enclave and passed to node state, but the enclave doesn't do anything with them. It makes more sense for them to be owned and constructed within the node state. To make that construction path a little cleaner, the `ConsensusType` in the configuration moves from the top-level to the `consensus::Configuration` struct.

Move channel manager into node state

---

src/ds/logger.h
src/ds/serializer.h
src/ds/test/ring_buffer.cpp
src/ds/test/serializer.cpp
src/enclave/enclave.h
src/enclave/interface.h
src/host/handle_ring_buffer.h
src/host/node_connections.h
src/node/channels.h
src/node/node_state.h
src/node/node_types.h
src/tls/key_exchange.h

Another cleanup carved off #2775.
`node_outbound` was written to ringbuffers directly, with `to_host->write`, rather than with the `RINGBUFFER_WRITE_MESSAGE` macro that every other instance used. This meant it didn't have the same error message handling and type-checking logic as every other ringbuffer write. This was done deliberately, since the types written were previously more distinct, and to allow appending multiple fields onto the ringbuffer without copying them into a single intermediate buffer. This removes those restrictions, getting the type safety without an additional copy, clarifying the exact types of the fields in this message and what they should be used for.
In particular, this lets us remove the generic 'blit anything' serialisation which occasionally failed when we …

Use standard ringbuffer type safety + macros when writing `node_outbound`

---

doc/audit/builtin_maps.rst
doc/requirements.txt

Temporary fix for https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=28845&view=logs&j=f1fd332c-cd58-5ba4-fc7d-3c1d3a3f0cd3&t=31418c00-d4df-5619-e99a-3cbbc8fcc481&l=3437 
Issue tracked in https://github.com/sphinx-doc/sphinx/issues/9433

Do not build docs with latest version of Sphinx

---

.azure-pipelines-gh-pages.yml
.azure-pipelines.yml
.daily.yml
.github/workflows/ci-checks.yml
.multi-thread.yml
.stress.yml
getting_started/setup_vm/roles/ccf_build/vars/common.yml

We only build mbedtls for the virtual build, and LTS changes there are very minor, but it's still good to stay in sync with the version we get from Open Enclave.

Update mbedtls from 2.16.8 to 2.16.10 to track Open Enclave

---

.azure-pipelines-gh-pages.yml
.azure-pipelines.yml
.daily.yml
.github/workflows/ci-checks.yml
.multi-thread.yml
.stress.yml
doc/audit/builtin_maps.rst
doc/requirements.txt
getting_started/setup_vm/roles/ccf_build/tasks/install.yml
getting_started/setup_vm/roles/ccf_build/vars/common.yml

Follow-up from #2787 
We now use the latest version of Doxygen, which we have to build from source.

Use latest version of Doxygen

---

tests/infra/remote.py

The latest Intel DCAP produces the following line on stderr, which causes our clean shutdown check to fail:
```
[get_qpl_handle ../qe_logic.cpp:295] Failed to set logging callback for the quote provider library
```

Ignore stderr noise produced by 1.11 Intel DCAP

---

src/consensus/aft/raft.h
src/consensus/aft/test/logging_stub.h
src/kv/deserialise.h
src/kv/kv_types.h
src/node/progress_tracker.h

If a backup observes a signature mismatch it should rollback to the last committed index.

BFT rollback correctly on signature mismatch

---

src/apps/tpcc/tpcc.cmake

resolves #2786
The tpcc_bft used to take close to 90s (timeout limit) to run. However, with #2682 there was a slight performance degradation and we are now seeing the test occasionally not completing on time.

Fix TPCC BFT timeout issue

---

src/crypto/key_pair.h
src/crypto/mbedtls/key_pair.cpp
src/crypto/mbedtls/key_pair.h
src/crypto/openssl/key_pair.cpp
src/crypto/openssl/key_pair.h
src/crypto/openssl/openssl_wrappers.h
src/crypto/san.h
src/crypto/test/crypto.cpp
src/node/identity.h
src/node/node_state.h
src/tls/test/cert.cpp

Part of #2554 
Historically, mbedtls was the only crypto backend we used for generating node/service certificates. However, mbedtls [doesn't support parsing x509 v3 extensions from a CSR](https://github.com/ARMmbed/mbedtls/issues/2912) and we circumvented that by specifying the SANs explicitly when the certificate was created from the CSR, rather than reading the SANs from the CSR directly. This was OK while the CSRs and certificates were created on the same nodes, but won't be the case after #2554 (joining node will pass its CSR to the primary which will sign it when the node becomes trusted). 
This PR adds the ability to read the extensions from the CSR and apply them to the certificate directly (**OpenSSL implementation only**). This avoids having to store the SANs for each node in the …

Read SubjectAltName field from CSR

---

.multi-thread.yml
.threading_canary

The bft tests are failing consistently since https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=29098&view=results, they need investigation, but we must keep the main build green in the meantime to avoid CFT regressions.

Turn off BFT tests in Multi-threaded job

---

src/enclave/main.cpp

I moved `consensus_type` in #2780, from a top-level argument to nested within the passed config.
This broke compilation, which tries to access an undefined variable, but only when `ENABLE_BFT=OFF`, which only happens in the release job. We should think about adding a regular build configuration which tests this flag, since every other build currently uses `ENABLE_BFT=ON` (and then runs tests on that BFT build).

Release fix: Move `consenus_type` check to where it is now defined

---

getting_started/setup_vm/app-dev.yml
getting_started/setup_vm/app-run.yml

This change was applied to build release images for 1.0.8 and is necessary going forward until the switch to clang-10.

Do not try to use non-existent focal-8 llvm repo (#2836)

---

tests/infra/checker.py
tests/infra/network.py
tests/partitions_test.py

I noticed the partitions test had gotten very verbose, printing repeated identical calls to `find_primary`:
We explicitly capture these repeated attempts to remove this spam. However, we recently added a call to `find_backup()` which doesn't have this protection, and transitively calls `find_primary()` if not given a node, resulting in this spam.
The fix is 2-fold: don't do this in the loop (to trigger a view change, we should be able to submit a single transaction?), and pass an existing node so that even this doesn't need to call `find_primary()`.
Halves the output length of `partitions_test`:
```
$ sudo ./tests.sh -VV -R partitions_cft | wc -l
720
$ sudo ./tests.sh -VV -R partitions_cft | wc -l
339
```

Reduce spam in Python infra

---

.daily_canary
src/consensus/aft/test/main.cpp

I made a change in #2840 to implement `raft_test`'s `dispatch_all` in terms of `dispatch_all_and_DOCTEST_CHECK`, to reduce code duplication. This introduced an unsafe cast, spotted by the SAN in the instrumented daily build. This removes that cast - `constexpr` out the assertion block, rather than passing and casting-to an incorrect type.

Remove unsafe cast in `raft_test`

---

.daily_canary
src/node/rpc/frontend.h

Fix for #2847.
I misread the spec for the `Location` header when first implementing this `TEMPORARY_REDIRECT` response, and as a result it was junk. We returned `Location: 127.4.5.6:1234`, and the client treats this as an alternative relative path, so if it's a redirection for `/app/log/private` it produces `/app/log/127.4.5.6:1234`. We now correctly return a complete URL to the redirected resource, in the same way we do for `PERMANENT_REDIRECT`s in the `node_frontend`, including the same assumption that `pubhost:pubport` is useable by the client.
I'm surprised this wasn't seen before. I think we only hit this path when a forwarded request reaches a node who is no longer primary, and the recent `check_can_progress` changes made that more common. I can't think of a way to trigger that …

Return compliant URL in `Location` header of `TEMPORARY_REDIRECT` responses

---

python/ccf/proposal_generator.py

Fixes `forum_app`, which has broken because of some dependency upgrade now using a `.js_commonjs-proxy` file (previously built but not used, so safely never uploaded). There's a risk that this uploads junk in future, if apps include more non-source things under their build folder, but seems a necessary tradeoff.

Remove .js file from glob pattern when uploading JS apps

---

src/consensus/aft/raft.h

See discussion in #2853. Don't understand why this doesn't work, much less why it doesn't work _in the way it does_, but this workaround seems to placate the tests so seems a sensible compromise for now.

Fix for `recovery_test_bft`: Restore old AppendEntriesResponse value

---

scripts/check-format.sh

Without `-Werror`, this raises warnings but doesn't reformat. I think we want no warnings, to format all.

Fix `check-format.sh` script: Pass -Werror

---

doc/contribute/release_ccf.rst

Since we cannot automatically create Issues/PRs without permission escalation (#2837), we will instead rely on a manual labelling policy to ensure things reach the LTS.
I've briefly documented this policy here. We should probably replace `lts` in these docs with `N.x`, and the same in our existing labels (`lts-candidate` -> `1.x-candidate`, `lts` -> `1.x`), for future sanity.

Document LTS PR label policy

---

.azure-pipelines-templates/daily-matrix.yml
.azure-pipelines-templates/matrix.yml
.azure-pipelines-templates/stress-matrix.yml
.multi-thread.yml

Note `1es-dcv2-focal` is capped to two executors at the moment, for quota reasons. I will bump it up once this is merged and the old pool is no longer used.

Switch all containerised SGX builds to hosted 1ES pool

---

src/node/progress_tracker_types.h
src/node/test/progress_tracker.cpp

Previous code incorrectly computed threshold=3 when count=2, was unnecessarily complex.

Fix BFT threshold calculation

---

src/node/rpc/frontend.h

Contains the fix to `TEMPORARY_REDIRECT`'s `Location` header from #2849.

Cherry-pick #2849 to LTS 1.x

---

.daily_canary
tests/lts_compatibility.py

Part of #2554 
In the LTS compatibility test, we only used the initial constitution of the `from_install` installation. We now update the constitution to the latest version after each code update, to be as close to a real deployment as we can.

Update constitution and add node to LTS compatibility test

---

.azure-pipelines-gh-pages.yml
.azure-pipelines-templates/common.yml
tests/infra/github.py
tests/lts_compatibility.py
tests/requirements.txt

As we somehow cannot use GitHub token to prevent the GitHub API throttle (see #2779), this PR removes the use of the GitHub API and replaces it with plain old Git.

Remove use of GithHub API for `lts_compatibility` test

---

src/node/config.h
src/node/node_state.h
src/node/rpc/node_call_types.h
src/node/rpc/node_frontend.h
src/node/rpc/serialization.h
src/node/rpc/test/node_frontend_test.cpp

The `service_status` field wasn't serialised in the `/node/join` response. Hopefully this doesn't break any BFT test but it might as I think all nodes join as `Follower` rather than `Learner` in BFT. 
Also updated the serialisation format for the `/node/join` response, using `std::optional` for the `NetworkInfo` struct which is only set when the node has been trusted.

Serialise `service_status` field in Join response

---

.daily_canary
tests/e2e_suite.py
tests/infra/network.py
tests/reconfiguration.py

Fix #2896 
The `test_node_replacement`, when chained after `test_kill_primary` failed consistently as the consensus couldn't make progress. This is because the `at_least_n_nodes(3)` requirement wasn't precise enough. In this case, the network was already degraded when the test started (4 trusted nodes but 1 is stopped) so the backup suspension at the end of the test meant that they were only 2 nodes left for consensus, which is less than the quorum of 3.
Also added a `--dry-run` option to the test suite, and tweaked the local node id logic in the infra so that node ids aren't re-used when a node is retired.

Fix `test_node_replacement` failure in `full_test_suite`

---

CMakeLists.txt
doc/audit/builtin_maps.rst
src/consensus/aft/raft.h
src/consensus/aft/raft_consensus.h
src/consensus/aft/test/committable_suffix.cpp
src/consensus/aft/test/driver.h
src/consensus/aft/test/main.cpp
src/http/authentication/cert_auth.h
src/kv/kv_types.h
src/kv/test/stub_consensus.h
src/node/byzantine_identity.h
src/node/entities.h
src/node/hooks.h
src/node/identity.h
src/node/network_tables.h
src/node/node_state.h
src/node/reconfig_id.h
src/node/resharing.h
src/node/resharing_tracker.h
src/node/resharing_types.h
src/node/rpc/call_types.h
src/node/rpc/error.h
src/node/rpc/node_frontend.h
src/node/rpc/serialization.h
src/node/rpc/test/node_frontend_test.cpp
tests/reconfiguration.py

Adds identity hooks and makes reconfiguration dependent on having an identity (if enabled). Addresses  #2724.

Resharing hooks and RPC

---

.azure-pipelines-templates/matrix.yml

This is to save execution time, because suites only relatively rarely seem to catch errors that individual tests don't in CI.
They remain very useful though, because they've caught subtle problems more than once, so we do want to run them in Daily.

Disable suites in CI, leave them in Daily

---

CMakeLists.txt
tests/infra/e2e_args.py

Revert "Reduce signature interval to 100ms in e2e tests"

---

.azure-pipelines-templates/matrix.yml

We currently have these mitigations enabled in debug, which slows down both building and running test in CI. This isn't useful.
The remain on:
- by default, because it's the safe choice
- in Release builds, Perf test builds and in the Daily everywhere
Debug build, as in SGX CI, without mitigations:
real    2m43.526s
user    16m14.244s
sys     0m54.846s
With:
real    3m55.891s
user    17m45.885s
sys     0m56.196s

Disable LVI mitigations in Debug builds

---

cmake/common.cmake

Note: `POSITION_INDEPENDENT_CODE` is already set by the `add_enclave_library_c`/`add_host_library` helpers.

Use cmake helpers for `http_parser` library

---

cmake/common.cmake
tests/infra/remote.py
tests/unit_test_wrapper.sh

We ceased needing this wrapper code when we removed coverage.

Remove now-unnecessary profiling wrappers

---

CMakeLists.txt
tests/election.py

Slightly more test concurrency, slight speedup.

Run election tests concurrently

---

src/consensus/aft/request.h
src/consensus/aft/revealed_nonces.h
src/kv/deserialise.h
src/kv/map.h
src/kv/set.h
src/kv/test/kv_test.cpp
src/kv/value.h
src/node/backup_signatures.h
src/node/constitution.h
src/node/genesis_gen.h
src/node/historical_queries.h
src/node/ledger_secrets.h
src/node/node_state.h
src/node/progress_tracker_types.h
src/node/rpc/frontend.h
src/node/rpc/member_frontend.h
src/node/rpc/test/frontend_test.cpp
src/node/secret_broadcast.h
src/node/secrets.h
src/node/share_manager.h
src/node/shares.h
src/node/snapshot_evidence.h
src/node/snapshotter.h
src/node/view_change.h

Fairly standalone change, which will be required for adding hooks on the signatures table (as part of #2958). 
The `kv::Set` and `kv::Value` (introduced in #2599) didn't yet support local and global commit hooks. This PR adds support for those and also convert the remaining service tables to using `kv::Value`.

Add hooks for `kv::Set` and `kv::Value` and convert remaining service tables

---

src/apps/js_generic/js_generic.cpp
src/js/oe.cpp
src/js/plugin.h
src/js/wrap.cpp
src/js/wrap.h
src/node/node_state.h
src/node/rpc/member_frontend.h

This PR mostly defines the interface for JS FFI plugins, both for defining plugins and how to register them. The `openenclave` global is now such a plugin (which is currently hard-coded to be always registered), which meant moving more code into `oe.cpp`. The interface is very generic currently and a plugin can do anything to a `JSContext`.
- A plugin defines a human-readable name (used for logging only).
- A plugin includes the CCF version it was built against. If during registration it doesn't match the running version, an exception is thrown. Only exact matches are allowed.
- A plugin defines a function that extends an existing `JSContext` arbitrarily. The function doesn't receive any other arguments currently.
- Plugins are registered both in `js_generic` and for governance calls. …

JS FFI plugin interface with `openenclave` as first plugin

---

.azure-pipelines-gh-pages.yml
js/ccf-app/package.json
tests/js-modules/modules.py
tests/npm-app/package.json

Cherry-picking #2923, to fix `modules_test` in the CI of the 1.x branch.

Cherry-pick #2923 to 1.x LTS

---

CHANGELOG.md
doc/build_apps/api.rst
doc/build_apps/logging_cpp.rst
include/ccf/historical_queries_adapter.h
samples/apps/logging/logging.cpp
src/apps/js_generic/js_generic.cpp
src/endpoints/common_endpoint_registry.cpp
src/http/http_consts.h
src/node/rpc/error.h
tests/e2e_logging.py

Address #2640. This is essentially two changes:
1. Switch from 400 to 404, for historical transactions on requests that aren't committed (yet).
2. Give a different error reason for transaction ids that are invalid (forever) vs unknown/pending (so far, but may resolve).
TODO:

Historical adapter v2

---

doc/build_apps/kv/kv_how_to.rst

There seem to be a find&replace mismatch between example 1 and 2. I
think this is what the original intention was.

Key-value doc fix

---

.azure-pipelines-gh-pages.yml
.azure-pipelines.yml
.daily.yml
.github/workflows/ci-checks.yml
.multi-thread.yml
.stress.yml
CHANGELOG.md
getting_started/setup_vm/roles/openenclave/vars/common.yml

To be cherry-picked on LTS. This minor release of Open Enclave picks up the latest OpenSSL (1.1.1l) and its CVE fixes.
Open Enclave release notes: https://github.com/openenclave/openenclave/releases/tag/v0.17.2
OpenSSL release notes: https://www.openssl.org/news/openssl-1.1.1-notes.html

Open Enclave upgrade 0.17.2

---

.daily_canary
tests/infra/network.py

On recovery, the first node local ID was wrongly set to how many nodes were in the previous service + the next local ID to allocate. For example, when recovering a 3-node service (IDs: 0, 1 and 2), the first recovery node ID was 6 (instead of 3)

Python infra: Fix node ID gap in recovery

---

getting_started/setup_vm/roles/ccf_build/tasks/install.yml

My environment had an override for the default generator do be ninja and
the ansible-playbook failed. This forces the generator, regardless of
what your default is.
Fixes #2993

Force makefile generator on mbedtls build

---

.azure-pipelines-templates/daily-matrix.yml
.azure-pipelines-templates/matrix.yml
.azure-pipelines-templates/test.yml
.multi-thread.yml
CMakeLists.txt

As noted in #2996, we have a CTest test case which requires root permissions, meaning that new users trying a straight build-and-run will see errors. Instead of requiring them to provide root permissions, I think we should move that test to a standalone configuration so it is only run on-demand (by passing `-C partitions`).
Fixes #2996.

Move `partitions_cft` to its own CTest configuration

---

tests/infra/runner.py

Giving these args long names for readability:
```
python ... --help
...
-N, --show-only       List all sub-tests without executing (default: False)
-R <string>, --regex <string>
Run sub-tests whose name includes this string (default: None)
```
<sub>(Sure it's not really a regex, but it's `-R` to match the CTest argument which _is_ a `--regex`, so I think that's what it's _called_ even if it's not what it _does_?)</sub>
Also printing just the thread name rather than the raw thread object, and filtering before printing to match CTest. Compare:
Old
```
python ... -R cpp -N
...
<Thread(js, initial)>
<Thread(cpp, initial)>
```
New
```
python ... -R cpp -N
...
cpp
```

Tweak arg names and behaviour of ConcurrentRunner

---

tests/suite/test_requirements.py

Finding where a test starts in a full CI run was tedious. We now colour the test name differently. We also include the list of `kwargs` arguments to the test, to differentiate the same test called with different arguments.

Python infra: improved test description

---

.daily_canary
tests/infra/github.py

During a release, the release tag is created first, but the release itself isn't created until the CI has successfully run. This means that we should ignore existing tags that haven't yet got a release (like we already do for the `lts_compatibility` test).

Fix issue with latest tag and release in progress

---

.daily_canary
src/node/node_state.h

As touched on #2991, most objects (e.g. `history`, `encryptor`) were initialised in multiple places in `node_state.h` because the node ID (`self`) wasn't known until the node had joined or recovered the service. This is no longer the case since node IDs are now derived from the node's public key, so attempting to simplify this.

Simplify objects initialisation in `node_state.h`

---

tests/e2e_logging.py

The service identity isn't stable across recovery.

Fix LTS recovery

---

.azure-pipelines-templates/daily-matrix.yml
tests/e2e_logging.py

lts_compatibility was getting close to 300, and now exceeds it because receipt verification has become more expensive as a result of #2991.

Bump daily timeout

---

.azure-pipelines-v8.yml
scripts/build-v8.sh

Creating a script to build V8 and a pipeline config to run that,
publishing an artifact with the monolith version (ready for embedding).
The pipeline has two build options:
* VERSION (mandatory): ex. 9.4.146.17
* PUSH_ARTIFACT: true|false
We only need to publish the artifact once, but we can continue to build
making sure the build still works with the expected version, which it
won't if the version is updated upstream.
The version of the artifact needs to be changed due to Universal
Packages' constraints. It can only accept three sections, but with the
four from V8 and one from our builds, we'd have five.
Given that the first two sections in V8's version is the Chrome version
(ex. 9.4 -> 94), we join them. We also need to join the two last ones,
so that we can add a build ID.
The final …

V8 pipeline publishing artifact

---

tests/lts_compatibility.py

`version` is the full string (`ccf-...`) while `major_version` should be the major version integer.

Fix incorrect version comparison in test

---

src/node/channels.h
src/node/node_state.h
src/tls/key_exchange.h

Since #2801 we've had a high rate of failures in the `lts_compatibility` build. After investigating the logs I believe I've found the root cause. Opening as a PR with a forced repro initially, and then I'll add the resolution.
A healthy join of a new-node to old-node looks like this:
```
35:10.928 |03|       Node has now joined the network as node n[3=1735]: all domains (node_state.h:578)
35:10.967 |00| Initiating node channel with 3=1735. (channels.h:713)
35:11.035 |00| Node channel with 3=1735 is now established. (channels.h:690)
35:11.059 |03|       Node channel with n[0=2f90] is now established. (channels.h:732)
```
The failures we're seeing look like this:
```
35:17.470 |04|         Node has now joined the network as node n[4=e75f]: all domains (node_state.h:578)
35:17.508 |00| …
```

Channels fix: Resolve lts_compatibility test failures

---

README.md

Badge currently links to `badge.svg`. Now it is a hyperlink to the workflow it describes.

Correct containers badge link in README

---

include/ccf/historical_queries_interface.h
src/node/historical_queries.h
src/node/rpc/test/node_stub.h

This brings parity with `get_store_range`.
I also did some minor cleanup.

Add `get_state_range` to historical queries interface

---

.daily_canary
tests/lts_compatibility.py

Recent LTS compatibility failures (eg. https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=33677&view=results) seem to be caused by an assumption in the test that nodes resuming from suspension will not cause an election.
This seems to have been mostly the case pre-new channels but not any more. This change is simplifying the test somewhat, to retire old nodes and trigger transactions after they've gone.
What it does _not_ do is guarantee that we go through a situation where a primary running new code is replicating to nodes running old code successfully, but is closer to how a code upgrade is probably run. If we want to reliably test that particular mixed scenario, all I can think of is to force the election to come down the way we want by tweaking timeouts.
As @eddyashton …

A more basic LTS test

---

.azure-pipelines-v8.yml
scripts/build-v8.sh
scripts/fetch-v8.sh

Adding a new script to fetch the pipeline artifact for using V8 into
CCF.
Mistakes on artifact naming have made it hard to get the right package.
When implementing the fetch script I realised the problem and have now
fixed in all three places: build-v8, pipeline, fetch-v8
Also, build now fetches the tag "$VERSION" instead of relying the
branch-head to be on the same version and failing.
A future addition would be to pass less info (ex. 9.4) and get the
script to fetch the head and figure out the version on its own.

Fetch and improve V8 build

---

src/kv/test/stub_consensus.h
src/node/historical_queries.h
src/node/test/historical_queries.cpp
tests/historical_query_perf.py
tests/lts_compatibility.py

Signature verification is only required to confirm provenance. To confirm integrity, it is sufficient to validate the existing GCM header. Providence is not a meaningful property for nodes to confirm, instead they can return receipts which allow callers to check signatures + provenance if they wish.
An additional check which we didn't have to do previously but do now is explicitly confirming that each entry is a precursor to the current state, by checking its (integrity-protected) TxID matches the consensus' view history.
TODO:

Historical query perf improvements: Replace signature verification with GCM header check

---

CHANGELOG.md
include/ccf/historical_queries_interface.h
src/kv/test/stub_consensus.h
src/node/historical_queries.h
src/node/rpc/test/node_stub.h
src/node/test/historical_queries.cpp

#3041 - Historical query performance improvement
#3037 - Supporting API standardisation (not strictly required, but makes the above a simpler merge)
Also added missing links to `CHANGELOG.md`.

Cherry-pick #3037 and #3041 to 1.x LTS

---

.daily_canary
tests/infra/network.py
tests/partitions_test.py

Fix for recent failure in Daily: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=33725&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=a2a8c6c1-1b13-59a7-596c-97d4f22a6857&l=214
The main issue was that `wait_for_primary_unanimity` wasn't working as intended. Additionally, while looking at this, we realised that we were waiting unnecessarily long for all of our election timeouts, as we doubled them twice. The base election duration should be 1 election + some roundtrips for it, then the multiplier correctly waits for N such elections.

Fix partitions_test

---

.daily_canary
tests/infra/jwt_issuer.py
tests/infra/network.py
tests/reconfiguration.py
tests/suite/test_requirements.py

The `reconfiguration.test_node_replacement` failed with the seed `SHUFFLE_SUITE_SEED=1633506379` because the test didn't take into account nodes that were previously killed.

Fix `full_test_suite` node replacement

---

tests/nobuiltins.py

#3146 was wrong, and relied on `/commit` returning a `tx_id` header (which it normally doesn't, but does one-off on service open!)
This is a correction to that; call an endpoint which reliably does KV reads, to find the service's current tail.

Fix #2 for nobuiltins - wait for stable commit from a real TxID

---

doc/conf.py

The doc job is starting to take quite a long time, and so it's tempting not to maintain documentation for older LTS releases, particularly since the changes from one LTS to the next are very small.
I think we also only should build the doc for the latest -dev, but that's quite a bit more difficult to do with regexps sadly.

Do not build doc pre-1.0.1x

---

CHANGELOG.md
src/host/main.cpp

Noticed that this else was in the wrong place, so it is [always printed](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=35699&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=cf4e34b3-24ee-5d97-0df9-ba9302d9fe90&l=28232) on `start` nodes, and doesn't actually exit when it says it does. Fixing both of those directly on the LTS branch.

[LTS] Correct reporting of missing `cchost` subcommand

---

python/ccf/ledger_viz.py

I keep misreading the key printed by `ledger_viz`.
At a glance, I find the word "Signature", and the colour right next to it is red, so the initial read is that Signatures are red. I think the problem is that the `: ` spacer introduces more distance between the key and its value, than the ` ` separator between entries.
This changes the separator so that my feeble brain can read it at a glance.

Tweak printing of legend for `ledger_viz`

---

tests/nobuiltins.py

Yet another attempt following #3146 and #3150, to fix what was originally a one-off CI failure.
~~The last fix only worked if the signature had happened before the `/node/network` read, otherwise the TxIDs would never actually match (despite indicating that the intended commit had occurred). Rather than re-implementing more of the commit tracking logic, we just reuse the existing `wait_for_commit`, and then do a final call to get the stable `/node/commit` value after that.~~
@jumaffre has pointed out that the network setup infra is already waiting for its changes to be globally committed. The increasing TxID is not caused by a slow commit, it comes from a snapshot being produced (every 10tx in all tests by default). We could increase the snapshot interval to avoid this, but I think it's …

Another fix for 'nobuiltins'

---

src/endpoints/common_endpoint_registry.cpp

Noticed that `/api` was not callable when there is no known primary, because the node attempts to forward it. This is unnecessary - it is read-only, and should be marked as such.

Change '/api' endpoint to be read-only

---

.daily_canary
CHANGELOG.md
js/ccf-app/package.json
src/node/ledger_secrets.h
src/node/test/encryptor.cpp
tests/infra/github.py

When a backup node joins a service, it is given the entire history of ledger secrets so far (part of the `/node/join` response). If an election is triggered when the node is catching up, the node will rollback its store, which will cause the ledger secrets to be rolled back too. This is incorrect since the backup will need the ledger secrets to decrypt further entries, once the catch up phase is complete.
For example, if a new node joined without a snapshot and received the ledger secrets at seqnos `{1, 10}`, caught up till `5` at which point an election was triggered (new joiner's store is rolled back at `5`, ledger secrets at now `{1}`), it wouldn't have been able to deserialise entries from `10` onwards.
We now protect the initial ledger secrets received in the `/node/join` response so …

Never rollback initial ledger secrets

---

CHANGELOG.md

The primary motivation for this release is to make sure the release pipeline is still fully functional, following recent changes.

Update changelog for -dev6

---

src/consensus/aft/raft.h
tests/reconfiguration.py

This fixes a bug in the retirement logic for 2tx reconfiguration. A node would not revert to being a follower after it's change to `RETIRING` was rolled back. It does so with this fix, but it now triggers a long series of elections, sometimes ending up in a situation where it rejects append entries for a long time (possibly forever).
Also adds a function to wait for reconfiguration completion in tests to avoid tests interfering with each other.

Fix retirement bugs in 2tx reconfig

---

tests/infra/network.py

Noticed in an unlucky local run. This check can fail if _no_ nodes know the current primary, since the current loop assumes that (eventually) the number of primaries retrieved matches the number of nodes. So we need to assert both the length, and the equality of all retrieved primaries.
Note this doesn't apply to the similar check for commits, since that always gets a response-per-node.

Fix check for primary unanimity

---

include/ccf/tx_id.h
src/crypto/openssl/x509_time.h

Adding two missing headers that are probably included elsewhere but are
needed in these files.
This was discovered by removing some includes from headers in TLS.

[NFC] Add missing headers

---

.daily_canary
doc/overview/consensus/index.rst
src/consensus/consensus_types.h
src/host/main.cpp
src/node/node_state.h
tests/infra/e2e_args.py
tests/infra/network.py
tests/infra/remote.py

The BFT status interval was unused and we now use the Raft election timeout for BFT view changes as well.

Remove BFT timeouts options

---

.daily_canary
tests/e2e_tutorial.py
tests/infra/network.py
tests/infra/node.py
tests/infra/remote.py
tests/lts_compatibility.py
tests/recovery.py

Part of #2612 
Minor change to consider multiple read-only ledger directories as opposed to just one as CCF nodes accept an arbitrary number of them but the infra only coped with one so far.

Infra: Consider multiple read-only ledger directories

---

src/crypto/ecdsa.h
src/crypto/openssl/openssl_wrappers.h

ECDSA_SIG_set0 owns the pointer, so the `release` return value can be
ignored, but this is specific of this pattern and the Unique_BIGNUM
class itself should always return it and let the user decides.
This commit adds a comment (with reference) to make explicit why we're
ignoring the release return values.

Silencing a warning for ignoring return value

---

python/ccf/proposal_generator.py

Noticed while doing some manual testing that this arg was missing a type annotation, and as a result wasn't correctly exposed to the CLI, and was actually listed as a required arg.
Before:
```
$ python ../python/ccf/proposal_generator.py set_ca_cert_bundle --help
usage: proposal_generator.py set_ca_cert_bundle [-h] cert_bundle_name cert_bundle_path skip_checks
positional arguments:
cert_bundle_name
cert_bundle_path
skip_checks
optional arguments:
-h, --help        show this help message and exit
$ python ../python/ccf/proposal_generator.py set_ca_cert_bundle ./foo ./bar
usage: proposal_generator.py set_ca_cert_bundle [-h] cert_bundle_name cert_bundle_path skip_checks
proposal_generator.py set_ca_cert_bundle: error: the following arguments are required: skip_checks
```
After:
```
$ python …
```

Make `--skip-checks` an optional arg to `set_ca_cert_bundle` proposal

---

.daily_canary
tests/test_install.sh

#3229 broke the Daily: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=37140&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=20753e5b-87ba-5bdc-0f17-d34c09f927a7&l=291
I believe that's because of this missing `-e`. Running Daily on this PR to confirm.

Test fix - install package so that jinja's PackageLoader works

---

src/consensus/aft/raft_consensus.h
src/kv/kv_types.h
src/kv/test/stub_consensus.h

We used to have `emit_signature` in both `Consensus` and `History`. Now the only used implementation is in `History`, so we can remove this vestigial method from `Consensus`.

Remove unused method

---

CHANGELOG.md
python/ccf/ledger.py
src/kv/encryptor.h
src/kv/generic_serialise_wrapper.h
src/kv/kv_types.h
src/kv/raw_serialise.h
src/kv/snapshot.h
src/kv/test/null_encryptor.h
src/node/test/encryptor.cpp

See #3275. Internally, CCF now interprets the former `bool is_snapshot` field in ledger transactions as an `enum EntryType entry_type`. The values and their semantics remain identical for now, but will be extended in 2.0. This change is back-ported to provide a user-friendly error in the event that 1.x nodes attempt to read a ledger produced by 2.x nodes (#3275).

Convert is snapshot to entry type, cherry-pick #3275 to LTS

---

doc/requirements.txt

See broken doc build https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=37978&view=results under https://github.com/microsoft/CCF/pull/3284 for details.
```
Running Sphinx v4.3.1
Exception occurred:
File "/__w/1/s/env/lib/python3.8/site-packages/m2r.py", line 59, in <module>
class RestBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'
```

Pin mistune to pre-2.x to fix doc build

---

src/ds/contiguous_set.h
src/ds/test/contiguous_set.cpp

Another standalone piece pulled from #3280.
Converts the iterator in `ds::ContiguousSet` from a forward iterator to a random-access iterator, so it can implement a reasonably efficient `lower_bound`/`upper_bound`. Also has an efficient constructor for creating a subset of another `ContiguousSet`, copying its ranges directly. And >200 lines of related unit tests.

Extend API of `ds::ContiguousSet` to support random access

---

CHANGELOG.md
doc/schemas/node_openapi.json
src/consensus/aft/raft.h
src/consensus/aft/raft_consensus.h
src/kv/kv_types.h
src/kv/test/stub_consensus.h
src/node/hooks.h
src/node/node_state.h
src/node/rpc/node_frontend.h
src/runtime_config/default/actions.js
tests/infra/consortium.py
tests/reconfiguration.py

Here's a sketch of how we could do 1tx to 2tx reconfiguration migration. Not necessarily intended to be merged, just a basis for discussion on how we want to do things. 
I think adding a hook on the service config table is a good idea in general, even if all we want to do is to reject any unwanted updates.

1tx to 2tx reconfiguration migration

---

.daily_canary
src/runtime_config/default/actions.js

I believe the regression was introduced in #3198 because of my comment (https://github.com/microsoft/CCF/pull/3198#discussion_r760363198): even if the proposal execution is atomic, `triggerRecoverySharesRefresh()` needs to read the `kv::Tx`'s own writes to find out the latest value of the recovery threshold.

Fix recovery threshold update proposal action

---

.daily_canary
tests/infra/github.py

We've started to hit this new error in the Daily pipeline: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=38267&view=logs&j=e982d093-d12a-5a2d-1a1d-0c6d38b8823f&t=8be5454d-0d8f-51e4-7372-58df022e9ebc&l=31963
This is because we download LTS releases many times in a row when running the `lts_compatibility_*` end-to-end test. 
The infra will now skip the release download from GitHub and use the local install if this one already exists.

Skip LTS download if it already exists locally

---

scripts/v8/v8-9.4.146.17.patch
src/apps/js_v8/v8_oe_stubs.cpp

With these patches, the `e2e_logging.py` tests pass, except for the last one, which produces garbage output. I suspect that's an issue with the custom historical adapter though, not with V8 or OE.

V8 memory handling patches

---

.daily_canary
src/node/node_state.h
src/node/rpc/node_call_types.h
src/node/rpc/node_frontend.h
src/node/rpc/serialization.h
tests/governance.py

Resolves #2893 
This was the last item in the node certificate renewal work stream: because transactions can be rolled back, nodes shouldn't present the renewed endorsed certificate until the renewal has been (globally) committed. This is mostly trivial, except for the very first transaction that needs to know about the endorsed certificate before the first signature is emitted (since endorsed node certificates are currently recorded in the signature). 
Also remove a few unused BFT-specific code paths here and there.

Update endorsed node certificate on global hook

---

.github/workflows/ci-containers.yml
doc/contribute/build_images.rst
doc/contribute/index.rst

Attempt to solve #3303. Will trigger when a tag starting with `ccf_ci_image/$TAG` is pushed, and will create an image from this tag called `ccfciteam/ccf-ci:$TAG`.
Note: I know it says container**s**, and we only have the one CI container now, but I have a hunch this won't last and renaming GitHub CI flows is zero fun, since you can never delete the old ones.
Also note the deliberate absence of `:latest`, as opposed to releases, because I can't imagine ever using that happily.

Add job to build CI containers

---

tests/e2e_logging.py

At some point verification wasn't supported in js_generic due to missing receipt endpoints, but this is not the case anymore.

Always run txs.verify() in e2e_logging test

---

tests/infra/remote.py

New log output if a node was killed by a signal:
```
43: 11:27:26.261 | ERROR    | infra.remote:stop:495 - 127.6.188.245 exited with signal: Segmentation fault
```
Fixes #3331.

Print signal a node was terminated by

---

getting_started/setup_vm/roles/ccf_build/vars/common.yml

Same as #3355, for different reasons: the post-release containers building job fails because of this at the moment.

Update doxygen on 1.x

---

.daily_canary
src/tls/openssl/context.h

These are the approved ciphers and curves that we can support. The TLS
1.2 cipher remains the same for compatibility, but the TLS 1.3 cipher
suites is updated to include stronger ciphers.
Comparing the TLS Report, now that I know what to look for, this is now
on par with the previous report (same bit-rate, server-order, restricted
curves), but strictly better with TLS 1.3 and more, stronger approved
ciphers in 1.3.

Add more ciphers and restrict elliptic curves in OpenSSL

---

Doxyfile

Follow-up from #3355 
Running the new version of `doxygen` yields the following warnings:
```bash
$ cd CCF/
$ doxygen
warning: Tag 'LATEX_SOURCE_CODE' at line 1738 of file 'Doxyfile' has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'RTF_SOURCE_CODE' at line 1820 of file 'Doxyfile' has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOCBOOK_PROGRAMLISTING' at line 1918 of file 'Doxyfile' has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'CLASS_DIAGRAMS' at line 2105 of file 'Doxyfile' has become obsolete.
To avoid this …
```

Update Doxyfile to 1.9.3

---

doc/conf.py

Resolving the issue that produced this: https://github.com/microsoft/CCF/pull/3386#discussion_r782272910
`conf.py` tries to install exactly `colors@1.4.0` when building all versions of our docs. But if you run `npm install colors@1.4.0`, it modifies `package.json` to make the version `^1.4.0`, which we absolutely don't want. The fix is a more precise argument `--save-exact`, which modifies `package.json` to (the current value) `1.4.0`, not `^1.4.0`.

Save exact version to `package.json`

---

tests/infra/proc.py
tests/jwt_test.py

The `SGX_AESM_ADDR` environment variable affects whether in-process or out-of-process attestation is used. Specifically, in-proc is only used when this env var is unset. We only test in-proc attestation, and this is enforced on `cchost` as we explicitly wipe the environment whenever we invoke it.
This PR applies the same behaviour to invocations of `oeutil generate-evidence` (used in the `jwt_test`), to ensure they use the tested in-process attestation regardless of system-wide settings.
Some more pointers for anyone investigating this in future:
- [OE docs around in-proc vs out-of-proc selection](https://github.com/openenclave/openenclave/blob/753e3227b9721851d363f028e37e5431f2311ca3/docs/GettingStartedDocs/Contributors/SGX1GettingStarted.md#determine-call-path-for-sgx-quote-generation-in …

Always use in-process attestation when calling oeutil

---

src/crypto/openssl/public_key.cpp
src/crypto/test/crypto.cpp

This fixes the decoding of DER-encoded public keys. Our OpenSSL-based implementation used the wrong function and could not decode keys from mbedTLS, which we need/want for LTS compatibility reasons. The new test now checks that both implementations produce identical DER encodings and that they can decode each other's keys.

Fix decoding of public keys in DER format

---

tests/reconfiguration.py

Noticed this while investigating #2320 
The existing `test_add_as_many_pending_nodes` test aims to test that pending nodes do not participate in consensus. However, it only stopped the nodes at the end of the test, once they are retired, instead of stopping them early and verifying that the service can still make progress.

Tweak `test_add_as_many_pending_nodes` reconfiguration test case

---

doc/_templates/page.html

Our docs were missing an "Edit on GitHub" button. I had a look for an off-the-shelf extension, but there don't seem to be any with clean config or that work directly with the Furo theme.
Instead I'm just inserting it manually into the footer, via a `<script>` tag that modifies the default footer.
If we want to fiddle with the template further we could put it elsewhere on the page, but it seems most naturally to be next to `Show Source`, which we have no control over with this theme.
Looks like this (hovering to show link destination):

Add an Edit link in docs footer

---

src/node/hooks.h

In preparation for https://github.com/microsoft/CCF/pull/3409, 1.x nodes should be able to tolerate nodes being deleted from the KV store.

Accept node deletion in 1.x LTS

---

src/common/enclave_interface_types.h
src/enclave/ccf_v.h
src/enclave/enclave.h
src/enclave/main.cpp
src/host/enclave.h
src/host/main.cpp

Before the enclave node is initialised, and the logger structure is
setup (sending logs through the ring buffer), any error ends up as
InternalError because we can't see the logs yet.
This commit changes that by creating the logging infrastructure before
the node is created (but after the ring buffer is setup), so that any
logs during that time, inside the enclave, can be flushed out and
displayed with the other error messages.
This allows us to be more verbose inside the enclave while constructing
the objects and creating the nodes, which helps debug the causes that
enclaves fail.
Extra work done to pass CreateNodeStatus around instead of throwing
exceptions, handling OE and CCF errors across enclave<->host barriers,
adding a new type of error (version mismatch) and adding a few traces …

Allow logging before enclave node creation to be seen

---

src/crypto/curve.h

Predictably, I failed to remove one mbedTLS `#include`. Interestingly, this wasn't caught in any CI runs, but during the CodeQL build (https://github.com/microsoft/CCF/runs/4857169154?check_suite_focus=true) after merging my changes into `main`.

Remove an mbedTLS include

---

src/crypto/pem.h
src/crypto/test/crypto.cpp
src/enclave/tls_endpoint.h
src/node/test/encryptor.cpp
src/tls/cert.h
src/tls/test/main.cpp
src/tls/tls.h
tests/infra/path.py

This commit cleans up the final references to MbedTLS on the code,
making sure what's left is consistent with OpenSSL.
The only remaining references to "MbedTLS" are the ones that we
need to worry about when we work on #3429.

Remove the final MbedTLS references from the code

---

docker/app_ci
docker/app_run

It is already installed as part of the `ccf_build` role here: https://github.com/microsoft/CCF/blob/c157123e284034d96ac66a26cfe1dbc26ec5aa9b/getting_started/setup_vm/roles/ccf_build/vars/common.yml#L23 
Note that we still do this in the `app_run` image as it is necessary to install the CCF debian package from GitHub.

Do not uninstall `curl` from `app_ci` docker image

---

cmake/common.cmake

Without those, `compile_commands.json` still included OE bits even if virtual is the only compile target, subsequently causing errors in intellisense.

CMake: add missing sgx target guards

---

doc/build_apps/auth/jwt.rst
src/node/jwt_key_auto_refresh.h

This corrects the comments in #3445 after it was merged.
* Rewords the doc paragraph a bit to include auto-refresh.
* Makes clear that each attempt is an issuer, not a key.
* Fixes the MD vs RST format for links.
* Only records an attempt for issuers that have auto-refresh enabled.

Corrections from JWT key PR

---

.azure-pipelines-gh-pages.yml
doc/conf.py
doc/historical_ccf_requirements.txt

I've noticed that the documentation on historical versions of our docs was broken:
This is because:
1. We re-generate the docs for all (including historical `-dev` and LTS releases) every time the GH pages CI job runs on main (*)
2. The Python client API was recently removed on `main` (see #3372), along with its dependencies
We now import the historical version of the `ccf` package when building the versioned docs (with `sphinx-multiversion`) and install the corresponding historical dependencies. (We could try to install the historical dependencies on the fly, from the historical checkout, but this requires running `cmake` to generate `version.py`, but the auto-checkout is in a temporary directory but `cmake` requires a specific directory name to deduce the version, etc. - I think it's …

Fix Python docs for historical versions

---

.daily_canary
cmake/ccf_app.cmake

I broke the daily in #3419, as I wasn't applying the additional linker commands in virtual SAN builds.

Daily fix - export symbols in SAN build

---

js/ccf-app/src/endpoints.ts
src/apps/js_generic/js_generic_base.cpp

The current js_generic implementation does not expose the current request path in the request object that is presented via the TS package.  The issue is mentioned in #3092.  This PR has the changes for both the core js_generic code and the TS package.

Updated js_generic and the ts package to include the request path in the request object.

---

doc/_static/css/custom.css
doc/conf.py

I use the dark theme on our docs, and noticed that strings in highlighted sections (such as JSON strings) have a weirdly light background, which makes them hard to read. This tweaks the CSS for those highlights, hopefully without breaking anything else.
Before:
After:

Change docs CSS to make text in JSON samples visible

---

doc/_static/css/custom.css

There are various theming options for mermaid diagrams, but I couldn't find anyway to re-render them based on the current light theme/dark theme selection. Going with a simple hack suggested by @achamayou - Add a white background to all mermaid divs, so they remain readable.
Before:
After:

Add white background to mermaid divs in dark theme docs

---

src/enclave/rpc_sessions.h
src/node/jwt_key_auto_refresh.h
src/node/node_state.h
src/tls/README.md
src/tls/ca.h
src/tls/cert.h
src/tls/context.h
src/tls/test/main.cpp

Fixes one of the two CodeQL security reports reported recently (both are spurious). Also fixes #3432.

Fix TLS certificate verification

---

src/enclave/tls_endpoint.h
src/tls/client.h
src/tls/context.h
src/tls/server.h
src/tls/test/main.cpp

When moving to OpenSSL, we left some options open for the day we
implement QUIC and need to reuse the TLS context.
However, while looking at QUIC implementation, we realised it doesn't
need some of the things we expected, for example, it doesn't support
DTLS.
There is an effort to port DTLS to QUIC [1], but that seems it's not
going anywhere, so we shouldn't wait for that to work, given this
is a simple cleanup. We can add later, of course.
[1] https://tools.ietf.org/id/draft-rescorla-quic-over-dtls-00.html
Also cleaning the debug BIO hook that is no longer used.

More TLS cleanups

---

tests/e2e_logging.py

A new version of Black was [just released](https://black.readthedocs.io/en/stable/change_log.html#id1). It contains exactly one breaking change for our code:
> Remove spaces around power operators if both operands are simple (#2726)
I think we want to stick with the latest version (especially since it's finally non-Beta!), but this kind of behaviour change is extremely annoying (and will likely break on our next `release/1.x` build...).

Format with Black v22.1.0

---

.azure-pipelines-templates/matrix.yml

The `SGX Release` job we run in the Daily CI is different than the `SGX Release` we run for actual releases. The latter included more tests, in particular the perf tests, which increase the run time and take us over the 60m total limit. This removes those perf tests -there's already an `SGX Perf` job in the same run, which gets similar results (and from build args consistent with other perf tests, if slightly different than the release artifact).

Skip perf tests in tag release job

---

python/ccf/ledger.py
src/kv/kv_types.h

WriteSetWithClaims was only ever used in a couple of dev releases, but there is no intention for it to be used in 2.0.0 final, now that every new-style transaction has commit evidence. As @letmaik suggested, we might as well remove it.

Remove unused WriteSetWithClaims

---

python/ccf/ledger.py
src/kv/kv_types.h

Reverts microsoft/CCF#3485 - This change is incompatible with 1.0.18, and would require a remapped 1.0.19. The minor code simplification isn't worth the extra hassle and risk.

Revert "Remove unused WriteSetWithClaims"

---

doc/conf.py

Note that this does not hardcode this for any specific version of the docs and can be removed/modified at any point.

Add 2.0 announcement in docs

---

tests/infra/interfaces.py

To support calls like `sandbox.sh -v -n local://0.0.0.0:8000,127.0.0.1:8000 -p samples/apps/logging/liblogging.virtual.so`

Fix handling of public addresses in sandbox script

---

.azure-pipelines-gh-pages.yml
doc/conf.py

- Do not publish documentation from release tags (we really only want to publish the documentation from `main` so that it always uses the latest theme, etc.).
- Only run `sphinx-build` (i.e. no multiversion) from pull requests (we don't need to re-build the whole versioned documentation, but only check that the documentation for the local checkout works).

GitHub Pages CI Job updates

---

.daily_canary
src/host/dns.h
src/host/tcp.h

Here is an overly cautious fix for the cleanup of DNS resolution request objects. We probably don't stricly need `pending_resolve_requests` to be global, but I believe the lock on it is necessary. The key change here is that we run over all pending resolution requests in `~TCPImpl` and we set all references to `this` to `nullptr`, so that we can skip the callback when it fires later. 
Fixes #3491.

Fix for async DNS resolution request cleanup

---

CMakeLists.txt
scripts/v8/fetch.sh
src/apps/js_v8/js_v8_base.cpp
src/apps/js_v8/tmpl/request.cpp
src/apps/js_v8/tmpl/request.h
src/apps/js_v8/v8_runner.cpp
tests/e2e_logging.py
tests/js-custom-authorization/custom_authorization.py

Part of #3314.
~~Draft for now, because this will need updating after #3498 is merged.~~ - This is done, the fields added to the QuickJS implementation in #3498 are now also implemented in V8.
~~Includes part of #3324 - setting max heap size to same as QuickJS, but hit the same barriers that issue notes on setting a stack limit. For now, we just test that _a_ (much larger) stack limit still applies to V8.~~ - Gave up on this. Seems even the heap constraint has some platform-dependence that I'm missing, so the CI behaviour is different than local. Just disabled the `limits` test in V8 for now, with a comment pointing at #3324.

Enable auth e2e test in V8

---

doc/audit/receipts.rst

The default name for this file is now `service_cert.pem`. I believe this is the last reference to the old name in the docs.

Remove docs references to old `networkcert.pem`

---

tests/lts_compatibility.py

**Change on 1.x LTS branch**
Testing the compatibility with the next LTS version (i.e. 2.0 in this case) would require the 1.x Python infra to know how to spin up 2.0 nodes. This is too expensive to maintain so let's remove this ability from the `release/1.x` branch, and from `main` too (second PR to follow).

Remove LTS compatibility test with next release (1.x branch)

---

3rdparty/exported/fmt/args.h
3rdparty/exported/fmt/chrono.h
3rdparty/exported/fmt/color.h
3rdparty/exported/fmt/compile.h
3rdparty/exported/fmt/core.h
3rdparty/exported/fmt/format-inl.h
3rdparty/exported/fmt/format.h
3rdparty/exported/fmt/os.h
3rdparty/exported/fmt/ostream.h
3rdparty/exported/fmt/posix.h
3rdparty/exported/fmt/printf.h
3rdparty/exported/fmt/ranges.h
3rdparty/exported/fmt/xchar.h
cgmanifest.json
include/ccf/endpoint_registry.h
include/ccf/entity_id.h
src/ds/json_schema.h
src/ds/logger.h
src/ds/openapi.h
src/host/time_bound_logger.h
src/node/channels.h
src/node/historical_queries.h

Constexpr and consteval changes in clang 12+ requires upgrading fmt to 8.1.1.
This does bring some changes as fmt::format assumes compile-time constant format string and verfication:
1) No constexpr formatter for scoped enums. Need to provide it.
2) Format string for format_to must be constant string.
3) Cannot have `{` or `}` as printed characters in format string.
4) Formatters need to be defined before first usage. 
5) FMT_STRING fails to build in some contexts involving lambdas. But the benefit for FMT_STRING is not clear to me for clang 12+ as it forces compile-time constant format strings even without it (at least this is my limited understanding).
Also added a fix for a newly added warning triggering on parsing code.

Upgraded fmt to 8.1.1

---

src/enclave/main.cpp
src/enclave/oe_shim.h

Make use of newly added `oe_enclave_log_set_callback()` in Open Enclave 0.17.6 to redirect logs to the standard CCF mechanism.

Redirect openenclave logging

---

src/crypto/openssl/base64.h
src/crypto/openssl/openssl_wrappers.h
src/host/enclave.h

New base64 tests introduced yesterday spotted a regular leak on error paths, luckily caught by sanitizers. This fixes those, we should probably do a scan for similar paths in the new OpenSSL code.
Also fixing an uninitialized var from another of yesterday's PRs.

Fix new SAN issues in base64 test

---

.azure-pipelines-gh-pages.yml
.daily_canary
tests/infra/network.py
tests/infra/runner.py

The ledger consistency verification run at the end of all end-to-end tests seems to be skipped for most cases. I want to make sure this is still working, and measure any eventual impact on the total duration of our tests.

Re-enable ledger consistency verification

---

python/ccf/ledger.py
python/ccf/read_ledger.py
tests/governance.py
tests/governance_history.py

This was broken because untested in the CI. We now test this in `governance_history`.

Fix for `read_ledger.py` for snapshot parsing

---

doc/_templates/page.html
doc/index.rst

A recent update to the furo theme broke our hack that inserted an `Edit on GitHub` link to the footer. This restores that link, more closely matching the existing `Edit on GitHub` button that the theme inserts for RTD so that it's a) consistent with other sites, and b) less likely to break in future. This uses more of the `html_context` defined in `conf,py`, and less hard-coded URL elements.
The edit button is now this little pencil icon:
Additionally, this moves the link to the GitHub repo from the sidebar to an icon in the footer, again for consistency with other sites using this theme. Happy to revert that, if we prefer the verbose version in the sidebar.
Before:
After:

Restore edit on GitHub link

---

Doxyfile
doc/conf.py
doc/contribute/onboarding.rst

Fix for #3513.
@jumaffre noticed that this hadn't actually worked - the `html_extra_path` is checked before Doxygen is run, and on the current branch. So it worked locally, since I'd previously run `doxygen`, but not in CI/with `sphinx-multiversion`. Instead, we just copy the Doxygen html output to the Sphinx output directory, and add an appropriate relative link to it.

Explicitly copy doxygen HTML output

---

include/ccf/crypto/sha256_hash.h
include/ccf/crypto/symmetric_key.h
src/crypto/symmetric_key.cpp
src/crypto/test/bench.cpp
src/crypto/test/crypto.cpp
src/indexing/enclave_lfs_access.h
src/kv/encryptor.h
src/node/channels.h
src/node/encryptor.h
src/node/ledger_secret.h
src/node/share_manager.h
src/node/test/channels.cpp

Side effect of #3569 was introducing a new public-header-includes-private chain from `symmetric_key.h`. This was because `GcmHeader` was templated on the `IV_SIZE`, so the implementation details need to be public. I've refactored that so `GcmHeader` is no longer templated (but still fixed-size by construction), and derived a supporting type for the users that still want statically known IV sizes.
Additionally I've simplified this public interface a little, moving the Tx-encryption specifics (interpreting the IV as a seqno + term + snapshot-bit) out of the public definition, and closer to where it's used.

Update GcmHeader types

---

src/js/openenclave.cpp
src/node/quote.h

OE custom claims were cleaned up using `oe_free_claims` instead of `oe_free_custom_claims`, which technically resulted in a memory leak and the error message reported in #3571. 
Fixes #3571

Fix cleanup of custom claims

---

src/js/wrap.cpp

Fix SAN build from combination of recent changes (added `js_trigger_snapshot` function, while changing the interface type from `AbstractNodeState` to `AbstractGovernanceEffects`).

Correct type in js_trigger_snapshot

---

doc/contribute/build_ccf.rst

This is useful when building old versions of CCF locally, without having to use a different dev VM altogether.

Document ways to build old CCF versions in container

---

scripts/ci-checks.sh

Now that #2428 is largely complete (only remaining violations are in sample apps, but the public headers themselves are pure-public), I want to ensure we don't accidentally regress.

Add CI check that enforces public-only headers

---

src/host/main.cpp

Companion to #3612, and follow-up to #3413.
If the `create_node` ECALL blocks, we currently get very little debugging information. This adds a separate thread flushing the outbound ringbuffer while that ECALL executes, so we will get more precise `LOG_` output indicating the point where the code blocked.

Log early messages from a separate thread

---

CHANGELOG.md
python/ccf/ledger.py
python/ccf/ledger_viz.py
python/ccf/read_ledger.py

Looking at #3616, with #3618, I realised our CLI is still a little awkward, since it requires complete directories. Obviously it's possible to copy the target chunk file/files to a separate directory to parse with `--insecure-skip-validation`, but it seems easier if we just handle that conversion ourselves.
So wherever these classes/CLIs expect a ledger directory, they'll now also accept a specific ledger chunk.
Note this does make it easier to specify non-contiguous chunks, but that was already possible with the directory approach.

Take individual chunk files in ledger parsing tools

---

CHANGELOG.md
doc/schemas/gov_openapi.json
src/node/rpc/member_frontend.h
tests/governance.py
tests/infra/member.py

Resolves #3615.
Sample response:
```
$ curl -k https://127.0.0.1:8000/gov/members | jq .
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1272  100  1272    0     0   124k      0 --:--:-- --:--:-- --:--:--  124k
{
"ae5b09279cdbec24d0e94b7a4cf2f2654da1a101be8a299c8da3179bdf370bbc": {
"cert": "-----BEGIN CERTIFICATE-----\nMIIBtjCCATygAwIBAgIUOq1HvRmQIXLu9gBMtF6MKxQXHM0wCgYIKoZIzj0EAwMw\nEjEQMA4GA1UEAwwHbWVtYmVyMDAeFw0yMjAzMDExMTQzMThaFw0yMzAzMDExMTQz\nMThaMBIxEDAOBgNVBAMMB21lbWJlcjAwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAARF\nnMUOQ3/Nq8PNGfSosV4JujMDBvcfBnCXYoNs6S/i6Hre35COiuR48kok/QVX16bJ\naioX2wVwtdxwBQUwVBChUBLXNeRegGphw+8s/s3qSMTWwRb3Kte6JHkmK/++hyWj\nUzBRMB0GA1UdDgQWBBR0/SjlakLHzEcwANCaUkRkT8vvoTAfBgNVHSMEGDAWgBR0\n/Sj …
```

Add `GET /gov/members` endpoint

---

doc/schemas/app_openapi.json
doc/schemas/gov_openapi.json
doc/schemas/node_openapi.json
include/ccf/entity_id.h
samples/apps/logging/logging.cpp
src/node/rpc/member_frontend.h
src/node/rpc/node_frontend.h

While looking at our OpenAPI documents, I noticed that we report IDs for Members, Users, and Nodes as the same type (`EntityID`). This is losing some information, and makes the OpenAPI less descriptive. This plugs in a per-instance name to the OpenAPI.

Distinguish different kinds of EntityID in OpenAPI

---

python/ccf/ledger.py

Fixes #3622.
As discussed in that issue, our viz/parsing tools are incorrect if we have duplicate transactions in multiple chunks. Detecting this duplication and if we have a complete range is hard in the presence of re-chunking and truncation, but we don't think "real" ledger dirs should ever have that much noise. So the simple solution is to demand a contiguous range, which we get from all existing single ledgers.

`ledger.py` reports errors on non-contiguous ranges

---

src/http/test/http_test.cpp
tests/e2e_logging.py
tests/infra/network.py
tests/infra/node.py
tests/infra/remote.py
tests/infra/remote_shim.py

This fixes a bug in #3634, which was producing occasional time-outs in the CI.
One of the new e2e HTTP fuzzing tests produced random data, and assumed this would be unparseable. However, if the random data was, for instance, a single byte containing an ASCII `P`, that would not produce a parsing error. This is a valid prefix for a HTTP request, so the parser would pause, expecting more data. This test now checks (very broadly!) for similar cases, and appends a null-byte to ensure the data is malformed. We'd like a smarter fuzzer here that can determine whether requests are valid or invalid, but for now we're generating reliably-invalid requests.
Some adjacent cleanup:
- Moving the illegal tests to a separate runner, and plumbing through an option to swallow the output they produce in node …

Fix HTTP fuzzing tests to produce consistently invalid requests

---

src/host/node_connections.h
src/host/rpc_connections.h

Non-functional change. Just rename the behaviours to keep my sanity when
trying to remember which is which when working with this code.

[NFC] Rename rpc/node connection behaviours

---

tests/e2e_logging.py

Older versions of curl produce different expected error messages, so no we accept one of multiple.

Multiple expected curl error messages

---

src/enclave/rpc_context.h
src/http/http_endpoint.h
src/http/http_parser.h
src/http/test/http_test.cpp
tests/e2e_logging.py
tests/infra/network.py
tests/infra/node.py
tests/infra/remote.py

This is a cherry-pick of #3634 with some additional tweaks to work on the 1.x branch.
Before #3636, this e2e test triggered a crash - now it is a regression test confirming that the crash no longer occurs.
The main semantic change in this backport is that it does not test that WebSocket upgrades are ignored. On 1.x, some endpoints _may_ be WebSocket enabled, so this test would return a 405. WebSocket upgrades are still tested by other test cases on this branch, and remain disabled in main and 2.x.
Edit - this also includes the fixes to those tests from #3640.

[LTS 1.x] Port HTTP parsing/protocol tests (#3634) to 1.x
