- src/kv/kv.h
> KV cleanup

- src/ds/champmap.h
Clarify the numeric types and values that define the CHAMP map's structure. This has the additional benefit of allowing easy modification to the elements stored at each node while ensuring that collisions are managed properly. The hash size may also be easily increased to 64 bits if we expect very large maps.
> Refactor CHAMP map bits

- cmake/common.cmake
- cmake/crypto.cmake
- src/kv/kv.h
This is much easier:
```
cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
run-clang-tidy-7
```
Unfortunately there's a bit of work left before that can be part of the CI.
> Clang tidy

- src/kv/kv.h
- src/node/test/history.cpp
If a rollback or a compact happens during a commit(), a leader may cease to replicate.
> Fix replication sequence bug

- .vsts-ci-templates/build_and_test.yml
- src/node/entities.h
- tests/infra/ccf.py
- tests/infra/jsonrpc.py
The python client now auto-detects which curve to use depending on the type of the Elliptic Curve used for the server CA.
> Support new curve from python

- src/host/ledger.h
> Better error handling in ledger

- tests/infra/rates.py
histogram to report all non-zero results and making test not exit so easily.
> Rates test tweak

- tests/coverage/style_html.py
Changing background colour for dark theme users
> Changing background color

- CMakeLists.txt
- src/node/nodestate.h
- src/node/rpc/consts.h
- src/node/rpc/managementfrontend.h
- tests/e2e_logging.py
- tests/e2e_scenarios.py
- tests/election.py
- tests/governance.py
- tests/infra/ccf.py
- tests/infra/jsonrpc.py
- tests/recovery.py
> Get quotes rpc

- CMakeLists.txt
- cmake/common.cmake
- cmake/preproject.cmake
- sphinx/source/getting_started.rst
- src/node/nodestate.h
- src/node/rpc/frontend.h
- src/node/rpc/test/frontend_test.cpp
Clean up cmake flags and update documentation, to address concerns raised in #143
> Clean up cmake flags

- src/pbft/pbft_deps.h
Fix build to match a pbft change.
> Fixed ITimer build

- sphinx/source/schemas/getNetworkInfo_result.json
- src/node/rpc/calltypes.h
- src/node/rpc/consts.h
- src/node/rpc/frontend.h
- src/node/rpc/serialization.h
As discussed in #197, this is useful for clients
> Add getNetworkInfo RPC

- notice-check.py
Fixing https://lgtm.com/projects/g/microsoft/CCF/alerts/?mode=list
> Fix LGTM warning

- samples/apps/smallbank/smallbank.cmake
- samples/perf_client/perf_client.h
- samples/perf_client/timing.h
This is no longer needed now that we have full time series.
> Remove warmup cooldown

- src/clients/memberclient.cpp
- tests/infra/ccf.py
- tests/memberclient.py
- tests/recovery.py
> Argument names are clearer

- src/consensus/ledgerenclave.h
- src/consensus/ledgerenclavetypes.h
- src/consensus/pbft/pbft.h
- src/consensus/raft/raft.h
- src/consensus/raft/rafttypes.h
- src/consensus/raft/test/enclave.cpp
- src/enclave/enclave.h
- src/host/enclave.h
- src/host/ledger.h
- src/host/nodeconnections.h
- src/node/consensustypes.h
- src/node/nodestate.h
- src/node/nodetypes.h
- src/node/rpc/frontend.h
Continuing issue #300 
- some renaming/reshuffling
- merged consensus_msg_raft and consensus_msg_pbft into consensus_msg
- frontend to use consensus instead of raft
> More consensus unification

- getting_started/setup_vm/D-oe.yml
> Remove reference to repo fork

- cmake/common.cmake
- cmake/crypto.cmake
Ahead of tomorrow's session with @letmaik
> Remove GCC-specific code, since we do not support GCC at the moment

- .devcontainer/devcontainer.json
- .gitattributes
- .gitmodules
- 3rdparty/evercrypt
- cmake/common.cmake
- cmake/crypto.cmake
- sphinx/source/getting_started.rst
Fix for #351, as kindly suggested by @letmaik
> Docker on windows

- sphinx/source/ledger.rst
- src/apps/logging/logging.cpp
- src/apps/luageneric/luageneric_test.cpp
- src/clients/memberclient.cpp
- src/kv/kv.h
- src/kv/test/kv_test.cpp
- src/luainterp/txscriptrunner.h
- src/node/entities.h
- src/node/genesisgen.h
- src/node/networktables.h
- src/node/nodestate.h
- src/node/proposals.h
- src/node/quoteverification.h
- src/node/rpc/memberfrontend.h
- src/node/rpc/test/membervoting_test.cpp
- src/runtime_config/default_whitelists.h
- src/runtime_config/gov.lua
- tests/infra/ccf.py
- tests/memberclient.py
- tests/votinghistory.py
> Prefix tables

- docker/Dockerfile.nosgx
image has been pushed to docker hub
> adding ci dependencies to non sgx docker image

- src/consensus/pbft/pbft.h
> Revert "Add should_mac_message config parameter"

- src/node/rpc/nodefrontend.h
- tests/addnode.py
- tests/code_update.py
- tests/infra/ccf.py
Resolves https://github.com/microsoft/CCF/issues/375. 
Add a check in `nodefrontend.h` to check that a new node does not conflict with the network config of an existing node. Also, some small refactoring in `ccf.py`.
> Fix issue and add e2e test

- src/consensus/pbft/pbft.h
This reverts commit 1bd657b72dc5bb65500bf59e3ebb98033fb6bd27.
> Revert "Revert "add should_mac_message config parameter (#369)" (#372)"

- src/consensus/pbft/pbft.h
- src/consensus/pbft/pbftconfig.h
- src/enclave/enclavetypes.h
- src/kv/kvtypes.h
- src/node/history.h
- src/node/nodestate.h
- src/node/rpc/frontend.h
- tests/e2e_logging_pbft.py
in the ePBFT configuration when a node join late we need to pass a certificate and also initialize ePBFT on the late joining node.
> PBFT - late joining node 1/????

- .azure-pipelines-templates/checks.yml
- src/node/rpc/frontend.h
Re adding this as it looks like it was removed by mistake at some point
> Re enable formatting check in CI

- .azure-pipelines-templates/matrix.yml
- CMakeLists.txt
- cmake/common.cmake
Only runs for SGX (enforced by Azure Pipelines yaml) with Raft (enforced by cmake).
> Test Suite on the CI

- tests/infra/ccf.py
Remove duplicated `wait_for_all_nodes_to_be_trusted()` and consortium-only `accept_recovery()`. Also re-order functions in `Network` class.
> Cleanup ccf.py

- samples/apps/smallbank/app/oe_sign.conf
> Increase the number of heap pages in small bank

- samples/apps/smallbank/app/oe_sign.conf
- src/node/rpc/frontend.h
- tests/infra/runner.py
resolves #595 
- Make the getMetrics request run on the node that receives it (ePBFT mode)
- for small bank fix issue that does not raise all errors
> Pbft small bank

- samples/apps/smallbank/clients/small_bank_client.cpp
- samples/apps/smallbank/smallbank.cmake
- src/consensus/pbft/libbyz/Big_req_table.cpp
- src/consensus/pbft/libbyz/Client_proxy.h
- src/consensus/pbft/libbyz/Log.h
- src/consensus/pbft/libbyz/Pre_prepare.h
- src/consensus/pbft/libbyz/parameters.h
This enables us to properly run more than 256 pre_prepare batches.
> Fix how we create and delete certificates in the log

- src/host/dns.h
Regarding #615 adding more info in log
> more info in log

- .github/CONTRIBUTING.md
- README.md
The yaml files referred to from our `README.md` were outdated.
> Update README.md and contribution guidelines

- src/node/test/merkle_bench.cpp
```
./merkle_bench | grep mt_serialize | cut -d '=' -f 2 | sort -g
1 : 1310 bytes, 1310 bytes/hash, 3993.75% overhead
2 : 1342 bytes, 671 bytes/hash, 1996.88% overhead
10 : 1822 bytes, 182.2 bytes/hash, 469.375% overhead
100 : 7550 bytes, 75.5 bytes/hash, 135.938% overhead
1000 : 65054 bytes, 65.054 bytes/hash, 103.294% overhead
10000 : 641086 bytes, 64.1086 bytes/hash, 100.339% overhead
```
Where overhead is the extra amount of bytes on top of the space needed for the leaves. For larger trees (which is what we care about), the Everest implementation is therefore close to optimal.
> Add size checks for merkle tree

- tests/infra/clients.py
To stop CI test failures that are related to join sometimes needing a bit more time to complete
> connection timeout with http

- src/consensus/pbft/pbft.h
- src/node/nodestate.h
> Use the sig_max_tx parameter for ePBFT signing

- samples/apps/smallbank/tests/verify_small_bank_500k.json
Resolves #640 
Add a file to run small bank with 500,000 tx so that there is enough time for vtune to collect useful numbers
> Add small bank 500k tx json file

- src/node/nodestate.h
> Log network open

- src/enclave/enclave.h
> Assert buffer sizes before out copies

- sphinx/source/operators/index.rst
- sphinx/source/operators/resource_usage.rst
> Document resource usage in CCF

- tests/infra/remote.py
- tests/infra/runner.py
Hopefully this will help us diagnose the CI failures.
> Add hard timeout for perf tests

- .azure-pipelines.yml
- docker/Dockerfile
- getting_started/setup_vm/roles/openenclave/vars/common.yml
> Upgrade to 0.8.0 final

- src/enclave/httpendpoint.h
- src/node/history.h
> Reduce logging

- sphinx/source/members/index.rst
- sphinx/source/operators/start_network.rst
- tests/keygenerator.sh
This somehow didn't make it to #827
> Fix docs for member-info

- src/node/rpc/test/frontend_test.cpp
> Test make_error from simple handlers

- samples/apps/txregulator/tests/txregulatorclient.py
- tests/connections.py
- tests/e2e_logging.py
- tests/e2e_scenarios.py
- tests/election.py
- tests/infra/ccf.py
- tests/infra/clients.py
- tests/infra/consortium.py
- tests/infra/logging_app.py
- tests/infra/node.py
- tests/infra/rates.py
- tests/late_joiners.py
- tests/receipts.py
- tests/rekey.py
- tests/schema.py
Replace #858, and resolve #845.
> Remove stream logic

- sphinx/source/developers/index.rst
- sphinx/source/developers/threading.rst
Resolves #877
Please read, review and make additional suggestions on what to add.
> Threading documentation

- sphinx/source/concepts.rst
- sphinx/source/members/common_member_operations.rst
- sphinx/source/members/constitution.rst
- sphinx/source/members/proposals.rst
- sphinx/source/quickstart/build.rst
- sphinx/source/quickstart/index.rst
- sphinx/source/quickstart/oeengine.rst
- sphinx/source/quickstart/requirements.rst
Also we say in some places that a node `can't join the network` until the members accept it, but we start by making a node join the network and then having members vote for it, so replaced those mentions with `node can't participate in the network`
> Fix some typos, etc in the docs

- .azure-pipelines-templates/common.yml
- .azure-pipelines-templates/matrix.yml
- .azure-pipelines-templates/ninja.yml
- .azure-pipelines.yml
- tests/infra/remote.py
It is only tested on `Release` builds at the moment.
> Test install on every build

- .azure-pipelines-templates/metrics.yml
Otherwise the script, the requirements etc are missing: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=6032&view=logs&j=6098999b-e9f4-505d-2641-8ca371929814&t=a5a1bbc5-5951-5de7-633d-0f70e49bb83b
> Need a checkout every time

- tests/infra/runner.py
- tests/late_joiners.py
- tests/perfclient.py
> Add way of specifying number of localhost clients

- .daily.yml
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#opting-out-of-ci
> Don't trigger Daily build on every master commit

- metrics.yml
Pick up fixes from https://github.com/jumaffre/cimetrics/releases/tag/v0.2.10
> Configure PR user and EWMA span for CI Metrics

- sphinx/source/operators/start_network.rst
- sphinx/source/quickstart/build.rst
- sphinx/source/quickstart/index.rst
- sphinx/source/quickstart/requirements.rst
- sphinx/source/quickstart/upgrading_app.rst
Resolves https://github.com/microsoft/CCF/issues/1026 
All feedback welcome 👍
> Install instructions in the docs

- src/host/tcp.h
> Handle writes during RECONNECTING

- .cmake-format.py
- CMakeLists.txt
Suite wasn't labeled correctly, leading to #1045
> Fix e2e label

- src/consensus/pbft/libbyz/replica.cpp
In PBFT pull writing to the ledger off the critical path.
> Write to ledger after sending

- .azure-pipelines-templates/matrix.yml
Include virtual build in CCF releases.
> Include virtual build in releases

- .azure-pipelines-templates/checks.yml
- .pylintrc
- sphinx/source/conf.py
- tests/code_update.py
- tests/connections.py
- tests/coverage/style_html.py
- tests/e2e_logging.py
- tests/e2e_scenarios.py
- tests/e2e_suite.py
- tests/infra/ccf.py
- tests/infra/clients.py
- tests/infra/crypto.py
- tests/infra/ledger.py
- tests/infra/member.py
- tests/infra/net.py
- tests/infra/node.py
- tests/infra/notification.py
- tests/infra/path.py
- tests/infra/proc.py
- tests/infra/proposal.py
- tests/infra/rates.py
- tests/infra/remote.py
- tests/infra/remote_client.py
- tests/infra/runner.py
- tests/late_joiners.py
- tests/memberclient.py
- tests/raft_scenarios_runner.py
- tests/tlstest.py
- Adds a `.pylintrc` configuration file with a few disabled checks
- Fixes all other linter issues
- Adds a step to `checks.yml` to run this linter in the CI
> Run Pylint in CI

- cmake/pbft.cmake
- src/consensus/pbft/libbyz/test/replica_unit_tests.cpp
and refactored the pbft unit test so that it is easier re usable and removes duplicate code
> Adding unit test for no-op pre prepare

- src/apps/js_generic/js_generic.cpp
- src/apps/logging/logging_js.lua
- tests/e2e_logging.py
A better mapping on the JS side would probably be ArrayBuffer (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer), but it wasn't obvious how to get that to work inexpensively in QuickJS.
> Make js_generic a little more generic in the spirit of things to come

- CMakeLists.txt
- samples/apps/txregulator/tests/txregulatorclient.py
> enable more tests with pbft

- src/kv/kv.h
> Remove legacy code

- getting_started/setup_vm/ccf-dependencies.yml
- getting_started/setup_vm/roles/intel/tasks/sgx-driver.yml
- getting_started/setup_vm/roles/intel/vars/common.yml
> Manually install 1.33 driver

- src/consensus/pbft/libbyz/prepare.h
> Objects must be 8 byte aligned

- doc/operators/start_network.rst
> Update signature documentation

- doc/conf.py
> Fix doxygen and breathe to use the right code for each version

- CMakeLists.txt
- cmake/common.cmake
- cmake/pbft.cmake
Also replaces OE's deprecated `oehostapp` with `oehost`.
> Use libc++ on cchost as well

- doc/quickstart/requirements.rst
Thanks @syhamza for spotting this!
> Fix command mistake

- tests/infra/ccf.py
- tests/infra/e2e_args.py
- tests/infra/remote.py
> Forward domain in cchost

- README.md
As discussed: https://github.com/microsoft/CCF/issues/1235
> Move code coverage to a pinned issue

- .azure-pipelines-templates/common.yml
- .azure-pipelines-templates/daily-matrix.yml
- .azure-pipelines-templates/matrix.yml
- .azure-pipelines-templates/test.yml
> Increase timeout for SAN tests

- src/consensus/pbft/libbyz/parameters.h
> Remove unused parameters

- tests/infra/suspension.py
Fix for failures such as https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=9181&view=ms.vss-test-web.build-test-results-tab
This contains two changes:
1. A timeout extension, because we're currently cutting it really close on the replay_new_view test, hence the failure
2. A fix to use the actual value returned by commit, as opposed to the incidental version header, which is meaningless since it is a "No KV" transaction
> Fix PBFT suspension timeout

- samples/apps/smallbank/clients/small_bank_client.cpp
- samples/perf_client/perf_client.h
- samples/perf_client/scenario_perf_client.cpp
- samples/perf_client/timing.h
> Do not use seqnos from non-transaction RPCs in performance tests

- getting_started/setup_vm/roles/ccf_build/vars/common.yml
> add jq to build container

- src/ds/champ_map.h
- src/ds/test/map_test.cpp
- src/kv/kv_types.h
- src/kv/map.h
- src/kv/store.h
- src/kv/test/kv_test.cpp
- src/kv/untyped_map.h
> Deserialize the KV

- .azure-pipelines-gh-pages.yml
- doc/conf.py
We forgot about doc when we did #1335
> Update documentation config to use new prefix

- src/node/rpc/node_frontend.h
- tests/infra/clients.py
- tests/ws_scaffold.py
> Wait for secondary to know the network is open

- .azure-pipelines-gh-pages.yml
- .azure-pipelines.yml
- getting_started/setup_vm/roles/ccf_build/vars/common.yml
> Add sudo to build container

- src/kv/tx.h
> Set committed at a more intuitive location

- src/node/rpc/frontend.h
Spotted and reported by Soren.
@eddyashton since you are making changes to the signature code, could you add a test for this?
> Add missing quote in response

- getting_started/setup_vm/roles/intel/vars/common.yml
Pick up most recent Intel driver, released at the same time as the 2.10 PSW.
> Upgrade driver in playbook

- doc/developers/kv/kv_how_to.rst
- doc/developers/kv/kv_serialisation.rst
- doc/members/accept_recovery.rst
- doc/members/constitution.rst
- doc/members/proposals.rst
- doc/operators/container.rst
- python/ccf/proposal_generator.py
Part of #1352. Now that we have this script, tell users about it for 0.12.
> Document proposal_generator.py

- doc/operators/ledger_python.rst
- python/ccf/clients.py
- python/ccf/commit.py
- python/ccf/ledger.py
- python/ccf/proposal_generator.py
- python/setup.py
- python/tutorial.py
- scripts/ci-checks.sh
Resolves #1433 
We also check for type correctness in `python/` with `mypy` from `ci-checks.sh`.
> Python type annotations

- python/ccf/proposal_generator.py
- src/apps/js_generic/js_generic.cpp
- src/node/rpc/member_frontend.h
- tests/modules.py
Fixes https://github.com/microsoft/CCF/issues/1478.
> Support relative paths in js modules

- scripts/check-cmake-format.sh
There's an issue with the new release 0.6.12: https://github.com/cheshirekow/cmake_format/issues/219
> Pin cmake-format to 0.6.11

- src/node/rpc/endpoint_registry.h
- src/node/rpc/user_frontend.h
> Remove old install() shims and handlers

- src/node/rpc/node_frontend.h
> Never forward /node/state

- samples/apps/smallbank/smallbank.cmake
Comment in #1564, this is taking CI time and the output isn't useful at the moment.
> Remove sig fwd test

- CMakeLists.txt
- cmake/common.cmake
- src/node/rpc/member_frontend.h
> Remove OE 0.10 workarounds

- .azure-pipelines-gh-pages.yml
- .azure-pipelines.yml
- .daily.yml
I'd entirely forgotten about this, thank you @wintersteiger for reminding me!
> Update CI container

- .nodes.sh
We've now got new nodes and the Azure perf machines have been renamed.
> Update perf nodes setup

- .daily.yml
- python/tutorial.py
> Fix tutorial

- doc/developers/index.rst
- doc/developers/upgrading_app.rst
- doc/members/accept_recovery.rst
- doc/operators/deploy_app.rst
- doc/operators/index.rst
- doc/operators/ledger.rst
- doc/operators/recovery.rst
- doc/quickstart/build.rst
- doc/quickstart/index.rst
- doc/users/index.rst
Resolves #1640 
+ some minor fixes (pages that were no longer displayed, etc.)
> Minor documentation fixes

- CHANGELOG.md
- tests/e2e_logging.py
Fixes an occasional error in `full_test_suite`.
Includes some changes to `CHANGELOG.md`
> test_illegal talks to primary, not hardcoded node

- tests/infra/consortium.py
- tests/infra/e2e_args.py
- tests/infra/network.py
- tests/modules.py
Example:
```sh
cd build
../start_test_network.sh --package libjs_generic --js-app-bundle ../tests/js-app-bundle
```
> Add --js-app-bundle to test infra

- cmake/common.cmake
> Install getting_started scripts with source permissions

- src/apps/js_generic/js_generic.cpp
daily ci (with san): https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=13805&view=results
> JS: fix memory leak in jsonCompatibleToBuf

- .azure-pipelines-templates/daily-matrix.yml
- src/consensus/aft/impl/state.h
- src/consensus/aft/raft.h
- src/node/progress_tracker.h
- src/node/test/progress_tracker.cpp
> AFT: In BFT mode use Byzantine commit

- samples/apps/smallbank/smallbank.cmake
Run smallbank with BFT consensus
> Smallbank bft

- CMakeLists.txt
- tests/e2e_logging.py
#1748 seems to have broken the snapshot test suite. Disabling it for now until a fix is found so that other PRs can be merged.
> Disable snapshot suite

- python/ccf/proposal_generator.py
It accidently picked up folders ending in `.js`.
> Fix deploy_js_app proposal generation

- samples/apps/forum/src/controllers/site.ts
Note that this is still without token validation.
> Add Microsoft login to Forum sample

- CHANGELOG.md
- samples/apps/forum/src/controllers/poll.ts
- samples/apps/forum/src/types/ccf.ts
- src/apps/js_generic/js_generic.cpp
- src/apps/logging/logging_js.lua
- tests/modules.py
- tests/npm-app/src/types/ccf.ts
- tests/npm-tsoa-app/src/types/ccf.ts
Fixes https://github.com/microsoft/CCF/issues/1780.
Changes:
- `get(key)` returns `undefined` instead of throwing an exception if `key` does not exist
- `delete(key)` returns a `false` instead of throwing an exception if `key` does not exist, and `true` instead of `undefined` otherwise 
- `set(key, val)` returns the map object instead of `undefined`
> Align js kvmap API to standard Map

- samples/apps/forum/package.json
- samples/apps/forum/tsconfig.json
Addresses https://github.com/microsoft/CCF/issues/1796#issuecomment-715897771.
> JS: Use different ES target version for node.js in forum sample tests

- samples/apps/forum/src/authentication.ts
- samples/apps/forum/src/controllers/poll.ts
- samples/apps/forum/src/error_handler.ts
- samples/apps/forum/tsoa-support/routes.ts.tmpl
Just general sanity improvements.
> Handle auth errors in error handler in forum app

- CHANGELOG.md
- cmake/cpack_settings.cmake
- getting_started/setup_vm/roles/openenclave/vars/common.yml
As usual, this doesn't affect the perf environment until the DevEnv repo is upgraded etc.
> Upgrade to OE 0.12 final

- src/node/rpc/call_types.h
- src/node/rpc/serialization.h
Noticed while auditing our API types for #278
> Remove unused types

- CHANGELOG.md
- doc/schemas/app_openapi.json
- doc/schemas/gov_openapi.json
- src/node/rpc/call_types.h
- src/node/rpc/common_endpoint_registry.h
- tests/governance.py
- tests/infra/consortium.py
> /user_id takes a pem string

- CHANGELOG.md
- src/node/rpc/member_frontend.h
- src/runtime_config/gov.lua
- src/runtime_config/gov_ca_cert_mismatch.lua
- src/runtime_config/gov_ca_certs.lua
- src/runtime_config/gov_veto.lua
- src/runtime_config/operator_gov.lua
> Pass proposer id

- src/node/rpc/test/member_voting_test.cpp
- src/runtime_config/operator_gov.lua
> Operator changes pass on submit when proposed by operator

- python/ccf/proposal_generator.py
Currently blocking the release pipeline for 0.15.0
> Fix incorrect typing

- samples/apps/smallbank/tests/small_bank_serdes_bench.cpp
- src/consensus/aft/impl/execution.cpp
- src/consensus/consensus_types.h
- src/enclave/rpc_context.h
- src/host/main.cpp
- src/http/http_rpc_context.h
- src/http/ws_rpc_context.h
- src/kv/test/kv_bench.cpp
- src/node/encryptor.h
- src/node/node_state.h
- src/node/test/encryptor.cpp
- tests/e2e_logging.py
- tests/infra/e2e_args.py
- tests/infra/network.py
- tests/infra/remote.py
- tests/infra/runner.py
- some renaming
- for bft set min required nodes to be 3 not 4
> Minor cleanup

- doc/schemas/node_openapi.json
- src/node/rpc/node_frontend.h
> Correctly report GetQuote schema

- samples/apps/forum/test/util.ts
> Resolve missing Promise resolve type

- cgmanifest.json
> Update cgmanifest for evercrypt 0.3.0

- src/node/progress_tracker.h
- src/node/progress_tracker_types.h
resolves #1976
Refer to the linked issue for description of the issue
> Fix aft evidence mismatch issue

- CHANGELOG.md
Also including @letmaik's changes from #1998
> 0.16.0 changelog

- CHANGELOG.md
- doc/audit/builtin_maps.rst
- doc/audit/builtin_tables.rst
- doc/audit/index.rst
- doc/schemas/app_openapi.json
- doc/schemas/gov_openapi.json
- doc/schemas/node_openapi.json
- python/utils/verify_quote.sh
- src/node/code_id.h
- src/node/genesis_gen.h
- src/node/quote.h
- src/node/rpc/member_frontend.h
- tests/code_update.py
> Only store valid Code IDs

- src/node/rpc/common_endpoint_registry.h
- src/node/rpc/error.h
- src/node/rpc/frontend.h
- src/node/rpc/json_handler.h
- tests/zap.config
Fixes https://github.com/microsoft/CCF/issues/1979.
> Return 400 instead of 500 for user errors

- tests/infra/crypto.py
Fixes https://github.com/microsoft/CCF/issues/2041
PyJWT 2.0.0 [was released over the holiday](https://github.com/jpadilla/pyjwt/releases/tag/2.0.0).
> Fix Python JWT decoding issue

- src/node/node_state.h
- src/node/rpc/member_frontend.h
- src/node/rpc/node_frontend.h
> Re-enable quotes in BFT mode

- python/tutorial.py
> Fix tutorial 

- src/libmerklecpp/merklecpp.h
- src/libmerklecpp/test/CMakeLists.txt
- src/libmerklecpp/test/unit_tests.cpp
- src/node/test/merkle_test.cpp
Some minor fixes for the Merkle trees and removal of parent pointers for performance.
> Merkle tree fixes

- .daily_canary
- python/ccf/clients.py
- src/node/rpc/node_frontend.h
- tests/e2e_logging.py
Hopefully fixing `Test installed CCF` in the Daily CI.
> Allow redirects by default, but make this overridable

- src/ds/spin_lock.h
> Remove our implementation of pthread_spin_trylock

- src/apps/js_generic/js_generic.cpp
- src/consensus/aft/impl/execution.cpp
- src/enclave/rpc_handler.h
- src/kv/kv_types.h
- src/kv/store.h
- src/kv/tx.h
- src/node/history.h
- src/node/rpc/frontend.h
- src/node/rpc/test/member_voting_test.cpp
Remove left-over code from the PBFT days, noticed while making changes to the History. And a few other bits of bobs too, while I'm at it.
> Remove dead code

- CHANGELOG.md
To be merged once https://github.com/microsoft/CCF/releases/tag/ccf-0.17.2 is released
> Changelog update for 0.17.2

- CHANGELOG.md
- doc/schemas/app_openapi.json
- doc/schemas/gov_openapi.json
- doc/schemas/node_openapi.json
- src/node/rpc/call_types.h
- src/node/rpc/common_endpoint_registry.h
- src/node/rpc/endpoint_registry.h
- src/node/rpc/serialization.h
- tests/e2e_logging.py
- tests/jwt_test.py
Closes https://github.com/microsoft/CCF/issues/2068.
> Make endpoint_metrics response flat

- cmake/common.cmake
- src/consensus/aft/async_execution.h
- src/consensus/aft/raft.h
- src/node/channels.h
part of #2055
Run execution/applying table data on backups on the non main thread (if it exists).
> On backup run work async

- CHANGELOG.md
- doc/schemas/node_openapi.json
- python/utils/verify_quote.sh
- src/node/rpc/node_frontend.h
- tests/governance.py
> rename /quote to /quotes/self

- src/enclave/snmalloc.cpp
This is expected to cut down on CTest time in the NoSGX config.
> Attempt to speed up NoSGX Debug CI

- cmake/common.cmake
The comment suggests to remove the wrong line when you upgrade.
> Fix comment for upgrading snmalloc

- src/node/history.h
We should not hold onto memory just for fun
> Fix BFT memory issue

- cmake/common.cmake
- src/enclave/app_interface.h
- src/node/historical_queries.h
- src/node/historical_queries_adapter.h
This may or may not be what we want long term, but in the interest of getting 0.18.5 out, that's how it's going to be for now.
> Align src and install paths for new includes

- .threading_canary
- src/kv/kv_types.h
- src/node/history.h
Add locks whenever we touch the tree in history
> Fix history locking issues

- tests/e2e_suite.py
A simple filter to select which tests of the suite to run.
> Add regexp filter for E2E test suite

- CHANGELOG.md
- doc/build_apps/js_app_bundle.rst
- doc/conf.py
- samples/apps/forum/src/authentication.ts
- samples/apps/forum/src/models/poll.ts
- src/js/builtin.ts
- src/js/util.ts
- tests/npm-app/src/endpoints/crypto.ts
- tests/npm-app/src/endpoints/jwt.ts
- tests/npm-app/src/endpoints/log.ts
Point 1 of https://github.com/microsoft/CCF/issues/2315 and missing jsdocs for HistoricalState.
> PascalCase JS names & JS doc for HistoricalState

- tests/reconfiguration.py
[This](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=21082&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded&l=15965) new failure in the CI is from the new test added in #2338. The nodes lists it is comparing directly are unordered, produced by undefined iteration order of `foreach`ing through a KV table, so adding a pending node can re-order the `Trusted` nodes. This sorts those lists before comparing them.
> Fix new reconfiguration test: Sort nodes before comparison

- src/crypto/test/crypto.cpp
Adds a test case that compares the implementations of RSA OAEP. It turned out there was no bug to fix, but we can keep the test case anyways.
> Add RSA OAEP implementation comparison test

- CHANGELOG.md
- js/ccf-app/src/endpoints.ts
- samples/apps/forum/src/authentication.ts
- src/apps/js_generic/js_generic.cpp
- tests/js-authentication/src/endpoints.js
Fixes https://github.com/microsoft/CCF/issues/2362
> JS: Rename key_issuer -> keyIssuer

- .azure-pipelines-gh-pages.yml
- .azure-pipelines.yml
- .daily.yml
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- cmake/ccf_app.cmake
- cmake/cpack_settings.cmake
- getting_started/setup_vm/roles/openenclave/vars/common.yml
No modifications to our source.
TODO:
> Update to OpenEnclave 0.15.0~rc1

- src/host/tcp.h
Potential/partial fix for #2378. I believe this is the right thing to do, but I wasn't able to verify that this actually fixes anything yet.
> Avoid double-close on a uv handle

- .azure-pipelines-gh-pages.yml
- .azure-pipelines.yml
- .daily.yml
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- cmake/cpack_settings.cmake
- getting_started/setup_vm/roles/openenclave/vars/common.yml
> Upgrade to OE 0.15.0 final

- src/js/wrap.cpp
> fix js_dump_error swallowing exceptions

- js/ccf-app/src/crypto.ts
- js/ccf-app/src/global.ts
- js/ccf-app/src/polyfill.ts
- js/ccf-app/test/polyfill.test.ts
- tests/js-modules/modules.py
- tests/npm-app/app.json
- tests/npm-app/src/endpoints/crypto.ts
> js: add ccf.digest to ccf-app

- src/crypto/openssl/key_pair.cpp
Failed to add this change in a previous PR. Gets rid of `strtok`/`strdup` in favor of `nonstd::split`.
> Cleaner parsing of certificate names

- python/ccf/read_ledger.py
Also added an argparse parser as I expect more to be added soon!
> Add regex table filter to read_ledger.py

- python/ledger_tutorial.py
Fix for issue hit in the Daily
> Read all chunks after shutdown

- python/ccf/ledger.py
> Fix incorrect assumption about non-committed ledger files

- tests/infra/consortium.py
- tests/infra/network.py
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=24392&view=results
> Fix recovery executed from tutorial

- tests/reconfiguration.py
> Test retiring pending nodes

- tests/e2e_suite.py
- tests/reconfiguration.py
- tests/suite/test_requirements.py
> Test suite fixes

- doc/build_apps/install_bin.rst
This fixes the code block that broke with the earlier #2575 Thanks @jumaffre for noticing
> Fix broken code block in install doc

- doc/schemas/node_openapi.json
- src/node/rpc/node_call_types.h
- src/node/rpc/node_frontend.h
- src/node/rpc/serialization.h
- tests/reconfiguration.py
Leftover from https://github.com/microsoft/CCF/pull/2582#discussion_r630312522 which wasn't included in that PR.
> Rename value returned by `/node/version` endpoint

- tests/e2e_logging.py
Trade off some clarity for execution time.
> Fewer requests in escape test

- .daily_canary
- CHANGELOG.md
- src/consensus/aft/raft.h
- src/consensus/aft/test/logging_stub.h
- src/node/node_state.h
- src/node/snapshotter.h
- src/node/test/snapshotter.cpp
- tests/infra/logging_app.py
Fix for ledger chunking and snapshot out-of-sync (#2607).
> 1.0.2 bugfix

- .azure-pipelines-templates/test.yml
- tests/partitions_test.py
Tracked by https://github.com/microsoft/CCF/issues/2616
> Temporarily deactivate unstable partitioning test in CI

- src/consensus/aft/async_execution.h
- src/consensus/aft/impl/view_change_tracker.h
- src/consensus/aft/raft.h
- src/consensus/aft/raft_types.h
- src/node/progress_tracker.h
- src/node/test/progress_tracker.cpp
resolves #2590
Look at the issue for details
> AFT: add skip view

- tests/sandbox/sandbox.sh
Fix #2638
Tested against 2.0.0-dev0
> Use full package name when installing via pip

- CMakeLists.txt
- python/requirements.txt
- tests/rotation.py
Effectively replaced by the more accurate #2586.
> Remove redundant suspension-based rotation test

- .daily_canary
- tests/lts_compatibility.py
Follow-up from #2644, in which I modified (and broke!) a test that only runs in the daily CI.
> Fix daily after Python snapshot support

- doc/conf.py
> Pin TypeScript to a version TypeDoc supports

- doc/audit/python_library.rst
- doc/build_apps/kv/kv_how_to.rst
- python/ccf/ledger.py
- python/ccf/read_ledger.py
- python/ledger_tutorial.py
- tests/infra/github.py
- tests/ledger_operation.py
- tests/lts_compatibility.py
> Release 1.0.4, take 2

- CHANGELOG.md
- doc/audit/builtin_maps.rst
- doc/schemas/gov_openapi.json
- src/crypto/pem.h
- src/node/rpc/member_frontend.h
- tests/infra/jwt_issuer.py
- tests/jwt_test.py
Part of #2519, preferable to #2674 in my opinion.
> Add JWT keys endpoint and use it in tests

- tests/connections.py
See https://github.com/microsoft/CCF/issues/2645#issuecomment-868379810.
Fixes an occasional failure in the Threading CI.
> Avoiding a crash in `connections_test` is acceptable

- doc/conf.py
- doc/governance/constitution.rst
- doc/requirements.txt
Plus some opportunistic cleanup in dependencies and conf.py
> Missing constitution file

- CHANGELOG.md
- include/ccf/base_endpoint_registry.h
- samples/apps/nobuiltins/nobuiltins.cpp
- src/endpoints/base_endpoint_registry.cpp
- tests/nobuiltins.py
Moving `get_quotes_for_all_trusted_nodes_v1` to the LTS branch. While it is not technically a bug or security fix, it's a reasonably small, self-contained additive improvement.
> Pick #2511

- CHANGELOG.md
- src/node/code_id.h
- src/node/node_state.h
- src/node/nodes.h
- src/node/quote.h
- src/node/rpc/member_frontend.h
- src/node/rpc/node_frontend.h
- src/node/rpc/node_interface.h
- src/node/rpc/test/node_stub.h
> Pick #2472

- .azure-pipelines-gh-pages.yml
- .azure-pipelines.yml
- .daily.yml
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- getting_started/setup_vm/roles/openenclave/vars/common.yml
- src/http/http_status.h
- tests/jwt_test.py
Move from -rc2 to final now that it is available.
> Upgrade to Open Enclave 0.17.0 final

- CHANGELOG.md
Release dev branch on the latest Open Enclave.
> Update changelog for -dev2

- python/ccf/ledger.py
> Fix return type for ledger `get_public_domain`

- doc/schemas/node_openapi.json
- python/ccf/ledger.py
- python/ccf/proposal_generator.py
- src/consensus/aft/raft.h
- src/enclave/reconfiguration_type.h
- src/kv/kv_types.h
- src/node/config.h
- src/node/hooks.h
- src/node/node_state.h
- src/node/nodes.h
- src/node/rpc/member_frontend.h
- src/runtime_config/default/actions.js
- tests/infra/consortium.py
- tests/reconfiguration.py
This adds the new `RETIRING` consensus state, the associated logic, and a test.
> Add retiring state for 2-tx reconfiguration

- .daily_canary
- src/node/config.h
- src/node/rpc/member_frontend.h
- src/runtime_config/default/actions.js
Fixes the breakage in yesterday's daily build.
> Fix LTS compatibility issue in service config

- .azure-pipelines-gh-pages.yml
- .azure-pipelines.yml
- .daily.yml
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- CHANGELOG.md
- cmake/ccf_app.cmake
- cmake/cpack_settings.cmake
- docker/app_ci
- docker/app_run
- docker/ccf_ci
- getting_started/setup_vm/roles/openenclave/vars/common.yml
- tests/jwt_test.py
Upgrade to the latest Open Enclave release.
> Upgrade to Open Enclave 0.17.1

- .daily_canary
- CHANGELOG.md
- include/ccf/tx.h
- src/apps/smallbank/tests/small_bank_serdes_bench.cpp
- src/consensus/aft/raft.h
- src/consensus/aft/raft_types.h
- src/consensus/aft/test/logging_stub.h
- src/crypto/symmetric_key.h
- src/kv/apply_changes.h
- src/kv/committable_tx.h
- src/kv/deserialise.h
- src/kv/encryptor.h
- src/kv/generic_serialise_wrapper.h
- src/kv/kv_types.h
- src/kv/store.h
- src/kv/test/kv_contention.cpp
- src/kv/test/kv_dynamic_tables.cpp
- src/kv/test/kv_serialisation.cpp
- src/kv/test/kv_test.cpp
- src/kv/test/null_encryptor.h
- src/node/history.h
- src/node/node_state.h
- src/node/rpc/frontend.h
- src/node/rpc/test/proposal_id_test.cpp
- src/node/test/encryptor.cpp
- src/node/test/history.cpp
- tests/election.py
- tests/infra/network.py
Cherry-pick #2755 onto 1.x LTS as well as some changes #2635 (extracting the view when deserialising a store entry).
> Cherry-pick #2755 onto 1.x LTS

- src/consensus/aft/raft.h
- src/node/progress_tracker.h
- src/node/test/progress_tracker.cpp
How far things rollback in CFT and BFT is different. In BFT when rolling back in most cases (the ones in this PR) we should rollback to the last prepared.
> Fix some of the BFT rollback related bugs

- .daily_canary
- tests/e2e_logging.py
- tests/suite/test_suite.py
Fix for https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=29152&view=results
> Fix test_random_receipts to actually work across view changes

- .azure-pipelines-templates/daily-matrix.yml
- .azure-pipelines-templates/matrix.yml
Switch the NoSGX/virtual mode builds to a hosted 1es pool.
> Switch NoSGX builds to 1es pool

- src/consensus/aft/raft.h
- src/node/node_state.h
- src/node/rpc/node_call_types.h
- src/node/rpc/node_frontend.h
- src/node/rpc/serialization.h
- src/node/rpc/test/node_frontend_test.cpp
- tests/infra/node.py
> Switch BFT to hashed public key node ids

- src/http/authentication/sig_auth.h
- src/http/http_sig.h
- src/http/test/http_test.cpp
- src/node/rpc/test/frontend_test.cpp
- tests/governance.py
> Report HTTP signature parsing error to client 

- tests/npm-app/package.json
> npm updates

- CHANGELOG.md
- CMakeLists.txt
> Bump minimum cmake version to 3.16

- CMakeLists.txt
- cmake/common.cmake
Closes #2944.
Also removes a left-over of a bad merge (or similar).
> Remove dead cmake code

- CMakeLists.txt
- tests/tests.sh
> Set BETTER_EXCEPTIONS env var correctly

- src/consensus/aft/test/committable_suffix.cpp
> Fix out of bounds access

- src/runtime_config/test/resolve.js
- tests/infra/consortium.py
- tests/infra/network.py
This is a small speedup/logging reduction on startup.
> Combine adding users and opening

- src/node/ledger_secrets.h
> Change log level for invalid rollback of ledger secrets

- cmake/common.cmake
https://github.com/microsoft/CCF/pull/2954#issuecomment-916941771
> partly revert #2954 to avoid compiler warning

- doc/schemas/app_openapi.json
- doc/schemas/gov_openapi.json
- doc/schemas/node_openapi.json
- doc/use_apps/verify_tx.rst
- include/ccf/historical_queries_interface.h
- include/ccf/receipt.h
- samples/apps/logging/logging.cpp
- src/js/wrap.cpp
- src/node/rpc/member_frontend.h
- src/node/rpc/node_frontend.h
- tests/e2e_logging.py
> Remove root from receipts

- include/ccf/historical_queries_adapter.h
- src/endpoints/common_endpoint_registry.cpp
Preliminary step for #2640.
At first I thought this was finally an occasion to use a function alias, but that doesn't support default arguments, so it wasn't.
> Version historical query adapter

- tests/infra/consortium.py
New line appeared recently in Python output, looks like temporary debugging.
> Remove debug line

- CMakeLists.txt
- samples/apps/logging/CMakeLists.txt
- samples/apps/nobuiltins/CMakeLists.txt
- tests/code_update.py
- tests/committable.py
- tests/connections.py
- tests/e2e_logging.py
- tests/e2e_suite.py
- tests/election.py
- tests/governance.py
- tests/jwt_test.py
- tests/membership.py
- tests/partitions_test.py
- tests/reconfiguration.py
- tests/recovery.py
- tests/rotation.py
- tests/schema.py
- tests/tlstest.py
- tests/vegeta_stress.py
Possible solution for https://github.com/microsoft/CCF/issues/2942.
@eddyashton @achamayou Are the sample `CMakeLists.txt` files now too complicated due to the extra condition?
> cmake: standalone samples

- .azure-pipelines-gh-pages.yml
- .azure-pipelines.yml
- .daily.yml
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- CHANGELOG.md
- getting_started/setup_vm/roles/openenclave/vars/common.yml
> Cherry-pick #2992: Upgrade to Open Enclave 0.17.2

- tests/election.py
Too many timeout failures on this one.
> Run election tests one after the other

- doc/governance/hsm_keys.rst
- python/utils/scurl.sh
> Update recovery documentation

- doc/governance/hsm_keys.rst
> Fix argument in doc

- cmake/common.cmake
> Document USE_SNMALLOC

- tests/e2e_logging.py
Quick extension to existing test, to confirm that the current range optimisation is actually faster. Will use the numbers for this total fetch as a baseline for future optimisations.
> Improve test to confirm historical range query optimisation

- .azure-pipelines-gh-pages.yml
- CHANGELOG.md
- doc/build_apps/api.rst
- doc/schemas/app_openapi.json
- doc/schemas/gov_openapi.json
- doc/schemas/node_openapi.json
- include/ccf/base_endpoint_registry.h
- include/ccf/endpoint_registry.h
- samples/apps/logging/logging.cpp
- src/endpoints/base_endpoint_registry.cpp
- src/endpoints/common_endpoint_registry.cpp
- src/node/endpoint_metrics.h
- src/node/rpc/call_types.h
- src/node/rpc/member_frontend.h
- src/node/rpc/node_frontend.h
- src/node/rpc/serialization.h
Address #2971.
This is exposing a public and versioned way to get metrics, for the benefit of applications that want to customise or version themselves the output.
> Get metrics v1

- CMakeLists.txt
- python/ccf/clients.py
- samples/apps/logging/logging.cpp
- src/node/historical_queries.h
- tests/e2e_logging.py
- tests/historical_query_perf.py
- tests/infra/network.py
I've been running some local perf tests of the historical query performance, this adds it as an automated test for the CI. There are a few easy improvements to be had (increasing the page size), but I'll add those to this PR later to confirm that the CIMetrics entry works as expected.
> Add perf test of historical query fetching

- tests/partitions_test.py
Fix for https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=33432&view=logs&j=383d248c-4494-5797-d98f-6cef5140601e&t=e2a9a03b-05b9-518e-9333-58ea2a6d0fbc
> Increase post-departition timeout

- python/ccf/ledger_viz.py
- python/requirements.txt
- python/setup.py
Idea shamelessly ripped off from the historical query optimisation document that @eddyashton wrote.
This may or may not be a useful way to decide if signature interval parameters are set correctly at a glance. In fact it's very likely that a distribution plot of interval between signatures would be more useful, but this looks nice and was very short to write.
> Ledger viz

- doc/overview/release_policy.rst
Fixes https://github.com/microsoft/CCF/issues/3038
> docs: js api stability

- tests/nobuiltins.py
Noticed this one-off failure in the CI: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=35421&view=logs&j=ee9484ec-b476-577b-aa0e-d5ddfcbcd149&t=8e7d12cf-69d2-5704-84b7-b6fd04033d7b&l=18138
I believe this is a bug in the test, since it assumes that it can call `/app/commit` at the start and that will remain the commit point (until it submits something else). However, since it does this immediately after the network has started, it's possible that the governance transactions haven't actually committed yet, in which case commit _will_ still advance shortly, and asserting that it's the same in a future response is incorrect.
`2.23` != `2.25`
The fix is just to wait for the service's current tail (provided in the response headers) to match the commit value.
> Fix for `nobuiltins` - wait for stable commit

- .azure-pipelines-templates/cmake.yml
- .azure-pipelines.yml
- .daily.yml
- .multi-thread.yml
- .stress.yml
- CHANGELOG.md
- doc/build_apps/build_setup.rst
#3147 
Purely a CI fix, so that other PRs can successfully run their checks on the LTS branch.
> Cherry-pick #3147 to 1.x LTS

- src/consensus/aft/raft.h
https://github.com/microsoft/CCF/pull/3145#discussion_r741725763
Split into its own PR, for separate evaluation.
> Increase initial Raft batch window size

- CHANGELOG.md
- doc/build_apps/api.rst
- include/ccf/historical_queries_interface.h
- samples/apps/logging/logging.cpp
- src/js/historical.cpp
- src/node/historical_queries.h
- src/node/rpc/test/node_stub.h
- src/node/test/historical_queries.cpp
> Rename drop_requests to address #3105

- doc/operations/index.rst
- js/ccf-app/package.json
- js/ccf-app/src/global.ts
- js/ccf-app/src/historical.ts
- js/ccf-app/typedoc.json
> Typedoc upgrade plus some doc fixes

- js/ccf-app/package.json
- tests/npm-app/package.json
> Unpin typescript

- doc/audit/ledger.rst
> Clarify ledger format docs around serialisation of read transactions

- doc/schemas/node_openapi.json
- src/kv/kv_types.h
- src/node/rpc/node_frontend.h
> Consensus config schema

- .daily_canary
- tests/infra/network.py
- tests/lts_compatibility.py
#3208 was set to auto-merge but the (failed) Daily doesn't gate PRs from being merged. This PR fixes the issue.
> Fix Daily failures caused by #3208

- .daily_canary
- CMakeLists.txt
- cmake/common.cmake
This was accidently changed in #3209
> Rename tests from `_CFT` to `_cft`

- doc/operations/configuration.rst
- doc/operations/ledger_snapshot.rst
Small change picked up along the way.
> Fix typos in docs

- CHANGELOG.md
- doc/schemas/node_openapi.json
- src/node/rpc/node_frontend.h
- tests/reconfiguration.py
Follow-up to https://github.com/microsoft/CCF/pull/3198#discussion_r756391952
> Add service config endpoint

- tests/historical_query_perf.py
Point 4 in https://github.com/microsoft/CCF/pull/3258#issuecomment-98142749
> Rename Historical query perf test in CIMetrics

- .azure-pipelines-gh-pages.yml
- .azure-pipelines.yml
- .daily.yml
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- CHANGELOG.md
- cmake/ccf_app.cmake
- cmake/cpack_settings.cmake
- getting_started/setup_vm/roles/openenclave/vars/common.yml
> Update LTS to Open Enclave 0.17.5

- cmake/version.cmake
> Only scan for release tags

- scripts/v8/v8-9.4.146.17.patch
- tests/js-modules/modules.py
Fixes https://github.com/microsoft/CCF/issues/3340
> V8: assume UTC+0

- src/apps/js_v8/tmpl/ccf_global.cpp
- src/apps/js_v8/tmpl/template.h
- src/apps/js_v8/v8_runner.cpp
- tests/js-modules/modules.py
Some minor drive-by changes extracted from https://github.com/microsoft/CCF/pull/3336.
> V8: minor changes

- python/ccf/clients.py
- python/requirements.txt
> Upgrade httpx to 0.21

- doc/conf.py
- js/ccf-app/package.json
Hopefully fixes the GH Pages CI job. 
More details: https://snyk.io/blog/open-source-npm-packages-colors-faker/
> Pin colors deps to 1.4.0

- src/apps/js_v8/tmpl/ccf_global.cpp
- src/crypto/key_wrap.cpp
- src/crypto/key_wrap.h
- src/crypto/mbedtls/rsa_key_pair.cpp
- src/crypto/mbedtls/rsa_key_pair.h
- src/crypto/mbedtls/rsa_public_key.cpp
- src/crypto/mbedtls/rsa_public_key.h
- src/crypto/openssl/rsa_key_pair.cpp
- src/crypto/openssl/rsa_key_pair.h
- src/crypto/openssl/rsa_public_key.cpp
- src/crypto/openssl/rsa_public_key.h
- src/crypto/rsa_key_pair.h
- src/crypto/rsa_public_key.h
- src/js/crypto.cpp
> Harmonize key wrapping label arguments

- doc/_templates/sidebar/brand.html
- doc/conf.py
I ran the FastPass automated check from https://accessibilityinsights.io/, and it found 2 problems with our docs. This PR resolves both, making our docs more useable with assistive technology.
> Resolve Docs accessibility issues found by FastPass

- src/host/tcp.h
This doesn't do much but helps with #1486 before we add metrics.
> Connection log

- src/crypto/openssl/public_key.cpp
- src/crypto/openssl/rsa_public_key.cpp
Drive-by PR while doing something else.
> Fix a couple of throws

- src/enclave/rpc_sessions.h
- src/node/rpc/error.h
> Return JSON body in session cap limit error

- doc/host_config_schema/cchost_config.json
- samples/config/join_config.json
- samples/config/minimal_config.json
- samples/config/recover_config.json
- samples/config/start_config.json
Spotted by @letmaik 
These weren't in sync with the C++ code.
> Fix JSON configuration RPC public address

- .daily_canary
- doc/host_config_schema/cchost_config.json
- python/ccf/migrate_1_x_config.py
- samples/config/join_config.json
- samples/config/minimal_config.json
- samples/config/recover_config.json
- samples/config/start_config.json
- src/common/configuration.h
- src/crypto/curve.h
- src/host/configuration.h
- tests/config.jinja
- tests/infra/remote.py
Make enum casing consistent in configuration.
> Camel case `cchost` configuration enums

- js/ccf-app/src/global.ts
- src/apps/js_v8/tmpl/receipt.cpp
- src/js/historical.cpp
> Add receipt leaf components to Typescript definition

- .daily.yml
> Fix Daily to use OE 0.17.6 base image

- tests/infra/github.py
- tests/lts_compatibility.py
Same as https://github.com/microsoft/CCF/pull/3514 but on `main` this time.
& additional fixes for format introduced in #3512
> Remove compatibility test with next LTS

- .daily_canary
- tests/infra/clients.py
- tests/partitions_test.py
Caused by https://github.com/microsoft/CCF/pull/3450, forgot to run the daily there.
> Fix partitions test broken by per-interface endorsement

- doc/operations/ledger_snapshot.rst
These invariants were not documented anywhere, even though we try very hard/have tests to verify those, mostly for auditor and operator convenience.
> Document ledger invariants

- .azure-pipelines-templates/test.yml
- tests/e2e_operations.py
- tests/infra/network.py
This causes [intermittent issues](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=41709&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=3aae4c9d-f0dc-5b97-1b0e-f86312395af9&l=22373) in the `schema_test_cft` test.
> Do not verify service ledger consistency on live service

- src/host/tcp.h
With hindsight, this was a completely obvious memory leak...
Fixes #3553
> Fix DNS resolution memory leak

- doc/operations/recovery.rst
Lost instructions when we switched to config files.
> Fix recovery start instructions

- .daily_canary
- CMakeLists.txt
I wasn't building `kv_bench` locally, so had missed the dependency on the new `ccf_kv` lib.
> Fix Daily Build

- .daily_canary
- CMakeLists.txt
> Disable LTS tests for Unsafe build

- tests/infra/network.py
Addresses https://github.com/microsoft/CCF/issues/3658
> Infra: guards logging message for ledger verification

- python/ccf/ledger.py
- python/ccf/ledger_viz.py
- python/ccf/read_ledger.py
- tests/recovery.py
Mainly to allow multiple iterations over a ledger.
> Better Python Ledger iterators

- src/node/node_state.h
- src/node/snapshotter.h
- tests/infra/network.py
- tests/recovery.py
> Trigger snapshot at end of recovery

- doc/audit/builtin_maps.rst
- python/ccf/ledger.py
- python/ccf/ledger_viz.py
- src/service/genesis_gen.h
- tests/recovery.py
> Improvements relating to service status

- doc/architecture/tcp_internals.rst
- doc/audit/python_library.rst
- doc/build_apps/api.rst
- doc/build_apps/logging_cpp.rst
- include/ccf/rpc_context.h
Mainly removal of `enclave::RpcContext`, which doesn't seem to exist anymore.
> Fix some Sphinx complaints

- .daily_canary
- src/consensus/aft/raft.h
- src/consensus/aft/test/committable_suffix.cpp
- src/consensus/aft/test/driver.h
- src/consensus/aft/test/enclave.cpp
- src/consensus/aft/test/logging_stub.h
- src/consensus/aft/test/main.cpp
- src/consensus/ledger_enclave.h
- src/consensus/ledger_enclave_types.h
- src/host/ledger.h
- src/host/test/ledger.cpp
- src/indexing/test/common.h
- src/kv/committable_tx.h
- src/kv/deserialise.h
- src/kv/kv_types.h
- src/kv/store.h
- src/kv/test/kv_test.cpp
- src/kv/test/stub_consensus.h
- src/node/node_state.h
- src/node/snapshotter.h
- src/node/test/history.cpp
- src/node/test/snapshotter.cpp
- tests/infra/network.py
- tests/lts_compatibility.py
> Synchronise ledger chunks via entry header flags

- samples/apps/logging/logging.cpp
- src/node/historical_queries.h
- src/node/test/historical_queries.cpp
> Return an error when empty historical ranges are requested

- src/tls/context.h
These lines are repeated above. Minor cleanup, no functional impact.
> Remove duplicate lines

- .daily_canary
- src/ds/pending_io.h
- tests/e2e_logging.py
Currently broken, tracking in #3830. ~~Disabling to fix the Daily build.~~
Also converting the failure into a sensible timeout.
EDIT: Found and the actual bug, just variable shadowing.
> Fix ownership issue in UDP echo test

- doc/build_apps/api.rst
- doc/build_apps/logging_cpp.rst
- include/ccf/historical_queries_adapter.h
- include/ccf/indexing/strategy.h
- samples/apps/logging/logging.cpp
Cleaning up some dangling docs refs as well.
These docs will be fleshed out further in future. For now, a description of the current system and pointers towards the sample strategy.
> Describe indexing strategies in docs

- src/ds/pending_io.h
https://github.com/microsoft/CCF/security/code-scanning/729
> Code scanning alert: Match `new[]` with `delete[]`

- src/endpoints/authentication/cert_auth.cpp
- src/node/rpc/frontend.h
- src/node/rpc/test/frontend_test.cpp
Straight cherry-pick of #3840.
> [LTS 2.x] Port authn error counting fix (#3840) to 2.x

- src/tls/context.h
> [LTS 2.x] Port duplicate line removal (#3826) to 2.x

- .daily_canary
- tests/infra/node.py
> [LTS 2.x] Cherry-pick RC version fix #3860 to 2.x LTS

- CHANGELOG.md
- include/ccf/endpoint.h
- samples/apps/logging/logging.cpp
- samples/apps/nobuiltins/nobuiltins.cpp
- src/endpoints/common_endpoint_registry.cpp
- src/endpoints/endpoint.cpp
- src/endpoints/endpoint_registry.cpp
- src/node/rpc/node_frontend.h
> Remove set_execute_outside_consensus

- CHANGELOG.md
- include/ccf/endpoint.h
- samples/apps/logging/logging.cpp
- samples/apps/nobuiltins/nobuiltins.cpp
- src/endpoints/common_endpoint_registry.cpp
- src/endpoints/endpoint.cpp
- src/endpoints/endpoint_registry.cpp
- src/node/rpc/node_frontend.h
- tests/js-launch-host-process/app.json
- tests/npm-app/app.json
> Deprecate set execute outside consensus

- .github/workflows/backport.yml
Fixing https://github.com/microsoft/CCF/pull/3898
> Fix backport GH Action

- .github/workflows/backport.yml
Follow-up from https://github.com/microsoft/CCF/pull/3899
> Backport GH Action: clone full repository

- CHANGELOG.md
- doc/audit/builtin_maps.rst
- doc/schemas/node_openapi.json
- src/enclave/enclave.h
- src/enclave/main.cpp
- src/node/historical_queries_adapter.cpp
- src/node/node_state.h
- src/node/rpc/network_identity_interface.h
- src/node/rpc/node_frontend.h
- src/service/genesis_gen.h
- src/service/network_tables.h
- src/service/tables/previous_service_identity.h
- tests/infra/network.py
- tests/lts_compatibility.py
- tests/recovery.py
- tests/start_network.py
- tests/suite/test_suite.py
> [LTS 2.x] Cherry pick `/node/network/previous_identity` (#3880) to 2.x LTS

- CHANGELOG.md
- docker/app_dev
- docker/app_run
- docker/ccf_ci
To be tagged as `ccf_ci_image/oe-0.17.7-2`.
> PSW update to 2.16.100

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-quictls.yml
- .azure-pipelines-v8.yml
- .azure-pipelines.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
> Update to build image to PSW 2.16.100

- getting_started/setup_vm/roles/openenclave/vars/common.yml
To be tagged as `ccf_ci_image/oe-0.18.0-0`
> Upgrade CI image to Open Enclave 0.18.0

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-v8.yml
- .azure-pipelines.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- CHANGELOG.md
- cmake/ccf_app.cmake
- cmake/cpack_settings.cmake
- src/ds/ccf_memcpy.h
- src/ds/ring_buffer.h
- src/enclave/enclave.h
Upgrade code to Open Enclave 0.18.0, and use `oe_memcpy_with_barrier()` where necessary.
> Upgrade to Open Enclave 0.18.0

- CHANGELOG.md
Preparing for 2.0.1. Draft PR until all changes are in (then we can use this for a final check/update PR numbers).
Waiting for #3932, #3933.
> Prepare release notes for 2.0.1

- CHANGELOG.md
- doc/schemas/app_openapi.json
- doc/schemas/gov_openapi.json
- doc/schemas/node_openapi.json
- include/ccf/ds/openapi.h
- include/ccf/endpoint.h
- samples/apps/logging/logging.cpp
- src/endpoints/endpoint_registry.cpp
- src/node/rpc/member_frontend.h
- src/node/rpc/node_frontend.h
Manual cherry-pick (+ CHANGELOG merge) of #3935.
> [release/2.x] Cherry pick:  Describe forwarding behaviour in generated OpenAPI (#3935)

- src/node/node_state.h
> Report mismatched certificates in `transition_service_to_open` proposal.

- CHANGELOG.md
Finalise release notes for 2.0.4.
> Update release notes for 2.0.4

- .daily_canary
- cmake/ccf_app.cmake
- cmake/common.cmake
- tests/npm-app/build_bundle.js
> Move `COMPILE_LIBCXX` so that it is set for apps

- doc/operations/recovery.rst
Thanks to @andpiccione for reporting the error.
> Docs: Fix quorum formula

- tests/infra/clients.py
We couldn't turn on `--http2` with the sandbox, even though it's an explicitly added option, because that also turns on `CurlClient`.
The only reason that disabled `http2` support is that our `from_raw` HTTP parser calls `HTTPResponse`, which throws up if it sees `HTTP/2`. This replaces that bit of the status line if it's present, and the parser proceeds to happily parse the remaining request.
> Support HTTP/2 with Python CurlClient

- 3rdparty/exported/nlohmann/json.hpp
- cgmanifest.json
This is deliberately not back ported to 2.x (yet), because the release is too recent at this point.
> Upgrade nlohmann::json from 3.10.2 to 3.11.2

- 3rdparty/internal/CLI11/App.hpp
- 3rdparty/internal/CLI11/CLI.hpp
- 3rdparty/internal/CLI11/Config.hpp
- 3rdparty/internal/CLI11/ConfigFwd.hpp
- 3rdparty/internal/CLI11/Error.hpp
- 3rdparty/internal/CLI11/Formatter.hpp
- 3rdparty/internal/CLI11/FormatterFwd.hpp
- 3rdparty/internal/CLI11/Macros.hpp
- 3rdparty/internal/CLI11/Option.hpp
- 3rdparty/internal/CLI11/Split.hpp
- 3rdparty/internal/CLI11/StringTools.hpp
- 3rdparty/internal/CLI11/Timer.hpp
- 3rdparty/internal/CLI11/TypeTools.hpp
- 3rdparty/internal/CLI11/Validators.hpp
- 3rdparty/internal/CLI11/Version.hpp
- cgmanifest.json
Last part of #4040 
This is deliberately not backported, because it's not used in enclave, and so is unlikely to have a positive impact on security or stability.
> Upgrade CLI11 from 2.1.1 to 2.2

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-quictls.yml
- .azure-pipelines-v8.yml
- .azure-pipelines.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- CHANGELOG.md
- cmake/ccf_app.cmake
- cmake/cpack_settings.cmake
> Upgrade to OpenEnclave 0.18.2

- doc/schemas/app_openapi.json
- src/endpoints/endpoint_registry.cpp
- tests/e2e_logging.py
... by reverting openapi_schema changes so that it can test with old nodes
successfully.
> Fix lts_compatibility test

- src/http/http2_endpoint.h
- src/http/http_endpoint.h
Initializing vars to deal with code scanning alerts https://github.com/microsoft/CCF/security/code-scanning/734 and https://github.com/microsoft/CCF/security/code-scanning/735.
> Initialize actor variables

- src/apps/external_executor/CMakeLists.txt
- src/apps/external_executor/protobuf/CMakeLists.txt
Fix order-dependent build failure introduced by #4257.
> Add dependency required between protobuf libs

- CHANGELOG.md
- include/ccf/historical_queries_adapter.h
- src/node/historical_queries_adapter.cpp
> Remove old adapter and is_tx_committed

- 3rdparty/exported/merklecpp/merklecpp.h
- cgmanifest.json
See https://github.com/microsoft/merklecpp/releases/tag/v1.0.1
> Upgrade merklecpp from 1.0.0 to 1.0.1

- doc/operations/troubleshooting.rst
This error may occur for new CCF users after setting up a fresh environment.
> Add docs on `OE_SERVICE_UNAVAILABLE`

- .azure-pipelines-templates/matrix.yml
- tests/infra/node.py
- tests/suite/test_suite.py
- tests/vegeta_stress.py
Aiming to fix the CI failures from latest release attempt: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=52330&view=results
> Release pipeline fixes

- .github/workflows/containers.yml
- getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml
- getting_started/setup_vm/roles/ccf_install/vars/common.yml
- The job wasn't picking up the correct Debian packages from the GitHub release
- The tag detection wasn't working, and always defaulted to `latest`
> Fix container release job

- 3rdparty/exported/fmt/chrono.h
- 3rdparty/exported/fmt/color.h
- 3rdparty/exported/fmt/compile.h
- 3rdparty/exported/fmt/core.h
- 3rdparty/exported/fmt/format-inl.h
- 3rdparty/exported/fmt/format.h
- 3rdparty/exported/fmt/ostream.h
- 3rdparty/exported/fmt/ranges.h
- 3rdparty/exported/fmt/std.h
- 3rdparty/exported/fmt/xchar.h
- cgmanifest.json
> Upgrade fmt from 9.0.0 to 9.1.0

- .azure-pipelines-templates/common.yml
- .azure-pipelines-templates/install_deb.yml
- .azure-pipelines-templates/matrix.yml
Re-apply https://github.com/microsoft/CCF/pull/4416 for 3.0.0-rc1.
> Run SNP release job on virtual (#4416)

- doc/contribute/build_setup.rst
- doc/operations/run_setup.rst
> Update docs after container name changes

- .github/workflows/codeql-analysis.yml
- getting_started/setup_vm/ccf-dev.yml
Fix current issue with CodeQL pipeline: https://github.com/microsoft/CCF/actions/runs/3393107897
> Fix CodeQL pipeine

- .github/workflows/npm.yml
- .github/workflows/pypi.yml
> Final tweaks to package publishing jobs

- scripts/ci-checks.sh
As requested: https://github.com/microsoft/LSKV/pull/165#issuecomment-1311637006
From the original pr this adds folds to the CI output
> Update ci-checks to use gha fold output

- python/ccf/cose.py
> Allow passing content on stdin to ccf_cose_sign1

- .github/workflows/containers.yml
- .github/workflows/pypi.yml
- getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml
As this is currently failing for `4.0.0-dev0`.
> Fix containers and PyPi release workflows

- include/ccf/odata_error.h
- include/ccf/rpc_context.h
- src/enclave/forwarder_types.h
- src/enclave/rpc_sessions.h
- src/node/node_types.h
- src/node/rpc/forwarder.h
- src/node/rpc/rpc_context_impl.h
- tests/e2e_tutorial.py
- tests/infra/clients.py
- tests/infra/commit.py
- tests/infra/logging_app.py
- tests/infra/network.py
- tests/infra/node.py
- tests/lts_compatibility.py
- tests/partitions_test.py
NB: Includes some risky manual merges. Relying on CI for testing of these changes.
> [release/2.x] Cherry pick: Session consistency: Parse forwarded messages with consistency info (#4595)

- doc/contribute/build_ccf.rst
> Add documentation warning about memory usage during builds

- doc/conf.py
- doc/use_apps/issue_commands.rst
> Fix doc links and warnings

- doc/overview/index.rst
> Update Overview page to add the maintenance section

- tla/ccfraft.tla
Added comments from:
https://github.com/microsoft/CCF/issues/4582#issuecomment-1323235839
https://github.com/microsoft/CCF/issues/4582#issuecomment-1323424528
The stated properties have been verified for both TLC configurations.  However, in the interest of symmetry reduction, not added to the configurations.
> Add comments for spec constants.

- src/apps/external_executor/external_executor.cpp
- tests/external_executor/executors/logging_app.py
- tests/external_executor/executors/wiki_cacher.py
- tests/external_executor/external_executor.py
... to the appropriate Executor.
This needs a bit more work
> Validate supported endpoints and dispatch

- .devcontainer/devcontainer.json
I think this should be built-in VS code functionality, but until it is, it's a very helpful addition to our devcontainer
> Include the gitlens extension in CCFs devcontainer

- tla/.gitignore
- tla/SIMCoverageccfraft.R
- tla/SIMCoverageccfraft.cfg
- tla/SIMCoverageccfraft.tla
- tla/SIMccfraft.cfg
- tla/SIMccfraft.tla
Make an informed decision about action probabilities based on state variable coverage.
Background: https://www.youtube.com/watch?v=cYenTPD7740
> Bias random simulation to forward-progress actions. 

- .devcontainer/devcontainer.json
- .vscode/launch.json
- src/consensus/aft/test/logging_stub.h
https://github.com/microsoft/CCF/issues/4681
> Remove elements from map outside of loop.

- .github/workflows/build-ci-container.yml
> Run build-ci-container on 1ES pool

- doc/governance/hsm_keys.rst
- python/ccf/cose.py
- python/setup.py
- [Offline cose sign1 signing (#4718)](https://github.com/microsoft/CCF/pull/4718)
> [release/3.x] Cherry pick: Offline cose sign1 signing (#4718)

- CMakeLists.txt
- doc/architecture/performance/generator.rst
- doc/architecture/performance/submitter.rst
- python/requirements.txt
- tests/infra/network.py
- tests/infra/piccolo_driver.py
- tests/perf-system/analyzer/analyzer.py
- tests/perf-system/generator/generate_packages.py
- tests/perf-system/generator/generator.py
- tests/perf-system/generator/logging_generator.py
- tests/perf-system/submitter/handle_arguments.h
- tests/perf-system/submitter/submit.cpp
A bunch of cleanup to the piccolo driver and submitter, and 2 big perf fixes buried in them - I'll highlight those inline.
> Speed up piccolo test runs

- src/consensus/aft/raft.h
- src/consensus/aft/test/driver.cpp
- src/consensus/aft/test/driver.h
https://github.com/microsoft/CCF/issues/4684
> https://github.com/microsoft/CCF/issues/4684

- tla/ccfraft.tla
If-then-else instead of disjunct lists.
> Deadlock after some 20 steps with two, three, four Nodes

- doc/host_config_schema/cchost_config.json
- doc/operations/certificates.rst
- getting_started/setup_vm/roles/perf-tool/tasks/install.yml
- include/ccf/node/acme_subsystem_interface.h
- include/ccf/service/acme_client_config.h
- src/node/acme_client.h
- src/node/ccf_acme_client.h
- src/node/node_state.h
- src/node/rpc/acme_subsystem.h
- src/node/rpc/node_interface.h
(And the `app_protocol` option to the ACME HTTP client.)
> Add SANs to ACME client

- .github/workflows/build-ci-container.yml
See current error: https://github.com/microsoft/CCF/actions/runs/4085702103/jobs/7044020106#step:6:13
> Fix build of SNP PR container

- .github/workflows/ci-containers.yml
- docker/ccf_ci
- getting_started/setup_vm/roles/ccf_build/tasks/install.yml
- getting_started/setup_vm/roles/ccf_run/tasks/install.yml
Resolve [build issue](https://github.com/microsoft/CCF/pull/5010#issuecomment-1430370860) on release/3.x.
> Revert to clang 10 by  default and build with clang 12 separately

- include/ccf/endpoints/authentication/cose_auth.h
- src/endpoints/authentication/cose_auth.cpp
- src/node/rpc/member_frontend.h
- tests/governance.py
- tests/governance_js.py
- tests/infra/clients.py
- [Improve error messages in COSE Sign Auth policies (#5019)](https://github.com/microsoft/CCF/pull/5019)
> [release/3.x] Cherry pick: Improve error messages in COSE Sign Auth policies (#5019)

- tests/suite/test_suite.py
> Disable failing test in `recovery_test_suite`

- src/consensus/aft/raft.h
- src/consensus/aft/test/driver.cpp
- src/consensus/aft/test/driver.h
- tests/raft_scenarios/4582.2
- tests/raft_scenarios/4806
- tests/raft_scenarios/election_while_reconfiguration
- tla/MCccfraft.tla
- tla/MCccfraftWithReconfig.tla
- tla/ccfraft.tla
https://github.com/microsoft/CCF/issues/4806
> (Raft) Node without configuration can become primary/leader #4806

- getting_started/setup_vm/app-dev.yml
Address issue hit in https://github.com/microsoft/CCF/actions/runs/4387296912
> Add default clang_version in app-dev.yml

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-quictls.yml
- .azure-pipelines-templates/cmake.yml
- .azure-pipelines-templates/common.yml
- .azure-pipelines-templates/daily-matrix.yml
- .azure-pipelines-templates/matrix.yml
- .azure-pipelines.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/build-ci-container.yml
- .github/workflows/ci-checks.yml
- .github/workflows/ci-containers.yml
- .gitignore
- .multi-thread.yml
- .stress.yml
- cmake/cpack_settings.cmake
- cmake/preproject.cmake
- docker/ccf_ci_built
- getting_started/setup_vm/app-dev.yml
- getting_started/setup_vm/ccf-dev.yml
- getting_started/setup_vm/roles/ccf_build/tasks/install.yml
- getting_started/setup_vm/roles/ccf_build/vars/clang15.yml
- getting_started/setup_vm/roles/ccf_run/tasks/install.yml
- getting_started/setup_vm/roles/ccf_run/vars/clang15.yml
- getting_started/setup_vm/roles/llvm_repo/vars/common.yml
- scripts/azure_deployment/arm_aci.py
- src/ds/test/map_test.cpp
- src/enclave/tls_session.h
- src/tls/test/main.cpp
- tests/test_install_build.sh
> Clang 15 for Virtual and SNP

- doc/build_apps/release_policy.rst
> Update release and support dates

- .github/workflows/containers.yml
- docker/app_dev
- docker/app_run
- getting_started/setup_vm/app-dev.yml
- getting_started/setup_vm/app-run.yml
Retro-actively applied to 4.0.0-dev6
> Fix app containers to use clang 15 on SNP and Virtual

- CHANGELOG.md
> Release notes for 4.0.0-rc0

- doc/operations/data_persistence.rst
> Document data durability

- CHANGELOG.md
Update release notes prior to 4.0.0 release.
> Update release notes for 4.0.0 final

- tla/MCccfraft.tla
- tla/MCccfraftWithReconfig.tla
- tla/Traceccfraft.tla
- tla/ccfraft.tla
Addresses https://github.com/microsoft/CCF/commit/5301f6739fd19c89cef582bff998c32d49095cd2#r111868896
> Tame state-space explosion

- tla/ccfraft.tla
Fixes bug introduced with 9356212463b0d57afc4af4f2897b8513a95a2dc5
> Don't blindly trust copilot.

- tla/Traceccfraft.cfg
- tla/Traceccfraft.tla
Part of https://github.com/microsoft/CCF/issues/5057
> Change Traceccfraft validation from using an action constraint to using a next-state relation approach.

- .github/workflows/backport.yml
- doc/architecture/performance/analysis.rst
- tests/perf-system/analyzer/analyze_packages.py
- tests/perf-system/analyzer/analyzer.py
- tests/perf-system/analyzer/throughput_analysis.py
This PR is to upstream various minor improvements to the piccolo analyzer. 
[Ignoring whitespace changes makes the diff much more readable]
> Miscellaneous improvements to Piccolo 

- .ruff.toml
- python/ccf/ledger.py
- python/ccf/ledger_viz.py
- python/ccf/read_ledger.py
- python/ledger_tutorial.py
- scripts/ci-checks.sh
- tests/ca_certs.py
- tests/e2e_logging.py
- tests/e2e_operations.py
- tests/external_executor/executors/logging_app/logging_app.py
- tests/external_executor/executors/util.py
- tests/external_executor/executors/wiki_cacher/wiki_cacher.py
- tests/governance.py
- tests/governance_history.py
- tests/infra/clients.py
- tests/infra/consortium.py
- tests/infra/logging_app.py
- tests/infra/network.py
- tests/infra/piccolo_driver.py
- tests/infra/remote_client.py
- tests/js-modules/modules.py
- tests/lts_compatibility.py
- tests/raft_scenarios_runner.py
- tests/reconfiguration.py
- tests/recovery.py
Before:
real    1m36.260s
user    1m17.446s
sys     0m13.619s
After:
real    0m51.070s
user    0m41.184s
sys     0m11.767s
Ruff has an extensive selection of plugins that look interesting too.
> Switch from pylint to ruff

- .cmake-format.py
- CMakeLists.txt
- cmake/common.cmake
- cmake/preproject.cmake
- src/apps/tpcc/tpcc.cmake
Since we have a number of other flags that only work with Clang, we might as well have this one be set correctly too.
Edit: a bit of cleanup in cmake while I'm here.
> Fix color diagnostics

- doc/governance/js_runtime.rst
Small update to JS runtime documentation to add exception reporting features added in 4.0.1
> Update js_runtime.rst documentation per 4.0.1

- doc/use_apps/issue_commands.rst
> Document governance command idempotence

- tla/ccfraft.tla
Left-over of https://github.com/microsoft/CCF/commit/c2208dc6ee996d796cfcd270832e8c4c8a401922
> Replace  messages  with  Messages.

- tla/Traceccfraft.tla
https://github.com/microsoft/CCF/issues/5057
> Include log's timestamp in trace spec.

- tla/Traceccfraft.tla
> Syntactic Refactoring of Traceccfraft.tla

- src/consensus/aft/raft.h
https://github.com/microsoft/CCF/issues/5057
Towards validating fancy_election.1 and suffix_collision.2.
> Log values of committable_indices in TLA+ validation JSON logging

- .azure-pipelines-templates/trace_validation.yml
- tla/Traceccfraft.tla
- tla/ccfraft.tla
Add matching of match_idx and sent_idx to trace validation (Traceccfraft.tla).
https://github.com/microsoft/CCF/issues/5057
> Add matching of match_idx and sent_idx to trace validation (Traceccfraft.tla).

- samples/apps/basic/oe_sign.conf
Bump up values to facilitate benchmarking.
> Update oe_sign.conf settings

- src/ds/test/logger_json_test.cpp
Fixes #5420, broken since #5375.
> Fix `logger_json_test`

- cmake/preproject.cmake
- src/apps/tpcc/app/tpcc_setup.h
- src/ds/state_machine.h
- src/host/ledger.h
- src/host/lfs_file_handler.h
- src/host/main.cpp
- src/host/tcp.h
- src/host/udp.h
- src/indexing/strategies/seqnos_by_key_bucketed.cpp
- src/kv/store.h
- src/kv/untyped_map.h
- src/node/acme_client.h
- src/node/historical_queries.h
- src/node/history.h
- src/node/node_state.h
- src/node/rpc/member_frontend.h
- src/node/rpc/node_frontend.h
- src/node/share_manager.h
- [Remove shadowing instances from the code (#5449)](https://github.com/microsoft/CCF/pull/5449)
> [release/4.x] Cherry pick: Remove shadowing instances from the code (#5449)

- .azure-pipelines-gh-pages.yml
- .azure-pipelines.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/build-ci-container.yml
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- CHANGELOG.md
- cmake/cpack_settings.cmake
- cmake/open_enclave.cmake
- docker/ccf_ci_built
- getting_started/setup_vm/roles/openenclave/vars/common.yml
- scripts/azure_deployment/arm_aci.py
> Update to Open Enclave 0.19.3

- CHANGELOG.md
Update release notes for 4.0.6
> Release notes for 4.0.6

- tests/perf-system/submitter/submit.cpp
- tests/requirements.txt
Second item in #5491, also see https://github.com/pola-rs/polars/issues/10226.
> Remove chunk_size limit on WriteTable call, and unpin polars

- src/apps/js_generic/oe_sign.conf
Support larger number of threads in JS Generic app
> Increase NumTCS for JS Generic app

- tests/perf-system/submitter/submit.cpp
> Remove usage of deprecated gettimeofday and switch to monotonic clock

- tests/infra/basicperf.py
Sample:
```
{
"average_throughput_tx/s": 68734.55727813902,
"average_request_input_mb/s": 5.925099022265421,
"average_request_output_mb/s": 1.0521512779018807,
"all_clients_active_from": "2023-08-04T13:33:29.111778",
"all_clients_active_to": "2023-08-04T13:33:52.372435",
"all_clients_active_duration_s": 23.260657,
"all_clients_active_percentage": 79,
"total_duration_s": 29.097445
}
```
> Produce JSON stats summary in basicperf

- .azure-pipelines-templates/daily-matrix.yml
- .azure-pipelines-templates/matrix.yml
- .azure-pipelines-templates/stress-matrix.yml
Working around ongoing provisioning issues.
> Switch to a backup pool

- tests/perf-system/submitter/submit.cpp
Both are affected by NTP. `REALTIME` might be non-monotonic if an admin adjusts time, but uhhh, don't do that during a perf test. `REALTIME` lets us correlate with wall-clocks on other systems, hopefully with an NTP-minimised skew.
> Piccolo submitter: Use `CLOCK_REALTIME` rather than `CLOCK_MONOTONIC`

- tests/infra/basicperf.py
Calculation was incorrectly using the total duration, oops.
> Fix all active throughput calculation

- .azure-pipelines-templates/common.yml
- .azure-pipelines-templates/daily-matrix.yml
- .azure-pipelines-templates/install_extended_testing_tools.yml
- .azure-pipelines-templates/matrix.yml
- .azure-pipelines-templates/stress-matrix.yml
- .multi-thread.yml
- CMakeLists.txt
- getting_started/setup_vm/ccf-dev.yml
- getting_started/setup_vm/ccf-extended-testing.yml
- [Install vegeta and pebble and run corresponding tests in Daily (#5529)](https://github.com/microsoft/CCF/pull/5529)
> [release/4.x] Cherry pick: Install vegeta and pebble and run corresponding tests in Daily (#5529)

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-templates/daily-matrix.yml
- .azure-pipelines-templates/deploy_aci.yml
- .azure-pipelines.yml
- .azure_pipelines_snp.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- docker/ccf_ci_built
- scripts/azure_deployment/arm_aci.py
Follow up to #5529, which results in a slightly smaller CI/CD image.
> Update CI jobs to 10-08-2023 base

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-templates/deploy_aci.yml
- .azure-pipelines.yml
- .azure_pipelines_snp.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- docker/ccf_ci_built
- scripts/azure_deployment/arm_aci.py
See https://github.com/microsoft/CCF/releases/tag/ccf_ci_image%2F11-08-2023
> Update CI image to 11-08-2023

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-templates/deploy_aci.yml
- .azure-pipelines.yml
- .azure_pipelines_snp.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/ci-checks.yml
- .multi-thread.yml
- .stress.yml
- docker/ccf_ci_built
- scripts/azure_deployment/arm_aci.py
> Update CI image from 11-08 to 14-08

- .azure-pipelines-templates/matrix.yml
Fixes https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=74862&view=logs&j=77890be3-fbd3-52a1-2c40-e5bc14cbbdef&t=37e815a4-02f1-50e0-9ecd-dc1a864da067
> Install testing tools for release jobs

- CHANGELOG.md
- doc/schemas/node_openapi.json
- src/node/node_state.h
- src/node/rpc/node_frontend.h
- src/node/rpc/node_interface.h
- src/node/rpc/node_operation.h
- src/node/rpc/node_operation_interface.h
- src/node/rpc/test/node_stub.h
- tests/e2e_common_endpoints.py
- tests/e2e_operations.py
- tests/reconfiguration.py
- tests/recovery.py
- [Add app and gov read endpoints (#5574)](https://github.com/microsoft/CCF/pull/5574)
> [release/4.x] Cherry pick: Add app and gov read endpoints (#5574)

- tests/infra/basicperf.py
> Update away from deprecated polars function names

- python/utils/verify_quote.sh
> Add default `443` port to `verify_quote.sh`

- tla/ccfraft.tla
Have to be manually added to TLC's config files for now.
> Add two high-level liveness properties and a suitable fairness constraints.

- src/consensus/aft/raft_types.h
> Add comment about contains_new_view

- tla/Traceccfraft.tla
- tla/ccfraft.tla
> Move Alias to ccfraft.

- tla/Traceccfraft.tla
> Refactor IsRcvAppendEntriesRequest to eliminate conjunct that matches the *next* logline.

- tla/MCccfraft.cfg
- tla/MCccfraft.tla
- tla/MCccfraftWithReconfig.cfg
- tla/ccfraft.tla
> Remove two auxiliary variables from ccfraft.

- doc/research/index.rst
Add a level of indirection, consistent with the IA-CCF entry.
> Update documentation to point to TR entry

- src/consensus/aft/raft.h
- src/ds/serialized.h
- src/node/test/encryptor.cpp
Also add a missing check in the read (string) variant.
> Improve error detail in raft message recv

- .azure-pipelines-templates/configure.yml
- .azure-pipelines-templates/deploy_aci.yml
- .azure-pipelines-templates/misc.yml
- .azure-pipelines-templates/scan_build.yml
- .azure-pipelines-templates/trace_validation.yml
Follow-up to #5720 and and #5716.
> Add missing -e to script tasks that were missing it

- src/crypto/openssl/key_pair.cpp
- src/crypto/test/bench.cpp
Connected to #5663, cannot find a repro at this time, but surfacing the return code should at least help if it happens again.
> Report rc on keygen failure

- CHANGELOG.md
- doc/host_config_schema/cchost_config.json
- src/host/configuration.h
- src/host/main.cpp
- tests/config.jinja
- tests/infra/remote.py
- [Add CLI argument for SNP context directory (#5686)](https://github.com/microsoft/CCF/pull/5686)
> [release/4.x] Cherry pick: Add CLI argument for SNP context directory (#5686)

- tla/MCccfraft.cfg
- tla/MCccfraftWithReconfig.cfg
- tla/SIMccfraft.cfg
- tla/ccfraft.tla
Related: https://github.com/microsoft/CCF/issues/3950
> Raft Paper section 5.4.2: "[A leader] never commits log entries from previous terms...".

- .azure-pipelines-templates/configure.yml
Following #5774. We have a similar problem as reported here: https://developercommunity.visualstudio.com/t/tasksetvariable-result-when-using--scri/1594491?q=task.setvariable
Guessing, though unable to confirm, that the issue is from the trailing space preceding the comments, so removing the comments.
> Restore running full CI on main, take 3

- tla/consensus/Traceccfraft.tla
@achamayou does this scratch your itch?
> Meaningful warning when the ndjson input file has no content.

- tla/consensus/MCccfraft.cfg
- tla/consensus/MCccfraft.tla
- tla/consensus/MCccfraftWithReconfig.cfg
- tla/consensus/ccfraft.tla
Some minor tweaks to tidy up some TLA+ code, removing some dead code and fixing indentation
> TLA+ tidy up

- tla/consensus/Traceccfraft.tla
> IsRcvProposeVoteRequest does not define the successor state(s).

- tla/consensus/MCccfraft.cfg
- tla/consensus/MCccfraft.tla
- tla/consensus/MCccfraftWithReconfig.cfg
- tla/consensus/SIMccfraft.tla
- tla/consensus/Traceccfraft.cfg
- tla/consensus/Traceccfraft.tla
- tla/consensus/ccfraft.tla
> Refactor hardcoded set of all Servers out of ccfraft.

- .azure-pipelines-templates/model_checking.yml
- metrics.yml
- tests/upload_tlc_stats.py
Also try 5 columns to see what that looks like.
> Add other MC stats

- doc/governance/gov_api_schemas/upgrading_from_classic.rst
> Clarify casing change in documentation

- .azure-pipelines-templates/trace_validation.yml
- tests/trace_viz.py
Appends to a single node, trace validation.
> Add append scenario to CI

- tests/trace_viz.py
Give up on suffixes, TxID and commit only, and tag signatures on replicate:
> More compact trace viz, signatures

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-templates/deploy_aci.yml
- .azure-pipelines.yml
- .azure_pipelines_snp.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/ci-checks.yml
- .github/workflows/tlaplus.yml
- .multi-thread.yml
- .stress.yml
- docker/ccf_ci_built
- scripts/azure_deployment/arm_aci.py
Pick up recent base image fixes, update from 26-10-2023 to 05-12-2023.
> Refresh base image

- getting_started/setup_vm/roles/ccf_build/vars/clang11.yml
> Add lld to dependencies

- tla/consensus/ccfraft.tla
> Only send AEs to known servers

- tla/consensus/MCccfraft.tla
- tla/consensus/SIMCoverageccfraft.R
- tla/consensus/SIMCoverageccfraft.cfg
- tla/consensus/SIMCoverageccfraft.tla
- tla/consensus/SIMccfraft.cfg
- tla/consensus/SIMccfraft.tla
- tla/consensus/ccfraft.tla
https://github.com/microsoft/CCF/assets/88777/26d303fb-77e4-4643-8cfb-866a245b1c75
> Bias simulation towards to behaviors where followers are more often in sync.

- .devcontainer/devcontainer.json
- .devcontainer/tlaplus/devcontainer.json
- js/ccf-app/test/tsconfig.json
- js/ccf-app/tsconfig.json
- tests/js-interpreter-reuse/tsconfig.json
- tests/npm-app/tsconfig.json
To fix CI failure here: https://github.com/microsoft/CCF/actions/runs/7559747092/job/20584236488?pr=5931
> Running prettier over JSON files

- doc/governance/adding_member.rst
> Update documentation to reflect the need to provide signed input to POST state-digests

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-templates/deploy_aci.yml
- .azure-pipelines.yml
- .azure_pipelines_snp.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/ci-checks.yml
- .github/workflows/tlaplus.yml
- .multi-thread.yml
- .stress.yml
- docker/ccf_ci_built
- scripts/azure_deployment/arm_aci.py
Same as #5955 on the LTS branch.
> Update CI image to 25-01-2024 on release/4.x

- python/ccf/cose.py
- python/ccf/ledger_code.py
- python/ccf/ledger_viz.py
- scripts/azure_deployment/arm_aci.py
- tests/governance.py
- tests/infra/basicperf.py
- tests/infra/clients.py
- tests/infra/consortium.py
- tests/infra/network.py
- tests/infra/remote.py
- tests/lts_compatibility.py
Result of `git ls-files tests/ python/ scripts/ .cmake-format.py | grep -e '\.py$' | xargs black ` to fix CI failure here https://github.com/microsoft/CCF/actions/runs/7666015400/job/20892996824?pr=5919
> Black reformat python files

- src/consensus/aft/test/driver.cpp
- tests/raft_scenarios_runner.py
- tests/trace_viz.py
Makes working on scenarios easier:
> Add the driver command at the end of the trace viz

- .github/workflows/codeql-analysis.yml
- getting_started/setup_vm/ccf-dev.yml
Check that doesn't break anything before attempting 22.04 upgrade. Related to #5963.
> Add require_open_enclave flag to dev playbook and use it in CodeQL pipeline

- tests/raft_scenarios_runner.py
- tests/trace_viz.py
Performance regression spotted by @lemmy in #5927, see https://github.com/microsoft/CCF/pull/5972/files#r1474095517.
Before https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=81093&view=logs&j=0c81e209-1101-513f-1f15-37e9c3575eb2&t=a05664f3-ab91-5eb2-6acd-14e2179ad708
> Finished in 19min 11s at (2024-02-01 03:39:26)
After https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=81113&view=logs&j=0c81e209-1101-513f-1f15-37e9c3575eb2&t=a05664f3-ab91-5eb2-6acd-14e2179ad708
> Finished in 24s at (2024-02-01 09:38:35)
> Empty cmd is now "" rather than null

- .github/workflows/backport.yml
Backport action was moved from 
https://github.com/sqren/backport-github-action
to 
https://github.com/sorenlouv/backport-github-action
> Update backport action

- src/crypto/sharing.h
> Improve doxygen in sharing.h

- tla/consensus/ccfraft.tla
Fixes https://github.com/microsoft/CCF/issues/5979 and will help to align spec and implementation
> Ignoring AE messages before commit index

- tla/consensus/Traceccfraft.tla
- tla/consensus/ccfraft.tla
Follow up from https://github.com/microsoft/CCF/pull/5988
Low risk change.
> Comments to document use of `sent_idx` in spec

- src/consensus/aft/test/driver.cpp
- src/consensus/aft/test/driver.h
Pulling out a few actions proposed in previous PRs (#5991), adding them explicitly here.
> Add actions for Raft scenarios

- .azure-pipelines-templates/azure_cli.yml
- .azure-pipelines-templates/build-ci-container.yml
- .azure-pipelines-templates/install_deb.yml
- .azure-pipelines-templates/install_ssh_key.yml
- .azure-pipelines-templates/ninja.yml
- .azure-pipelines-templates/release.yml
- .azure-pipelines-templates/test_on_remote.yml
- .azure-pipelines-templates/trace_validation.yml
Spotted after a build break left a Ninja step green (!).
> Make CI jobs that run important commands with pipes report correctly when they fail

- src/consensus/aft/test/driver.cpp
- src/consensus/aft/test/driver.h
- tests/raft_scenarios/append
- tests/raft_scenarios/bad_network
- tests/raft_scenarios/check_quorum
- tests/raft_scenarios/election
- tests/raft_scenarios/election_while_reconfiguration
- tests/raft_scenarios/fancy_election.1
- tests/raft_scenarios/fancy_election.2
- tests/raft_scenarios/multi_election
- tests/raft_scenarios/reconfiguration
- tests/raft_scenarios/reconnect
- tests/raft_scenarios/reelection
- tests/raft_scenarios/replicate
- tests/raft_scenarios/retire_one
- tests/raft_scenarios/soft_rollback
- tests/raft_scenarios/startup
- tests/raft_scenarios/startup_2nodes
- tests/raft_scenarios/suffix_collision.1
- tests/raft_scenarios/suffix_collision.2
- tests/raft_scenarios/suffix_collision.3
- tla/trace2scen.py
Spun out of #5973, convenient in retirement scenarios.
> RaftDriver: Add `assert_detail`

- tla/consensus/MCAliases.tla
- tla/consensus/Traceccfraft.tla
Related https://github.com/microsoft/CCF/pull/6000
> Strengthen assertions in trace validation

- .azure-pipelines-templates/trace_validation.yml
- tla/tlc.sh
- De-duplicate flags once more
- Attempt to nudge CI output towards something useful
> Tidy up TV cli again

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-release.yml
- .azure-pipelines-templates/deploy_aci.yml
- .azure-pipelines.yml
- .azure_pipelines_snp.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/ci-checks.yml
- .github/workflows/tlaplus.yml
- .multi-thread.yml
- .stress.yml
- docker/ccf_ci_built
- scripts/azure_deployment/arm_aci.py
Base image update to pick up latest versions of packages.
> Update CI image from 25-01-2024 to 12-02-2024

- .azure-pipelines-templates/trace_validation.yml
- tla/tlc.sh
Follow up to https://github.com/microsoft/CCF/pull/6012#discussion_r1486446069
> Only use StateDeque for trace validation

- tla/consensus/MCccfraft.cfg
- tla/consensus/MCccfraft.tla
- tla/consensus/MCccfraftAtomicReconfig.cfg
- tla/consensus/MCccfraftWithReconfig.cfg
- tla/consensus/SIMccfraft.tla
> Spring cleaning TLA+ 

- tests/trace_viz.py
Another couple of issues spotted in #5973 that do not need to be bundled.
> Trace Viz: Add missing retirement phase and fix commit index display

- .azure-pipelines-templates/model_checking.yml
- tla/consensus/ccfraft.tla
https://github.com/microsoft/CCF/issues/6038
> Report TLA+ spec coverage ever 10 minutes and once at the end of model checking

- tla/consensus/MCccfraft.tla
https://github.com/microsoft/CCF/issues/6045
> n.type = AppendEntriesRequest missing from disjunct.

- tla/consensus/ccfraft.tla
> Change addedNodes

- tla/consensus/ccfraft.tla
CommittedLogAppendOnlyProp asserts that the committed log is append-only, and LogInv asserts that the committed log of all servers is the same.  Given that and the fact that TLC checks ReplicationInv for every state, it implies that TLC will have already checked ReplicationInv for all lower commit indices.
> Refactor ReplicationInv to reduce its computational complexity.

- .azure-pipelines-templates/matrix.yml
- .azure-pipelines-templates/model_checking.yml
> Remove Model Checking dependency in main CI post-split

- tla/consensus/ccfraft.tla
- tla/consistency/SingleNode.tla
Follow up to https://github.com/microsoft/CCF/pull/5973#discussion_r1525984553
> Adopt a consistent 'ing style in TLA+

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-model-checking.yml
- .azure-pipelines-release.yml
- .azure-pipelines-templates/deploy_aci.yml
- .azure-pipelines.yml
- .azure_pipelines_snp.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/ci-checks.yml
- .github/workflows/tlaplus.yml
- .multi-thread.yml
- .stress.yml
- docker/ccf_ci_built
- scripts/azure_deployment/arm_aci.py
Regular CI image refresh to pick up latest base image.
> Update CI image from 12-02-2024 to 15-03-2024

- tla/consensus/ccfraft.tla
- tla/consistency/SingleNode.tla
Quick cleanup pass over comments and the spec. Amusingly (?) every single raft.h line number reference was wrong.
> TLA comment update

- .github/workflows/pypi.yml
> Update to checkout@v4 pypi.yml on release/4.x

- .gitignore
- scripts/TLAi-linter.genai.js
- tla/consensus/Traceccfraft.tla
Trace validation succeeds: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=83342&view=logs&j=0c81e209-1101-513f-1f15-37e9c3575eb2&t=a05664f3-ab91-5eb2-6acd-14e2179ad708
> Refactor Traceccfraft to reuse IsRequestVoteRequest.

- src/node/gov/api_version.h
Before it was like:
```
GET /proposal
"NO. Gimme an ?api-version= arg."
GET /proposal?api-version=foo
"NO. Only supported api-versions are: bar, baz"
GET /proposal?api-version=bar
```
Now we cut out the middle request, with a more helpful initial error.
```
GET /proposal
"NO. Gimme an ?api-version= arg. Only supported api-versions are: bar, baz"
```
> Report supported API versions in `MissingApiVersionParameter` response

- Doxyfile
- js/ccf-app/src/crypto.ts
- js/ccf-app/src/global.ts
> Misc doc fixes

- .azure-pipelines-templates/trace_validation.yml
- tests/raft_scenarios_runner.py
> Emit consensus traces in separate directory

- tests/jwt_test.py
For the purpose of testing JWT authentication, we need to set a root CA used to validate the connections made to fetch the list of keys and the keys themselves.
The test had historically used [`SSLContext.get_cat_certs()`](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.get_ca_certs), which would contain the root of trust loaded to validate the peer. The behaviour seems to have changed recently, and a large list (but not quite all the CA cert store) is returned instead.
In the absence of another API that can be used to conveniently fetch the root authority ultimately used to check the chain ending in a server's leaf cert, this PR hardcodes the Digicert Global Root CA, used by Entra. Although the hardcoding is unfortunate, the expiry date on the cert (2031) should mean that the …
> Fix jwt_test

- .azure-pipelines-templates/common.yml
- .azure-pipelines-templates/matrix.yml
- .azure-pipelines-templates/metrics.yml
- .azure-pipelines-templates/push_perf_data.yml
- .azure-pipelines-templates/test.yml
- tests/commit_latency.py
- tests/historical_query_perf.py
- tests/infra/piccolo_driver.py
- tests/infra/runner.py
- tests/upload_pico_metrics.py
Backports the following commits to release/4.x:
- #6125 
- #6130
> [release/4.x] Cherry-pick: Remove/disable cimetrics

- 3rdparty/exported/fmt/args.h
- 3rdparty/exported/fmt/chrono.h
- 3rdparty/exported/fmt/color.h
- 3rdparty/exported/fmt/compile.h
- 3rdparty/exported/fmt/core.h
- 3rdparty/exported/fmt/format-inl.h
- 3rdparty/exported/fmt/format.h
- 3rdparty/exported/fmt/os.h
- 3rdparty/exported/fmt/ostream.h
- 3rdparty/exported/fmt/printf.h
- 3rdparty/exported/fmt/ranges.h
- 3rdparty/exported/fmt/std.h
- 3rdparty/exported/fmt/xchar.h
Update to latest before investigating https://github.com/microsoft/CCF/security/code-scanning/891
> Update fmtlib from 10.1.1 to 10.2.1

- 3rdparty/exported/nlohmann/json.hpp
Update to latest before investigating https://github.com/microsoft/CCF/security/code-scanning/863
> Upgrade nlohmann/json from 3.11.2 to 3.11.3

- include/ccf/ds/json.h
- src/clients/perf/timing.h
- tests/perf-system/submitter/submit.cpp
Spotted by CodeQL as https://github.com/microsoft/CCF/security/code-scanning/867, https://github.com/microsoft/CCF/security/code-scanning/865 and https://github.com/microsoft/CCF/security/code-scanning/866.
> Fix value narrowing in comparisons

- src/js/core/context.cpp
- src/js/core/context.h
- src/node/gov/handlers/proposals.h
https://github.com/microsoft/CCF/security/code-scanning/864
> Tidy up code handling code_ident.content to make it clearer to CodeQL

- src/consensus/aft/impl/state.h
- src/consensus/aft/raft.h
> Raft tidy up

- tests/fuzzing.py
- tests/infra/checker.py
- tests/infra/piccolo_driver.py
- tests/infra/runner.py
> Clean up test TODOs

- tla/consistency/ExternalHistory.tla
- tla/consistency/ExternalHistoryInvars.tla
- tla/consistency/MCMultiNode.cfg
- tla/consistency/MCMultiNodeCommitReachability.cfg
- tla/consistency/MCMultiNodeInvalidReachability.cfg
- tla/consistency/MCMultiNodeReadsNotLinearizable.cfg
- tla/consistency/MCSingleNode.tla
- tla/consistency/MCSingleNodeCommitReachability.cfg
- tla/consistency/MultiNode.tla
- tla/consistency/SingleNode.tla
Contains no substantive changes
> Spring clean consistency spec

- tla/consistency/ExternalHistoryInvars.tla
A bonus invariant to check that there's no conflicts between tx statuses
> Additional consistency invariant

- tla/consensus/Traceccfraft.tla
Items moved to #6183 for discussion and investigation. Should unblock #6177.
> Consensus tv todo cleanup

- tla/consensus/Traceccfraft.tla
- tla/consensus/ccfraft.tla
> Document lack of request payload validation in ctv

- .github/workflows/bencher.yml
- cmake/common.cmake
- tests/infra/basicperf.py
- tests/infra/bencher.py
~~(Draft while I experiment with the results)~~
Adding a few more tests to Bencher, removing `^` suffix, adding a Memory metric (docs slightly unclear, but suggests you can define these on-the-fly?), experimenting with some other Bencher options.
> Extend Bencher testing, add Memory metric

- .azure-pipelines-templates/azure_cli.yml
- .azure-pipelines-templates/deploy_aci.yml
> [release/4.x] Cherry-pick: SNP CI: Login to az cli with VM's user-managed identity (#6123)

- tests/npm-app/app.json
Mis-formatted in #6236, committed too eagerly.
> Fix format of `npm-app/app.json`

- samples/apps/basic/basic.cpp
- tests/programmability.py
Also add support for client certifications authentication.
> Progammability: multiple authentication methods

- getting_started/setup_vm/roles/openenclave/vars/common.yml
New images built and pushed by https://github.com/microsoft/CCF/actions/runs/9497647758
> Update from Open Enclave 0.19.4 to 0.19.6

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-model-checking.yml
- .azure-pipelines-release.yml
- .azure-pipelines-templates/deploy_aci.yml
- .azure-pipelines.yml
- .azure_pipelines_snp.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/bencher.yml
- .github/workflows/ci-checks.yml
- .github/workflows/tlaplus.yml
- .multi-thread.yml
- .stress.yml
- CHANGELOG.md
- cmake/cpack_settings.cmake
- cmake/open_enclave.cmake
- docker/ccf_ci_built
- scripts/azure_deployment/arm_aci.py
> Update to use latest CI image containing Open Enclave 0.19.6

- src/san_common.suppressions
The related UB has been fixed in the dependency.
> Remove unnecessary suppression

- .azure-pipelines-gh-pages.yml
- .azure-pipelines-model-checking.yml
- .azure-pipelines-release.yml
- .azure-pipelines-templates/deploy_aci.yml
- .azure-pipelines.yml
- .azure_pipelines_snp.yml
- .daily.yml
- .devcontainer/devcontainer.json
- .github/workflows/bencher.yml
- .github/workflows/ci-checks.yml
- .github/workflows/tlaplus.yml
- .multi-thread.yml
- .stress.yml
- CHANGELOG.md
- cmake/cpack_settings.cmake
- cmake/open_enclave.cmake
- docker/ccf_ci_built
- getting_started/setup_vm/roles/openenclave/vars/common.yml
- scripts/azure_deployment/arm_aci.py
Pick up latest version of Open Enclave.
> Upgrade base to open enclave 0.19.7

- .azure-pipelines-templates/matrix.yml
Will move the remaining items in a follow up PR once the release has moved too.
> Remove jobs that have been moved to GHA in #6295

- CHANGELOG.md
- include/ccf/ds/logger.h
- src/apps/tpcc/clients/tpcc_client.cpp
- src/consensus/aft/test/driver.cpp
- src/consensus/aft/test/driver.h
- src/consensus/aft/test/main.cpp
- src/ds/test/logger.cpp
- src/ds/test/logger_bench.cpp
- src/ds/test/logger_json_test.cpp
- src/enclave/main.cpp
- src/enclave/ringbuffer_logger.h
- src/endpoints/test/endpoint_registry.cpp
- src/host/handle_ring_buffer.h
- src/host/main.cpp
- src/host/test/ledger.cpp
- src/http/test/http_test.cpp
- src/kv/test/kv_bench.cpp
- src/kv/test/kv_contention.cpp
- src/kv/test/kv_test.cpp
- src/node/test/encryptor.cpp
- src/node/test/endorsements.cpp
- src/node/test/history_bench.cpp
- src/node/test/snapshotter.cpp
- tests/perf-system/submitter/submit.cpp
> Re-namespace ::logger to ccf::logger

- .github/workflows/build.yml
No reason to keep it different anymore, now that the whole container runs as root.
> Align partitions test on other tests

- CMakeLists.txt
- cmake/crypto.cmake
- include/ccf/crypto/pem.h
- src/crypto/pem.cpp
- src/crypto/test/pem.cpp
- tests/perf-system/submitter/CMakeLists.txt
> Add unit test to split_x509_cert_bundle

- CHANGELOG.md
Aggregate release notes from dev releases and release candidates into a single 5.0.0 block.
> Release notes 5.0.0

- python/ccf/_versionifier.py
- python/requirements.txt
- tests/infra/github.py
- tests/infra/node.py
- tests/infra/remote.py
Adjust to https://github.com/pypa/setuptools/issues/2825
> Import from packaging directly, add to requirements

- .github/workflows/ci-containers-ghcr.yml
- .github/workflows/containers-ghcr.yml
> Rename job for readability

- python/pyproject.toml
> Upgrade python cryptography package

- python/pyproject.toml
Intended to quote and remote `--dirty` in the previous PR, but got too trigger happy with the red button.
> Tweak `git_describe_command`

- samples/apps/logging/js/src/logging.js
- samples/apps/logging/logging.cpp
- tests/e2e_logging.py
Continuing #6401 here, as soon as I don't have write access to @eddyashton's branch
> UPDATED Correct error response for /app/log/public/historical/range when given a future to_seqno

- tests/e2e_logging.py
Implicit TX may have occured due to periodic snapshots, thus last tx id + 1 could suddenly become valid. Instead of doing it +2/+3/etc we put a smart wait with last TX refetch to preserve the test logic and hoping for deterministic behaviour in the future.
Closes #6417
> Fix flakiness for hist range test

- tests/infra/crypto.py
- tests/js-custom-authorization/custom_authorization.py
Raw issuer may exceed the limit of characters for attributes.
> Change raw issuer to digest before passing to x509

- CHANGELOG.md
- src/node/gov/handlers/service_state.h
> Return schema correctly in gov/service/javascript-app endpoint

- CHANGELOG.md
- src/endpoints/authentication/jwt_auth.cpp
- tests/js-custom-authorization/custom_authorization.py
Closes https://github.com/microsoft/CCF/issues/6427
> Improve JWT auth error msg

- cmake/crypto.cmake
- cmake/t_cose.cmake
- src/crypto/openssl/cose_sign.cpp
- src/crypto/openssl/cose_sign.h
- src/crypto/test/crypto.cpp
Closes #6445 .
Please see issue description for details.
> COSE signing API for raw payload

- python/pyproject.toml
> Update setuptools requirement

- README.md
> Typo Update in README.md

- CHANGELOG.md
- src/node/node_state.h
- tests/infra/network.py
- tests/reconfiguration.py
> Shut down on join 400

- .github/CONTRIBUTING.md
Moved pointers to current version of the automated workflows.
> Update CONTRIBUTING.md with current workflows

- tla/consensus/SIMccfraft.cfg
Check main properties `QuorumLogInv` and `LeaderCompletenessInv ` during simulation.
> Revert https://github.com/microsoft/CCF/pull/5939

- .devcontainer/tlaplus/devcontainer.json
> Update devcontainer.json to enable cdot by default

- tla/consensus/MCccfraft.cfg
- tla/consensus/MCccfraft.tla
Spotted https://github.com/microsoft/CCF/pull/6529
> Limiting the terms reached by ProposeVote

- .github/workflows/long-test.yml
Same as #6536 but for long tests.
> Allow manual trigger of long test on branches

- tests/certs.py
> Fix openssl cmd spaces on Azure Linux

- CHANGELOG.md
- doc/build_apps/api.rst
- doc/build_apps/js_app_bundle.rst
- include/ccf/common_auth_policies.h
- include/ccf/endpoint.h
- include/ccf/endpoints/authentication/cert_auth.h
- include/ccf/endpoints/authentication/js.h
- js/ccf-app/src/endpoints.ts
- samples/apps/logging/js/app.json
- samples/apps/logging/js/src/logging.js
- samples/apps/logging/logging.cpp
- src/endpoints/authentication/cert_auth.cpp
- src/js/extensions/ccf/request.cpp
- tests/e2e_logging.py
- tests/npm-app/app.json
- tests/npm-app/src/endpoints/auth.ts
- [Any cert authn policy (#6608)](https://github.com/microsoft/CCF/pull/6608)
> [release/5.x] Cherry pick: Any cert authn policy (#6608)

- doc/build_apps/run_app.rst
- tests/sandbox/sandbox.sh
> Remove enclave type usage in sandbox

- tests/e2e_logging.py
Fix for https://github.com/microsoft/CCF/actions/runs/11840661125/job/32995126516?pr=6620
> Fix TxID lookup in e2e logging test

- docker/sgx_deps_pin.sh
- getting_started/setup_vm/roles/openenclave/vars/common.yml
> Update Open Enclave to 0.19.8 and PSW to 2.25.100

- CMakeLists.txt
Following suggestion in https://github.com/microsoft/CCF/pull/6681#discussion_r1873013941
> Unbuffer by default on non-CI

- CHANGELOG.md
- src/node/gov/handlers/service_state.h
- tests/js-modules/modules.py
> Add a `?case=original` query argument to `GET /gov/service/javascript-app`

- doc/audit/builtin_maps.rst
Fix https://github.com/microsoft/CCF/actions/runs/12636572852/job/35208946128
Caused by #6601
> Add missing table description

- 3rdparty/exported/fmt/args.h
- 3rdparty/exported/fmt/base.h
- 3rdparty/exported/fmt/chrono.h
- 3rdparty/exported/fmt/color.h
- 3rdparty/exported/fmt/compile.h
- 3rdparty/exported/fmt/format-inl.h
- 3rdparty/exported/fmt/format.h
- 3rdparty/exported/fmt/os.h
- 3rdparty/exported/fmt/ostream.h
- 3rdparty/exported/fmt/printf.h
- 3rdparty/exported/fmt/ranges.h
- 3rdparty/exported/fmt/std.h
- 3rdparty/exported/fmt/xchar.h
- cgmanifest.json
- src/ds/std_formatters.h
- src/kv/kv_types.h
> Update fmtlib from 10.2.1 to 11.1.2

- .github/workflows/long-test.yml
> Add missing libcurl to Azure Linux long test pipeline

- python/src/ccf/cose.py
> Check VDS value on receipts

- tests/infra/network.py
> Remove error message ignore in ASAN runs

- CMakeLists.txt
- src/host/test/env.cpp
I oopsed this right out of the CMake.
> Build and test `test/env.cpp`

- .github/workflows/release.yml
- scripts/install-azure-linux-extended.sh
> Protocol tests on azure linux

- CHANGELOG.md
- python/pyproject.toml
- src/node/jwt_key_auto_refresh.h
- src/tls/ca.h
- tests/jwt_test.py
> Handle multiple certificates in JWT CA bundle correctly

- CHANGELOG.md
- doc/schemas/node_openapi.json
- python/pyproject.toml
- src/node/rpc/node_frontend.h
- tests/code_update.py
> Add `/node/attestations` and `/node/attestations/self` endpoints

- cmake/cpack_settings.cmake
See https://github.com/microsoft/CCF/pull/6825#discussion_r1957366577
and https://github.com/microsoft/CCF/pull/6825#discussion_r1957366823
Also see the explanation in the CMake file
> Normalise RPM package name

- cmake/cpack_settings.cmake
Ooops
https://github.com/microsoft/CCF/pull/6834#discussion_r1961994212
> Fix cpack comment

- .github/workflows/long-test.yml
- scripts/setup-ci.sh
- tests/acme_endorsement.py
- tests/npm_tests.py
Enables ASAN+TSAN on Azure Linux.
Includes a workaround for #6853.
And a workaround for #6862.
> Enable TSAN/ASAN on AL in CI

- .github/workflows/doc.yml
- scripts/setup-ci.sh
- tests/start_network.py
Getting rid of CCF CI images use
Tried running with commented deploy step: https://github.com/microsoft/CCF/actions/runs/13631175237
> Try docs on AL container

- .github/workflows/codeql-analysis.yml
Getting rid of CCF CI images use
> Move CodeQL job to Azure Linux image

- tests/consistency_trace_validation.py
- tests/e2e_logging.py
A few packages bumped overnight, this updates our tests to handle them all.
> Handle latest Azure Linux package versions

- CHANGELOG.md
- CMakeLists.txt
- python/pyproject.toml
> Drop verify_quote.sh script

- CHANGELOG.md
Adding entry to CHANGELOG missed from #6913.
> [release/5.x] Update 5.x CHANGELOG

- tests/infra/github.py
> Another attempt to fix the LTS test

- .github/workflows/containers-ghcr.yml
> Only build release containers on 5.x (tentative)

- .github/workflows/long-test.yml
- scripts/scan-build.sh
> Long test on Azure Linux only

- doc/host_config_schema/cchost_config.json
- doc/operations/platforms/snp.rst
- samples/config/start_config_aci_sev_snp.json
> Update documentation and sample configurations for snp_endorsements_file

- doc/build_apps/migration_5_x_to_6_0.rst
> Fix 5->6 migration doc style

- tests/recovery.py
Missed during #6974, broke daily long test https://github.com/microsoft/CCF/actions/runs/14526905491/job/40760056139.
> Fix long test (folloup ledger.py rework)

- python/src/ccf/split_ledger.py
Another driveby improvement to the Python utils. This allows us to split a ledger file at arbitrary seqnos (gated by an additional CLI arg), which should simplify repro of #6968 and related ledger chunking issues.
> Allow `split_ledger.py` to operate at non-signature transactions

- doc/build_apps/install_bin.rst
Fix a typo in the download URLs
> Fix download url

- tests/infra/github.py
> Minor simplification in LTS release selection logic

- tla/consensus/ccfraft.tla
Fix typo mistake - commmitted to committed
> Fix typo mistake - commmitted to committed

- .clang-tidy
- CMakeLists.txt
- cmake/tools.cmake
- include/ccf/kv/untyped_map_diff.h
- include/ccf/kv/untyped_map_handle.h
- include/ccf/tx.h
- src/js/core/wrapped_value.cpp
- src/kv/tx.cpp
- src/kv/untyped_map_diff.cpp
- src/kv/untyped_map_handle.cpp
> Clang tidy KV code

- tests/npm_tests.py
Discovered and filed in https://github.com/microsoft/CCF/issues/6853
Presumably fixed in https://github.com/microsoft/SymCrypt-OpenSSL/issues/109
> Test all curves for EdDSA under ASAN

- include/ccf/crypto/openssl/openssl_wrappers.h
uniq_ptr wrapper for DER CSRs, we already have one for PEM, this is useful for aDNS.
> Add Unique_X509_REQ_DER

- python/src/ccf/ledger.py
This was noticed and fixed in #6849 (Feb '25), but I overwrote that in the refactor of #6974 (Apr '25, based on an older branch).
> Restore correct node membership condition in `ledger.py`

- .github/workflows/release.yml
To enable reproducible builds, this PR resolves the image digest and uses it in build
> Use image digest in build

- .github/workflows/release.yml
- scripts/setup-ci.sh
This PR persists some metadata needed to reproduce the CCF build and adds it to what is published at the end of the build.
Depends on:  #7060
> Publish Reproduce Metadata

- doc/operations/cli.rst
- doc/operations/index.rst
> Doc for cchost

- src/consensus/aft/test/logging_stub.h
- src/kv/committable_tx.h
- src/kv/kv_types.h
- src/kv/store.h
- src/kv/test/kv_test.cpp
- src/node/node_state.h
- src/node/rpc/node_frontend.h
- src/node/snapshotter.h
- src/node/test/snapshotter.cpp
Pulled out of #6811 for clarity.
> Renames to distinguish Tx and Store flag enums

- cmake/common.cmake
> Only set SAN-related test properties when appropriate SAN is on

- samples/apps/basic/CMakeLists.txt
- samples/apps/logging/CMakeLists.txt
- samples/apps/nobuiltins/CMakeLists.txt
- samples/apps/programmability/CMakeLists.txt
> Sample apps cmake bump-up

- doc/build_apps/auth/jwt.rst
> Make the doc sample `set_ca_cert_bundle` proposal obviously a placeholder

- .github/workflows/ci.yml
- doc/conf.py
Follow-up to #7169 
Disable duplicate labels thingy because I give up.
> Enforce warnings-free docs

- CMakeLists.txt
> Run perf longer for more stable results

- .clang-tidy
- src/node/test/endorsements.cpp
- src/node/uvm_endorsements.cpp
- src/node/uvm_endorsements.h
And add a few tests, while I'm there.
> Remove another clang-tidy exception

- .github/workflows/bencher-ab.yml
- scripts/compare_bencher_ab.py
- tests/tests.sh
Triggers on label, runes main VS current commit.
Seems like it's impossible to comment the result from the action on forks, which is what we use for development, so currently went for simply uploading an .md artifact. e.g.:
UPD. Changed to post as job summary in the job run itself, so less clicking (thanks to Amaury): https://github.com/microsoft/CCF/actions/runs/17458286438
P.S. Python thing is fully vibe-coded, sorry for that.
P.P.S. Reviewed it anyway, is way too verbose but seems doing the right thing.
> AB perf test

- python/src/ccf/cose.py
> Update for python-cwt 3.2.0

- CHANGELOG.md
- python/src/ccf/receipt.py
- tests/e2e_logging.py
- tests/recovery.py
- tests/requirements.txt
> [release/6.x] Cherry pick: Remove pyopenssl (#7297)

- CHANGELOG.md
- python/utils/submit_recovery_share.sh
Backport #7306 to unblock #7320
> [release/5.x] Cherry pick: Recovery shares script changes (#7306)
