doc/build_apps/example.rst
Removed duplicate 'public' word on the GET /app/log/public/ endpoint description (C++ logging application example)
=> Edit example.rst

CHANGELOG.md, doc/host_config_schema/cchost_config.json, doc/schemas/node_openapi.json, include/ccf/service/node_info.h, samples/constitutions/default/actions.js, src/common/configuration.h, src/host/configuration.h, src/host/main.cpp, src/node/node_state.h, src/node/rpc/call_types.h, src/node/rpc/node_call_types.h, src/node/rpc/node_frontend.h, src/node/rpc/serialization.h, tests/config.jinja, tests/governance.py, tests/governance_js.py, tests/infra/consortium.py, tests/infra/network.py, tests/infra/node.py, tests/infra/remote.py
Resolves #3644.
`node_data` can be passed at cchost startup time*, or via a `set_node_data` proposal. The objects returned in `/network/nodes` also include `last_written`, as a hint to when each node was added.
_\* The config argument is a top-level field named `node_data_json_file`. It's a path to a file for consistency with `member_data`. We could inline these now that we have a JSON config, rather than requiring them to be dumped to a separate file, but it's a more awkward change when migrating from 1.x to 2.x_
=> Add free-form `node_data` field

CHANGELOG.md
Should have been part of #3664.
=> Describe `enclave::` namespace removal in changelog

3rdparty/exported/nghttp2/includes/nghttp2/nghttp2ver.h, 3rdparty/exported/nghttp2/nghttp2_buf.h, 3rdparty/exported/nghttp2/nghttp2_frame.c, 3rdparty/exported/nghttp2/nghttp2_frame.h, 3rdparty/exported/nghttp2/nghttp2_hd.c, 3rdparty/exported/nghttp2/nghttp2_net.h, 3rdparty/exported/nghttp2/nghttp2_outbound_item.h, 3rdparty/exported/nghttp2/nghttp2_pq.h, 3rdparty/exported/nghttp2/nghttp2_session.c, 3rdparty/exported/nghttp2/nghttp2_session.h, 3rdparty/exported/nghttp2/nghttp2_stream.c, 3rdparty/exported/nghttp2/nghttp2_submit.c, cgmanifest.json
Note that this library isn't currently included in CCF (requires `-DENABLE_HTTP2`, which is `OFF` by default).
=> Update `nghttp2/nghttp2` to 1.47.0

tests/e2e_operations.py, tests/recovery.py
When running the recovery tests more than 3 times with ledger splitting enabled, it frequently happened that the ledger files on disc went out of sync. We didn't see this in CI runs because we only ever ran 3 or 4 recoveries with splitting enabled for some of them. That test is now moved to e2e_operations, where we check that the split ledger can be read successfully and the recovery tests run without splitting ledgers.
=> Move split ledger test

src/host/tcp.h
Fixes #3693 
According to the libuv docs, the `res` must be freed manually. Something around that must have changed though, as I never saw this the last time I tested for leaks and the exactly same test I used at that time, now produced lots of these errors, where it used to produce none. Perhaps I was just unbelievably lucky then.
=> Fix yet another DNS resolver memory leak

src/crypto/openssl/openssl_wrappers.h
Lib fmt will print these `NUL` bytes if we retain them. We don't actually want them here, they're just reserved memory, so truncate before returning.
=> Truncate OpenSSL::error_string

doc/schemas/app_openapi.json, include/ccf/ds/openapi.h, include/ccf/endpoint.h, samples/apps/logging/logging.cpp, src/ds/test/openapi.cpp
We previously marked all auto-generated OpenAPI request/response bodies as `application/json`, on the assumption they were using JSON serializers. This is obviously not true for plain-text responses, leading to inaccurate OpenAPI elements (and a follow-on warning during docs build).
We would ideally only insert the `application/json` content type if we knew it was using a JSON serializer, but that would need a type trait from the macro that doesn't currently exist, and it's not clear what we do in the fallback cases (we need a sensible default value, since the content type of each response is required).
=> Describe text objects as `text/plain` in generated OpenAPI

src/node/node_state.h, tests/infra/node.py
This currently blocks releases on new `2.x` release candidates.
https://github.com/microsoft/CCF/pull/3746 modified the logic around recovering ledger entries, which is also used to verify 1.x snapshots. This is only tested when cutting a new 2.0 release candidate tag. 
This is now fixed:
```bash
$ "python3" "lts_compatibility.py" "-b" "." "--label" "lts_compatibility" "--host-log-level" "info" "--worker-threads" "0" ... "--ccf-version" "ccf-2.0.0-rc7" "--check-ledger-compatibility" "--check-2tx-reconfig-migration" -e virtual --release-install-path /opt/ccf/
09:42:46.919 | SUCCESS  | __main__:<module>:623 - Compatibility report:
{
"version": "ccf-2.0.0-rc7",
"live compatibility": {
"with release (/opt/ccf/)": "ccf-1.0.19"
}
}
```
I will fix the LTS compatibility tag detection logic …
=> Fix 1.x snapshot verification on 2.x node join

CHANGELOG.md, tests/infra/github.py
This is expected to fail until https://github.com/microsoft/CCF/pull/3775 is merged.
When committing to `main`, the `lts_compatibility` test only checked for live compatibility with the latest release candidate (i.e. `ccf-2.0.0-rc6`), but not with the latest previous final release (i.e. `ccf-1.0.19`). The compatibility with `ccf-1.0.19` was only checked when the next release tag (i.e. `ccf-2.0.0-rc7`) was cut:
```bash
{
"version": "ccf-2.0.0-rc6-27-gea38c18f",
"live compatibility": {
"with previous LTS": "ccf-2.0.0-rc6",
"with same LTS": null
}
}
```
This now checks for compatibility with both `ccf-2.0.0-rc6` and `ccf-1.0.19`, helping us catch compatibility issues early:
```bash
{
"version": null,
"live compatibility": {
"with previous LTS": "ccf-1.0.19",
"with same LTS": "ccf-2.0.0-rc6" …
```
=> Better LTS compatibility checks when committing to `main`

.azure-pipelines-templates/daily-matrix.yml, .daily_canary, tests/e2e_logging.py
#3776 seems to have taken the `lts_compatibility` over its allowed timeout so this PR reduces the number of receipts we sample in this test.
=> Reduce number of verified receipts in LTS compatibility test

.daily_canary, tests/infra/network.py
This issue has recently [appeared in the Daily CI](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=44605&view=results), only with release SGX builds (?). I couldn't reproduce the error locally, but it seems that the timeout current value is dangerously low, and this may throw if the disk is slow.
=> Increase timeout while waiting for committed snapshot

tests/infra/remote.py
The recent changes to add early-crash detection broke the `-d` argument to sandbox/start_network/etc. Specifically, `check_done` attempts to access `self.proc`, which only exists in the `self.remote.start()` path, but not if the node was started manually with a debugger.
I considered moving the `Detect whether node started up successfully` block, so it wouldn't run at all on the debugger-attached nodes. I think this approach, even though it's an ugly change, gives nice behaviour - if debug-attached nodes crash on start-up, the infra recognises this quickly from missing startup files, rather than ignoring it entirely.
=> Restore ability to launch infra nodes with debugger attached

python/requirements.txt
Fix break introduced in later releases, see https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=44775&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=3e1ef318-4174-5329-41dd-e9ef66c4c6d0
=> Pin requests-http-signature to 0.2.0

include/ccf/crypto/pem.h, include/ccf/ds/json.h, include/ccf/ds/json_schema.h, include/ccf/ds/openapi.h, include/ccf/entity_id.h, include/ccf/tx_id.h, src/ds/test/json_schema.cpp, src/ds/test/openapi.cpp, src/kv/kv_types.h
C++ nitty-gritty:
We do argument-dependent lookup (ADL) to find various type-specific functions for JSON serialisation and schema generation. I used `const T&` as the lookup type, which means `T` must be constructible, so doesn't support abstract types (and introduces a dumb runtime construction cost!). We can get the same dispatch using `const T*`, but without introducing extra requirements on the type.
=> Use pointers for JSON schema ADL

.daily_canary, tests/lts_compatibility.py
Since releasing [2.0.0-rc8](https://github.com/microsoft/CCF/releases/tag/ccf-2.0.0-rc8), the `lts_compatibility` test is failing because of the ledger chunks inconsistency introduced in https://github.com/microsoft/CCF/pull/3768 when upgrading from 1.x to 2.x-rc8+. I've simplified the logic so that we accept any ledger incompatibility when upgrading from 1.x to 2.x-rc8+.
=> Fix LTS ledger compatibility chunks

.azure-pipelines-gh-pages.yml, .azure-pipelines-v8.yml, .azure-pipelines.yml, .daily.yml, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml, CHANGELOG.md
Follow-up attempt at https://github.com/microsoft/CCF/pull/3812
=> Upgrade Open Enclave to 0.17.7

CHANGELOG.md, doc/generate_config_rst.py, doc/host_config_schema/cchost_config.json, python/ccf/migrate_1_x_config.py, src/host/main.cpp, tests/config.jinja
Resolves #3813 
We did not throw an error when an operator started a node with extra entries in the JSON configuration file. This was because we parsed the configuration file into the `host::CCHostConfig` configuration type first (`nlohmann::json(config_str)`), which removed the extra entries. We now do this with `nlohmann::json::parse(config_str)`, which we feed directly to `valijson`.
I also updated the documentation generator to accommodate this and fixed a couple of inconsistencies in some of the sample configuration files.
=> Stricter JSON configuration schema for `cchost` 

.daily_canary, doc/host_config_schema/cchost_config.json
I broke the daily build in #3816.
=> Allow `null` for `node_client_interface` field in `cchost` configuration

tla/download_or_update_tla.sh
The current tla+ install script (https://github.com/microsoft/CCF/blob/main/tla/download_or_update_tla.sh) fetches tla+ from  https://tla.msr-inria.inria.fr/tlatoolbox/dist/tla2tools.jar, however, this file has not been updated since December 2020. This PR updates the URL in the install script to point at the latest GitHub release for tla+.
**Aside:**
As acknowledged in the file itself, this script was originally adapted from https://github.com/pmer/tla-bin. I have also reported this issue to tla-bin (https://github.com/pmer/tla-bin/issues/14) and its now been fixed (https://github.com/pmer/tla-bin/pull/15).
=> Updating URL of tla2tools in TLA+ install script

src/endpoints/authentication/cert_auth.cpp, src/node/rpc/frontend.h, src/node/rpc/test/frontend_test.cpp
Discovered while following up on something from #3770:
> - Don't increment successes in /jwt_metrics when a manual /jwt_keys/refresh returns 500.
The reason that was happening is 2-fold.
1. First, exceptions thrown by an authentication policy result are caught in `http_endpoint.h`  rather than the main loop in `frontend.h`, and don't get counted in endpoint metrics. I've fixed that by extending the scope of the generic `try-catch`, to cover all of the code once the `endpoint` is known.
2. Second, the node cert authentication policy was throwing an OpenSSL error when called anonymously (eg, by `curl https://127.0.0.1:8000/node/jwt_keys/refresh -k -X POST`). I've converted this to a nicer error working within the authn policy chain system. A missing cert means you can't use …
=> Fix counting of authentication exceptions in endpoint metrics

.github/workflows/containers.yml, CHANGELOG.md, getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml, getting_started/setup_vm/roles/ccf_install/vars/common.yml
Resolves https://github.com/microsoft/CCF/issues/3825
Note the new `--extra-vars run_js=true` argument when building the new `public/ccf/app/run-js` image.
=> Add new JS application runtime docker image

.daily_canary, tests/infra/node.py
The `lts_compatibility` test is currently failing on `release/2.x`, because this `version_rc` function fails to parse versions like `ccf-2.0.0-1-g51f57be9a`. Now it recognized that they're not a release candidate.
=> Correct RC version detection in Python infra

CHANGELOG.md, doc/host_config_schema/cchost_config.json, src/host/main.cpp, src/node/hooks.h
This adds a `published_address` to the configuration of the node-interface. The reason to add this is that my nodes run in different virtual networks, where they may have the same `bind_address`, or when the `bind_address` is not an internet-reachable address, e.g. `0.0.0.0:0`.
In my specific use-case, I have two nodes on Azure VMs in different vnets. One of them on `10.1.0.4` and the other on `172.18.0.4` and they do not themselves know what their actual IPs are. I can make them bind to `0.0.0.0`, but then that address is put into the nodes table and consequently nodes can't connect to each other when they use the address from the nodes table. Thus, I now put `published_address` into the nodes table, which defaults to the `bind_address` if not specified.
Many thanks to @jumaffre for …
=> Add published_address to node-to-node interface configuration

.devcontainer/devcontainer.json
I think this got slowly muddled up. The purpose of the `.devcontainer.json` file is to help build CCF locally. To do so, we should use the CI container rather than `ccf/app/dev` which is to build applications.
=> Use CCF CI container in VSCode `.devcontainer.json`

doc/architecture/merkle_tree.rst, doc/architecture/raft_tla.rst, doc/use_apps/index.rst, doc/use_apps/issue_commands.rst, doc/use_apps/python_tutorial.rst, doc/use_apps/verify_quote.rst, doc/use_apps/verify_tx.rst
=> Docs: Remove mention of `ccf` Python client from docs

CMakeLists.txt
Because we are setting our cpack values *before* we define the CMAKE_INSTALL_PREFIX, they are generally wrong!
But, we rarely notice, since we run cmake again (just to extract flags) *before* cpack in our release process: https://github.com/microsoft/CCF/blob/main/.azure-pipelines-templates/install_deb.yml#L4
And so we typically end up ok, except sometimes on local builds, where most of the files mysteriously end up installed in /usr/local if cmake has been run once and only once.
Special thanks to @eddyashton for helping me spot this.
=> Fix cmake install prefix

.azure-pipelines-templates/install_deb.yml, cmake/common.cmake, tests/recovery_benchmark.sh, tests/test_install.sh
This PR adds a new `recovery_benchmark.sh` script to conveniently measure how long a recovery procedure takes. The script accepts parameters to change the signature interval, to recover from a snapshot and how long to load the service for (i.e. how many entries to recover). 
The script is also run in the Daily pipeline.
=> Add recovery benchmark script

.github/workflows/backport.yml
Follow-up from https://github.com/microsoft/CCF/pull/3897
It turns out that we want to always overwrite the canary file to avoid merge conflicts. I followed the steps described in https://github.com/microsoft/CCF/pull/3675.
=> Backport GH Action: canary file is always overwritten 

.backportrc.json, .github/workflows/backport.yml, doc/contribute/release_ccf.rst
The backport GitHub Action is now working (see https://github.com/microsoft/CCF/pull/3892 -> https://github.com/microsoft/CCF/pull/3904). 
This PR cleans up a few things (e.g. do not publish verbose comments on original PR) and adds documentation for it.
=> Cleanup backport GitHub Action

.github/workflows/backport.yml, doc/contribute/release_ccf.rst
It turns out, there's no way to only trigger a GH Action if a label ends with a specific pattern (here, `-todo`) but only when it contains a specific string (here `auto-backport`). So I'm reverting the changes introduced in https://github.com/microsoft/CCF/pull/3905 and the `auto-backport` label is now necessary.
=> Backport GH Action: `auto-backport` label is required

getting_started/setup_vm/ccf-dev.yml, getting_started/setup_vm/roles/pebble/tasks/install.yml, getting_started/setup_vm/roles/pebble/vars/common.yml
This adds [pebble](https://github.com/letsencrypt/pebble) to our CI images. This is used for local ACME client tests.
=> Add pebble to CI images

CHANGELOG.md, src/enclave/client_endpoint.h, src/enclave/tls_endpoint.h, src/http/http_endpoint.h, src/node/node_state.h, tests/config.jinja, tests/infra/network.py, tests/infra/remote.py, tests/reconfiguration.py
- [Shutdown new joining node early if target service certificate is invalid (#3895)](https://github.com/microsoft/CCF/pull/3895)
=> [release/2.x] Cherry pick: Shutdown new joining node early if target service certificate is invalid (#3895)

src/node/rpc/test/node_frontend_test.cpp
Was failing in ~1/256 runs, when the final byte of the new node's DER was null.
This is a quickfix for the test, will add a more intrusive fix for this general type confusion separately.
=> Fix DER vs PEM confusion in `node_frontend_test`

.daily_canary, .pylintrc, tests/infra/remote.py
When the Python infra copies ledger files (e.g. when starting a new node), it is possible that a ledger file gets committed while the infra is copying the file, resulting in rare errors in the CI (e.g. [here](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=46315&view=logs&j=e982d093-d12a-5a2d-1a1d-0c6d38b8823f&t=8be5454d-0d8f-51e4-7372-58df022e9ebc&l=18006)). 
We now retry copying files if the initial copy fails (and up to 5 times), like we already do with snapshot files.
=> Infra: make ledger file copy more resilient

.azure-pipelines-gh-pages.yml, .azure-pipelines-v8.yml, .azure-pipelines.yml, .daily.yml, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml
- [Update to build image to PSW 2.16.100 (#3921)](https://github.com/microsoft/CCF/pull/3921)
=> [release/2.x] Cherry pick: Update to build image to PSW 2.16.100 (#3921)

CHANGELOG.md, docker/app_dev, docker/app_run, docker/ccf_ci
- [PSW update to 2.16.100 (#3920)](https://github.com/microsoft/CCF/pull/3920)
=> [release/2.x] Cherry pick: PSW update to 2.16.100 (#3920)

doc/audit/builtin_maps.rst
Fixing a warning in the docs build, which appears to have recently escalated to a build failure.
=> Fix docs warning

.daily_canary, CMakeLists.txt, include/ccf/crypto/key_pair.h, include/ccf/crypto/pem.h, src/clients/perf/perf_client.h, src/crypto/openssl/key_pair.cpp, src/crypto/openssl/key_pair.h, src/host/main.cpp, src/js/crypto.cpp, src/js/wrap.cpp, src/node/node_state.h, src/node/rpc/gov_effects_interface.h, src/node/rpc/test/frontend_test.cpp, src/node/rpc/test/frontend_test_infra.h, src/node/rpc/test/node_frontend_test.cpp, src/node/rpc/test/proposal_id_test.cpp, src/node/test/history.cpp, src/service/genesis_gen.h
Follow up to #3916, hoping to avoid similar issues in other places.
The real fix here is that when a `crypto::Pem` is constructed with contents, it confirms they look a bit like a PEM. Maybe that check should be more precise, but I think it's sufficient for now. This broke a bunch of unit tests, which used various kinds of empty PEMs, but now generate plausible test identities.
I'd like to remove the default constructor for PEMs as well, so we disallowed empty PEMs as well, at compile time. Unfortunately this is tricky to do alongside JSON serialization - we _can_ convert to `crypto::Pem` even when it is not default-constructible, but we'd need to do the same thing for all of our PoD JSON-serialized structs which hold `crypto::Pem`s (or make those `std::optional` or similar). That's …
=> Ensure `crypto::Pem`s contain PEM encoded contents

.azure-pipelines-templates/release.yml
- [Fix rename properly (#3930)](https://github.com/microsoft/CCF/pull/3930)
=> [release/2.x] Cherry pick: Fix rename properly (#3930)

.azure-pipelines-templates/install_deb.yml, CMakeLists.txt, cmake/ccf_unsafe-config.cmake.in, cmake/cpack_settings.cmake, cmake/version.cmake, samples/apps/logging/CMakeLists.txt, tests/test_install_build.sh
- [Unsafe different project (#3894)](https://github.com/microsoft/CCF/pull/3894)
=> [release/2.x] Cherry pick: Unsafe different project (#3894)

src/enclave/enclave.h, src/node/node_configuration_subsystem.h, src/node/node_state.h, src/node/rpc/frontend.h, src/node/rpc/member_frontend.h, src/node/rpc/node_frontend.h, src/node/rpc/node_interface.h, src/node/rpc/test/frontend_test.cpp, src/node/rpc/user_frontend.h
This adds a node configuration subsystem. This will be used in the `RpcFrontend` to get better performance by exposing the node configuration directly instead of via a read-only transaction, which will be important in #3945 + follow-ups.
=> Add node configuration subsystem

doc/conf.py
`nghttp2.org` no longer responds to HTTP1.1, which means it looks dead to Sphinx's link-check (and various other services).
```
$ curl https://nghttp2.org/nghttp3/programmers-guide.html -I --http1.1
curl: (52) Empty reply from server
$ curl https://nghttp2.org/nghttp3/programmers-guide.html -I --http2
HTTP/2 200
...
```
This PR adds those URLs to the ignore list.
=> Ignore nghttp2 URLs in linkcheck

src/enclave/ringbuffer_logger.h
Uninitialized variable leads to terrible, horrible, no good very bad logging like this (in debug virtual builds):
```
2022-06-23T10:45:51.198881Z        100 [info ] ../src/host/main.cpp:412             | Startup host time: 2022-06-23 10:45:51
2022-06-23T10:45:51.200313Z        100 [info ] ../src/host/main.cpp:464             | Creating new node: new network (with 3 initial member(s) and 3 member(s) required for recovery)
2022-06-23T10:45:51.200338Z        100 [info ] ../src/host/main.cpp:544             | Initialising enclave: enclave_create_node
2022-06-23T10:45:51.300529Z -1655951080.618 0   [trace] ../src/enclave/enclave.h:110         | Creating ledger secrets
2022-06-23T10:45:51.300577Z -1655951080.618 0   [trace] ../src/enclave/enclave.h:113         | Creating node …
```
=> Initialize enclave logging offset

README.md
We seem to have an empty row, a lone badge up top and a not particularly compact layout as a result. This is a bit better, I think.
=> Fix README layout

CHANGELOG.md, cmake/version.cmake, doc/schemas/node_openapi.json, src/node/rpc/node_call_types.h, src/node/rpc/node_frontend.h, src/node/rpc/serialization.h, tests/reconfiguration.py
- [Reflect unsafe status in /node/version (#3942)](https://github.com/microsoft/CCF/pull/3942)
=> [release/2.x] Cherry pick: Reflect unsafe status in /node/version (#3942)

doc/audit/builtin_maps.rst, doc/host_config_schema/cchost_config.json, doc/operations/certificates.rst, doc/schemas/node_openapi.json, include/ccf/endpoint.h, include/ccf/service/node_info_network.h, src/endpoints/endpoint.cpp, src/node/acme_challenge_frontend.h, src/node/node_configuration_subsystem.h, src/node/rpc/frontend.h, tests/acme_endorsement.py, tests/infra/interfaces.py
This adds a new configuration field to restrict endpoints to a particular set of endpoints (as paths in a regexes).
=> Allow regex to specify endpoints to serve on an interface

.threading_canary, include/ccf/ds/mutex.h, include/ccf/endpoint_registry.h, src/consensus/aft/impl/state.h, src/consensus/aft/raft.h, src/ds/histogram.h, src/ds/test/stub_writer.h, src/enclave/main.cpp, src/enclave/rpc_sessions.h, src/endpoints/authentication/sig_auth.cpp, src/endpoints/base_endpoint_registry.cpp, src/endpoints/endpoint_registry.cpp, src/host/dns.h, src/host/ledger.h, src/host/tcp.h, src/kv/store.h, src/kv/untyped_map.h, src/node/historical_queries.h, src/node/history.h, src/node/jwt_key_auto_refresh.h, src/node/ledger_secrets.h, src/node/node_state.h, src/node/node_to_node_channel_manager.h, src/node/request_tracker.h, src/node/rpc/frontend.h, src/node/snapshotter.h, src/node/test/historical_queries.cpp
- [Use custom mutex implementation on SGX (#3978)](https://github.com/microsoft/CCF/pull/3978)
=> [release/2.x] Cherry pick: Use custom mutex implementation on SGX (#3978)

.daily_canary, src/enclave/tls_endpoint.h, tests/e2e_common_endpoints.py
We no longer append to `pending_read` in enclave when a session is closing. This could have caused large memory growth in enclave when the client was sending very large messages.
As hinted by @letmaik in https://github.com/microsoft/CCF/issues/3912, when a client sends a large message, it is possible that it still writes to the now-closed socket before receiving the error response from the server. The infra wasn't resilient to such failures (see [here](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=47039&view=logs&j=abb827b0-1387-5f0d-393d-8da14bd7f99d&t=328e9e87-12fb-5696-903c-0f14a0ce494d&l=39382)) and this PR addresses this.
=> Do not buffer incoming TLS frames if session is closed

CHANGELOG.md, include/ccf/crypto/pem.h, tests/infra/consortium.py
- [Remove null byte from PEM files (#3885)](https://github.com/microsoft/CCF/pull/3885)
=> [release/2.x] Cherry pick: Remove null byte from PEM files (#3885)

.daily_canary, CHANGELOG.md, doc/operations/recovery.rst, doc/schemas/node_openapi.json, include/ccf/service/tables/service.h, src/node/rpc/call_types.h, src/node/rpc/node_frontend.h, src/node/rpc/serialization.h, src/service/genesis_gen.h, tests/infra/consortium.py, tests/infra/network.py, tests/infra/node.py, tests/lts_compatibility.py, tests/recovery.py
- [Track number of service recoveries  (#3982)](https://github.com/microsoft/CCF/pull/3982)
=> [release/2.x] Cherry pick: Track number of service recoveries  (#3982)

tests/recovery.py
Before: `2022-06-30T09:11:35.4678419Z 34/53 Test #40: recovery_test_cft ................   Passed  228.30 sec`
After: `2022-06-30T10:51:10.7841394Z 34/53 Test #40: recovery_test_cft ................   Passed  142.45 sec`
=> Only run 3 recoveries

CHANGELOG.md, doc/host_config_schema/cchost_config.json, doc/operations/start_network.rst, doc/schemas/node_openapi.json, include/ccf/service/tables/service.h, src/common/configuration.h, src/host/configuration.h, src/host/main.cpp, src/node/node_state.h, src/node/rpc/call_types.h, src/node/rpc/node_call_types.h, src/node/rpc/node_frontend.h, src/node/rpc/serialization.h, src/service/genesis_gen.h, tests/config.jinja, tests/e2e_operations.py, tests/infra/remote.py, tests/recovery.py
- [Add arbitrary service data (#3997)](https://github.com/microsoft/CCF/pull/3997)
=> [release/2.x] Cherry pick: Add arbitrary service data (#3997)

.daily_canary, CMakeLists.txt, python/ccf/_versionifier.py, python/setup.py, tests/infra/consortium.py, tests/infra/node.py, tests/lts_compatibility.py
Same as https://github.com/microsoft/CCF/pull/4003 but on `main`.
=> Infra: Fix node version detection

doc/architecture/raft_tla.rst
The previous link is now dead so the doc is now pointing to the TLA+ website index instead.
=> Docs: Fix TLA+ link

.daily_canary, tests/code_update.py, tests/lts_compatibility.py, tests/reconfiguration.py
Potential fix for https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=47460&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=3aae4c9d-f0dc-5b97-1b0e-f86312395af9&l=28107
Follow-up from https://github.com/microsoft/CCF/pull/3971. We need to wait for a transaction to be committed by the new leader before proceeding.
=> Infra: Fix LTS test commit stuck

.azure-pipelines-gh-pages.yml, .azure-pipelines-quictls.yml, .azure-pipelines-v8.yml, .azure-pipelines.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml, CHANGELOG.md, cmake/cpack_settings.cmake
=> Upgrade to Open Enclave 0.18.1

js/ccf-app/src/converters.ts, js/ccf-app/src/global.ts, js/ccf-app/src/historical.ts, js/ccf-app/src/kv.ts, js/ccf-app/typedoc.json
Some links that Typedoc failed to resolve, I think because of some ambiguous `CCF` name? Fixed by explicit module references.
=> Fix warnings in Typedoc build

.azure-pipelines-gh-pages.yml, .azure-pipelines-quictls.yml, .azure-pipelines-v8.yml, .azure-pipelines.yml, .daily.yml, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml, CHANGELOG.md, cmake/cpack_settings.cmake
- [Upgrade to Open Enclave 0.18.1 (#4023)](https://github.com/microsoft/CCF/pull/4023)
=> [release/2.x] Cherry pick: Upgrade to Open Enclave 0.18.1 (#4023)

src/consensus/aft/test/driver.h, src/ds/test/thread_messaging.cpp, src/ds/thread_messaging.h, src/enclave/main.cpp
I don't think we should be calling this externally, as it implies an owning/responsible system. Instead we can cleanup when the static instance is destroyed to avoid leaks.
=> Drop tasks in `ThreadMessaging` destructor

doc/build_apps/logging.rst
Make it clear that verbose logging in application must be manually enabled, and is distinct from framework verbosity.
=> Clarify documentation on verbose logging

include/ccf/service/code_digest.h, src/ds/files.h, src/node/historical_queries_adapter.cpp, src/service/tables/node_signature.h
- If the default copy constructor is defined manually and the copy assignment operator is used, then the latter also needs to be defined.
- The constructor for std::span with statically defined extent (via the template argument) has been made `explicit` so .
- Changes to the type of `std::filesystem::path` make it so that it is not default formattable by fmtlib, it needs the `fmt/ostream.h` header.
=> Improved compatibility for clang-12 and clang-13

include/ccf/tx.h
This patch changes to comments about Key-Value Store API.
This PR is related to issue #4055.
>/** Get a **read-write** handle by map name. Map type must be specified
to
>/** Get a **write-only** handle by map name. Map type must be specified
Thanks.
=> <docs>[kvStoreAPI]: correct the comments in WriteOnlyHandle

doc/build_apps/run_app.rst
It's been a while since the `sandbox.sh` script started to listen on `127.0.0.1:8000` by default but these samples hadn't been updated.
=> Docs: change sandbox address to default `127.0.0.1:8000`

doc/conf.py
These links (automatically generated by the OpenAPI Sphinx extension) have become flaky lately, e.g.: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=48244&view=logs&j=f1fd332c-cd58-5ba4-fc7d-3c1d3a3f0cd3&t=31418c00-d4df-5619-e99a-3cbbc8fcc481&l=537 so we now ignore them.
=> Docs: ignore link check for RFC2616

tests/infra/github.py
Resolves #4090 
The LTS compatibility test deduces the version(s) with which to test compatibility based on the name of the local branch/tag. However, the backport GitHub Action automatically creates a branch prefixed with `backport/` to backport the changes (see for example [here](https://github.com/microsoft/CCF/pull/4086)), which breaks the assumptions of the LTS compatibility, which will always run the LTS compatibility test as if it was run on `main` (i.e. skipping compatibility test with the previous LTS). 
This PR fixes this, so that the `backport/` prefix is ignored by the LTS compatibility test.
=> Infra: Ignore `backport` prefix in branch name in LTS test

src/indexing/test/indexing.cpp
The unit tests for multi-threaded indexing added in #4075 are occasionally failing, as the watchdog timer identifies that the test has been running for more than 10s. This may be a deadlock, or an unusually unlucky/slow run.
Decorating these tests with `may_fail(true)`, so they are still run but won't cause a test failure when they fail. Will investigate the failure in more detail at a later date.
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=48310&view=logs&j=e982d093-d12a-5a2d-1a1d-0c6d38b8823f&t=8be5454d-0d8f-51e4-7372-58df022e9ebc&l=441
```
18: Test command: /__w/1/s/build/indexing_test
18: Test timeout computed to be: 10000000
18: terminating with uncaught exception of type doctest::detail::TestFailureException
18: [doctest] doctest version is "2.4.8"
18: [doctest] run …
```
=> Mark multi-threaded indexing tests as `may_fail`

include/ccf/endpoint_context.h, samples/apps/logging/logging.cpp, src/endpoints/endpoint_registry.cpp, src/http/http_builder.h, src/node/rpc/frontend.h, src/node/rpc/test/frontend_test.cpp
- [Re-execute auth policies on conflict (#4102)](https://github.com/microsoft/CCF/pull/4102)
=> [release/2.x] Cherry pick: Re-execute auth policies on conflict (#4102)

CHANGELOG.md, include/ccf/rpc_context.h, src/endpoints/endpoint_registry.cpp, src/node/rpc/rpc_context_impl.h, src/node/rpc/test/frontend_test.cpp
- [Add a method that decodes path parameters (#4126)](https://github.com/microsoft/CCF/pull/4126)
=> [release/2.x] Cherry pick: Add a method that decodes path parameters (#4126)

getting_started/setup_vm/roles/openenclave/vars/common.yml
To be tagged as `ccf_ci_image/oe-0.18.2-0`.
=> Update playbooks to use OE 0.18.2

.azure-pipelines-gh-pages.yml, .azure-pipelines-quictls.yml, .azure-pipelines-v8.yml, .azure-pipelines.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml, CHANGELOG.md, cmake/ccf_app.cmake, cmake/cpack_settings.cmake
Manual backport of #4134.
(Re-creation of #4135, which fails `lts_compatibility` test due to branch name)
=> [release/2.x] Cherry pick: Upgrade to OpenEnclave 0.18.2 (#4134)

CMakeLists.txt, src/common/enclave_interface_types.h, src/ds/ring_buffer.h, src/enclave/enclave_time.cpp, src/enclave/enclave_time.h, src/enclave/main.cpp, src/host/enclave.h, src/host/time_updater.h, src/node/test/channels.cpp
Manual backport of #4127.
Includes some refactoring/re-implementation, due to the lack of PAL in 2.x branch.
=> [release/2.x] Cherry-pick: Mitigations for potential stale reads from Legacy xAPIC (#4127)

python/ccf/ledger.py
Assertions of state transitions in `ledger.py` didn't handle recoveries started during an existing recovery.
=> Update `ledger.py` to handle multiple recoveries

doc/governance/adding_member.rst
Minor changes after some customer interactions.
1. Use a JSON file to save and send the request digest (eliminates manual copying for convenience).
2. `--data-binary '{"state_digest": <...>}'` seems to work inconsistently, maybe because the content length is slightly different based on the system...?
3. Add note on how to verify activation of the member.
=> Update docs for activating a member

doc/build_apps/example_cpp.rst, doc/schemas/app_openapi.json, include/ccf/actors.h, samples/apps/logging/logging.cpp, src/endpoints/endpoint_registry.cpp, src/http/http2_endpoint.h, src/http/http_endpoint.h, src/http/http_rpc_context.h, tests/connections.py, tests/e2e_logging.py, tests/nobuiltins.py, tests/recovery_benchmark.sh, tests/test_install.sh
Resolves #3893 
This change will allow applications to use endpoints as defined when creating them i.e. an endpoint created at `/log/private`
will be available at `/log/private` without the additional prefix of `/app/`. The reference openapi schema now reflects this change.
This change will also allow existing (and new) applications to continue using and calling with `/app/` prefix as well.
TODO:
=> Remove hardcoded prefix `/app` for application endpoints

tests/governance.py, tests/infra/github.py
Flagged by Pylint since v2.15.0. Seems sensible to add a small timeout to these calls. All our wrapped CCF client calls already include a timeout.
=> Add timeouts to raw requests calls

getting_started/setup_vm/ccf-dev.yml, getting_started/setup_vm/roles/ccf_build/vars/common.yml, getting_started/setup_vm/roles/protoc/tasks/install.yml, getting_started/setup_vm/roles/protoc/vars/common.yml
This is required by the [external executor app](https://github.com/microsoft/CCF/tree/main/src/apps/external_executor), as well as any built-in apps that want to support gRPC.
=> Add `protoc` to `ccf-ci` image

include/ccf/ds/nonstd.h, include/ccf/http_consts.h, include/ccf/rpc_context.h, src/apps/external_executor/external_executor.cpp, src/http/http2.h, src/http/http2_endpoint.h, src/http/http2_types.h, src/http/http_rpc_context.h
Pretty barebones at the moment, but sufficient for setting the `grpc-response` trailer required by gRPC clients.
I think technically we should only be inserting response trailers if a `te: trailers` header was received in the request, and not everything requires the `trailer:` response header, but we can revisit those if they cause problems.
=> Add support for setting HTTP/2 trailing headers

include/ccf/kv/map_handle.h
Fixing line break midway through a code sample in docs. See image below
=> Removing a line break from map_handle.h

cmake/common.cmake
The protobuf cmake that is included since #4181 adds some unhelpful `message()`s to our CMake output - an empty line for some missing version, and a version with no prefix. It'd be fine if they indicated they were about protobufs, or were only enabled by a flag (all the cmake file's _other_ logging is gated by `protobuf_VERBOSE`, I don't know why this isn't).
If we were on CMake 3.17, we could at least add some [context](https://cmake.org/cmake/help/latest/variable/CMAKE_MESSAGE_CONTEXT.html#variable:CMAKE_MESSAGE_CONTEXT) ourselves to prefix these lines, but we're not.
This approach is taken from [here](https://stackoverflow.com/a/38983571/747433), and mutes _all_ logging by the included cmake. This isn't ideal - I'd still like logs if there are errors! But assuming we continue with no …
=> Silence messages from protobuf cmake

.azure-pipelines-templates/cmake.yml, .azure-pipelines-templates/common.yml, .azure-pipelines-templates/platform.yml, CHANGELOG.md, cmake/common.cmake, samples/scripts/sgxinfo.sh, samples/scripts/snpinfo.sh
Revert some of the changes done in #4184 so that we have two different scripts, one for SGX and one for SEV-SNP.
=> Add `snpinfo.sh` script

getting_started/setup_vm/app-dev.yml
So that developers using the `https://mcr.microsoft.com/ccf/app/dev/` image can use `protoc` out of the box.
=> Add `protoc` to app dev Docker image

.daily_canary, src/endpoints/endpoint_registry.cpp, src/node/rpc/test/frontend_test.cpp, tests/e2e_logging.py
Fixing a bug introduced by #4205.
Also adding test cases to catch this regression faster in future, in both unit and e2e tests.
=> Fix daily build: Empty URIs should return a 404

samples/constitutions/operator/resolve.js
In the sample `resolve.js` for operators, `isOperator` can throw an exception if a member is defined without member data as member data field access was unconditional (i.e. `info.member_data.is_operator` without checking if `info.member_data` is defined). Further, `isRecoveryMember` checks if the member has a public encryption key, but the public encryption key is not a field in member data.
=> Fix operator resolve.js to not throw on undefined member data

.azure-pipelines-templates/daily-matrix.yml
We specify these `COMPILER_LAUNCHER` args in `matrix.yml`, but not `daily-matrix.yml`. The result is that although we mounted a useful shared drive for cached build results for Daily builds, we never actually used it.
=> Use ccache to speed up Daily build

CHANGELOG.md, samples/constitutions/default/actions.js, tests/e2e_logging.py, tests/recovery.py
Fixes #4229.
Our sample constitution had an incorrect implementation of `set_user`, which didn't nest `user_data` in the same object type that other actions (`set_user_data`) did, and the C++ parsers expect.
So this proposal:
```
{
"actions": [
{
"args": {
"user_id": "12689d4e3997db1e8d7635c83d1c5955e35edaf3a1398ec163d10c145b03bb42",
"user_data": {
"hello": "world"
}
},
"name": "set_user_data"
}
]
}
```
Would (when it passes) result in this write to the ledger:
```
table "public:ccf.gov.users.info" (1 write):
12689d4e3997db1e8d7635c83d1c5955e35edaf3a1398ec163d10c145b03bb42:
{
"user_data": {
"hello": "world"
}
}
```
But this proposal:
```
{
"actions": [
{
"args": {
"cert": "-----BEGIN CERTIFICATE-----\nMIIBsTCCATigAwIBAgIURSeMI2U1egZEjwwwms/OxH24hGMwCgYIKoZIzj0EAwMw\nEDEOMAwGA1UEAwwFdXNlcjA …
```
=> Fix set user metadata nesting

src/enclave/forwarder_types.h, src/node/node_types.h, src/node/rpc/forwarder.h, src/node/rpc/test/frontend_test.cpp
- [Parse new versions of forwarded request (#4185)](https://github.com/microsoft/CCF/pull/4185)
=> [release/2.x] Cherry pick: Parse new versions of forwarded request (#4185)

tests/start_network.py
Minor addition to the existing `sandbox.sh` script: it is sometimes useful to be able to start the script and automatically shut down after the service is successfully open, for example when app developers run this script as part of their CI.
=> Add option to automatically shut down `sandbox.sh`

.gitignore
Context for this: I had to make some changes to the VSCode auto-generated `c_cpp_properties.json` file and this change was being picked up by git. We already ignore couple of other files under .vscode currently, just applying this broadly now to all files under .vscode
=> Add .vscode files to git ignore

doc/build_apps/run_app.rst
Following feedback from @MahatiC about the ambiguous use of "distributed".
=> Clarify documentation

cmake/protobuf.cmake
Using `LIBPROTOBUF_INCLUDE_DIRS` in the `BUILD_INTERFACE` somehow meant that this interface was also present in the final install, preventing apps to use `libprotobuf` included in the CCF debian package.
=> Fix `libprotobuf` install

doc/build_apps/example_cpp.rst, samples/apps/logging/logging.cpp
It fixes the page https://microsoft.github.io/CCF/main/build_apps/example_cpp.html .
Current:
The right-hand side of the assignment to `records_handle` is missing. 
After the fix
Run `livehtml.sh` locally and see if the doc looks correct.
=> Fix table access snippet in the doc

.azure-pipelines-templates/configure.yml, CHANGELOG.md, CMakeLists.txt, cmake/protobuf.cmake
This is required for the new `libprotobuf` dependency.
=> Also install `.inc` files

python/requirements.txt
The current pin blocks the tests from passing on release/2.x.
=> Upgrade cryptography pin

CHANGELOG.md, samples/constitutions/default/actions.js, tests/e2e_logging.py
- [Fix set user metadata nesting (#4231)](https://github.com/microsoft/CCF/pull/4231)
=> [release/2.x] Cherry pick: Fix set user metadata nesting (#4231)

src/host/enclave.h
We fail during enclave initialisation if this is misaligned, but rely on `std::string` storage to actually provide this allocation. While this has worked on our test machines, it is not guaranteed in any way.
Instead we use `std::aligned_alloc` to provide the memory for the padded config, and now copy regardless of whether additional padding was required.
=> Ensure `ccf_config` arg is properly aligned

src/host/enclave.h
- [Ensure `ccf_config` arg is properly aligned (#4272)](https://github.com/microsoft/CCF/pull/4272)
=> [release/2.x] Cherry pick: Ensure `ccf_config` arg is properly aligned (#4272)

doc/schemas/app_openapi.json, doc/schemas/gov_openapi.json, doc/schemas/node_openapi.json, include/ccf/ds/openapi.h, samples/apps/logging/logging.cpp, src/endpoints/endpoint_registry.cpp, src/node/rpc/member_frontend.h, src/node/rpc/node_frontend.h
Resolves #2004
Tasks
~- [ ] Define API to enable per endpoint error schema definition~
This PR is a WIP, just pushing this whilst I work on something else (and also the last task above is pending discussion) 
Edit: Last task will be in a different PR
=> Add error schema to openapi definition

tests/infra/commit.py, tests/infra/consortium.py
This is basically #4283, but also modifying the timeout in `consortium.vote_using_majority()`. Evidence this works is the [green run](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=50379&view=results) of #4285 (which includes the core timeout change, and also a bunch of hacks to the CI to run the failing test in a loop).
Still don't have a complete story on why this test, and this test only, is newly slower, so consider this a mitigation rather than a total fix.
=> Increase `wait_for_commit` timeouts to workaround `lts_compatibility` failures

tests/infra/commit.py, tests/infra/consortium.py
- [Increase `wait_for_commit` timeouts to workaround `lts_compatibility` failures (#4286)](https://github.com/microsoft/CCF/pull/4286)
=> [release/2.x] Cherry pick: Increase `wait_for_commit` timeouts to workaround `lts_compatibility` failures (#4286)

python/utils/scurl.sh
I think CRLF line endings will make `scurl.sh` unexecutable (it certainly does for Ubuntu's bash), but just in case we make sure that we don't produce the wrong TBS string.
=> Ensure LF line returns are used in construction of scurl's To-Be-Signed string

doc/schemas/app_openapi.json, include/ccf/endpoint.h, samples/apps/logging/logging.cpp, src/endpoints/endpoint.cpp, src/endpoints/endpoint_registry.cpp, src/node/rpc/frontend.h
This is an attempt to work around the `lts_compatibility` test (see https://github.com/microsoft/CCF/pull/4168) and may end up resolving https://github.com/microsoft/CCF/issues/4292
=> Remove `app` prefix from API docs

src/node/quote_endorsements_client.h
Follow-up from #4277 
The resilience added to the attestation endorsements client meant that some races could occur between the watchdog task and the handler for the response. These two races (a) timing out too many times, b) receiving a response after having timed out too many times) are now fixed.
=> Fix client endorsements fetching logic

3rdparty/exported/quickjs/quickjs-time.h, src/js/wrap.cpp, tests/js-api/app.json, tests/js-api/src/endpoints.js, tests/js-custom-authorization/custom_authorization.py
Our stubs for QuickJS's `gettimeofday` functions weren't clearing the passed value, so were relying on uninitialized data.
Beyond that, we don't actually want to rely on `gettimeofday` to seed the random state, which is the implementation of `Math.random()` that QuickJS uses. Instead we overwrite this function entirely with our own implementation, which uses our existing in-enclave `Entropy`.
Includes an end-to-end test that tries to ensure we don't see the same sequence of numbers from this, across calls or network restarts.
=> Fix implementation of `Math.random()` in JS interpreter

js/ccf-app/src/converters.ts, js/ccf-app/test/kv.test.ts
Resolves #4326.
If the calling TypeScript has used `any` or other kinds of type erasure, they may actually pass us a key or value of completely the wrong type. Rather than encoding junk, we now throw a `TypeError`.
=> Enforce type of arg in TS DataConverter.convert

CHANGELOG.md, include/ccf/crypto/curve.h, js/ccf-app/src/global.ts, js/ccf-app/test/polyfill.test.ts, src/crypto/openssl/public_key.cpp, src/crypto/test/bench.cpp, src/crypto/test/crypto.cpp, src/js/crypto.cpp, tests/infra/crypto.py, tests/js-modules/modules.py
Issue: #4319
- Allow to pass 'secp256k1' to [`generateEcdsaKeyPair()`](https://microsoft.github.io/CCF/main/js/ccf-app/functions/crypto.generateEcdsaKeyPair.html). [`verifySignature()`](https://microsoft.github.io/CCF/main/js/ccf-app/functions/crypto.verifySignature.html) should be able to verify signatures made with secp256k1.
Note: I only changed codes related to JS crypto API. So files like `src/node/acme_client.h` is not edited.
=> Add secp256k1 to the JS crypto API

cmake/ccf-config.cmake.in, cmake/ccf_unsafe-config.cmake.in, cmake/common.cmake, cmake/tools.cmake
In order for this to work, we need a few things:
- Install the ubsan.suppressions file
- Change the add_san function to point to the correct location, based on whether it is called on a CCF library or downstream app.
- Persist the value of the SAN option in ccf-config.cmake, so it gets picked up when importing CCF in downstream projects.
=> Allow applications to be built with sanitizers enabled.

.azure-pipelines-templates/stress-matrix.yml
This pipeline hasn't been running for a few days, because
=> Re-enable `CCF Github Stress` pipeline

include/ccf/ds/json_schema.h, include/ccf/pal/hardware_info.h
Importing these files throw an error during compilation because of the following missing headers.
=> add missing headers required when including files for certain options

.azure-pipelines-templates/install_deb.yml
This fixes the current failure in the Daily pipeline where two identical artefacts are published in the same pipeline.
=> CI: Do not publish debian package for SGXIceLake

.azure-pipelines-templates/install_deb.yml, getting_started/setup_vm/roles/ccf_build/vars/common.yml
CodeQL is failing because Doxygen v1.9.5 is out, and the previous v1.9.4 we were using is no longer present.
We already had to fix this in #3823. Rather than bumping the version, I think we should just download from SourceForge, which should host old versions for longer.
=> Download Doxygen from SourceForge to keep v1.9.4

CHANGELOG.md
Part of #4419 
Because this is a new major release, we aggregate the changelog accumulated on all `3.0.0-devX` releases so that users are presented with all relevant changes at once if they never upgraded to any intermediate `3.0.0-devX` release.
=> Aggregate `3.0.0-rc0` changelog

tests/infra/runner.py
This should get rid of the empty flat graphs here:
=> Don't upload empty metrics

doc/conf.py
The fix for the type warning in #4445 caused an undesired behaviour change in the doc build.
=> Fix smv filter

.azure-pipelines-templates/cimetrics.yml, .azure-pipelines-templates/common.yml
Implementing https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#ive-got-a-conditional-step-that-runs-even-when-a-job-is-canceled-how-do-i-manage-to-cancel-all-jobs-at-once
=> Tentative autoCancel fix

js/ccf-app/src/polyfill.ts, js/ccf-app/test/polyfill.test.ts
It resolves #4426 partially.
The actual implementation already exists.
=> Add EdDSA support for verifySignature() in polyfill

.stress.yml
Bring job in line with multi-threading: only trigger on direct job definition change. Includes get picked up post-merge to main. This is especially useful at the moment, with the churn in .azure-pipelines-templates.
=> Narrow down trigger for Stress job

getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml
We now install each Debian package under a different path `/opt/ccf_$platform` so the playbooks that build the runtime containers need to be updated accordingly.
=> Fix containers job for `3.0.0-rc1`

.github/workflows/npm.yml, .github/workflows/pypi.yml
pip shortens "3.0.0-rc1' to '3.0.0rc1' it seems, and for npm the only difference I can see is the directory, which perhaps makes finding package.json fail?
=> More script pkg fixes

getting_started/setup_vm/ccf-dev.yml, getting_started/setup_vm/roles/perf-tool/tasks/install.yml, getting_started/setup_vm/roles/perf-tool/vars/common.yml
The new performance tool is partly written in C++ and in Python. The component that will submit requests (and is not yet PRed) is written in C++. There are a few libraries that are required for the submitter component and they are installed through ansible. For this reason a new playbook under the directory `getting_started/setup_vm/roles/perf-tool` is created to be installed in addition to a yaml file containing the variable of the temporary folder to download the debian.
The installation of this playbook will be triggered by the `ccf-dev.yml` as this will be a part of the development.
The libraries that will be installed are arrow which is required for the libarrow and libparquet -dev containing the cpp headers, as well as the libstdc++-11-dev .
=> add a playbook to install perf tool dependencies

perf-system/generator/generate_packages.py
While making the suggested changes on the generator-pr, I missed an empty line on the arg parsing options, which very cunningly escaped my tests. As a result, when one wants to generate requests using command line options, the script would break.  This PR resolves this issue.
=> Remove empty line in generator, breaking the command line run

.azure-pipelines-templates/daily-matrix.yml, .azure-pipelines-templates/matrix.yml, .azure-pipelines-templates/stress-matrix.yml, .multi-thread.yml
- [Use new IceLake SGX pool for Azure DevOps (#4440)](https://github.com/microsoft/CCF/pull/4440)
=> [release/2.x] Cherry pick: Use new IceLake SGX pool for Azure DevOps (#4440)

doc/contribute/release_ccf.rst
Update to the CCF technical document (https://microsoft.github.io/CCF/main/contribute/release_ccf.html#labelling-lts-prs) to include detailed backporting labelling process.
=> Include detailed backporting process to the doc

doc/architecture/tls_internals.rst, doc/audit/receipts.rst, doc/build_apps/build_app.rst, doc/build_apps/example_cpp.rst, doc/use_apps/verify_tx.rst
Noticed a few cases in the docs where we were using the wrong kind of backticks. In `ReStructuredText`, we need to use single backticks (\`) for _italics_ (an underscore \_ in Markdown), and double backticks (``) for `monospace` (a single backtick \` in Markdown).
=> Docs emphasis fixes

getting_started/setup_vm/roles/intel/vars/common.yml
This is a fix for the `lts_compatibility` issue created by the update to Open Enclave 0.18.4. 
Open Enclave no longer pulls `libsgx-dcap-ql-dev` (see https://github.com/openenclave/openenclave/commit/70ceead69f55a99755e02b90e53648446f8006bf). This is fine for new nodes built against OE 0.18.4 but not OK for older nodes (e.g. 2.0.8) built against OE 0.18.2 that still expect to dynamically find `libsgx-dcap-ql-dev` at enclave creation.
=> Explicitly add `libsgx-dcap-ql-dev` to PSW

src/enclave/main.cpp
Because the enclave logger makes use of the ring buffer, we cannot log an error before we've checked that the ring buffer bounds are not in enclave memory so this PR moves the `is_outside_enclave` check early.
=> Move ring buffer bound check early

.azure-pipelines-gh-pages.yml, .azure-pipelines-quictls.yml, .azure-pipelines.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml, CHANGELOG.md, cmake/ccf_app.cmake, cmake/cpack_settings.cmake
- [Upgrade Open Enclave from 0.18.2 to 0.18.4 (#4510)](https://github.com/microsoft/CCF/pull/4510)
=> [release/2.x] Cherry pick: Upgrade Open Enclave from 0.18.2 to 0.18.4 (#4510)

.azure-pipelines-templates/install_deb.yml, getting_started/setup_vm/roles/ccf_build/vars/common.yml
- [Download Doxygen from SourceForge to keep v1.9.4 (#4432)](https://github.com/microsoft/CCF/pull/4432)
=> [release/2.x] Cherry pick: Download Doxygen from SourceForge to keep v1.9.4 (#4432)

include/ccf/crypto/eddsa_key_pair.h, js/ccf-app/src/crypto.ts, src/crypto/eddsa_key_pair.cpp, tests/js-modules/modules.py
Closes #4426 
Currently some functions don't show the doc correctly.
example:
https://microsoft.github.io/CCF/main/js/ccf-app/functions/crypto.generateEcdsaKeyPair.html
This PR fixes it.
```bash
cd js/ccf-app && npm run docs # it generates html files
```
=> Miscellaneous improvements in crypto API

tests/governance.py, tests/governance_js.py, tests/infra/member.py, tests/infra/remote.py
These changes managed to get the `liblogging.virtual.so` working through ssh for me.
For running (from the `build` dir): `../tests/sandbox/sandbox.sh -p samples/apps/logging/liblogging.virtual.so --node ssh://0.0.0.0:8000,<hostname>:8000 -v`
=> Sandbox ssh fixups

src/consensus/aft/test/committable_suffix.cpp, src/ds/test/oversized.cpp, src/ds/test/ring_buffer.cpp, src/indexing/test/indexing.cpp, src/indexing/test/lfs.cpp, src/kv/test/kv_contention.cpp, src/node/test/channels.cpp, src/node/test/historical_queries.cpp
Related to #4558.
I have a habit of writing smoky unit tests with a random seed. The problem is if those fail extremely rarely, we can't repro the failure. We should always log these seeds. Sometimes these then spin up multiple threads, so we still have non-deterministic and potentially non-reproducible runs, but logging the seed should at least help narrow down the issue.
=> Log seeds used in unit tests

include/ccf/byte_vector.h
Previously bytevectors were logged as text as long as they didn't contain null bytes. This could cause crashes if verbose logging in the enclave was enabled, the host used the JSON logger and the application wrote binary data to the KV. The log messages would contain invalid Unicode sequences, which made the JSON logger crash when trying to embed the message as a string field.
=> Only render bytevectors as text if all characters are printable.

.azure-pipelines-templates/platform.yml, .azure-pipelines.yml
Remove the hardcoded group creation of sgx_prv with 119, fetch the owner of /dev/sgx_provision instead.
Same as https://github.com/microsoft/scitt-ccf-ledger/pull/16
=> Try to get the correct group ID

.azure-pipelines-templates/cmake.yml
- [Try to get the correct group ID (#4575)](https://github.com/microsoft/CCF/pull/4575)
=> [release/2.x] Cherry pick: Try to get the correct group ID (#4575)

.azure-pipelines-templates/cmake.yml, .azure-pipelines-templates/common.yml
I was too keen to merge https://github.com/microsoft/CCF/pull/4577 and did not realise that the previous fix was not guarded by the target platform on the `release/2.x` branch, which breaks the CI pipeline.
=> [release/2.x] Fix virtual CI `sgx_prv` group

CHANGELOG.md, include/ccf/odata_error.h, include/ccf/rpc_context.h, src/enclave/forwarder_types.h, src/enclave/rpc_sessions.h, src/enclave/session.h, src/enclave/tls_session.h, src/http/http2_session.h, src/http/http_session.h, src/node/node_types.h, src/node/rpc/forwarder.h, src/node/rpc/frontend.h, src/node/rpc/rpc_context_impl.h, src/quic/quic_session.h, tests/e2e_tutorial.py, tests/infra/clients.py, tests/infra/commit.py, tests/infra/logging_app.py, tests/infra/network.py, tests/infra/node.py, tests/lts_compatibility.py, tests/partitions_test.py
Manual cherry-pick backport of #4595.
NB: This is still just the parsing component, and needs a follow-up PR (on `main` and `release/3.x`) which actually enables the behaviour.
=> [release/3.x] Cherry pick: Session consistency: Parse forwarded messages with consistency info (#4595)

.github/workflows/containers.yml, .github/workflows/pypi.yml, getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml
- [Fix containers and PyPi release workflows (#4607)](https://github.com/microsoft/CCF/pull/4607)
=> [release/3.x] Cherry pick: Fix containers and PyPi release workflows (#4607)

doc/architecture/raft_tla.rst
The CCF spec is pure TLA+.  Thus, no need to see or learn PlusCal.
=> Point to TLA+ documentation that doesn't confuse learners with PlusCal.

src/ubsan.suppressions
QCBOR has a bug which can cause memmove to be called with a NULL source argument (and zero size), which is technically undefined behaviour and triggers a UBSan violation.
This bug cannot be reached by CCF's use of QCBOR (it mostly occurs when encoding messages, which CCF doesn't do), but it affects downstream application which use QCBOR themselves and are forced to use the copy of the library provided by CCF.
https://github.com/laurencelundblade/QCBOR/issues/164
=> Add a UBSan suppression for QCBOR.

.github/workflows/github-projects.yml
Removing the line to automatically add PRs to the project board. Eddy found out that this seems to be a known issue (https://github.com/actions/add-to-project/issues/93) and because the PRs are from forks, dependabot can't read `secrets`. Not a high priority to add PRs automatically so removing this line.
=> Remove the line to add PRs

doc/operations/troubleshooting.rst, src/host/main.cpp
Explain info message we've logged from 2.0.2 until now, and restore SIG_IGN.
=> Restore SIG_IGN handler

CHANGELOG.md, include/ccf/crypto/verifier.h, src/kv/test/kv_snapshot.cpp, src/node/channels.h, src/node/test/channels.cpp, tests/infra/clients.py, tests/infra/node.py, tests/partitions_test.py
- [Remove unintended time checks from node-to-node validation (#4733)](https://github.com/microsoft/CCF/pull/4733)
=> [release/3.x] Cherry pick: Remove unintended time checks from node-to-node validation (#4733)

CHANGELOG.md, include/ccf/crypto/verifier.h, src/node/channels.h, src/node/test/channels.cpp, tests/infra/clients.py, tests/infra/node.py, tests/partitions_test.py
- [Remove unintended time checks from node-to-node validation (#4733)](https://github.com/microsoft/CCF/pull/4733)
=> [release/2.x] Cherry pick: Remove unintended time checks from node-to-node validation (#4733)

tests/partitions_test.py
Failures seem to take place, but post-failure diagnostics show nodes agreeing about the primary post-failure.
Edit: this is not because the timeout choice was unlucky, but because the view boundary was too strong: the comparison is strict.
=> Update minimum view on partition test

CHANGELOG.md, include/ccf/ds/logger.h, src/ds/champ_map.h, src/ds/map_serializers.h, src/ds/rb_map.h, src/ds/test/map_test.cpp, src/kv/test/kv_snapshot.cpp, src/kv/untyped_map.h, tests/partitions_test.py
- [Fix issues with snapshot generation for CHAMP (#4730)](https://github.com/microsoft/CCF/pull/4730)
=> [release/3.x] Cherry pick: Fix issues with snapshot generation for CHAMP (#4730)

.daily_canary, CHANGELOG.md, include/ccf/ds/logger.h, src/ds/champ_map.h, src/ds/map_serializers.h, src/ds/rb_map.h, src/ds/test/map_test.cpp, src/kv/untyped_map.h, tests/partitions_test.py
- [Fix issues with snapshot generation for CHAMP (#4730)](https://github.com/microsoft/CCF/pull/4730)
=> [release/2.x] Cherry pick: Fix issues with snapshot generation for CHAMP (#4730)

doc/overview/glossary.rst
Failure: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=58246&view=logs&j=f1fd332c-cd58-5ba4-fc7d-3c1d3a3f0cd3&t=f54bbde7-05c8-5993-df05-3aa12461823d&l=592
=> Docs: Fix broken SGX link

src/node/test/channels.cpp
Resolves #4738.
Non-critical, but will save some headaches the next time we add a unit test here.
=> `channels_test`: Remove order-dependent use of global state

.github/workflows/github-projects.yml
Add pull_request_target to GH project to allow fork PR access to secrets and automatically get added to the board.
=> Add pull_request_target to GH project

getting_started/setup_vm/ccf-dev.yml, getting_started/setup_vm/roles/h2spec/tasks/install.yml, getting_started/setup_vm/roles/h2spec/vars/common.yml
Part of #3342 
This PR adds [`h2spec`](https://github.com/summerwind/h2spec) to the CI image so that we can test CCF's HTTP/2 compliance.
=> Add `h2spec` to CI Docker image

CHANGELOG.md, src/apps/js_generic/oe_sign.conf
- [Increase NumHeapPages for js_generic (#4759)](https://github.com/microsoft/CCF/pull/4759)
=> [release/3.x] Cherry pick: Increase NumHeapPages for js_generic (#4759)

.azure-pipelines-templates/deploy_aci.yml
The check sees a value for pull request id even when run on main, so I've added a step to print the full env and also changed the check to look for the empty string instead
=> Fix the is PR check when deploying an ACI

CHANGELOG.md, src/host/main.cpp, src/node/rpc/node_frontend.h, tests/governance.py, tests/infra/network.py, tests/recovery.py
- [Fix recording of node_data in KV for Start nodes (#4762)](https://github.com/microsoft/CCF/pull/4762)
=> [release/2.x] Cherry pick: Fix recording of node_data in KV for Start nodes (#4762)

CHANGELOG.md, src/host/main.cpp, src/node/rpc/node_frontend.h, tests/governance.py, tests/infra/network.py, tests/recovery.py
- [Fix recording of node_data in KV for Start nodes (#4762)](https://github.com/microsoft/CCF/pull/4762)
=> [release/3.x] Cherry pick: Fix recording of node_data in KV for Start nodes (#4762)

tests/election.py
The election test will occasionally break because the newly elected primary hasn't had time to commit a new transaction, for example here: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=58749&view=logs&j=f3457e4b-102d-5a4f-f801-dc119e4853a8&t=ae98f324-492e-5969-593b-258ede9c5463
The test then proceeds to sample a view history, and assumes further view histories will be subsets of it as it queries, which turns out to be incorrect as a new transaction gets appended in the new term.
Adding a barrier to wait until at least one transaction is committed in a new term (necessarily a signature here) avoids this problem. A --repeat-until-fail 30 is generally enough to trigger the issue, and this one with the fix doesn't:
```
The following tests passed:
election_test
100% tests passed, 0 …
```
=> Fix election test

tests/infra/remote.py
=> Fix binary_dir arg on sandbox ssh remote

doc/schemas/gov_openapi.json, doc/schemas/node_openapi.json, include/ccf/http_configuration.h, src/apps/external_executor/external_executor.cpp, src/enclave/rpc_sessions.h, src/http/http2_callbacks.h, src/http/http2_parser.h, src/http/http2_session.h, src/http/http2_types.h, src/http/http_exceptions.h, src/http/http_parser.h, src/http/http_session.h, src/node/rpc/member_frontend.h, src/node/rpc/node_frontend.h, tests/e2e_common_endpoints.py, tests/e2e_logging.py, tests/infra/clients.py
Part of #3342 
This brings HTTP/2 in line with HTTP/1.1, with maximum request payload and header sizes now being enforced, and parsing errors being reported correctly. 
I've also re-enabled some tests in `e2e_logging.py` that were marked as `no_http2`.
=> HTTP/2: support for configuration and error reporting

include/ccf/odata_error.h, src/http/http2_callbacks.h, src/http/http2_session.h, src/http/http_rpc_context.h, src/http/http_session.h, src/node/rpc/frontend.h, src/node/rpc/rpc_context_impl.h, tests/e2e_logging.py, tests/infra/logging_app.py, tests/infra/member.py
Part of #3342 
As there are no current plans to support client request forwarding for HTTP/2 interfaces, we now return an error for such requests rather than forwarding the request to the primary node and inevitably timing out (as the HTTP/2 response cannot be serialised by the primary node and sent back to the client).
=> HTTP/2: return error for to-be-forwarded requests

.azure_pipelines_snp.yml, .github/workflows/build-ci-container.yml
If we have a day where there are no merges onto main, we never build an image for SNP CI, and since we cleanup images at the end of each day this would mean the regular run on SNP CI has no images to use
Fix is to run the build CI job at the start of each day
Also run CI on every push even if it doesn't touch SNP files so that the regular SNP run will also have the correct image
=> Handle SNP CI on days where there are no merges

tests/election.py
The `election_test` currently waits up to 15 times (`DEFAULT_TIMEOUT_MULTIPLIER` in `network.py`) the election timeout before declaring an election as unsuccessful. This is useful when waiting for elections during/after network partitions, but less so in the last iteration of the election test when we know for sure an election will not converge as we have killed more than `f` nodes. This PR reduces the time waiting for an unsuccessful election in this test only, shaving off 15 secs from the total `ctest` runtime.
=> Reduce time waiting for new primary in election test

tests/election.py
Opening for discussion.
I think there's a risk in #4797 reducing the wait time in non-failing cases to. This may introduce the occasional failures we saw before #4778 applied a uniform election timeout to all instances that we expect to pass.
This is an alternative implementation with the same goal - reduce the amount of time we wait for a new primary _when we expect this wait to fail_, to reduce the total test runtime.
=> Only set low timeouts when we expect `wait_for_new_primary` to fail

tla/install_deps.py
no-op if wget has previously been installed.
=> Install wget if install_deps.py script is executed in default codespace.

tests/reconfiguration.py
The test creates it's own network which currently lives alongside the network created for all other tests
Spun out from #4708 and therefore also contributes to https://github.com/microsoft/CCF/issues/4190
=> Run join_old_snapshot test outside after other network cleanup

.azure-pipelines-templates/deploy_aci.yml
When running the SNP pipeline manually for a PR, the PR id field isn't populated so the pipeline treats it like a run on a non-pr branch, meaning it gets the latest SHA from the merge branch rather than from the merge commit message as expected.
Fix is to look for the merge branch instead
=> Fix running SNP pipeline against PR manually

src/apps/external_executor/protobuf/CMakeLists.txt
CodeQL failing: https://github.com/microsoft/CCF/actions/runs/3902624547/jobs/6665906758#step:6:432
Looks like this dependency is somehow always present with Ninja, but not with Make?
So we could repro with:
```
$ mkdir build.make
$ cd build.make
$ cmake ..
$ make historical.proto.enclave
[  0%] Generate C++ source files from protobuf file historical.proto
Scanning dependencies of target historical.proto.enclave
[  0%] Building CXX object src/apps/external_executor/protobuf/CMakeFiles/historical.proto.enclave.dir/historical.pb.cc.o
In file included from /data/src/1.CCF/build.make/src/apps/external_executor/protobuf/historical.pb.cc:4:
/data/src/1.CCF/build.make/src/apps/external_executor/protobuf/historical.pb.h:31:10: fatal error: 'kv.pb.h' file not found
#include "kv.pb.h"
^~~~~~~~~
1 …
```
=> Add explicit dependency between proto libraries

doc/requirements.txt
`0.8.0` release of `sphinxcontrib.openapi` fails with this old pin, seems to build successfully when unpinned.
Link to failing run here: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=60545&view=logs&j=f1fd332c-cd58-5ba4-fc7d-3c1d3a3f0cd3&t=f54bbde7-05c8-5993-df05-3aa12461823d&l=189
=> Unpin mistune

3rdparty/exported/quickjs/quickjs-time.h, 3rdparty/exported/quickjs/quickjs.c, CHANGELOG.md, doc/build_apps/js_app_bundle.rst, js/ccf-app/src/global.ts, js/ccf-app/src/polyfill.ts, src/js/wrap.cpp, src/js/wrap.h, tests/js-api/app.json, tests/js-api/src/endpoints.js, tests/js-custom-authorization/custom_authorization.py
- [Add `enableUntrustedDateTime` to JS API (#4838)](https://github.com/microsoft/CCF/pull/4838)
=> [release/3.x] Cherry pick: Add `enableUntrustedDateTime` to JS API (#4838)

.azure-pipelines-attestation-container.yml, .azure-pipelines-templates/azure_cli.yml, .azure-pipelines-templates/deploy_attestation_container.yml, scripts/azure_deployment/arm_aci.py
Since https://github.com/microsoft/CCF/pull/4840, we rely on a Python virtual environment to install the specific and recent versions of the Azure Python SDK libraries. These also need to be installed before running the `arm_template.py` script in the Attestation Container CI. 
Also reenabled deployment of attestation container that was nuked by a merge conflict in #4840
=> Python virtual environment for Attestation Container CI

.azure-pipelines-templates/deploy_attestation_container.yml
Fix a bug found in https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=60945&view=logs&j=8475f160-5334-5e18-a167-ddf3956b7080&t=27153a35-fbab-5bbd-ba43-b73eac114b6d.
Previously the image deletion command was:
```bash
az acr repository delete --name attestationcontainerregistry --image attestation-container: --yes # image tag is missing
```
Now:
```bash
az acr repository delete --name attestationcontainerregistry --image attestation-container:<tag> --yes
```
As discussed [here](https://github.com/microsoft/CCF/pull/4694#discussion_r1068269446), this code will be changed again soon, but it's a temporary fix to prevent the failure
=> Fix azure pipeline variable

include/ccf/http_responder.h, src/node/acme_client.h
This adds support for external service CSRs in the ACME client. This is required when ACME requests are run on behalf of another node (e.g. in aDNS).
=> Add support for external service CSRs in ACME client

.azure-pipelines-templates/deploy_aci.yml, .azure-pipelines-templates/install_ssh_key.yml, .azure-pipelines-templates/test_on_remote.yml, .azure_pipelines_snp.yml
This will allow multiple concurrent jobs to use the same SSH key without one having to wait on the other
Specifically, useful for when we deploy secondary ACIs and want to install the key on those machines without having to wait on primary deployment
=> Separate SSH key generation into independent job

tests/requirements.txt
This is only used for testing, but flagged by CG because of https://security-tracker.debian.org/tracker/CVE-2021-41945.
=> Upgrade httpx pin on release/2.x

CHANGELOG.md
Addresses https://github.com/microsoft/CCF/pull/4882#discussion_r1085314765, which I'd missed. The branch protection rule for `release/*` has been adjusted so this can't happen again. Add entry for 3.0.5.
=> 3.0.5 release notes

CHANGELOG.md, cmake/preproject.cmake
We should have done this early in the 2.x cycle, but we seem to have forgotten.
=> Raise clang version requirement to 10

tests/infra/remote.py
The output of this `log_errors` function prints the path to the node stdout file it is parsing, which VSCode helpfully treats as a link. This adds the exact line number (in the stdout file) where the error was found, making the link even more helpful.
=> Include line number when Python infra links to error in node output

src/node/node_state.h
No point in starting an ACME client if we don't have a valid directory URL. As a side-effect, this also enables the use of custom ACME clients (e.g. in aDNS, where it's the parent that runs the client on behalf of a (subdomain) network), by specifying an ACME interface, but without a directory/configuration.
=> Don't start ACME clients without directory URL

.pylintrc, python/ccf/merkletree.py, tests/acme_endorsement.py, tests/infra/network.py, tests/infra/piccolo_driver.py, tests/infra/remote.py, tests/infra/runner.py, tests/partitions_test.py, tests/reconfiguration.py
New Pylint release: https://github.com/PyCQA/pylint/releases/tag/v2.16.0
Flags any instance of `raise Exception` as too broad.
Have replaced these, mostly with equivalent assertions.
=> Update to pylint 2.16.0 - remove uses of `raise Exception`

include/ccf/actors.h, src/enclave/enclave.h, src/http/http_rpc_context.h, src/node/acme_challenge_frontend.h, src/node/node_state.h
The ACME frontend was binding to the entire `.well-known` directory, intercepting any requests make to it, including to paths outside of the particular `acme-challenge` sub-directory.
This was preventing applications from handling any paths inside the `.well-known`, which may be necessary to implement certain protocols, such as did:web.
The code to extract the actor name from an incoming request is special cased for the .well-known directory, in which case it will include the second path component in the actor's name. THe ACME frontend's actor is now the full `.well-known/acme-challenge`.
We did consider implementing this by instead moving the ACME endpoints into the CommonEndpointRegistry, indirectly making them part of the application frontend, and removing the .well-known actor. …
=> Allow applications to add .well-known endpoints.

.azure-pipelines-templates/deploy_aci.yml
Especially with ACI being flaky, it's possible for ACI deployment to succeed but something goes wrong such that the IP addresses aren't populated. In this case, workspace cleanup fails as we can't SSH into the deployed ACI which blocks ACI cleanup.
This PR separates them so ACI cleanup happens even if workspace cleanup fails
=> Cleanup ACI even when workspace cleanup failed

.azure-pipelines-templates/deploy_aci.yml
Even if primary ACI deployment failed, secondary ACI deployment may have succeeded so attempt to cleanup regardless of the state of the primary
=> Make secondary ACI cleanup independent of primary

.azure-pipelines-gh-pages.yml
Link checks lead to intermittent false positives that can (and do!) block PRs to be merged. While it was useful to run it once and fix links then, running it for every commit is overkill. I've left it commented out so that it's easy to run it again in the future (e.g. before a major release).
=> Docs: Disable link checks

.azure-pipelines-templates/azure_cli.yml
0.2.9 fails
```
RuntimeError: Generating security policy failed with status code 1: /opt/az/lib/python3.10/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
```
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=64586&view=logs&j=b406b919-62d2-5750-bc8d-d446fee5d947&t=6a3b144b-9708-57a0-a920-f77d8a10714e&l=100
=> Downgrade confcom to 0.2.6 to avoid CI failure

.azure-pipelines-gh-pages.yml, .azure-pipelines-quictls.yml, .azure-pipelines-templates/cmake.yml, .azure-pipelines.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml, CHANGELOG.md, cmake/cpack_settings.cmake, getting_started/setup_vm/roles/openenclave/vars/common.yml
- [Upgrade to Open Enclave 0.18.5 (#5004)](https://github.com/microsoft/CCF/pull/5004)
=> [release/2.x] Cherry pick: Upgrade to Open Enclave 0.18.5 (#5004)

tests/infra/network.py
Fix a bug triggered by the full test suite here: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=64801&view=logs&j=77890be3-fbd3-52a1-2c40-e5bc14cbbdef&t=37e815a4-02f1-50e0-9ecd-dc1a864da067&l=17120 when the `test_recover_service_aborted` test was scheduled first.
=> Infra: fix for full test suite error

3rdparty/exported/t_cose/CONTRIBUTING.md, 3rdparty/exported/t_cose/inc/t_cose/t_cose_sign1_verify.h, 3rdparty/exported/t_cose/src/t_cose_sign1_verify.c, 3rdparty/exported/t_cose/test/t_cose_test.c, CHANGELOG.md, cgmanifest.json
Upgrades t_cose from [v1.1 to v1.1.1](https://github.com/laurencelundblade/t_cose/compare/v1.1...v1.1.1). 
t_cose v1.1.1 introduces the option to allow unknown critical header parameters in COSE_Sign1 envelopes. This option is desirable for SCITT & Notary interoperability.
=> Update t_cose from v1.1 to v1.1.1

getting_started/setup_vm/ccf-dev.yml
`ccf-dev.yml` playbook fails due to undefined `clang_version` variable
=> Fix `clang-version` in playbook

src/host/node_connections.h
This can happen regularly in normal operation, so shouldn't logged at level `FAIL`.
=> Reduce level of `Ignoring node_outbound to unknown node` log

.github/workflows/codeql-analysis.yml
v1 is deprecated:
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
And our workflow is failing:
https://github.com/microsoft/CCF/actions/workflows/codeql-analysis.yml
Hopefully these things are related, else I'll chase down the next fix.
=> Update CodeQL GitHub Actions steps to v2

python/requirements.txt
- [Update cryptography requirement from ==38.* to ==39.* in /python (#4792)](https://github.com/microsoft/CCF/pull/4792)
=> [release/3.x] Cherry pick: Update cryptography requirement from ==38.* to ==39.* in /python (#4792)

python/requirements.txt
- [Update cryptography requirement from ==38.* to ==39.* in /python (#4792)](https://github.com/microsoft/CCF/pull/4792)
=> [release/2.x] Cherry pick: Update cryptography requirement from ==38.* to ==39.* in /python (#4792)

tests/js-custom-authorization/custom_authorization.py
This 2ms seemed like it should be enough, but has been hit at least once in the CI:
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=65843&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=bb1a7e6d-8f5b-56e4-638c-b498b20b4b62&l=13973
Increasing this limit further to account for: debug builds, multi-test contention, random-CI-machine-contention, unknown unknowns.
=> Increase datetime API test timeout

CHANGELOG.md, src/host/ledger.h, src/host/node_connections.h, src/host/test/ledger.cpp, src/indexing/test/indexing.cpp, src/node/historical_queries.h, src/node/test/historical_queries.cpp, tests/e2e_logging.py, tests/infra/logging_app.py
- [Historical queries: Handle large requests being truncated by the host (#5026)](https://github.com/microsoft/CCF/pull/5026)
- [Revert test case for large historical queries (#5040)](https://github.com/microsoft/CCF/pull/5040)
- [Historical queries: Do not fetch entries until an early-enough secret has been fetched (#5058)](https://github.com/microsoft/CCF/pull/5058)
=> [release/2.x] Cherry pick: Historical queries fixes (#5026, #5040, #5058)

CHANGELOG.md, src/host/ledger.h, src/host/node_connections.h, src/host/test/ledger.cpp, src/indexing/test/indexing.cpp, src/node/historical_queries.h, src/node/test/historical_queries.cpp, tests/e2e_logging.py, tests/infra/logging_app.py
- [Historical queries: Handle large requests being truncated by the host (#5026)](https://github.com/microsoft/CCF/pull/5026)
- [Revert test case for large historical queries (#5040)](https://github.com/microsoft/CCF/pull/5040)
- [Historical queries: Do not fetch entries until an early-enough secret has been fetched (#5058)](https://github.com/microsoft/CCF/pull/5058)
=> [release/3.x] Cherry pick: Historical queries fixes (#5026, #5040, #5058)

CMakeLists.txt
This test keeps failing on access to external resources (wikipedia in this case), but external executors aren't supported in 3.x, and we don't need to hold up the release for that.
=> Disable external executor test

CHANGELOG.md, src/node/rpc/node_frontend.h
- [Avoid rewriting node info when `retired_committed` is already set (#5094)](https://github.com/microsoft/CCF/pull/5094)
=> [release/3.x] Cherry pick: Avoid rewriting node info when `retired_committed` is already set (#5094)

CHANGELOG.md, src/node/rpc/node_frontend.h
- [Avoid rewriting node info when `retired_committed` is already set (#5094)](https://github.com/microsoft/CCF/pull/5094)
=> [release/2.x] Cherry pick: Avoid rewriting node info when `retired_committed` is already set (#5094)

tests/external_executor/external_executor.py, tests/suite/test_requirements.py
The `WikiCacher` external executor makes requests to Wikipedia and so can be flaky in our CI. This PR disables the single `WikiCacher` executor test, and replaces it with the `LoggingExecutor` wherever possible.
=> External executor: disable `WikiCacher` test

src/enclave/enclave.h
This line was always wrongly printed at the end of the recovery of the public ledger. This shouldn't be printed as the enclave now requests batches of 100 entries to the host and so on the last request to the host, `ledger_no_entry_range` is returned, with `to_seqno = from_seqno + 100`, which triggers this incorrect log line.
=> Remove noisy recovery log line

tla/ccfraft.tla
Change to address issue found by @lemmy, model checking does not seem adversely affected:
```
$ ./tlc.sh MCccfraftWithReconfig.tla -config MCccfraft.cfg
TLC2 Version 2.18 of Day Month 20?? (rev: 30cab3d)
Running breadth-first search Model-Checking with fp 70 and seed 6400660138401708556 with 32 workers on 32 cores with 1963MB heap and 64MB offheap memory [pid: 6399] (Linux 5.4.0-1104-azure amd64, Microsoft 17.0.6 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file /workspaces/CCF/tla/MCccfraftWithReconfig.tla
Parsing file /workspaces/CCF/tla/ccfraft.tla
Parsing file /tmp/tlc-7914316506238689958/TLC.tla (jar:file:/workspaces/CCF/tla/tla2tools.jar!/tla2sany/StandardModules/TLC.tla)
Parsing file /tmp/tlc-7914316506238689958/_TLCTrace.tla …
```
=> Remove unnecessary condition

doc/_static/css/custom.css
Resolves #5129.
The hack I added previously to make mermaid diagrams visible ("if the theme is `dark`, set the `background-colour` of all mermaid elements to `0xffffff`") missed a case - when the theme is `auto` and that produces a dark background because of the browser's/OS's preferences. This adds a similar override in the CSS for this case as well.
=> Fix rendering on mermaid diagrams in docs when using auto theme

doc/build_apps/get_started.rst, doc/build_apps/install_bin.rst, doc/conf.py, doc/operations/run_setup.rst, doc/requirements.txt
This PR updates the documentation to reflect the recent support for different TEE platforms and different versions of `clang`. 
To keep the rendered documentation concise, we now also make use of [`sphinx-inline-tags`](https://sphinx-inline-tabs.readthedocs.io/en/latest/usage.html).
=> Docs: update instructions for different platforms

.azure_pipelines_snp.yml
Previously, a change under .azure-pipelines-templates/* would trigger the SNP test job, attempting to deploy an image the image build job never produced, because its trigger is more restrictive.
This PR fixes that by aligning both triggers.
=> Align SNP job triggers

tests/infra/github.py
This PR stops testing compatibility with release candidates as this was overly precautious, and we may break compatibility between release candidate and final release on purpose (just like we are doing for 4.0.0).
=> LTS test: stop testing compatibility with release candidates 

CHANGELOG.md, doc/schemas/gov_openapi.json, include/ccf/odata_error.h, include/ccf/rpc_context.h, include/ccf/service/tables/jsengine.h, samples/constitutions/default/actions.js, src/apps/js_generic/js_generic_base.cpp, src/js/wrap.cpp, src/js/wrap.h, src/node/rpc/frontend.h, src/node/rpc/member_frontend.h, src/node/rpc/rpc_context_impl.h, tests/infra/consortium.py, tests/js-modules/modules.py, tests/npm-app/app.json, tests/npm-app/src/endpoints/rpc.ts
- [JS runtime traces in responses (#5237)](https://github.com/microsoft/CCF/pull/5237)
=> [release/4.x] Cherry pick: JS runtime traces in responses (#5237)

CMakeLists.txt, cmake/common.cmake, src/endpoints/endpoint_registry.cpp, src/endpoints/test/endpoint_registry.cpp
Resolves #5224.
This was partially supported previously. This PR makes the parser a little stricter to ensure reasonable parsing for the kind of paths we actually care about, eg
```
/{id}:withdraw
/{id}:{action}
/commit:{action}
```
anywhere in the path. Each end of each template must be delimited by either an end of the string, or one of the characters `:` or `/`.
=> Support action style (`:`) templated paths

tla/Traceccfraft.tla
The "send_request_vote_response" disjunct is reported as another "IsRcvRequestVoteRequest" action with zero coverage.
Refactoring of https://github.com/microsoft/CCF/issues/5057
=> Remove outdate trace validation action.

doc/host_config_schema/cchost_config.json, doc/schemas/gov_openapi.json, doc/schemas/node_openapi.json, include/ccf/node/acme_subsystem_interface.h, include/ccf/node/session.h, include/ccf/research/custom_protocol_subsystem_interface.h, include/ccf/service/node_info_network.h, src/enclave/enclave.h, src/enclave/rpc_sessions.h, src/enclave/session.h, src/host/main.cpp, src/host/rpc_connections.h, src/node/node_state.h, src/node/rpc/acme_subsystem.h, src/node/rpc/custom_protocol_subsystem.h, src/node/rpc/custom_protocol_subsystem_interface.h, src/node/rpc/member_frontend.h, src/node/rpc/node_frontend.h, src/node/rpc/node_interface.h, src/node/test/node_info_json.cpp, src/quic/msg_types.h, src/quic/quic_session.h, tests/e2e_logging.py, tests/infra/e2e_args.py, tests/infra/interfaces.py, tests/infra/node.py
This adds support for custom TCP and UDP protocols. It is used via a new subsystem, which should make it easy to either keep it private for now, or to clearly mark it as experimental (in docs, but perhaps also by moving it to `include/ccf/experimental`?).
=> Experimental: support for custom protocols

getting_started/setup_vm/roles/ccf_build/vars/clang11.yml, getting_started/setup_vm/roles/ccf_build/vars/clang15.yml, getting_started/setup_vm/roles/perf-tool/tasks/install.yml
Remove unnecessary dependencies (we no longer build Doxygen and no longer support experimental v8) and tweak arrow playbook to support several Ubuntu versions.
=> Minor playbooks tweaks

docker/app_dev, docker/app_run, docker/ccf_ci
These images are the same (see below), but we prefer relying on MCR mirror to reduce dependency of third-party services.
```
$ docker pull ubuntu:20.04
20.04: Pulling from library/ubuntu
ca1778b69356: Already exists 
Digest: sha256:db8bf6f4fb351aa7a26e27ba2686cf35a6a409f65603e59d4c203e58387dc6b3
Status: Downloaded newer image for ubuntu:20.04
docker.io/library/ubuntu:20.04
$ docker pull mcr.microsoft.com/mirror/docker/library/ubuntu:20.04
20.04: Pulling from mirror/docker/library/ubuntu
Digest: sha256:db8bf6f4fb351aa7a26e27ba2686cf35a6a409f65603e59d4c203e58387dc6b3
Status: Downloaded newer image for mcr.microsoft.com/mirror/docker/library/ubuntu:20.04
mcr.microsoft.com/mirror/docker/library/ubuntu:20.04
```
=> Update Dockerfiles to use Ubuntu MCR mirror

.azure-pipelines.yml, .azure_pipelines_snp.yml, .backportrc.json, .daily.yml, doc/conf.py
CCF [2.x is now end of life](https://microsoft.github.io/CCF/main/build_apps/release_policy.html#support-calendar) so this PR disables CI pipelines and documentation generation for `release/2.x`.
=> Disable `release/2.x` CI and doc generation

doc/build_apps/crypto.rst
There are various places where our docs are a little unclear. They were initially written to focus on the C++ API, and we should do a pass to rebalance/redirect to the JS equivalents where appropriate. This is one of the lowest hanging fruits.
=> Documentation: Point from C++ crypto page to JS crypto API

tests/infra/e2e_args.py, tests/infra/interfaces.py, tests/infra/network.py, tests/infra/node.py, tests/infra/remote.py, tests/start_network.py
- [Ensure e2e HTTP limit args are passed all the way through to the nodes (#5348)](https://github.com/microsoft/CCF/pull/5348)
=> [release/4.x] Cherry pick: Ensure e2e HTTP limit args are passed all the way through to the nodes (#5348)

tests/infra/e2e_args.py, tests/infra/interfaces.py, tests/infra/network.py, tests/infra/node.py, tests/infra/remote.py, tests/start_network.py
- [Ensure e2e HTTP limit args are passed all the way through to the nodes (#5348)](https://github.com/microsoft/CCF/pull/5348)
=> [release/3.x] Cherry pick: Ensure e2e HTTP limit args are passed all the way through to the nodes (#5348)

src/crypto/test/crypto.cpp
Minor OpenSSL 3.x compatibility fixes, extracted from https://github.com/microsoft/CCF/pull/5293.
=> Minor OpenSSL 3.x compatibility fixes

tests/external_executor/external_executor.py
This seems to be breaking with the latest version of ruff, but the shadowing isn't ideal so we might as well remove it.
=> Address issue hit by the latest version of ruff

CMakeLists.txt
Disabling this test for now to avoid flaky CI.
See https://github.com/microsoft/CCF/issues/4403
=> Disable flaky indexing test

src/kv/kv_types.h, src/node/history.h, src/node/test/snapshotter.cpp
Fixing a crash noticed while testing #5306. Specifically, when running an SGX build with >5 threads, we'd see a crash during serialisation:
```
2023-06-21T13:36:35.874589Z -0.008 1   [fail ] ../src/kv/committable_tx.h:244       | Error during serialisation
2023-06-21T13:36:35.874664Z -0.008 1   [fail ] ../src/kv/committable_tx.h:245       | Error during serialisation: invalid leaf indices
2023-06-21T13:36:35.874688Z -0.008 1   [fatal] ../src/node/rpc/frontend.h:639       | Failed to serialise
```
With a bit more logging and chasing up the stack, what's actually happening here is that a `MerkleTreeHistoryPendingTx` _S_ has been scheduled but stalled for a while, and in the interim a different signature has arrived, committed, and been compacted, flushing the merkle tree past the …
=> Avoid taking too-early dependency on `previous_signature_seqno`

.devcontainer/devcontainer.json
This is mainly prompted by the fact that apt update does not seem to work today as a result of the nodejs apt repo being in a bad state.
More generally though, imposing the time this takes on all users seems unwarranted. lldb works much better than gdb on our builds.
=> Remove gdb install

tla/Traceccfraft.cfg, tla/Traceccfraft.tla
Depends on https://github.com/tlaplus/tlaplus/commit/5b3286ba7a47b3e2cd21f44620fdca9b76e66d15
Part of https://github.com/microsoft/CCF/issues/5057
=> Boilerplate to validate the current TLA+ trace against an older trace.

include/ccf/crypto/entropy.h
This is a fix for a potential register re-use issue spotted by ASAN (as part of #4994), which had previously been ignored (#5050) because we did not understand what caused it.
Thank you to @neldredge for pointing our incorrect understand of input/output register usage in line assembly, and suggesting a further optimisation.
Once dependencies allow for it, we should switch to intrinsics rather than use inline assembly.
=> Fix unsafe inline assembly usage

tests/e2e_operations.py
The recently added `run_config_timeout_check` starts a `cchost` instance by hand so that we directly control the config. This was not started with any `stdout` redirection, so the node output was interleaved with the Python output in every e2e run, [as here](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=72581&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=bb1a7e6d-8f5b-56e4-638c-b498b20b4b62&l=36327):
```
57: 2023-07-06 03:23:59.634 | INFO     | {operations} e2e_operations:run_config_timeout_check:397 - Move a full config back
57: 0        100 [info ] ../src/host/main.cpp:161             | CCF version: ccf-4.0.0-121-gbc8b04a75
57: 1        100 [info ] ../src/host/main.cpp:169             | Configuration file 0.config.json:
57: 
57: 2        100 [info ] …
```
=> Remove node output from config timeout test appearing in e2e output

doc/audit/read_write_restrictions.rst
Noticed a minor typo in the docs:
This change makes that say _`Read-only`_ rather than _``Read-only` ``_
=> Remove extra quote-mark in documentation

CHANGELOG.md, src/tls/cert.h, tests/acme_endorsement.py
- [Include intermediate certs in TLS handshake (#5453)](https://github.com/microsoft/CCF/pull/5453)
=> [release/4.x] Cherry pick: Include intermediate certs in TLS handshake (#5453)

.github/workflows/build-ci-container.yml
See #4700.
Switching to `pull_request_target` let us trigger this from forks, with access to secrets, but doesn't apply the same security restrictions as `pull_request`. We may replace this with an ADO pipeline in future. For now, we can trigger rebuilds of the SNP CI containers with PRs from `microsoft/` branches.
=> Revert #4700 - restore `pull_request` trigger for `build-ci-container.yml`

tests/infra/remote.py
#5375 introduced a crash in the `lts_compatibility` test in SGX Debug builds that was missed until 4.0.5 was cut. It attempts to pass `--enclave-log-level Debug` to LTS nodes built with minimum logging level = INFO, and those nodes throw at CLI validation.
This is a quick-fix to stop passing the argument at all when it is potentially unsafe. It does mean the infra won't produce the verbose logs for SGX Debug, but we can resolve that with a more targeted fix when we have more time.
=> Fix `lts_compatibility` in SGX Debug - don't pass unsafe `--enclave-log-level`

.azure-pipelines-gh-pages.yml, .azure-pipelines.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/build-ci-container.yml, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml, CHANGELOG.md, cmake/cpack_settings.cmake, cmake/open_enclave.cmake, docker/ccf_ci_built, getting_started/setup_vm/roles/openenclave/vars/common.yml, scripts/azure_deployment/arm_aci.py
- [Update to Open Enclave 0.19.3 (#5460)](https://github.com/microsoft/CCF/pull/5460)
=> [release/4.x] Cherry pick: Update to Open Enclave 0.19.3 (#5460)

samples/constitutions/default/actions.js
This was renamed in the JS API a while ago, but missed from the SNP path while that test was omitted.
=> Fix SNP `code_update_test` - `ccf.digest` is now `ccf.crypto.digest`

samples/constitutions/default/actions.js
- [Fix SNP `code_update_test` - `ccf.digest` is now `ccf.crypto.digest` (#5464)](https://github.com/microsoft/CCF/pull/5464)
=> [release/4.x] Cherry pick: Fix SNP `code_update_test` - `ccf.digest` is now `ccf.crypto.digest` (#5464)

src/enclave/tls_session.h, src/tls/context.h
Spotted some odd TLS errors during multi-threaded perf tests, where clients were being disconnected. Tracked it down to this. There were cases where we got a `WANTS_WRITE/WANTS_READ` response from an attempted write, which means a handshake is still in-progress or similar, and we need to retry the write later. The default semantics are very strict, and we must "retry the write" with exactly the same pointer and size. Our source for this is a `pending_writes` buffer, so if it got resized and reallocated, we'd pass a new pointer and this would blow up. There's a magic flag to make it less strict, which it seems we want. This is well explained in [this StackOverflow answer](https://stackoverflow.com/questions/2997218/why-am-i-getting-error1409f07fssl-routinesssl3-write-pending-bad-write-retr) …
=> Fix bug in TLS context - allow incoming write buffer to be relocated

tests/infra/basicperf.py, tests/infra/piccolo/analyzer.py, tests/perf-system/submitter/parquet_data.h, tests/perf-system/submitter/submit.cpp
These were previously floats, resulting in hard-to-read tables and unlabelled latency units:
By using the Parquet Timestamp type (storing milliseconds since the Linux epoch), we get nice rendering in the output table (and a smattering of type safety)
This lets us compare when the clients were running at a glance, and recognise if one was running significantly before/after the others.
This PR includes removing a few sorts and replacing them with `min()`/`max()` where possible.
=> Use Timestamp Parquet type for recording Piccolo's timestamps

tests/infra/basicperf.py, tests/requirements.txt
There is a very substantial perf regression in read_parquet between polars 0.18.7 and 0.18.11 (>5x). We are also slowing down the analysis unnecessarily by keeping the network up.
=> Pin polars to 0.18.7, and shut down network and clients earlier

tests/infra/basicperf.py, tests/perf-system/submitter/submit.cpp
Following #5484, but with microsecond rather than millisecond.
Also inserting the latencies into the aggregate, rather than requiring recalculation.
=> Microsecond granularity for Piccolo

src/apps/js_generic/oe_sign.conf, tests/infra/basicperf.py, tests/infra/network.py, tests/perf-system/submitter/handle_arguments.h, tests/perf-system/submitter/submit.cpp
This adds a new flag `--stop-primary-after-s 5`, which when passed does the following things:
1. Set `--failover-server-address` to the first backup for all nodes otherwise pointing to the primary
2. Set the election timeout for all nodes but the first backup to 15 seconds, so as to ensure its election
3. After the configured number of seconds, shut down the primary
It's worth noting that the throughput diagram does not currently show the gap we would expect, owing to the immediate reconnection followed by a series of 4xx return codes, which we should not be counting as successful writes.
There are typically two reconnections:
```
2023-08-03T14:53:24.906610Z        100 [fail ] perf-system/submitter/submit.cpp:322 | Sending interrupted: unknown error, attempting reconnection to …
```
=> Add support for failover server to the submitter

src/clients/rpc_tls_client.h, tests/perf-system/submitter/parquet_data.h, tests/perf-system/submitter/submit.cpp
`read_raw_response` doesn't work correctly when it bridges responses. Replaced with existing `read_response` (both already include HTTP parse cost), and copy fields to multiple columns rather than reserialising (well, partial reserialisation for headers).
=> Piccolo submitter: Avoid splicing HTTP responses

tests/perf-system/submitter/submit.cpp
#5499 had a fun side effect:
Because `CLOCK_MONOTONIC` is time since "an arbitrary epoch" (boot time on Linux), but we store it as though it were a Linux-1970-epoch timestamp, we display confusing send and receive times.
This attempts to corrects that by offsetting the written times by the system's boot time. We can only approximate that, and that's only an approximate match for the start of `CLOCK_MONOTONIC`. But it gets us timestamps that are "correct" within a few seconds, and correctly ordered amongst themselves.
=> Offset send and receive times by (approximate) boot time

tests/infra/basicperf.py, tests/infra/network.py, tests/perf-system/submitter/submit.cpp
1. Piccolo now ignores SIGPIPE, since it will sometimes try to write to a socket after the primary has shut down unexpectedly
2. It is not possible to guarantee a primary will be elected in time, depending on the test duration, and so trying to snap the memory usage from the primary is now skipped
3. Filter out error responses produced as a result of the election
=> Resolve stability issues with usage of stop-primary in basicperf

tests/infra/basicperf.py
Add a `--add-new-node-before-primary-stops <hostname>` that can be combined with `--stop-primary-after-s <duration>`, which configures in a new node after stopping, and retiring the primary.
=> Add reconfiguration to basicperf

CMakeLists.txt, samples/apps/basic/basic.cpp, samples/apps/basic/js/app.json, src/consensus/aft/raft.h, src/host/node_connections.h, tests/infra/basicperf.py, tests/infra/consortium.py, tests/infra/network.py
Performs node replacement as an atomic transaction when using `--add-new-node-after-primary-stops`.
=> Atomic replacement of shutdown node

tests/infra/piccolo/generator.py
New version of `ruff` flags this, so format checks are currently failing.
=> Ruff lint update: Use `isinstance`

.azure-pipelines-gh-pages.yml, .azure-pipelines-templates/daily-matrix.yml, .azure-pipelines-templates/deploy_aci.yml, .azure-pipelines.yml, .azure_pipelines_snp.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml, docker/ccf_ci_built, scripts/azure_deployment/arm_aci.py
- [Update CI jobs to 10-08-2023 base (#5532)](https://github.com/microsoft/CCF/pull/5532)
=> [release/4.x] Cherry pick: Update CI jobs to 10-08-2023 base (#5532)

.azure-pipelines-gh-pages.yml, .azure-pipelines-templates/daily-matrix.yml, .azure-pipelines.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml
- [Update CI jobs to 10-08-2023 base (#5532)](https://github.com/microsoft/CCF/pull/5532)
=> [release/3.x] Cherry pick: Update CI jobs to 10-08-2023 base (#5532)

.azure-pipelines-gh-pages.yml, .azure-pipelines.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml
- [Update CI image from 11-08 to 14-08 (#5544)](https://github.com/microsoft/CCF/pull/5544)
=> [release/3.x] Cherry pick: Update CI image from 11-08 to 14-08 (#5544)

.azure-pipelines-templates/daily-matrix.yml, .azure-pipelines-templates/matrix.yml, .azure-pipelines-templates/stress-matrix.yml
- [Switch to a backup pool (#5512)](https://github.com/microsoft/CCF/pull/5512)
=> [release/3.x] Cherry pick: Switch to a backup pool (#5512)

.azure-pipelines-gh-pages.yml, .azure-pipelines-templates/deploy_aci.yml, .azure-pipelines.yml, .azure_pipelines_snp.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml, docker/ccf_ci_built, getting_started/setup_vm/roles/autoremove/install.yml, getting_started/setup_vm/roles/ccf_build/vars/clang11.yml, getting_started/setup_vm/roles/ccf_build/vars/clang15.yml, scripts/azure_deployment/arm_aci.py
- [Remove graphviz from llvm task (#5551)](https://github.com/microsoft/CCF/pull/5551)
=> [release/4.x] Cherry pick: Remove graphviz from llvm task (#5551)

.azure-pipelines-gh-pages.yml, .azure-pipelines.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .multi-thread.yml, .stress.yml, getting_started/setup_vm/roles/ccf_build/vars/clang11.yml, getting_started/setup_vm/roles/ccf_build/vars/clang15.yml
- [Remove graphviz from llvm task (#5551)](https://github.com/microsoft/CCF/pull/5551)
=> [release/3.x] Cherry pick: Remove graphviz from llvm task (#5551)

tests/election.py
Another `ruff` update, now flagging this in all format check runs.
=> Do not compare types, use `isinstance()`

tla/SIMccfraft.tla
=> Find a *shorter* counter-example.

3rdparty/exported/fmt/args.h, 3rdparty/exported/fmt/chrono.h, 3rdparty/exported/fmt/color.h, 3rdparty/exported/fmt/compile.h, 3rdparty/exported/fmt/core.h, 3rdparty/exported/fmt/format-inl.h, 3rdparty/exported/fmt/format.h, 3rdparty/exported/fmt/os.h, 3rdparty/exported/fmt/ostream.h, 3rdparty/exported/fmt/printf.h, 3rdparty/exported/fmt/ranges.h, 3rdparty/exported/fmt/std.h, 3rdparty/exported/fmt/xchar.h, CHANGELOG.md, cgmanifest.json, include/ccf/crypto/san.h, include/ccf/ds/unit_strings.h, include/ccf/service/node_info.h, include/ccf/service/node_info_network.h, include/ccf/service/tables/proposals.h, src/clients/perf/scenario_perf_client.cpp, src/clients/perf/timing.h, src/host/lfs_file_handler.h, src/host/snapshots.h, src/kv/kv_types.h, src/node/acme_client.h
Backports the following commits to `{release/4.x}`:
{ - [Update `fmt` library from `9.1.0` to `10.1.1` (#5605)](https://github.com/microsoft/CCF/pull/5605)}
=> [release/4.x] Cherry pick: Update `fmt` library from `9.1.0` to `10.1.1` (#5605)

CHANGELOG.md, doc/schemas/gov_openapi.json, include/ccf/service/tables/uvm_endorsements.h, samples/constitutions/default/actions.js, src/node/quote.cpp, src/node/rpc/member_frontend.h, src/node/uvm_endorsements.h, tests/code_update.py
Backports the following commits to `{release/4.x}`:
{ - [SEV-SNP: Make UVM endorsements SVN an arbitrary string (#5620)](https://github.com/microsoft/CCF/pull/5620)}
=> [release/4.x] Cherry pick: SEV-SNP: Make UVM endorsements SVN an arbitrary string (#5620)

tla/SIMccfraft.tla, tla/Traceccfraft.tla, tla/ccfraft.tla
Also enables more fine grained fairness constraints:
```tla
Spec == 
/\ Init
/\ [][Next]_vars
/\ WF_vars(Next)
/\ \A i, j \in Servers : WF_vars(Receive(i,j)
```
=> Syntactic change to show sender and receive in action labels of TLC counterexamples.

src/consensus/aft/raft.h, tla/ccfraft.tla
https://github.com/microsoft/CCF/issues/5341
=> matchIndex lower bound for nextIndex

cmake/open_enclave.cmake
In the upgrade to OE 0.19, we moved to building with Clang 11 so the LVI mitigation solution changed - `-mlvi-cfi` rather than a custom toolchain. In the process, we began linking against the unmitigated OE libs.
=> Restore use of `-lvi-cfg` variants of OE libs

tla/Network.tla, tla/Traceccfraft.cfg, tla/Traceccfraft.tla, tla/ccfraft.tla
Distinct 7 959
WithMessage <- OrderNoDupWithMessage
WithoutMessage <- OrderNoDupWithoutMessage
Messages <- OrderNoDupMessages
MessagesOf <- OrderNoDupMessagesOf
InitMessageVar <- OrderNoDupInitMessageVar
Distinct 287 675
WithMessage <- OrderWithMessage
WithoutMessage <- OrderWithoutMessage
Messages <- OrderMessages
MessagesOf <- OrderMessagesOf
InitMessageVar <- OrderInitMessageVar
Distinct 1 399 231
WithMessage <- ReorderDupWithMessage
WithoutMessage <- ReorderDupWithoutMessage
Messages <- ReorderDupMessages
MessagesOf <- ReorderDupMessagesOf
InitMessageVar <- ReorderDupInitMessageVar
default: 153 453
Numbers collected from checking MCccfraft.cfg with TLCGet("level") < 22 as state constraint and Send <- MCSend commented.
=> Support modeling different network guarantees.

CHANGELOG.md, CMakeLists.txt, cmake/crypto.cmake, cmake/open_enclave.cmake, cmake/t_cose.cmake, src/clients/tls_client.h, src/crypto/key_wrap.cpp, src/crypto/openssl/cose_verifier.cpp, src/crypto/openssl/key_pair.cpp, src/crypto/openssl/openssl_wrappers.h, src/crypto/openssl/public_key.cpp, src/crypto/openssl/public_key.h, src/crypto/openssl/rsa_key_pair.cpp, src/crypto/openssl/rsa_public_key.cpp, src/crypto/openssl/rsa_public_key.h, src/crypto/openssl/verifier.cpp, src/crypto/test/crypto.cpp, src/enclave/enclave.h, src/enclave/tls_session.h, src/node/snapshot_serdes.h
- [OpenSSL3: remove use of deprecated functions (#5481)](https://github.com/microsoft/CCF/pull/5481)
=> [release/4.x] Cherry pick: OpenSSL3: remove use of deprecated functions (#5481)

tla/Traceccfraft.tla
Strengthen validation of AE requests.
=> Match next logline iff AE response comes from the same node.

tests/js-custom-authorization/custom_authorization.py, tests/js-limits/app.json, tests/js-limits/src/limits.js, tests/js-modules/modules.py
Reverts microsoft/CCF#5594.
Intended to close this PR, not merge it - tweaking these numbers is dangerous, as the stack limits on each platform differ.
=> Revert "Extend testing of JS runtime limits"

tla/ccfraft.tla
=> Refactor invariants to prevent evaluation error when they appear as conjuncts of the initial predicate.

tests/infra/remote.py
This hasn't been backported yet, but 4.0.9 has released.
Have a plan for a better check, this is a quickfix.
=> Fix `lts_compatibility`: Bump version check for `--enclave-file` arg

src/enclave/rpc_sessions.h, src/http/error_reporter.h, src/http/http2_session.h, src/http/http_session.h, tests/infra/jwt_issuer.py, tests/jwt_test.py, tla/ccfraft.tla
Resolves #5511 
This contains two changes:
1. Do not try to look up a Listening Interface from a _client_ Connection ID. That look up will not complete. The consequence of that is that if an HTTP handling error takes places in an HTTPClientSession, we throw, causing #5511.
2. In server contexts, use the stable Listening Interface ID, rather than do a reverse lookup from Connection ID. If a race has caused the connection to close, reporting still works correctly, rather than throw.
=> Fix HTTP handling errors reporting

src/enclave/rpc_sessions.h, src/http/error_reporter.h, src/http/http2_session.h, src/http/http_session.h, tests/infra/jwt_issuer.py, tests/jwt_test.py
- [Fix HTTP handling errors reporting (#5680)](https://github.com/microsoft/CCF/pull/5680)
=> [release/4.x] Cherry pick: Fix HTTP handling errors reporting (#5680)

js/ccf-app/package.json
Breaking change in `get-func-name` 2.0.1, used by `chai` to test our JS package. Pinning to 2.0.0 for now.
https://github.com/chaijs/get-func-name/issues/42
=> Pin JS dependency to resolve `npm test` failure

js/ccf-app/package.json
- [Pin JS dependency to resolve &#x60;npm test&#x60; failure (#5688)](https://github.com/microsoft/CCF/pull/5688)
=> [release/4.x] Cherry pick: Pin JS dependency to resolve &#x60;npm test&#x60; failure (#5688)

.azure-pipelines-templates/stress-matrix.yml, .azure-pipelines-templates/test.yml, .stress.yml
I noticed that the `CCF Github Stress` pipeline completed [suspiciously fast](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=76519&view=logs&j=b69c18ba-eebc-5249-7cb0-46eb355ef417&t=2cf99aca-b9fc-5fa9-d216-d926ddc3fbc3) (45s). This is because it doesn't actually test anything - the stress tests are gated behind `LONG_TESTS`, which wasn't present, and this `ctest` adds a `vegeta` filter. So no tests match.
This resolves that, and additionally skips the `CTest Partitions` test in this job.
=> Restore test in the `Stress` pipeline

.azure-pipelines-templates/trace_validation.yml, .github/workflows/tlaplus.yml, tla/tlc.sh
Follow up to #5700. This:
1. Centralises the place where we set TLC options
2. Splits CI vs local, since it looks like we often want different settings
3. Re-enables ParallelGC, since turning it off does seem to extend runtime by about 15%
4. Disables coverage in CI, since that extends runtime by about 100%
=> Centralise TLC options, and enable ParallelGC again

.github/workflows/tlaplus.yml, js/ccf-app/package.json, tla/install_deps.py
Resolves #5703 by moving the MC run a 1ES GHA pool with bigger nodes than the default GH pool.
This involved somewhat more changes than expected, but reduces runtime substantially. I've deliberately left the simulation where it is now, since it's single threaded and probably wouldn't benefit much while hogging the machines in the pool for quite some time.
With change:
Without:
=> Run model checker in 1ES GHA pool

tests/infra/network.py
Spotted by @eddyashton, setting class defaults that get picked up when constructing instances is convenient, but unsafe when the values are mutable.
=> Fix unsafe usage of instance default in Node

tests/infra/jwt_issuer.py
Broke this in #5698, noticed while trying to cut a new dev release.
=> Retain old JWT paths for LTS tests

.azure-pipelines.yml
Will be using `release/0.x` separately for new release pipeline experiments.
=> Make main release pipeline safe for release experiments

CHANGELOG.md, js/ccf-app/src/kv.ts, tests/js-custom-authorization/custom_authorization.py, tests/js-interpreter-reuse/app.json, tests/js-interpreter-reuse/src/global_handle.ts, tests/js-interpreter-reuse/src/rollup_entry.ts
We have found an issue with interpreter reuse, where caching of KV handles can result in memory violations (attempting to access handles from a previous Tx). A full fix for this will land in future, marking such handles as dirty so they are refreshed in future invocations. This is a temporary/partial fix, resolving the issue for TypeScript applications by making all handle lookups lazy.
=> Intermediate fix for JS KV handle caching - TypedKvMap does lazy lookup

tla/Network.tla, tla/Traceccfraft.cfg, tla/Traceccfraft.tla
Follow-up to https://github.com/microsoft/CCF/pull/5716.  `fancy_election.2` completes in 23 seconds:
```
Semantic processing of module Naturals
Semantic processing of module Sequences
Semantic processing of module FiniteSets
Semantic processing of module TLC
Semantic processing of module Folds
Semantic processing of module Functions
Semantic processing of module FiniteSetsExt
Semantic processing of module SequencesExt
Semantic processing of module Bags
Semantic processing of module Network
Semantic processing of module ccfraft
Semantic processing of module Json
Semantic processing of module Integers
Semantic processing of module IOUtils
Semantic processing of module TLCExt
Semantic processing of module _TLCTrace
Semantic processing of module Traceccfraft
Starting... (2023-10-14 03:46:08) …
```
=> Speed up trace validation

tests/infra/consortium.py, tests/js-custom-authorization/custom_authorization.py, tests/js-interpreter-reuse/app.json, tests/js-interpreter-reuse/src/func_caching.js, tests/js-interpreter-reuse/src/rollup_entry.ts, tests/js-modules/modules.py
Just a regression test confirming current behaviour. Although the endpoint tries to reuse an interpreter, the interpreter cache is correctly flushed during app update. Note that this test will fail if the constitution is modified to _not_ flush interpreters in `set_js_app:apply`.
=> Test that JS app code is correctly updated despite interpreter reuse

.azure-pipelines-templates/release.yml, scripts/extract-release-notes.py
Sometimes we touch things and forget to mention them in the CHANGELOG. One place this is particularly dangerous is when we modify the constitution - the sample constitution is rarely touched, yet subtle changes to those actions can be critical for new features.
This adds support in our `extract-release-notes` script for automatically inserting a note whenever a path is touched, with a link (as close as I can get) to the corresponding diff, and uses this option to insert a note whenever the `samples/constitutions` folder changes. Note that most (especially major) changes should still be called out as a separate explicit entry in the release notes. This is designed to serve as a backstop to ensure such critical changes are always described in the release.
=> Auto report constitution changes

CHANGELOG.md, doc/host_config_schema/cchost_config.json, src/host/configuration.h, src/host/main.cpp, tests/config.jinja, tests/e2e_operations.py, tests/infra/remote.py
- [Pass enclave path as CLI argument rather than in configuration (#5665)](https://github.com/microsoft/CCF/pull/5665)
=> [release/4.x] Cherry pick: Pass enclave path as CLI argument rather than in configuration (#5665)

src/enclave/enclave.h, src/indexing/test/indexing.cpp, src/node/node_state.h, src/node/rpc/member_frontend.h, src/node/rpc/node_frontend.h, src/node/rpc/test/frontend_test.cpp, src/node/rpc/test/frontend_test_infra.h, src/node/rpc/test/node_frontend_test.cpp, src/node/rpc/test/node_stub.h, src/node/secret_broadcast.h, src/node/share_manager.h, src/node/test/historical_queries.cpp, src/service/internal_tables_access.h
- [Make `GenesisGenerator` methods static (#5333)](https://github.com/microsoft/CCF/pull/5333)
=> [release/4.x] Cherry pick: Make `GenesisGenerator` methods static (#5333)

CHANGELOG.md, doc/host_config_schema/cchost_config.json, include/ccf/endpoint_registry.h, include/ccf/odata_error.h, include/ccf/service/consensus_config.h, src/consensus/aft/raft.h, src/consensus/aft/test/test_common.h, src/consensus/consensus_types.h, src/kv/kv_types.h, src/kv/test/stub_consensus.h, src/node/rpc/frontend.h, src/node/rpc/node_frontend.h, tests/config.jinja, tests/e2e_operations.py, tests/infra/network.py, tests/infra/remote.py, tests/requirements.txt
- [Add basic backpressure mechanism if primary has too many in-flight transactions (#5692)](https://github.com/microsoft/CCF/pull/5692)
=> [release/4.x] Cherry pick: Add basic backpressure mechanism if primary has too many in-flight transactions (#5692)

tla/README.md
Addressing https://github.com/microsoft/CCF/pull/5751#issuecomment-1773058841
I think the docs are best of place for TLA+ related documentation so this readme just points to the docs page and includes a neat button to launch a TLA+ codespace (with the largest host for exhaustive model checking)
=> Updating TLA+ README.md

tla/consensus/MCccfraft.cfg, tla/consensus/MCccfraft.tla, tla/consensus/MCccfraftWithReconfig.cfg, tla/consensus/ccfraft.tla
Ignore consecutive signatures when model checking.
@eddyashton Please confirm that the first log entry cannot be a signature:
https://github.com/microsoft/CCF/blob/ee4bb4566b6f891198f92e20f3a64b6162d040a6/tla/consensus/ccfraft.tla#L651
=> Allow consecutive signatures.

tests/raft_scenarios/bad_network
Surprising failure of Trace Validation [here](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=77693&view=logs&j=0c81e209-1101-513f-1f15-37e9c3575eb2&t=a05664f3-ab91-5eb2-6acd-14e2179ad708) is caused by `bad_network` having non-deterministic behaviour, occasionally producing a trace which failed validation. For now I'm restoring the intended determinism - I'll investigate why the trace validation failed separately, and see if there's a further fix required.
Since our scenarios do not attempt to lock the RNG with a seed, each node's Raft election timeout is randomised, triggering somewhere between 50 and 100 ms of (faked) idleness. We add `periodic_all,10` steps to trigger heartbeat messages, and `periodic_one,N,110` to trigger an election. This scenario had 5 consecutive …
=> Modify `bad_network` scenario to be deterministic

.azure-pipelines-templates/configure.yml
#5773 was insufficient. It removed an error, but running a "does this contain any non-docs changes" on `main` runs obviously fails, yet we want to run the full CI there. This nests the check - we're _not_ docs-only by default, and only go docs-only if this is a PR run (env var is set) _and_ the diff reports docs-only changes.
=> Restore running full CI on main, take 2

tla/consensus/MCccfraft.cfg, tla/consensus/MCccfraftWithReconfig.cfg
`CommittableIndicesAreKnownSignaturesInv` was added in https://github.com/microsoft/CCF/pull/5764 but it is currently only checked by simulation. This PR adds it to the exhaustive mode checking.
=> Adding `CommittableIndicesAreKnownSignaturesInv` to exhaustive model checking

.azure-pipelines-templates/configure.yml
See #5774 &c.
ADO is doing something we don't understand:
```
Started: Today at 15:13
Duration: 6m 11s
Evaluating: and(succeeded(), eq(dependencies['configure']['outputs']['setVarStep.docOnly'], 'false'))
Expanded: and(True, eq('false''', 'false'))
Result: False
```
This started when the `set -ex` was introduced, so maybe that's what blows up. Backing that out here as a final flail.
=> Restore running full CI on main, take 4

tla/consensus/MCccfraft.cfg, tla/consensus/MCccfraft.tla, tla/consensus/MCccfraftWithReconfig.cfg
I believe that there is currently an issue in `MCccfraft.tla` where the first configuration in `Configurations` is ignored. Currently, the initial configuration is any subset of servers and then the next configuration is the 2nd set of servers in `Configurations` and so on.
~~I'm not sure yet if this is the best fix (verse using a separate initial state in MCccfraft.tla).~~ I think this is simplest fix so the best for now
This PR is related to (but separate from) https://github.com/microsoft/CCF/pull/5778
=> Changing index into `Configurations` in `MCccfraft.tla`

.azure-pipelines-gh-pages.yml, .azure-pipelines-templates/deploy_aci.yml, .azure-pipelines.yml, .azure_pipelines_snp.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .github/workflows/tlaplus.yml, .multi-thread.yml, .stress.yml, docker/ccf_ci_built, scripts/azure_deployment/arm_aci.py
- [Update CI images to 26-10-2023 (#5784)](https://github.com/microsoft/CCF/pull/5784)
=> [release/4.x] Cherry pick: Update CI images to 26-10-2023 (#5784)

src/apps/js_generic/js_generic_base.cpp, src/js/wrap.cpp, src/js/wrap.h
Close #5239 
Most instances of `js_dump_error` were removed in #5747, but there were a few left. They are replaced with a check on the runtime flags, and the output is either logged as app fail, or embedded in the response where appropriate.
=> Remove ungated js exception logging

tla/consensus/ccfraft.tla
This is a simple change which probably has some big implications for the TLA+ specs and the trace validation.
=> Restrict initial configuration in ccfraft.tla to a single node

src/consensus/aft/impl/state.h, src/consensus/aft/raft.h, tla/consensus/Traceccfraft.tla
I think the reason committable indices wasn't moved to state when it was created is because it was an intersection between the Raft and PBFT states, but there is no reason to keep it out now. It's convenient to have it there as we start logging `state` and `state_after` (will be a separate PR).
This contains no changes other than the move.
=> Move committable indices to state, to facilitate tracing

.github/workflows/tlaplus.yml, tla/consensus/MCccfraft.tla, tla/consensus/MCccfraftAtomicReconfig.cfg
Follow up from https://github.com/microsoft/CCF/pull/5801
This PR as a new configuration to the exhaustive model checking CI to test atomic reconfiguration from one node to another.
=> Adding a new configuration to the model checking CI

tla/consensus/Traceccfraft.tla
There's an issue in VScode's "TLA+ model checking" view. Expanding the _logline record fails when the current step is "add_configuration", as VScode struggles with "new_configurations: ...".
=> Align the _logline in a TLA+ counterexample with its corresponding entry in the JSON log, from which the TLA+ state has been constructed.

.azure-pipelines-templates/matrix.yml, .azure-pipelines-templates/model_checking.yml, .github/workflows/tlaplus.yml
Complement to #5807 to get cimetrics to work (GHA isn't supported).
=> Move model checking to main CI pipeline

src/consensus/aft/test/driver.cpp, src/consensus/aft/test/driver.h, tests/raft_scenarios/append, tests/raft_scenarios/startup
The driver was never updated after we switched to [network bootstrapping](https://microsoft.github.io/CCF/main/operations/start_network.html), which makes expressing impossible scenarios too easy, and realistic scenarios more tedious than necessary.
This is a small change in the direction of more realism in the driver. I have also changed the Start node to use force_become_leader(), as in the real system, which makes the initial tx id line up at 2.1.
Nodes are fully connected as soon as they are trusted, they can be disconnected manually where appropriate.
This is a chunk of #5769, enough to express realistic scenarios, but without converting the existing ones and requiring the cascading TLA+ changes just yet.
=> Add realistic reconfiguration commands for driver

tla/consensus/MCccfraft.cfg, tla/consensus/MCccfraft.tla, tla/consensus/MCccfraftAtomicReconfig.cfg, tla/consensus/MCccfraftWithReconfig.cfg, tla/consensus/SIMCoverageccfraft.cfg, tla/consensus/SIMCoverageccfraft.tla, tla/consensus/SIMccfraft.cfg, tla/consensus/SIMccfraft.tla, tla/consensus/Traceccfraft.cfg, tla/consensus/Traceccfraft.tla, tla/consensus/ccfraft.tla
=> Remove NotifyCommit to bring spec closer to implementation

tests/requirements.txt, tests/trace_viz.py
The JSON traces are painful to read when working on validation, especially with lots of nodes, I would really like something more compact and readable. I'd like to get this working for the traces we get from TLC too, eventually.
This needs a venv with the test dependencies installed to work. If you've run `make_traces.sh` before, you'll have that, just `source build/env/bin/activate`. Or just `pip install rich` in whatever venv you use.
The output looks like this:
Suggestions and changes very welcome.
=> Trace viz script

CHANGELOG.md, include/ccf/crypto/curve.h, include/ccf/crypto/jwk.h, js/ccf-app/src/global.ts, js/ccf-app/src/polyfill.ts, js/ccf-app/test/polyfill.test.ts, src/crypto/openssl/eddsa_key_pair.cpp, src/crypto/openssl/eddsa_public_key.cpp, src/js/crypto.cpp, tests/infra/crypto.py, tests/js-modules/modules.py
`ccf.crypto.generateEddsaKeyPair`, `pubEddsaPemToJwk` and `eddsaPemToJwk` now support `x25519` as well as `curve25519`.
=> Allow creating x25519 key pairs from JS

tla/consensus/ccfraft.tla
Draft of a suitable action property to address MTOLI weakness:
```tla
\* MoreThanOneLeaderInv is not violated if server A steps down and server B steps up as leader *atomically*, i.e., in a single action.
LeaderInNewTermProp ==
[][~ \E s, t \in Servers:
\* s steps down.
/\ state[s] = Leader /\ state[s]' # Leader
\* t steps up.
/\ state[t] # Leader /\ state[t]' = Leader
\* s and t are and remain in the same term.
/\ currentTerm[s] = currentTerm[t]
/\ (currentTerm[s] = currentTerm[t])']_vars
```
https://github.com/microsoft/tlaplus-examples/issues/3
=> Rewrite comments of MonoLogInv and MoreThanOneLeaderInv.

python/ccf/cose.py
Type checking break caused by https://github.com/TimothyClaeys/pycose/commit/bca82b6c7200061a4276c8c24b01eca1f20869b7, combined with limited type inference from mypy. Easily solved by pointing explicitly to the type of the base class.
=> Minimal fix to fix type checking for latest pycose

CHANGELOG.md, include/ccf/node/quote.h
Deprecated in 3.0.0, was due to be removed in 4.0.0.
=> Remove deprecated EnclaveAttestationProvider

src/consensus/aft/test/driver.cpp, src/consensus/aft/test/driver.h, tests/raft_scenarios/append, tests/raft_scenarios/startup
Useful for #5875, since the first node is usually known as "n1" in the spec, rather than "0" in the driver.
=> Allow driver to name the first node

python/ccf/ledger_viz.py
**Before**
Boxes are 1 char wide so you can only see the 4 from 14
**After**
Also change color of example to avoid clash with recovering service
=> Minor update to `ledger_viz.py` with `--write-view`

tla/consensus/SIMccfraft.cfg, tla/consensus/SIMccfraft.tla, tla/consensus/ccfraft.tla
* Show value of newConfiguration parameter of ChangeConfigurationInt in traces
* Add DebugInvUpToDepth invariant to SIMccfraft to quickly generate a trace of length N by passing N to TLC's `-depth` cli.
Related to https://github.com/microsoft/CCF/pull/5875
=> Minor refactorings

tests/e2e_batched.py
Change to address the following issue:
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=79909&view=logs&j=f3457e4b-102d-5a4f-f801-dc119e4853a8&t=ae98f324-492e-5969-593b-258ede9c5463
```
48: 13:06:11.719 | INFO     | __main__:run_to_destruction:115 - Large write set caused an exception, as expected
48: 13:06:11.719 | INFO     | __main__:run_to_destruction:116 - Exception was: Could not check if test requirements were met: 
48: 13:06:11.719 | INFO     | __main__:run_to_destruction:117 - Polling for 120s for node to terminate
```
in https://github.com/microsoft/CCF/blob/d95a0cea350970b223b60465eaeab47b38111748/tests/e2e_batched.py#L104
Large writes can cause an election without a crash, in which case the attempt to find a primary to look up available endpoints (quite unnecessary in …
=> Remove method support check in js batched stress test

tests/raft_scenarios/replicate_deprecated, tla/consensus/MCccfraft.cfg, tla/consensus/MCccfraftWithReconfig.cfg, tla/consensus/SIMccfraft.cfg, tla/consensus/ccfraft.tla
CCF's consensus optimistically updates the send_idx when an AE message is dispatched so it does not need to update it on a successful AE response
=> `NextIndex` is not updated on successful AE response

tla/consensus/MCccfraftAtomicReconfig.cfg
A minor change I forgot to push in #5895. removing `MatchIndexLowerBoundNextIndexInv` from atomic reconfig configuration file
=> Follow up to #5895 

tests/js-modules/modules.py, tests/requirements.txt
=> Enable x25519 JWT testing and pin JWCrypto>=1.5.1

scripts/ci-checks.sh
For some errors that ruff spots, such as unused includes, it will print an error along the lines of "I could have tried to fix this automatically, if you'd given me the `--fix` arg". It's odd-to-annoying ifthat appears when we _have_ passed the `-f[ix]` arg to our `ci-checks` wrapper!
So the wrapper's `fix` mode now enables ruff's `fix` mode, as it does with similar tools.
Also, because we have mixed verbosity of the tools called from this wrapper, I've modified it to always print group headings. There might be a reason this was disabled, that I've forgotten? But I think it makes the output far more readable.
=> Ask `ruff` to autofix Python lint errors, where possible

CMakeLists.txt, src/ds/serialized.h, src/ds/test/serialized.cpp, tests/connections.py
This change and test exposed an issue with `serialized::peek<T>` - it makes no alignment checks before reading entries (caught by ASAN).
This change adds some unit tests for `serialized::peek`, and changes the behaviour to test alignment and copy to scratch memory if misaligned.
=> Follow up to #5889 - avoid misaligned peeks

tla/consensus/MCccfraft.tla, tla/consensus/Traceccfraft.tla, tla/consensus/ccfraft.tla
Currently, `ccfraft.tla` keeps track of the global reconfiguration count. This variable does not exist in practice and is just used by exhaustive model checking (`MCccfraft.tla`) to limit the number of reconfiguration and determine the next candidate configuration. This PR removes `reconfigurationCount` by modifying `MCccfraft.tla` to use configurations directly instead.
=> Removing `reconfigurationCount` from `ccfraft.tla`

tests/raft_scenarios/bad_network, tests/raft_scenarios/fancy_election.1, tests/raft_scenarios/soft_rollback, tests/raft_scenarios/suffix_collision.1, tests/raft_scenarios/suffix_collision.2, tests/raft_scenarios/suffix_collision.3, tla/consensus/Traceccfraft.tla, tla/consensus/ccfraft.tla
Add soft rollback, fancy election 1, suffix collisions 1,2,3 and bad network scenarios, as well as spec fix necessary to align receive append entries response to the one on the implementation.
It is worth nothing that the spec and implementation of CCF differ from Raft on the term value set on receive append entries responses when they fail. @heidihoward spotted this earlier when reviewing the implementation, now is a good time to discuss and resolve the discrepancy:
**Raft**: term of the current, as provided previously on the send append entries.
From https://raft.github.io/raft.pdf (wouldn't it be nice if there was a way to link to a section in a paper?).
**CCF implementation**: [term of the last index in the backup's log](https://github.com/microsoft/CCF/blob/e5a7106a03686e5da881c1ec9f1 …
=> More trace validation scenarios

CHANGELOG.md, include/ccf/kv/set_handle.h, include/ccf/kv/untyped_map_handle.h, src/kv/test/kv_test.cpp, src/kv/untyped_map_handle.cpp
=> Add `contains_globally_committed` to `kv::Set`

tla/consensus/MCccfraft.cfg, tla/consensus/MCccfraftAtomicReconfig.cfg, tla/consensus/MCccfraftWithReconfig.cfg, tla/consensus/SIMccfraft.cfg, tla/consensus/ccfraft.tla
After investigation of the failure raised in https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=80403&view=logs&j=ef8c4b80-2ff7-5042-ecea-fb36384f1d0d&t=c2a7e65a-2f43-5dbb-c6d6-70df1fdcc7fc, it has become clear that MoreUpToDateCorrectInv does not hold, and that valid traces can break it.
[SIMccfraft.json](https://github.com/microsoft/CCF/files/13975430/SIMccfraft.json)
=> MoreUpToDateCorrectInv is not an invariant, move to Debug

.azure-pipelines.yml, .azure_pipelines_snp.yml, .daily.yml, .multi-thread.yml, .stress.yml
There was some gating, but it was incomplete. release/0.x is currently used to test package signing.
=> Do not run CI on older branches

.github/workflows/codeql-analysis.yml
Following #5949, this adds a further permission so that CodeQL can interact with code scanning alerts.
=> GHA permissions: Add security-events write permission for CodeQL

src/consensus/aft/test/driver.cpp, src/consensus/aft/test/driver.h
Ideally we'd have a swap_nodes, but:
1. it's not necessary to reproduce the issues spotted in #5919 and #5951
2. it's a bit awkward to do with the current $method_name(,\d+)+
I guess we'll do something like `swap_nodes,2,out,1,2,in,3,4` once we're done with the current issues.
=> Add swap_node to driver to enable new scenarios

.azure-pipelines-release.yml
The pipeline is being triggered in too many circumstances at the moment. Noticed when looking at artifact billing.
=> Restrict triggers for signed release pipeline

tla/consensus/ccfraft.tla
`removedFromConfigurations` currently uses `CurrentConfiguration` when deciding whether a `newConfiguration` removes any nodes. Unfortunately, when there are pending configurations and a new configuration removes a node that is added by a pending configuration, this does not get reflected in`removedFromConfigurations`.
Here's a possible fix but I'm open to suggestions
Follow on from https://github.com/microsoft/CCF/pull/5919#discussion_r1467440262
=> Using max in remove from configurations

.azure-pipelines-release.yml
I thought #5957 had done that, by removing the pr block, but the default is to run on pr it seems.
=> Disable pr builds

CMakeLists.txt, src/host/node_connections.h, tests/connections.py, tests/fuzzing.py, tests/requirements.txt
I spent a while trying to build a shim application around the channels that could be fuzzed independently, but it ended up with rewriting a lot of code (including some directly-buggy bits!) for little result.
Instead, the right approach seems to be to use something that can fuzz the node-to-node protocol on a cchost TCP port directly. `boofuzz`, a successor to `Sulley`, seems a good fit. It's got some annoying shortcomings, but was able to find the previously-known (and fixed) issues, and one new issue.
An obvious extension would be to model the internal message types, rather than just the external wrapper. I'll take a look at that next, and see if we can gauge if the resulting combinatorial search is viable.
=> Add fuzz test of node-to-node connection

tla/consensus/ccfraft.tla
Add `is_new_follower` to the consensus spec to unblock https://github.com/microsoft/CCF/pull/5925. This PR also:
- allows the follower to rollback when it receives an AE even if there are no conflicting entries (or no entries at all in the AE). 
- sets the initial send_idx to the length of the leader's log
- prevents the `ConflictAppendEntriesRequest` action from being taken without also taking `AppendEntriesAlreadyDone` or `NoConflictAppendEntriesRequest`
=> Adding `is_new_follower` to consensus spec

doc/schemas/node_openapi.json, src/consensus/aft/impl/state.h, src/consensus/aft/raft.h, src/kv/kv_types.h, src/node/rpc/node_frontend.h, tests/trace_viz.py
- Remove `RetirementPhase::Committed`, it is unused.
- Move retirement phase and index and committable index to state, so they are included in the trace.
- Use retirement state and phase in trace viz.
I think we probably want to stop accessing the details of the retirement state directly from raft.h, and use a few well chosen conditions, like is_retirement_known_by_all_future_primaries(), or is_later_than_retirement(idx), but that may be debatable and is best done separately.
=> Add retirement phase to state and retirement state to viz

tests/reconfiguration.py
Stop nodes after they are no longer needed, and remove a bit of dead code.
Spun off from #5973.
=> Clean up nodes in reconfiguration test

.devcontainer/devcontainer.json, .devcontainer/tlaplus/devcontainer.json, js/ccf-app/test/tsconfig.json, js/ccf-app/tsconfig.json, tests/js-interpreter-reuse/tsconfig.json, tests/npm-app/tsconfig.json, tla/consensus/Traceccfraft.tla
This was quite wrong, and/because not exercised until now. We don't actually need to do anything when this is matched, because Timeout is one of the next possible actions and gets matched automatically.
Also noticed during #5973.
=> Fix recv_propose_request_vote in trace validation

.azure-pipelines-templates/trace_validation.yml, tests/raft_scenarios/reelection, tla/consensus/Network.tla, tla/consensus/Traceccfraft.cfg, tla/consensus/Traceccfraft.tla
See https://github.com/microsoft/CCF/pull/5940. This achieves the same goal (allowing trace validation of scenarios like reelection) with a much smaller change - using AllSubSeqs (see https://github.com/microsoft/CCF/pull/5940#issuecomment-1901767392) in OrderDropMessages, and duplicating the ACK-dropping logic of https://github.com/microsoft/CCF/pull/5941 in the Trace spec.
Related https://github.com/tlaplus/tlaplus/pull/867, which softens the performance impact of this change on the TV.
=> Add reelection scenario, and minimal change to Network.tla to trace validate

.azure-pipelines-templates/trace_validation.yml, tla/consensus/Traceccfraft.cfg, tla/consensus/Traceccfraft.tla
When TLC fails to validate a log, it prints a counterexample for the `TraceMatched` property that doesn't provide sufficient information to pinpoint the exact problem.  During trace validation, TLC generates a set of traces—finite prefixes of the possible behaviors as defined by the specification. Among these, the longest trace is considered the first candidate for detailed analysis (in the case of a breadth-first search, all traces are of equal length). Then, users are particularly interested in exploring the successor states to final state of this longest trace. Additionally, users would want to know which part of the next-state relation, or any state or action constraint, was evaluated as FALSE, leading to the exclusion of the successor states from the model.
However, the longest trace …
=> Towards easier debugging of trace validation.

src/consensus/aft/raft.h, src/consensus/aft/raft_types.h
Pulling some non-functional changes out of #5991, so they can be merge separately:
- Rename the early `apply` (which _returns_ an ExecutionWrapper), to `deserialize`. This makes it more clearly distinct from the later `apply()` call (_on_ that ExecutionWrapper).
- Add `static_assert`s where we rely on AppendEntries containing a single term. This should cause build breaks if we change this assumption in future, or at least more clearly highlight where changes need to be made.
=> Minor Raft QoL cleanup

doc/use_apps/verify_tx.rst
Raised in #5981, although the internal C++ enums are still ALL_CAPS, we switched to CamelCase to meet Azure guidelines. It makes sense to follow that convention when describing values returned by the REST API.
=> Update status casing in documentation to match REST API

src/consensus/aft/test/driver.h
We're using the Mermaid output less, but its still useful for summarising a scenario. This PR adds the `logical_clock` values (inserted as `h_ts` in the JSON trace output) to each Mermaid line.
So when you look at the Mermaid:
You can find some corresponding (nearby) trace lines from the ndjson:
```
{"h_ts":"110","thread_id":"100","level":"debug","tag":"raft","file":"../src/consensus/aft/raft.h","number":"579","msg":"n[0] | Leader | Active | Replicating 1 entries"}
{"h_ts":"111","thread_id":"100","level":"debug","tag":"raft","file":"../src/consensus/aft/raft.h","number":"603","msg":"n[0] | Leader | Active | Replicated on leader n[0]: 5 (1 hooks)"}
{"h_ts":"112","thread_id":"100","level":"debug","tag":"raft_trace","file":"../src/consensus/aft/raft.h","number":"612","msg":{"function":"replic …
```
=> RaftDriver: Include logical clock timestamps in Mermaid output

src/consensus/aft/raft.h, src/consensus/aft/raft_types.h
This is just a style change, and should no impact on behaviour.
I just noticed that the way we construct Raft messages gives me the heebie jeebies:
```
AppendEntries ae = {
{raft_append_entries},
{end_idx, prev_idx},
state->current_view,
prev_term,
state->commit_idx,
term_of_idx,
contains_new_view};
```
1. Why are we repeating `AppendEntries` and `raft_append_entries`?
2. What are all these fields?
This PR tries to resolve both, by setting the `msg` field (basically a discriminator for a tagged union struct) from a templated type, and assigning to each field by name.
```
AppendEntries ae;
ae.idx = end_idx;
ae.prev_idx = prev_idx;
ae.term = state->current_view;
ae.prev_term = prev_term;
ae.leader_commit_idx = state->commit_idx;
ae.term_of_idx = term_of_idx;
```
This is only an extremely …
=> Minor Raft QoL: Make message construction more readable

src/consensus/aft/test/driver.cpp, src/consensus/aft/test/driver.h, tests/raft_scenarios/soft_rollback, tests/raft_scenarios/suffix_collision.2, tests/raft_scenarios/suffix_collision.3
I realised that the coverage of our `assert_commit_safety` action is unnecessarily sparse. We insert it occasionally, but could be missing any number of safety violations elsewhere. It's cheap enough (with the current scale of scenarios) to assert this on every node, at every step. So we do!
=> RaftDriver: Check `commit_safety` after every step, as invariant

tla/consensus/MCccfraft.cfg, tla/consensus/MCccfraftAtomicReconfig.cfg, tla/consensus/MCccfraftWithReconfig.cfg, tla/consensus/SIMCoverageccfraft.cfg, tla/consensus/SIMccfraft.cfg, tla/consensus/Traceccfraft.cfg, tla/consensus/ccfraft.tla
This PR adds the RetiredCommitted transaction to the consensus specification. 
This PR just allows leaders to add `RetiredCommitted` transactions but they will not be used for anything (yet!)
=> Adding RetiredCommitted transaction to consensus spec

src/consensus/aft/raft.h
Yet another spin off from #5973.
Backups observing their retirement tx committed should obviously not nudge a surviving node to run an election!
This does not happen in practice today, because retiring backups do not observe their retirement committed: the primary stops messaging them as soon it observes the commit.
=> Only nudge a successor on retirement completed if primary

include/ccf/crypto/entropy.h, include/ccf/crypto/symmetric_key.h, src/crypto/entropy.cpp, src/crypto/sharing.cpp, src/crypto/sharing.h, src/crypto/test/bench.cpp, src/crypto/test/crypto.cpp, src/crypto/test/secret_sharing.cpp, src/indexing/enclave_lfs_access.h, src/js/crypto.cpp, src/js/wrap.cpp, src/node/channels.h, src/node/ledger_secret.h, src/node/secret_share.h, src/node/share_manager.h, src/node/test/secret_share.cpp
Ensure that operations applied to the secret or to the shares are constant time, without relying on compiler optimisation, minor renaming and test improvements.
This is not particularly performance sensitive, but for the record:
Before:
```
commit c557d9c4642517fb12338a22b2742aa793800c5c (HEAD -> main)
cmake -GNinja -DCOMPILE_TARGET=virtual ..
share:
===============================================================================
Name (baseline is *)   |   Dim   |  Total ms |  ns/op  |Baseline| Ops/second
===============================================================================
share_10s_d1 * |      10 |     0.175 |   17515 |      - |    57091.6
share_100s_d1 |      10 |     0.210 |   20988 |  1.198 |    47646.3
share_1000s_d1 |      10 |     0.560 |   56005 |  3.197 |    17855.5 …
```
=> Improvements to secret sharing following review

.azure-pipelines-gh-pages.yml, .azure-pipelines-templates/deploy_aci.yml, .azure-pipelines.yml, .azure_pipelines_snp.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .github/workflows/tlaplus.yml, .multi-thread.yml, .stress.yml, docker/ccf_ci_built, scripts/azure_deployment/arm_aci.py
- [Update CI image from 25-01-2024 to 12-02-2024 (#6011)](https://github.com/microsoft/CCF/pull/6011)
=> [release/4.x] Cherry pick: Update CI image from 25-01-2024 to 12-02-2024 (#6011)

.azure-pipelines-templates/trace_validation.yml, tla/last_line.sh
Made possible by https://github.com/tlaplus/tlaplus/commit/f153944df690111878f521fc530ebc511a7e9892, sample output:
```
traces/append.ndjson
traces/election.ndjson
traces/reconnect.ndjson
traces/reconfiguration.ndjson
traces/multi_election.ndjson
traces/check_quorum.ndjson
traces/replicate.ndjson
traces/reelection.ndjson
traces/retire_one.ndjson
traces/startup.ndjson
traces/election_while_reconfiguration.ndjson
traces/startup_2nodes.ndjson
traces/soft_rollback.ndjson
traces/bad_network.ndjson
traces/swap_node_no_election.ndjson
"Last matched [181] send_append_entries (periodic_all,10)"
traces/suffix_collision.1.ndjson
traces/swap_node.ndjson
"Last matched [361] send_append_entries (periodic_all,10)"
traces/fancy_election.1.ndjson
traces/fancy_election.2.ndjson
```
We might want to add …
=> Add details of last matching line in TV CI

src/consensus/aft/raft.h, src/consensus/aft/test/driver.h, src/consensus/aft/test/logging_stub.h, src/kv/kv_types.h, src/node/node_state.h
No impact change extracted from #5973, expanding #5962 to provide raft with enough information to know when it can stop tracking nodes.
```
set_retired_committed(ccf::SeqNo seqno)
```
becomes
```
set_retired_committed(const std::vector<kv::NodeId>& node_ids)
```
=> Retired committed hook receives whole config

tla/consensus/Traceccfraft.tla
Also suppresses repeated messages on stdout in trace validation.
=> Help TLC to only evaluate JsonServers once.

tests/raft_scenarios/bad_network
Noticed that the `raft_scenario_test` is failing occasionally on 4.x. Unsure exactly where the non-determinism comes from (multiple nodes calling elections? Undefined dispatch order?), but it is resolved by ensuring the final primary emits a signature so that commit can be advanced to it.
=> Fix flaky scenario on 4.x branch

tla/consensus/ccfraft.tla
Found while making changes in #5973, when `IsRetiredCommittedLog` is used on `log'/commitIdx'`, for example through `CalcMembershipState`, this can produce out of bounds access (`commitIdx'` used to index into `log[i]`, as opposed to `log'[i]`).
=> Raft Spec: Fix IsRetiredCommittedLog to use log argument

tests/config.jinja, tests/infra/e2e_args.py, tests/infra/network.py
Also renamed `--sn` to `--subject-name` for clarity. The option existed previously, but was not correctly forwarded and set in the config template.
Thank you @takuro-sato for spotting this.
=> Expose node cert subject name in config correctly to test/sandbox infra

tla/consensus/MCAliases.tla, tla/consensus/Traceccfraft.tla, tla/consensus/ccfraft.tla
With #6044, allows the global removedFromConfiguration to go away. #5973 will need to add a node-scope equivalent to its modified all_other_nodes (GetServerSet(i) + nodes that have been removed from that but are not RetiredCommitted).
=> Update PlausibleSucessorNodes logic and remove the global removedFromConfiguration

CMakeLists.txt, src/kv/test/kv_bench.cpp
Noticed completely by accident on another PR. The combination of builds/tests we currently run never includes both CMake's `LONG_TESTS=ON` and the `benchmark` label to CTest, resulting in several picobenchmarks being skipped. One of those (`kv_bench`) was crashing on startup due to a missing initialization step.
I think these are all fast enough that they shouldn't be gated? Maybe they should be blocked in Debug runs or similar.
=> Get `kv_bench` running again

include/ccf/research/create_tx_claims_digest.h, samples/apps/logging/CMakeLists.txt, samples/apps/logging/create_tx_claims_digest.cpp, src/node/rpc/no_create_tx_claims_digest.cpp, src/node/rpc/node_frontend.h, tests/e2e_logging.py
Add a research API allowing applications to define a claims digest on the _create transaction_ of a network. As a sample, the following call is added to the logging app, to capture the digest of the constitution in the receipt of the _create transaction_.
```
namespace ccfapp
{
std::optional<ccf::ClaimsDigest::Digest> get_create_tx_claims_digest(kv::ReadOnlyTx& tx)
{
auto constitution = tx.ro<ccf::Constitution>(ccf::Tables::CONSTITUTION)->get();
if (!constitution.has_value())
{
throw std::logic_error("Constitution is missing");
}
return ccf::ClaimsDigest::Digest(constitution.value());
}
}
```
Note that this is a research API, and is subject to change without prior notice.
Closes #6055.
=> Add get_create_tx_claims_digest to the research API

tests/infra/network.py
With #5973, nodes that are retired committed, but not aware of it, can be disruptive to the network. There were a few cases in our tests that were updated in the PR, but this was missed and manifested itself in this CI run: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=82762&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=3aae4c9d-f0dc-5b97-1b0e-f86312395af9
Longer term, the implementation of PreVote (#2577) will resolve this.
=> Stop retired nodes in tests that resize network

.azure-pipelines-gh-pages.yml, .azure-pipelines-templates/deploy_aci.yml, .azure-pipelines.yml, .azure_pipelines_snp.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .github/workflows/tlaplus.yml, .multi-thread.yml, .stress.yml, docker/ccf_ci_built, scripts/azure_deployment/arm_aci.py
- [Update CI image from 12-02-2024 to 15-03-2024 (#6067)](https://github.com/microsoft/CCF/pull/6067)
=> [release/4.x] Cherry pick: Update CI image from 12-02-2024 to 15-03-2024 (#6067)

src/consensus/aft/test/committable_suffix.cpp
Fixes #6075.
This is an unlikely situation, but deterministically reproducible from a given seed.
We're attempting to produce ledgers which conflict across multiple terms, randomly, but in rare instances we'll actually produce view histories like this:
```
history_on_A = 1
history_on_B = 1, 5, 5, 5, 6, 6, 6, 6, 6
```
In this situation all of our later asserts (and reconciliation) will pass, but our sanity check here that one is not a prefix of the other needs to be softened.
Based on these 2 random choices:
```
const auto num_terms = rand() % 30 + 5;
for (size_t i = 0; i < num_terms; ++i)
{
create_term_on(rand() % 2 == 0, term_length);
}
```
We'll hit this case when every call to `create_term_on` has the same first argument (eg - all `false`, or all `true`). My napkin-math says that's …
=> Fix `raft_test`: check size of view histories before accessing

.azure-pipelines-gh-pages.yml, .azure-pipelines-templates/deploy_aci.yml, .azure-pipelines.yml, .azure_pipelines_snp.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .github/workflows/tlaplus.yml, .multi-thread.yml, .stress.yml, docker/ccf_ci_built, scripts/azure_deployment/arm_aci.py
Backports the following commits to release/4.x:
- #6080
=> [release/4.x] Cherry-pick: Update CI image from 15-03-2024 to 2024-03-21 (#6080)

src/node/node_state.h, src/node/rpc/frontend.h, src/node/rpc/rpc_context_impl.h
I believe this is no longer needed - the create request is correctly executed locally for other reasons.
=> Remove `is_create_request` flag

.github/workflows/tlaplus.yml, scripts/TLAi-linter.genai.js, tla/StatsFile.tla
I'm not 100% certain that this automation will have always access to the env secrets.  Unfortunately, I don't know how to check it without deploying it.
=> Add TLAi linter.

.azure-pipelines-gh-pages.yml, .azure-pipelines-templates/deploy_aci.yml, .azure-pipelines.yml, .azure_pipelines_snp.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .github/workflows/tlaplus.yml, .multi-thread.yml, .stress.yml, docker/ccf_ci_built, scripts/azure_deployment/arm_aci.py
Backports the following commits to release/4.x:
- #6105
=> [release/4.x] Cherry-pick: Update CI image from 2024-04-03 to 2024-03-15 (#6105)

.azure-pipelines.yml, .daily.yml
These are still running daily, but failing because they reference unsupported images. Removing, as 3.x has been out of support for several months.
=> Remove scheduled CI triggers for 3.x

.azure-pipelines-templates/common.yml, .azure-pipelines-templates/matrix.yml, .azure-pipelines-templates/metrics.yml, .azure-pipelines-templates/push_perf_data.yml, .azure-pipelines-templates/simulation.yml
`METRICS_MONGO_CONNECTION` contains a secret, so we are removing it. This currently means we must also disable cimetrics.
We should separately explore if there's a cheap way to add an alternative auth mechanism to cimetrics.
=> Remove use of `METRICS_MONGO_CONNECTION`, disable cimetrics

tla/consistency/ExternalHistory.tla, tla/consistency/MCMultiNode.cfg, tla/consistency/MCMultiNodeCommitReachability.cfg, tla/consistency/MCMultiNodeInvalidReachability.cfg, tla/consistency/MCMultiNodeReads.cfg, tla/consistency/MCMultiNodeReadsAlt.cfg, tla/consistency/MCMultiNodeReadsNotLinearizable.cfg, tla/consistency/MCSingleNode.cfg, tla/consistency/MCSingleNodeCommitReachability.cfg, tla/consistency/MCSingleNodeReads.cfg, tla/consistency/MultiNodeReads.cfg, tla/consistency/SingleNode.tla, tla/consistency/SingleNodeReads.tla, tla/consistency/TraceMultiNodeReads.cfg
Split from #6136, this is useful when doing trace validation to be able to re-use `RwTxExecuteAction` without changes. We want to append to an arbitrary view (there could be an isolated primary), but definitely not to 1.
=> Parameterise consistency spec on FirstView

.github/workflows/tlaplus.yml
Won't work because they haven't got access to tokens, this just results in a predictable red CI status.
=> Do not run TLAi on forks

tla/consistency/MultiNode.tla, tla/consistency/SingleNode.tla
Following discussion with @eddyashton, attempt to modify the consistency spec, in a minimal way, to allow for constructive Invalid (i.e. allow both the StatusCommittedResponseAction and the StatusInvalidResponseAction to make decisions about the future commit history).
This should be a no-op from an MC perspective (to be confirmed by the full CI), but would facilitate trace validation by allowing Invalid to be matched even when the known commit history doesn't extend far enough.
Quite tentative.
=> Enable both Invalid and Commit on the future of the head branch

.azure-pipelines-templates/trace_validation.yml, tla/consistency/TraceMultiNodeReads.cfg, tla/consistency/TraceMultiNodeReads.tla
Clone of https://github.com/microsoft/CCF/pull/6153 with branch in microsoft org because of TLAi linter. :-(
--------
```tla
markus@avocado [14:30:48] [~/src/TLA/_specs/MSFT/CCF/tla/consistency] [fa4029338]
-> % export TLC_OPTS="-Dtlc2.tool.queue.IStateQueue=StateDeque"
markus@avocado [14:30:52] [~/src/TLA/_specs/MSFT/CCF/tla/consistency] [fa4029338]
-> % tlc -note TraceMultiNodeReads -checkpoint 0               
TLC2 Version 2.18 of Day Month 20?? (rev: 03c7bf4)
Running breadth-first search Model-Checking with fp 6 and seed 1941814660562527685 with 1 worker on 10 cores with 7282MB heap and 64MB offheap memory [pid: 67804] (Mac OS X 13.6.6 aarch64, Homebrew 11.0.23 x86_64, MSBDiskFPSet, StateDeque).
[...]
Starting... (2024-04-26 14:30:54)
Implied-temporal checking--satisfiability problem …
```
=> Fix off by one in consistency tv

tla/consistency/MCMultiNodeCommitReachability.cfg, tla/consistency/MCMultiNodeReads.cfg, tla/consistency/MCMultiNodeReadsAlt.cfg, tla/consistency/MCSingleNode.cfg, tla/consistency/MCSingleNodeReads.cfg, tla/consistency/MultiNodeReads.cfg, tla/consistency/TraceMultiNodeReads.cfg
Low-risk change.
Squash any type-related discussions, and prevent future incantations of https://github.com/microsoft/CCF/pull/6164/commits/20d89bff161410663d14e0cd2ad0788fe6337409. ;-p
See section about *typed model values* in https://tla.msr-inria.inria.fr/tlatoolbox/doc/model/model-values.html
=> Use typed model values to prevent comparing things that shouldn't be compared.

include/ccf/endpoints/authentication/cose_auth.h, src/endpoints/authentication/cose_auth.cpp
Will hopefully assuage CodeQL's concern about potentially uninitialised fields in https://github.com/microsoft/CCF/security/code-scanning/864
=> Define and use constructors for COSE identities

tla/consensus/ccfraft.tla
I don't think there is a useful to add detail to that property without duplicating `CalcMembershipState()`, which is already short and clear.
=> Remove inapplicable TODO in ccfraft.tla

scripts/check-todo.sh, scripts/ci-checks.sh
We have had the check-todo script for a while now, as part of our executable project policy and it's done a good job of keeping tasks in issues, where they can be detailed, discussed and planned. Some directories had not been added at first, as we focused on the code we shipped, but we're not far off doing this across the project.
=> Tighten TODO check to all directories

.github/dependabot.yml, .github/workflows/codeql-analysis.yml
Resolving a deprecation warning:
https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
Also enabling Dependabot scanning of GitHub Actions (https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions).
=> Update CodeQL GitHub Actions to v3

src/js/core/runtime.h
Restoring intended initial values for these 2 bools, which were accidentally updated to verbose-by-default in a recent refactor.
=> Don't log JS exception details by default

.github/workflows/bencher_process.yml, .github/workflows/bencher_run.yml
Based on Bencher's [example](https://github.com/bencherdev/example/blob/main/.github/workflows/track_fork_pr_benchmarks.yml), we split the yaml in 2:
- `bencher_run.yml` runs on our runner, on PRs from our forks, and gathers benchmark results, uploading them as workflow artifacts
- `bencher_process.yml` runs based on the version in `main`, with access to secrets, downloads the prior artifacts and uploads them to bencher
Note that I differ from the pure sample here, and try to do this process for pushes to `main` as well as PRs. I'd like to minimise the number of workflows if possible, but will revert and have a standalone main CB workflow if necessary.
=> Run Bencher on PRs, upload results from workflow trigger

.github/workflows/bencher_process.yml, README.md
Seeing how the current Bencher config handles fork PRs (NB: Forked from a commit where bencher tests ran on main).
Unsure _why_ its unable to post comments, but it is, so removing that for now.
=> Update Bencher github-script versions, remove github-actions attempt

include/ccf/js/core/context.h, include/ccf/js/core/runtime.h, include/ccf/js/registry.h, include/ccf/service/tables/jsengine.h, src/apps/js_generic/js_generic_base.cpp, src/js/core/context.cpp, src/js/core/runtime.cpp, src/js/extensions/ccf/gov_effects.cpp, src/js/registry.cpp, src/node/gov/handlers/proposals.h, src/node/rpc/member_frontend.h, src/node/rpc/node_frontend.h
This was previously using the hard-coded, governance controlled JSEngine table. We now avoid reading directly from the KV deep in the execution flow, and instead pass in the runtime options at the call-point. For the `DynamicJSEndpointRegistry`, that's expected to be stored in another prefix-named table.
Eagle-eyed viewers will note we currently have no way to _populate_ that table. That's coming shortly, in another PR, with a broader expansion of the methods exposed by `DynamicJSEndpointRegistry`.
=> Ensure `DynamicJSEndpointRegistry` can control its own runtime options

include/ccf/js/common_context.h, src/apps/js_generic/js_generic_base.cpp, src/js/registry.cpp, src/node/gov/handlers/proposals.h, src/node/rpc/member_frontend.h
I added this `CommonContext` so we wouldn't have to list the same basic extensions everywhere, but then didn't use it for the app interpreters (`js_generic` and `registry.cpp`). This rejigs things a little so its useable in those situations.
=> Get intended reuse from `CommonContext`

.github/workflows/ci-checks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/daily-check.yml
This adds buttons to trigger manual runs, that might be useful for these workflows. Prompted by a flaky CodeQL run.
=> Add `workflow_dispatch` triggers to more GHA workflows

doc/schemas/gov_openapi.json, include/ccf/js/registry.h, include/ccf/service/tables/jsengine.h, samples/apps/basic/basic.cpp, src/js/registry.cpp, src/node/rpc/member_frontend.h, tests/infra/clients.py, tests/programmability.py
Part of #6223.
Slightly different semantics than the governance equivalent (`set_js_runtime_options`), which I find slightly cumbersome. Instead the (sample) endpoint accepts a `PATCH` request, with `null` values permitted to reset any field to its default. To support that, we change the serialisation of this `JSRuntimeOptions` object to be more permissive on deserialisation (where previously it had a sharp distinction between the original fields and those added later), and verbose on serialisation.
=> Add setters and getter for JS runtime options, and sample HTTP APIs

include/ccf/js/registry.h, src/js/registry.cpp
Not critical, but helpful for parity with `js_generic` deployed apps. This means that the builtin `/api` endpoint will document endpoints defined in JS. One major benefit of this is that we can reuse more of the existing e2e tests (which check that certain endpoints are available, via `GET /api`) with the new app-space JS deployment flow.
=> Implement `build_api` in `DynamicJSEndpointRegistry`

src/node/test/channels.cpp
Closes #5853
- Was able to repro same sort of failure locally by playing around with `sleep`s.
- Changing pure sleep to a more robust waiting + additional checks for messages to arrive.
- In case it reproduces, we'll be able to distinguish corrupted messages from messages never sent.
=> Smart wait for msg to arrive in channel test

samples/apps/basic/basic.cpp, samples/apps/basic/js/src/basic.js, src/js/registry.cpp, tests/e2e_logging.py, tests/programmability.py
~~(Opening as a draft because I've pulled some unrelated changes into other PRs. Would like to merge those first and rebase)~~
Closes an outstanding item from #6223.
Check if the endpoints are marked as `historical` in the same we do in `js_generic`. Test this (and many other JS APIs!) by running the full `e2e_logging` test suite on the `basic` app, with the JS logging app deployed via `PUT /custom_endpoints`.
=> Support `historical` mode endpoints in `DynamicJSEndpointRegistry`

getting_started/setup_vm/roles/openenclave/vars/common.yml
- [Update from Open Enclave 0.19.4 to 0.19.6 (#6262)](https://github.com/microsoft/CCF/pull/6262)
=> [release/4.x] Cherry pick: Update from Open Enclave 0.19.4 to 0.19.6 (#6262)

tests/infra/basicperf.py
Warnings before:
```
81: sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
81: sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
81: /data/src/2.CCF/tests/infra/basicperf.py:563: DeprecationWarning: Use of `how='outer'` should be replaced with `how='full'`.
```
=> Fix polars deprecation warnings

.azure-pipelines-gh-pages.yml, .azure-pipelines-templates/deploy_aci.yml, .azure-pipelines.yml, .azure_pipelines_snp.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .github/workflows/tlaplus.yml, .multi-thread.yml, .stress.yml, CHANGELOG.md, cmake/cpack_settings.cmake, cmake/open_enclave.cmake, docker/ccf_ci_built, scripts/azure_deployment/arm_aci.py
- [Update to use latest CI image containing Open Enclave 0.19.6 (#6263)](https://github.com/microsoft/CCF/pull/6263)
=> [release/4.x] Cherry pick: Update to use latest CI image containing Open Enclave 0.19.6 (#6263)

.github/workflows/ci-containers-ghcr.yml
See discussion in #6273, this makes for linear tag histories per image name, and make attestation much clearer.
=> Per-platform image names (#6273)

.azure-pipelines-gh-pages.yml, .azure-pipelines-templates/deploy_aci.yml, .azure-pipelines.yml, .azure_pipelines_snp.yml, .daily.yml, .devcontainer/devcontainer.json, .github/workflows/ci-checks.yml, .github/workflows/tlaplus.yml, .multi-thread.yml, .stress.yml, CHANGELOG.md, cmake/cpack_settings.cmake, cmake/open_enclave.cmake, docker/ccf_ci_built, getting_started/setup_vm/roles/openenclave/vars/common.yml, scripts/azure_deployment/arm_aci.py
- [Upgrade base to open enclave 0.19.7 (#6293)](https://github.com/microsoft/CCF/pull/6293)
=> [release/4.x] Cherry pick: Upgrade base to open enclave 0.19.7 (#6293)

tests/fuzzing.py
Follow up to #6292. Despite using `/dev/shm`, this is _still_ sometimes slow. So try aggressively removing the component entirely.
=> Remove boofuzz's database logger

.github/workflows/build.yml, .github/workflows/tlaplus.yml, src/node/rpc/test/frontend_test.cpp
Too many runs otherwise, especially when working on the release pipeline, which needs a branch + tags.
=> Only run CI and TLA jobs on pushes to main, not to other branches

.github/workflows/codeql-analysis.yml
With the CI job now run in-container, and with executors being re-used in the private pool to improve efficiency, there end up being directories created by root (inside the container) that the checkout step on non-container jobs is unable to clean up.
One possible solution is to move all jobs run in private pools to container images. I remembered, probably incorrectly, that CodeQL could not be run in a container. But that does not seem to be the case now, there are only a few requirements, which I think we meet: https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/running-codeql-code-scanning-in-a-container
=> Run CodeQL in container

tests/infra/clients.py
`programmability` is failing occasionally, because we print COSE request bodies, and those sometimes contain thing that look like loguru tags.
=> Escape loguru tags in request body

.github/workflows/build.yml, src/host/main.cpp, src/host/tcp.h, tests/fuzzing.py
`fuzz_test` is still extremely flaky following #6308, with some runs having a very low throughput (<200/s) and eventually timing out.
Adding some logging to confirm the monkey-patch is present and has made a difference.
EDIT - After additional investigation, got local repro (requires SGX Debug Verbose), and found the spammy logs that are slowing things down.
=> `fuzz_test`: Reduce logging spam at allocation quotas, to avoid test timeouts

src/host/snapshots.h
Noticed while debugging something else. If we can't open a snapshot (eg - reached fd limit), this code won't blow up but will log what's clearly an error (roughly `New snapshot file written to 5.snapshot [99999999999 bytes]`). This catches the OP failure earlier, and reports it as such.
Note that we're already robust to this failure in the sense that all snapshot attempts are best-effort - if the file already existed, or this fails, we still clear the `pending_snapshot`.
=> Cleaner error when we can't open a new snapshot file

CMakeLists.txt
We read `cchost_config.json` into a variable, and then `configure_file` to dump that into a `.h.in` file. But this doesn't add an automatic dependency - we don't rebuild when `cchost_config.json` changes. Usually that's not noticed, because some _other_ change to `cchost` has caused a reconfigure/rebuild, but it's annoying when you're iterating on this file exclusively.
=> Correctly track CMake dependencies for file reads

.github/workflows/README.md, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/tlaplus.yml
1. Remove re-triggers on push on main, for things that have just been tested on the branch. Our enforcement of linear history means we run the same build twice, unnecessarily.
2. Add weekly trigger for such jobs, so that they are triggered periodically enough to detect externally induced breaks, even if their normal trigger condition is not met for a while.
3. Cancel jobs running against older commits: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
=> Update CI triggers

src/host/rpc_connections.h
Avoid spamming the output when session closure flow doesn't match idle times.
=> Zero out idle time when deallocating the socket

.azure_pipelines_snp.yml
ACI CI only runs on schedule (midnight daily), or designated PRs to reduce number of runs and container leaks when deprovisioning fails, which is unfortunately quite common now.
=> Do not run ACI CI on every commit

.azure-pipelines-gh-pages.yml, .devcontainer/devcontainer.json, .github/workflows/bencher.yml, scripts/azure_deployment/arm_aci.py, src/endpoints/endpoint_utils.cpp
Documentation is still on ADO for now, but switched to `:latest`, so does the dev container. Neither requires reproducibility.
Bencher updates to a versioned CI image from GHCR.
=> Update azp base images

src/host/rpc_connections.h
In #6358, we introduced tcp::tcp_closed confirmation even if the enclave doesn't now about the session (see PR for details on why).
This started triggering more fail logs in the flows like that
- host initiates cleanup() call from on_disconnect(), tcp_close is sent to enclave
- enclave fails to parse http request and decides to kill the session, goes through stop() and sends tcp_stop to the host
- host responds to stopping with another tcp_close (which is not good, but chaning this requires more verification, so not done here)
- first tcp_closed confimaton goes from TLSSession destructor
- seconds comes from the unconditional confimation introduced in #6358 as a side effect of that change.
The log level is now reduced to info as soon as there's no flow failure in here.
=> Reduce fail->info on missing session id on close

python/pyproject.toml
Default describe picks up all tags, some of which are not versions.
```
$ git describe --tags --long
build/25-07-2024-1-g71b6758f0
$ git describe --tags --long --match ccf-*
ccf-5.0.0-17-g71b6758f0
```
=> Add `git_describe_command` for `setuptools_scm`

.azure-pipelines-templates/deploy_aci.yml, scripts/azure_deployment/arm_aci.py
Trying to work out why SNP is failing in check deployment.
Guessing that we now create some new kind of resource (a delegated manged identity?) that doesn't contain an `ip_address` field. Simplest debugging method is to dump the whole object.
EDIT - the problem was [a missing escape](https://github.com/microsoft/CCF/pull/6398/commits/d9fdb0386a8ddf15de466600ccf034418bdc60f7).
=> Fix SNP deploy step

.backportrc.json
`3.x` is out of support, `release/5.x` is imminent.
=> Update Backport branches

CHANGELOG.md, include/ccf/crypto/rsa_key_pair.h, include/ccf/crypto/rsa_public_key.h, js/ccf-app/src/global.ts, js/ccf-app/src/polyfill.ts, js/ccf-app/test/polyfill.test.ts, src/crypto/openssl/rsa_key_pair.cpp, src/crypto/openssl/rsa_key_pair.h, src/crypto/openssl/rsa_public_key.cpp, src/crypto/openssl/rsa_public_key.h, src/crypto/test/crypto.cpp, src/js/extensions/ccf/crypto.cpp, tests/infra/crypto.py, tests/npm_tests.py
=> Replace RSASSA-PKCS1-v1_5 with RSA-PSS in crypto API

doc/conf.py
1. Stop building documentation for unsupported 3.x branch
2. Remove historical mentions of Microsoft Research
=> Stop building documentation for CCF 3.x

.github/ISSUE_TEMPLATE/bug_report.md, getting_started/setup_vm/app-dev.yml, getting_started/setup_vm/app-run.yml
Next step in #6413, note that ccf-dev.yml retains SGX dependencies so we can continue to update build images from the main branch.
=> Remove SGX-specific dependencies from release playbooks

python/utils/verify_quote.sh
If talking to load balancer, we might retrieve node quotes for node 1, and then talk to node 2 when checking the public key. To make this work unconditionally, we now check all quotes until we find a match or report that there's no match.
=> Fixup verify quote script for load balancer

.github/workflows/tlaplus.yml, tests/raft_scenarios_runner.py
This change archives the traces, simplifying the process for users to experiment with TLA+ trace validation by eliminating the need to compile and run CCF.
The uncompresses traces only measure 124KB in size.
=> Ensure raft traces are always uploaded as workflow artifacts.

.devcontainer/tlaplus/devcontainer.json, tla/install_deps.py
TLA+ vscode extension moved, as described here https://github.com/tlaplus/vscode-tlaplus/issues/318
=> Update TLA+ dev container to include new TLA+ vscode extension

src/host/ledger.h, tests/recovery.py
=> Test and fix recovery with snapshot without ledger

.github/workflows/containers-ghcr.yml, .github/workflows/release.yml
=> Remove SGX target from release job(s)

.github/workflows/tlaplus.yml
"Error: Failed to CreateArtifact: Received non-retryable error: Faile…d request: (409) Conflict: an artifact with this name already exists on the workflow run"
Failed e.g. in https://github.com/microsoft/CCF/actions/runs/10968475748/job/30459866526
=> `upload-artifact` Github action fails because of non-unique artifact names.

.azure-pipelines-release.yml, CHANGELOG.md
Barring unforeseen last minute patches, this will be the last 4.x release. Support for 4.x [ends on 25/10/2024](https://microsoft.github.io/CCF/main/build_apps/release_policy.html#support-calendar).
=> Update base image and release notes for 4.0.22

tla/consensus/MCabs.cfg, tla/consensus/MCabs.tla, tla/consensus/abs.tla
* Refactor (simplify) TypeOK to use (more concise) Sequences!Seq operator.
* Define InitialLogs less explicitly.
* Add assumptions about abs.tla's constants (TLAPS will likely need those assumptions should we attempt writing a proof).
* Mitigate state-space explosion during explicit-state model checking by declaring constant Servers to be symmetric.
=> Refactor abstract consensus specification

.github/workflows/README.md, .github/workflows/ci-containers-ghcr.yml, .github/workflows/ci-verification.yml, .github/workflows/ci.yml, .github/workflows/long-verification.yml
As discussed with @lemmy on Friday, this PR splits off the long running parts of the verification to a label-triggered (+weekly) job.
Most of the verification steps remain as is, only a the reconfiguration model checking and the longer-running simulation is now triggered on `run-long-verification`-labeled PRs.
=> Split Verification Jobs

tla/consensus/MCccfraft.cfg, tla/consensus/MCccfraft.tla, tla/consensus/SIMccfraft.cfg, tla/consensus/SIMccfraft.tla
Part of "Run TLA+ consensus/consistency from vscode" #6490
https://github.com/microsoft/CCF/issues/6490
=> Remove writing state-space statistics after the demise of cimetrics.

.github/workflows/ci-containers-ghcr.yml
Not needed on main anymore, 5.x releases are best done using base images obtained by tagging `release/5.x`, which is already the case in practice.
=> Remove SGX base image building

tla/consensus/MCabs.cfg, tla/consensus/MCabs.tla, tla/consensus/MCccfraft.cfg, tla/consensus/MCccfraft.tla, tla/consensus/SIMccfraft.cfg, tla/consensus/SIMccfraft.tla, tla/consensus/abs.tla, tla/consensus/ccfraft.tla
Declared `abs!StartTerm` as a constant because TLC cannot evaluate non-enumerable `Min(Nat \ 0..StartTerm-1)`.
[Refactor]
=> Remove redefinitions of Terms in refinement mapping.

.github/workflows/long-verification.yml
The trigger works, but the jobs get skipped: https://github.com/microsoft/CCF/actions/runs/11224798043
Adding labels just because that's an easy way to get a run before this gets merged.
=> Allow manual runs of long verification

python/pyproject.toml, scripts/extract-release-notes.py
Closes #6546. Note that pyproject.toml needs to be updated at the same as CHANGELOG, ahead of releases, from now on.
=> Remove setuptools_scm and set version in pyproject.toml

tla/consensus/ccfraft.tla
(TLC can also evaluate some of the new definitions more efficiently)
=> Strengthen various *TypeInvs by defining every function's domain.

.github/workflows/ci.yml, CMakeLists.txt, cmake/ccf_app.cmake, src/ds/lru.h, src/ds/test/dl_list.cpp, src/node/history.h, src/node/rpc/test/frontend_test.cpp
Pre-requisite to Azure Linux migration. Adds a `USE_LIBCXX` cmake flag, make the few tweaks needed for the build to work with the version we have easily available on Ubuntu 20.04, and add a CI job to avoid regression before we complete the move.
=> Libstdc++ compatibility

src/service/internal_tables_access.h
Missed during #6555. A temporary passed to headers factory, UB at construction.
=> Fix memory corruption for COSE headers construction

src/http/http_accept.h
Fixes non-deterministic sorting, which was found when migrating to Azure Linux.
Was `a.x < b.y AND a.y < b.y`, meaning that `if a.x < b.x` **but** `a.y > b.y` then arguments will be considered equal, which is clearly not intended (both due to test issue and comment inside the comparator code).
=> Fix header parser comparator

CHANGELOG.md, include/ccf/crypto/curve.h, include/ccf/crypto/jwk.h, js/ccf-app/src/global.ts, js/ccf-app/test/polyfill.test.ts, src/crypto/openssl/public_key.cpp, src/crypto/test/bench.cpp, src/crypto/test/crypto.cpp, src/js/extensions/ccf/crypto.cpp, tests/npm_tests.py
=> Remove secp256k as unsupported by symcrypt on Mariner

CHANGELOG.md, include/ccf/crypto/cose.h, python/pyproject.toml, python/src/ccf/cose.py, samples/apps/logging/logging.cpp, src/crypto/cose.cpp, src/crypto/test/cose.cpp, tests/e2e_logging.py
=> Extend set_unprotected_header() to allow setting an empty header, and verify_receipt() to check claim_digest

src/node/historical_queries.h
During investigation of #6594 I found out that we may read `map::end()`. It revealed as infinite loop in the debugger:
```
NameError: name 'lldb' is not defined
* thread #1, name = 'historical_quer', stop reason = signal SIGSTOP
* frame #0: 0x00007ffff78273e7 libstdc++.so.6`std::_Rb_tree_increment(std::_Rb_tree_node_base*) + 23
frame #1: 0x0000555555679b3c historical_queries_test`std::_Rb_tree_iterator<std::pair<unsigned long const, std::shared_ptr<ccf::historical::StateCacheImpl::StoreDetails>>>::operator++(this=0x00007fffffff9ba8) at stl_tree.h:287:12
frame #2: 0x000055555567b53e historical_queries_test`std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::shared_ptr<ccf::historical::StateCacheImpl::StoreDetails>>, std::_Select1st<std::pair<unsigned long const, …
```
=> Fix accessing invalid iterator in historical state

src/crypto/openssl/public_key.cpp
Check #6594 for more details.
Long story short, I was not able to figure out why we used `d2i_PublicKey`, as I didn't really find an example of it in OpenSSL to be used together with `*_from_data` functions.
I've tweaked the params to pass the raw key data there and simply called `EVP_PKEY_fromdata` with `EVP_PKEY_PUBLIC_KEY` selection, and it seems to work just well.
=> OpenSSL 3.3: proper public key loading for EC keys

CHANGELOG.md, doc/build_apps/api.rst, doc/build_apps/js_app_bundle.rst, include/ccf/common_auth_policies.h, include/ccf/endpoint.h, include/ccf/endpoints/authentication/cert_auth.h, include/ccf/endpoints/authentication/js.h, js/ccf-app/src/endpoints.ts, python/pyproject.toml, samples/apps/logging/js/app.json, samples/apps/logging/js/src/logging.js, samples/apps/logging/logging.cpp, src/endpoints/authentication/cert_auth.cpp, src/js/extensions/ccf/request.cpp, tests/e2e_logging.py, tests/npm-app/app.json, tests/npm-app/src/endpoints/auth.ts
Add `ccf::any_cert_auth_policy` (C++)/ `"any_cert"` (TS/JS) to allow applications to configure certificate-based authentication with application-managed certificates, i.e. neither CCF users nor members, but application-level users.
=> Any cert authn policy

doc/build_apps/install_bin.rst, doc/contribute/build_setup.rst, doc/operations/run_setup.rst, getting_started/setup_vm/ccf-dev.yml
Follow-up to #6447. Changing defaults and updating docs to simplify install for SNP/virtual.
=> Trim SGX-specific packages from playbooks

src/node/history.h
Pulling standalone fixes out of #6616 to be merged separately.
Hidden by our suppressions file, but the `snapshot_test` unit test spots a lock inversion:
```
$ ./snapshot_test 
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
==================
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=63651)
Cycle in lock order graph: M0 (0x7b4400000be8) => M1 (0x7ffcc1b2f898) => M0
Mutex M1 acquired here while holding mutex M0 in main thread:
#0 pthread_mutex_lock <null> (snapshot_test+0x8051a) (BuildId: ba8a8b25dd81ecc61267ef6b9ef050dfb1148ded)
#1 std::__1::mutex::lock() <null> (libc++.so.1+0x4af15) (BuildId: e3dee72a81fed73680e4d05b6858c5327d95f499)
#2 ccf::kv::BaseTx::get_map_and_change_set_by_name(std::__1::basic_string<char, …
```
=> Delay lock taking slightly

src/node/node_state.h, src/node/rpc/node_call_types.h, src/node/rpc/node_frontend.h, src/node/rpc/serialization.h
Looking at the join RPC while adding COSE signatures issuer and subject, and these are unused.
=> Remove deprecated fields

src/kv/store.h
Without a lock, this is race-y access to `term_of_last_version` and `rollback_count`, which are normally protected by `version_lock`. There's a comment suggesting this should already have been acquired, but it definitely hasn't in the `MerkleTreeHistoryPendingTx::call()` path. It's not clear to me where it ever _was_ previously held.
=> Take `version_lock` when creating reserved Tx

src/node/rpc/cose_signatures_config.h, src/node/rpc/node_call_types.h, src/node/rpc/node_frontend.h, src/node/rpc/serialization.h
Prelude to adding support for COSE signatures issuer and subject configuration, which needs to be backported to 5.x to allow join compatibility.
=> Compatibility for cose_signatures_config field in /join response

src/kv/test/kv_contention.cpp
We've seen a single failure of this test when backporting a recent locking change.
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=87860&view=logs&j=b6a3fffa-f95e-580b-9bcb-4ae7d4681578&t=7439823f-f6a2-5514-9be9-467f4c602fdd&l=145
```
test 6
Start  6: kv_test
6: Test command: /CCF/build/kv_test
6: Environment variables: 
6:  TSAN_OPTIONS=suppressions=/CCF/tsan_env_suppressions
6:  ASAN_OPTIONS=alloc_dealloc_mismatch=0
6: Test timeout computed to be: 10000000
6: [doctest] doctest version is "2.4.11"
6: [doctest] run with "--help" for options
6: ===============================================================================
6: ../src/kv/test/kv_contention.cpp:253:
6: TEST SUITE: concurrency
6: TEST CASE:  get_version_of_previous_write ordering
6: 
6: …
```
=> Increase number of writes in concurrency test to ensure conflict

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/task.md
I've converted all issues, I think this is neater than and complementary with labels.
=> Update issue templates to use type

src/node/rpc/cose_signatures_config.h, src/node/rpc/node_call_types.h, src/node/rpc/node_frontend.h, src/node/rpc/serialization.h
- [Compatibility for cose_signatures_config field in /join response (#6632)](https://github.com/microsoft/CCF/pull/6632)
=> [release/5.x] Cherry pick: Compatibility for cose_signatures_config field in /join response (#6632)

tests/infra/e2e_args.py, tests/infra/remote.py
- Change default debugger to lldb
- Update DEFAULT_ENCLAVE_PLATFORM to use PLATFORM file, as `sandbox.sh` does
Without these changes, running an e2e test with `-d 0` resulted in generating an SGX directory and command, using cgdb, which does not work well with the current binaries.
=> Fix node debugging in e2e tests

tests/infra/interfaces.py
Fixes:
```
56:   File "/usr/lib/python3.12/dataclasses.py", line 1268, in dataclass
56:     return wrap(cls)
56:            │    └ <class 'infra.interfaces.NodeByRoleResolver'>
56:            └ <function dataclass.<locals>.wrap at 0x7f6a3b28e160>
...
56:   File "/usr/lib/python3.12/dataclasses.py", line 852, in _get_field
56:     raise ValueError(f'mutable default {type(f.default)} for field '
56: ValueError: mutable default <class 'infra.interfaces.TargetRole'> for field target is not allowed: use default_factory
```
Part of #6588
=> Azure Linux: tweak dataclass for compatibility with python 3.12

src/enclave/tls_session.h
Resolves #6619 
Checked w/o the macro on virtual (openssl 1.1.1), adding these calls doesn't really break anything, but I'm inclined to keep them until we remove all ssl macros in the future.
=> Support BIO read/write retries in OpenSSL 3.3

CHANGELOG.md, python/pyproject.toml, src/node/identity.h, tests/lts_compatibility.py
Follow-up to #5993.
When 5.x nodes join from pre-5.x nodes, they end up with a default `subject_name` (they get it in the join response, where it wasn't populated so had a default value). If they then try to renew the service cert, they'll cause a change in the service name. This is the minimal fix - ignore the serialised `subject_name` field, and always extract it from the given service identity.
This includes a small extension to the `lts_compatibility` test to verify this behaviour. When run on the 5.x branch, this caused a failure without the C++ change, and passes with the C++ change.
I'd like to make a more systematic cleanup of `identity.h` to remove some dead code and simplify the constructor paths, but will do that separately from this minimal fix.
=> When joining, always retrieve the service's `subject_name` from the given cert

CHANGELOG.md, src/node/identity.h, tests/lts_compatibility.py
- [When joining, always retrieve the service&#x27;s &#x60;subject_name&#x60; from the given cert (#6660)](https://github.com/microsoft/CCF/pull/6660)
=> [release/5.x] Cherry pick: When joining, always retrieve the service's `subject_name` from the given cert (#6660)

CHANGELOG.md, python/pyproject.toml, src/crypto/openssl/key_pair.cpp, src/crypto/test/crypto.cpp, tests/e2e_logging.py
Complement to #6660 as a follow up for #5993, to fix service endorsements for networks that have updated their service subject_name, and generally avoid depending on the OpenSSL quirk described in https://github.com/blaufish/openssl-pathlen/blob/master/README.md#rfc5280-self-issued-loop-hole
=> Extend pathlen for CAs

CHANGELOG.md, include/ccf/ds/json_schema.h, include/ccf/ds/openapi.h, src/ds/test/openapi.cpp
- [Schema support for std::unordered_set (#6634)](https://github.com/microsoft/CCF/pull/6634)
=> [release/5.x] Cherry pick: Schema support for std::unordered_set (#6634)

CHANGELOG.md, include/ccf/http_query.h, python/pyproject.toml, src/http/test/http_test.cpp
=> Add bool support to get_query_value()

CHANGELOG.md, src/crypto/openssl/key_pair.cpp, src/crypto/test/crypto.cpp, tests/e2e_logging.py
- [Extend pathlen for CAs (#6662)](https://github.com/microsoft/CCF/pull/6662)
=> [release/5.x] Cherry pick: Extend pathlen for CAs (#6662)

src/node/node_state.h
We've printed this pretty unhelpful line for a long time:
```
Deserialising public ledger entry [42]
```
42 is the number of bytes in this entry, we print no sign of how many entries we've actually processed, even though we know this. I think we should actually print summaries, but since we're already printing once-per-entry I've at least made it explicit which entry we think we're looking at.
=> Log progress of deserialising ledger during recovery

src/host/ledger.h
Seeing if this breaks anything in the CI, otherwise it seems like a clear correctness win.
=> Open `.committed` files read-only

src/node/rpc/frontend.h
For nodes that don't have an RPC interface with the default name "primary_rpc_interface", we'd print this:
```
Could not find startup config for interface primary_rpc_interface
```
for every forwarded requests. Spammy, ugly. Now we don't do that.
=> Don't try to access redirect config for forwarded requests

include/ccf/node/cose_signatures_config.h, include/ccf/node/startup_config.h, src/host/configuration.h, src/js/extensions/ccf/network.cpp, src/kv/kv_types.h, src/node/history.h, src/node/identity.h, src/node/node_state.h, src/node/rpc/node_call_types.h, src/node/rpc/node_frontend.h, src/node/rpc/node_interface.h, src/node/rpc/node_operation.h, src/node/rpc/node_operation_interface.h, src/node/rpc/serialization.h, src/node/rpc/test/frontend_test_infra.h, src/node/rpc/test/node_stub.h, src/node/test/historical_queries.cpp, src/node/test/history.cpp, src/node/test/snapshot.cpp, tests/lts_compatibility.py
Following #6660, this PR simplifies the `NetworkIdentity` type by flattening it to a single type. The core of the changes are those in `identity.h`, which removes `ReplicatedNetworkIdentity` and several fields from `NetworkIdentity`. This touches a bunch of other files for 2 reasons:
- Moved `COSESignaturesConfig` under the `ccf::` namespace, since it is in a public header.
- Rather than accessing `cose_signatures_config` from `NetworkIdentity`, the `/join` endpoint in `node_frontend.h` now accesses the single instance stored in/owned by `history.h`, which takes a few hops to reach. I think some of these hops are helpful, some may be unnecessary, but regardless this fits the existing style.
While we're doing this, be slightly stricter about the order of calls to history, and ensure we …
=> Simplify `NetworkIdentity` type

js/ccf-app/package.json, tests/js-interpreter-reuse/package.json, tests/js-interpreter-reuse/src/SlowConstructorService.ts, tests/npm-app/package.json
- [Address NPM version incompatibilities (#6679)](https://github.com/microsoft/CCF/pull/6679)
=> [release/5.x] Cherry pick: Address NPM version incompatibilities (#6679)

.azure-pipelines-release.yml, .azure-pipelines-templates/deploy_aci.yml, .azure_pipelines_snp.yml, .github/workflows/bencher.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/long-test.yml, .github/workflows/release.yml, .github/workflows/tlaplus.yml, CHANGELOG.md, cmake/cpack_settings.cmake, cmake/open_enclave.cmake, docker/ccf_ci_built
Follow up to #6685 using the build image created after it was merged to `release/5.x`.
=> Update to 05-12-2024 build image

.github/workflows/bencher.yml, src/apps/tpcc/app/tpcc.cpp
Including juggling of #6684 broke the TPCC build, which we only see in Bencher runs, which are only triggered on `main` commits.
This fixes the includes, and while we're here adds a cronjob schedule trigger for Bencher runs.
=> Fix TPCC build, add scheduled Bencher runs

.CodeQL.yml
This affects analyses running in CodeQL Central, but doesn't interact at all with the CodeQL CLI (aka - can't be tested locally). Guessing at field names from limited docs and other instances on GitHub.
=> Add a `.CodeQL.yml` file

tests/infra/crypto.py
Following #6695 (and #6379), this adds a CodeQL suppression for complaints about the key size.
=> Add a CodeQL suppression

CHANGELOG.md, python/pyproject.toml, python/src/ccf/merkletree.py, python/src/ccf/read_ledger.py, tests/governance_history.py
We noticed the `read_ledger.py` tool was surprisingly slow, meaning it was not helpful for verifying the integrity of large ledgers. This PR includes a few isolated, relatively non-controversial improvements:
- Add a `--quiet` flag to `read_ledger.py`. Printing a digest to terminal, per-transaction, was a major bottleneck. Further options to pipe transaction contents or summaries to files might be helpful in future, but aren't needed now.
- After that, the merkle tree's `get_merkle_root` was taking most of our time.
- First we cache the root for a given tree, rather than re-calculating it each time `get_merkle_root()` is called (for an otherwise unchanged tree). We get the root from separate calls for COSE signatures vs old signatures, without modifying the tree
- Then we change the …
=> Python ledger optimisations: Add a `--quiet` flag, and reuse calculated values in MerkleTree

CHANGELOG.md, cddl/ccf-merkle-tree-cose-signature.cddl, python/src/ccf/cose.py, src/crypto/openssl/cose_sign.cpp, src/crypto/openssl/cose_sign.h, src/node/history.h
This allows exposing keys in both binary and text formats more easily, since we will probably need to support both for the foreseeable future.
=> Encode COSE signature kids to hex to make them text-format friendly

CHANGELOG.md, doc/build_apps/api.rst, include/ccf/app_interface.h, python/pyproject.toml, src/enclave/enclave.h
This FFI plugin system is unused. Similar functionality is now available via `DynamicJSEndpointRegistry::get_extensions()`, and I think the similar naming of this is just confusing. Proposing that we deprecate it in 6.0.0, and remove implementation and all references shortly after.
=> Deprecate `get_js_plugins()`

tests/npm_tests.py
Partially closes #6588 ([check this out](https://github.com/microsoft/CCF/issues/6588#issuecomment-2568037993) + related comments in the thread for more details on the issue).
PEM differs after being converted to JWK and back due to math missmatch in openssl implementation (see ticket for details).
Replaced PEM comparison with signature verification.
=> Workaround private pem missmatch in e2e tests

CHANGELOG.md, doc/schemas/gov_openapi.json, include/ccf/crypto/ecdsa.h, include/ccf/crypto/jwk.h, include/ccf/crypto/rsa_public_key.h, include/ccf/endpoints/authentication/jwt_auth.h, include/ccf/service/tables/jwt.h, samples/constitutions/default/actions.js, src/crypto/ecdsa.cpp, src/crypto/openssl/rsa_public_key.cpp, src/crypto/openssl/rsa_public_key.h, src/endpoints/authentication/jwt_auth.cpp, src/http/http_jwt.h, src/js/extensions/ccf/crypto.cpp, src/node/gov/handlers/service_state.h, src/node/rpc/jwt_management.h, src/node/rpc/member_frontend.h, src/service/network_tables.h, tests/infra/crypto.py, tests/infra/jwt_issuer.py, tests/js-custom-authorization/custom_authorization.py, tests/jwt_test.py
Closes https://github.com/microsoft/CCF/issues/6601
**Key points**
* `JsonWebKeyData` created to avoid further changes in JsonWebKey, which is used for UVM endorsements parsing, as well as a base class for a plethora of key classes, which in turn are used in various key conversion APIs. Didn’t have enough courage to change that here.
* Crypto hierarchy issues ( #6673 ) are not addressed here, but using RSA keys instead of misused EC keys has been fixed.
* Following the approach of #6175, the new key metadata table has been introduced to work with the new tables, previous metadata becomes “legacy” alongside old `public_signing_key` and `public_signing_key_issuer` tables. These are to be pruned in #6222, the ticket has been updated to mention the current change.
* `nbf` claim is no longer …
=> Raw public keys support for JWT authentication

tests/start_network.py
This PR adds parameters to the start-network.py script to start a network with redirection.
=> Enable redirection when starting a network

.azure-pipelines-release.yml, .azure-pipelines-templates/deploy_aci.yml, .azure_pipelines_snp.yml, .github/workflows/bencher.yml, .github/workflows/ci-verification.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/long-test.yml, .github/workflows/long-verification.yml, .github/workflows/release.yml, docker/ccf_ci_built, getting_started/setup_vm/ccf-dev.yml, getting_started/setup_vm/roles/az_dcap/tasks/install.yml
Taking a step back after #6737 and #6739. We have been cutting CI images (`build/YYYY-MM-DD`) from `release/5.x` so as to get enough SGX attestation-verification dependencies to run the LTS compatibility tests in CI.
Local tests suggest that adding `az-dcap-client` is sufficient to start 5.x-era nodes (who link oehost), and is likely the smallest delta we can apply to be able to cut CI images from main. This in turn will let us make changes like #6739, which cannot be backported to 5.x without substantial associated changes and risk.
=> Add az-dcap-client back to main for now, to enable LTS-compatible base images

.azure-pipelines-templates/daily-matrix.yml, .azure-pipelines-templates/release-matrix.yaml, .github/workflows/ci-verification.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/long-test.yml, CMakeLists.txt
Unused since SGX removal, but did not trigger any warnings because the conflict check with *SAN effectively "used" the flag.
=> Remove unused LVI_MITIGATIONS flag

README.md
Odd that we failed to spot this for so long, almost as if the text was encrytped the entire time.
=> Correct readme typo

tests/start_network.py
This PR fixes a bug in the backup redirection config which is incorrectly pointing to the primary node.
=> Fixed the backup redirection config in the start_network.py

cmake/cpack_settings.cmake
Missed when curl was added as a dependency, meaning the 6.0.0-dev12 deb has a missing dependency.
=> Add curl as a dependency in cpack

CHANGELOG.md, python/pyproject.toml
This new feature was incorrectly added to the `dev12` changelog section, after `dev12` had been cut.
=> Prepare release notes for `6.0.0-dev13`

CHANGELOG.md, cmake/cpack_settings.cmake, getting_started/setup_vm/roles/ccf_build/tasks/install.yml, getting_started/setup_vm/roles/ccf_build/vars/clang15.yml, getting_started/setup_vm/roles/ccf_run/tasks/install.yml, getting_started/setup_vm/roles/ccf_run/vars/clang15.yml, python/pyproject.toml
Follow up to #6772, which had optimistically assumed that the Ubuntu 20.04 default (-9) was satisfactory. That is not in fact the case, it is missing `<span>` for example. -11 is installed in CI/ccf-dev contests through piccolo->parquet, which was hiding this problem until an application tried to use a -dev container.
=> Ensure the right version of libstdc++(11) is installed

CHANGELOG.md, getting_started/setup_vm/roles/ccf_install/tasks/deb_install.yml, python/pyproject.toml
`app-run` image building failed in dev14 because the ppa is not added in the corresponding playbook.
=> Fix app run container

src/crypto/openssl/openssl_wrappers.h
Memory used to be a hard constraint, it's not so bad now. I don't think we ever produce error strings in the hot-path, so I've opted to load these at the last minute rather than in static setup/teardown functions.
The result is that you get the same output as `openssl errstr`, rather than list of opaque codes, eg
```
error:068000A8:lib(13)::reason(168)
```
becomes
```
error:068000A8:digital envelope routines:func(2048):invalid fips mode
```
=> Load OpenSSL error strings

src/pal/quote_generation.h, tests/code_update.py, tests/infra/utils.py
We were previously calling `uname -a`, which includes node name, which obviously differs across real networked/containerised nodes.
We could call something that will be common across nodes (`uname -s -r`), but I think this is an unnecessary risk - it _still_ means we may get virtual nodes refusing to join because they are running in different environments, and doesn't actually get us any benefit. This call to `uname` was used so that we could add a shim to modify it without using a custom envvar/additional config value, but we don't actually have a use for modifying it. We test that measurement policy is applied by _removing_ the trusted measurement, rather than starting a node with an alternative measurement. Shipping anything that modifies it (a `uname` bash script shim, or some …
=> Use a hard-coded string for virtual measurement

src/pal/quote_generation.h
When I added virtual attestations, I blew up the memory use in our virtual nodes, because I slurped the entire package to digest it. That's daft - we can digest incrementally (NB: _Most_ reads we are wary of doing incrementally to avoid TOCTOUs, but this is insecure virtual path with no risks).
=> When computing virtual attestation, digest incrementally rather than slurping the entire package into memory

src/node/gov/handlers/service_state.h, tests/js-modules/basic-module-import/app.json, tests/js-modules/modules.py
Resolves #6733.
A sensible use case of `/gov/javascript-app` is to check that the stored app matches the bundle you submitted. As noted in #6433, we can't do a direct equality check on this, because we've recased the response fields to match the Azure API standards. We added a `?case=original` field, which falls back to the macro-generated `to_json` conversion.
However, as #6733 notes this is still imprecise - the generated C++ conversion function omits some fields if they match default values, so doesn't necessarily return every field from the original bundle. We could try explicitly writing every field (in the classic/original case), but would then be potentially returning _more_ fields than were specified in the original bundle, which would still prohibit a direct equality check. …
=> Update behaviour of `?case=original` query to `/service/javascript-app` - return raw contents

CHANGELOG.md, src/node/jwt_key_auto_refresh.h, src/tls/ca.h, tests/jwt_test.py
- [Handle multiple certificates in JWT CA bundle correctly (#6818)](https://github.com/microsoft/CCF/pull/6818)
=> [release/5.x] Cherry pick: Handle multiple certificates in JWT CA bundle correctly (#6818)

src/crypto/openssl/symmetric_key.cpp
This is not required to be set to something, but was check to freeze the existing implementation in #6610 when first migrating to AL3.0 and symcrypt. Now with the internal implementation changes this assertion is no longer true, therefore removed.
UPD. 99% sure this's the cause: https://github.com/openssl/openssl/pull/26658. Seems like error path fix, which also took away zeroing the data-written count.
=> Remove aad_len check on NULL out buffer

src/enclave/session.h, src/enclave/tls_session.h, src/http/http2_session.h, src/http/http_session.h
`HTTPSession` and `HTTP2Session` are identical - they only fork in further derived classes. This PR deduplicates their implementation as `ccf::EncryptedSession` (all that this common layer is really doing is passing incoming data through a `tls_io` object, and then deferring to a virtual `parse` function).
This is purely a refactoring of where code is defined and where the `error_reporter` instance lives, no behavioural changes.
=> Deduplicate HTTPSession implementation

include/ccf/pal/attestation.h, include/ccf/pal/attestation_sgx.h
This PR should add support for checking that a SGX attestation report is valid on SNP and Virtual nodes, using the openenclave::hostverify package.
This should allow an SGX node to join a Virtual or SNP cluster.
=> 5.0.x allow SGX attestation checking on SNP and Virtual

include/ccf/odata_error.h
Enables `std::optional` use of `ccf::ODataError` without unnecessary code duplication as in https://github.com/microsoft/scitt-ccf-ledger/blob/2e315354b26bc81cdb29664a7984f9b8071f680e/app/src/odata_error.h#L12
=> Add `operator==` to `ccf::ODataError`

.github/workflows/ci.yml, .github/workflows/long-test.yml, .github/workflows/release.yml, cmake/preproject.cmake
Removing back-and-forth clang version shuffling in CMake, doesn't seem relevant anymore, hence no need to specify CC= CXX= on Azure Linux, for instance.
=> Select newest clang be default

tests/start_network.py
- [Enable redirection when starting a network (#6732)](https://github.com/microsoft/CCF/pull/6732)
- [Fixed the backup redirection config in the start_network.py (#6755)](https://github.com/microsoft/CCF/pull/6755)
=> [release/5.x] Cherry pick: Enable redirection when starting a network (#6732) | Fixed the backup redirection config in the start_network.py (#6755)

include/ccf/pal/attestation.h, include/ccf/pal/attestation_sev_snp.h
Set v2 as the minimum, rather than the exact required.
=> Support v3 SNP attestations

include/ccf/pal/attestation.h, include/ccf/pal/attestation_sev_snp.h
- [Support v3 SNP attestations (#6841)](https://github.com/microsoft/CCF/pull/6841)
=> [release/5.x] Cherry pick: Support v3 SNP attestations (#6841)

CHANGELOG.md, src/crypto/openssl/public_key.cpp
- [Fix pctx leak with RAII wrapper (#6845)](https://github.com/microsoft/CCF/pull/6845)
=> [release/5.x] Cherry pick: Fix pctx leak with RAII wrapper (#6845)

src/kv/serialised_entry_format.h
While exploring primary-led chunking, I've stared at a lot of adjacent serialisation/flags code.
This is a very minor tweak - rather than declaring a "6 bytes are used" comment above, we reuse the calculated value in both places. We want `SerialisedEntryHeader` to fit in a `uint64_t`, 2 fields are already taking up space, so the maximum value for `size` is constrained to the remaining bits.
=> Minor clarity improvement to KV max entry size header value

CHANGELOG.md, python/src/ccf/ledger.py
- [Correct node membership condition (#6849)](https://github.com/microsoft/CCF/pull/6849)
=> [release/5.x] Cherry pick: Correct node membership condition (#6849)

doc/audit/builtin_maps.rst, doc/build_apps/auth/jwt.rst, doc/schemas/gov/2023-06-01-preview/examples/ServiceState_GetJwkInfo.json, doc/schemas/gov/2024-07-01/examples/ServiceState_GetJwkInfo.json, doc/schemas/gov/2024-07-01/gov.json, doc/schemas/gov_openapi.json, include/ccf/service/tables/jwt.h, src/node/rpc/member_frontend.h, tests/infra/consortium.py
Purge remaining references to (deprecated, long-unused) JWT key filter. This includes removing the vestigial field from some structs and related serialisers, which technically means that if nodes after this change try to interop with very old nodes, they might cause KV serialisation errors. That's unsupported, the `lts_compatibility` test covers exactly which versions are interoperable, and the only thing we need to maintain for _that_ is the field in `set_jwt_issuer` (for when this Python infra is speaking to a constitution which still requires the field).
Resolves #6589.
=> Remove JWT key filter from docs

doc/host_config_schema/cchost_config.json, samples/config/join_config.json, samples/config/minimal_config.json, samples/config/minimal_config_redirects_role.json, samples/config/minimal_config_redirects_static.json, samples/config/recover_config.json, samples/config/start_config.json, src/host/configuration.h, src/host/enclave.h
=> Cleanup SGX stuff in cchost config

src/kv/apply_changes.h
Taking another look at the still-failing tests in #6616, I managed to parse one of the consistent error stacks and I _think_ this is the right fix.
A pseudocode summary of this `apply_changes` function, which is taking a Tx-owned collection of local maybe-modified views over maps and applying them to the local persistent KV _if they're still valid_:
```
bool any_writes = false;
for (change: changes)
{
if (change.has_writes())
{
any_writes = true;
change.map.lock();
}
}
bool ok = true; // Becomes false if any prepare finds conflicts
if (any_writes)
{
for (change: changes)
{
if (!change.prepare()) // Check for conflicts with the current KV state
{
ok = false;
break;
}
}
}
if (ok)
{
for (change: changes)
{
change.commit(); // Apply the writes to the current KV state
}
}
for (change: changes) …
```
=> Fix potential data race: Lock all KV maps during `apply_changes`, even those which are read-only

src/snapshots/fetch.h
Just noticed we have a bunch of spam like this at node startup:
```
[info ] ../src/snapshots/fetch.h:77          | Ignoring invalid-looking HTTP Header ''
[info ] ../src/snapshots/fetch.h:77          | Ignoring invalid-looking HTTP Header ''
[info ] ../src/snapshots/fetch.h:77          | Ignoring invalid-looking HTTP Header ''
```
Looks like the curl callback that gives us headers also gives us the empty newline that terminates headers. This doesn't seem ideal, but whatever - we should ignore it.
=> Ignore empty header line in libcurl callback

src/host/enclave.h
Did too much in #6865, the `type` param is technically not necessary but passed as discussed in https://github.com/microsoft/CCF/pull/6865#discussion_r1975153697
=> Fix doc build on main

src/enclave/main.cpp, src/enclave/ringbuffer_logger.h
Writers should not be shared between threads, so make RingbufferLogger use a `thread_local` Writer.
I don't have the stack, but this was also found by TSAN in #6616.
=> Thread safety: Remove race in RingbufferLogger

.github/workflows/ci-verification.yml, .github/workflows/long-verification.yml
**Some** verification jobs run on **ubuntu-latest**, they **remain untouched** by this PR.
Those **using CCF CI image**, now **migrate to Azure Linux** image.
=> TLA CI on Azure Linux

tests/start_network.py
- [Removed default value for the redirection-kind param (#6872)](https://github.com/microsoft/CCF/pull/6872)
=> [release/5.x] Cherry pick: Removed default value for the redirection-kind param (#6872)

include/ccf/indexing/indexer_interface.h, include/ccf/indexing/strategy.h, src/indexing/indexer.h
Another fix pulled out from #6616.
=> Prevent racey access to indexer state

CHANGELOG.md, CMakeLists.txt, cmake/common.cmake, cmake/crypto.cmake, include/ccf/ds/ccf_exception.h, include/ccf/pal/snp_ioctl6.h, python/pyproject.toml, samples/CMakeLists.txt, src/consensus/aft/raft.h, src/ds/test/map_test.cpp, src/node/channels.h, src/node/rpc/forwarder.h, tests/perf-system/submitter/CMakeLists.txt
Closing the removal of internal LOG_* macros in public headers, following their deprecation in 3.0.
=> Remove direct usage of log in public headers

include/ccf/indexing/indexer_interface.h, include/ccf/indexing/strategy.h, src/indexing/indexer.h
- [Prevent racey access to indexer state (#6886)](https://github.com/microsoft/CCF/pull/6886)
=> [release/5.x] Cherry pick: Prevent racey access to indexer state (#6886)

CMakeLists.txt, src/node/node_state.h, tests/infra/node.py, tests/infra/remote.py, tests/recovery.py
An attempt to address #3755.
Force election mid-recovery, but make sure (!) election finishes when all nodes are still in`ReadingPrivateLedger` state.
> (!) Note. This's important, because if no primary is elected at the moment of reading last private TX, the user frontend will never be opened due to the current recovery design, so this recovery has to be discarded. This PR doesn't test that particular case.
To give election enough time, ledger is populated with many thousands of TXs, which are later verified post-recovery.
=> Test mid-recovery election

src/ds/test/work_beacon.cpp
Partial fix in #6925 missed the assertion on the next line. This adds an explanatory comment. Pulled out of #6926.
=> Fix flaky `work_beacon` test

tests/infra/github.py
Fixes LTS compatibility testing during Azure Linux releases.
=> Do no try to use current commit as an LTS compat testing target

src/node/node_state.h, src/node/secret_broadcast.h, src/service/internal_tables_access.h, src/service/tables/secrets.h
- [Consolidate single execution path for `begin_private_recovery()` (#6912)](https://github.com/microsoft/CCF/pull/6912)
=> [release/5.x] Cherry pick: Consolidate single execution path for `begin_private_recovery()` (#6912)

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGELOG.md, src/node/node_state.h, tests/infra/network.py, tests/partitions_test.py
- [Ensure that end-of-private-recovery service open transaction is written at-most-once (#6926)](https://github.com/microsoft/CCF/pull/6926)
Installs `strace` dependency manually to avoid updating CI images.
**Note! Had to remove `--decode-fds` in `strace` call in the test as it's not supported on Ubuntu 20.04.**
=> [release/5.x] Cherry pick: Ensure that end-of-private-recovery service open transaction is written at-most-once (#6926)

.github/workflows/ci.yml
Following #6348, we can only have a single CI running on `main` at once. I think this is rubbish - we can manually trigger, if something looks flaky I want N runs in parallel, not in series.
Based on the docs [here](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-on-specific-branches), I think this skips `cancel-in-progress` on `main`.
=> Don't cancel in-progress runs on main

include/ccf/pal/snp_ioctl6.h, src/pal/test/snp_ioctl_test.cpp
Should resolve #6956.
Further discussion in that ticket, but in summary our IOCTL call to `SEV_SNP_GUEST_MSG_REPORT` was passing too-small a struct, resulting in memory corruption as the response was written to our stack. Our `SafetyPadding` protection didn't catch this because the additional bytes were all 0s - the IOCTL zero'd both the padding bytes _and_ further data.
This separates the padding (the IOCTL is going to write some large struct that we don't fully parse/specify) from the sentinel/protection bytes (we want to catch if it writes beyond these bytes). The padding is increased to create a 4k struct, matching the kernel definition, and the sentinel bytes now contain some non-0 values.
Additionally, we add a unit test that fetches the attestation, which should now fail if the …
=> Increase IOCTL padding, and introduce non-0 sentinels to confirm padding safety

.github/workflows/ci.yml, .github/workflows/long-test.yml, .github/workflows/release.yml
Turns out the current filter doesn't really work
```
maxtropets@al-vm-test-2 [ ~/workspace/CCF/build ]$ ls -lah workspace/*.ledger/*
ls: cannot access 'workspace/*.ledger/*': No such file or directory
maxtropets@al-vm-test-2 [ ~/workspace/CCF/build ]$ ls -lah workspace/*/*.ledger/*
-rw-rw-r-- 1 maxtropets maxtropets  61K Apr  9 16:38 workspace/app_space_js_e2e_logging_cft_0/0.ledger/ledger_1-2.committed
-rw-rw-r-- 1 maxtropets maxtropets 5.4K Apr  9 16:39 workspace/app_space_js_e2e_logging_cft_0/0.ledger/ledger_3
```
This PR should fix it.
=> Fix uploading ledger files in CI

.github/workflows/long-test.yml
Should be harmless, it's still faster then Debug/ASAN, so comes at no cost
UPD. CI is red because see https://github.com/microsoft/CCF/pull/6979
=> Run long tests in release mode too

python/src/ccf/ledger_viz.py
Fixing a typo introduced in #6974, and missed since this tool has no automated tests.
=> Fix `ledger_viz.py` - remove accidental tuple

tests/infra/github.py
Following #7000, the `lts_compatibility` test has failed with the following error:
```
74:   File "/home/edashton/3.CCF/tests/infra/github.py", line 193, in has_release_for_tag_name
74:     get_package_url_from_tag_name(tag_name),
74:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
74:   File "/home/edashton/3.CCF/tests/infra/github.py", line 168, in get_package_url_from_tag_name
74:     raise ValueError(f"Unsupported tag name: {tag_name} for platform {platform}")
74: ValueError: Unsupported tag name: ccf-5.0.16 for platform snp
1/1 Test #74: lts_compatibility ................***Failed    6.21 sec
```
We'd previously fail one step later but politely - returning a junk 404 URL from this function and a `False` from the one above. Now we catch this `ValueError` one layer above and return …
=> Fix `lts_compatibility`: Handle unfindable packages from old (unsupported) platforms

tests/recovery.py
> Might be a little faster, but mostly for easier debugging. Previously these started multiple networks in sequence, with the same args, meaning that they reused (and mostly overwrote) the same workspace/ directories. This is an easy way to give them unique labels and so unique directories
=> Run the "from_files" recovery tests in separate runners

include/ccf/crypto/key_pair.h
Main is red: https://github.com/microsoft/CCF/actions/runs/15109725288/job/42466245543
because `pkey` changed to `pem` in #7009 and doc string left unchanged.
=> Fix doc job

src/http/curl.h, src/snapshots/fetch.h
Refactor out these the curl bits such that if anything breaks, it does so in this PR rather than the auto-dr one.
=> Refactor out generically useful bit of fetch.h into curl.h

tests/recovery.py
Added in #6920.
I've been monitoring the job for quite a bit, this test has around 80% success rate, when adding around 10 minutes (or more in ASAN).
I don't think it's worth it, it has to be more robust then that. Playing with timeout didn't pay off, it's depends too much on a HW situation and seems to be completely random in CI.
I suggest excluding it from the run for now, created a ticket to revisit it (#7032).
=> Disable election-mid-recovery test

CHANGELOG.md, python/src/ccf/ledger.py, src/snapshots/snapshot_manager.h, tests/e2e_operations.py
#5273 introduced an unnoticed break from our documented behaviour - snapshots were written directly to a `.committed` file (in multiple `fwrite()` calls), rather than being renamed from an intermediate file. This means any consumer of `.committed` snapshots could read invalid files (incomplete, perhaps entirely empty, depending how they interleaved with the `fwrite()` calls and implicit flushing), and could not distinguish these from correct files without attempting to parse the file.
This PR modifies an existing e2e test to reproduce this behaviour - aggressively reading snapshots directly from the node's output directory, as they are being written. It also includes the fix of restoring the intermediate file - CCF will again (as documented) write to a temporary file `snapshot_X-Y` file, …
=> Fix empty committed snapshots: Restore behaviour of writing to temporary uncommitted file and renaming

CHANGELOG.md, python/src/ccf/ledger.py, src/host/snapshots.h, tests/e2e_operations.py
- [Fix empty committed snapshots: Restore behaviour of writing to temporary uncommitted file and renaming (#7029)](https://github.com/microsoft/CCF/pull/7029)
=> [release/5.x] Cherry pick: Fix empty committed snapshots: Restore behaviour of writing to temporary uncommitted file and renaming (#7029)

src/host/test/ledger.cpp, src/snapshots/snapshot_manager.h
Following #7029 (and resulting perf runs + manual investigation in #7033), we think this `fsync()` cost is too high to leave inline in the current (blocking) message handler. This PR moves it to the UV threadpool via `uv_queue_work`, where we will `fsync()` the completed snapshot, then rename the file to `.committed`.
There's a slight hack to make this work in the `ledger_test` unit test - rather than linking uv and spinning up a parallel thread to run the UV main thread, we just add a `#define` branch to call these functions inline (equivalent to the previous behaviour). As we transition more of the IO to use UV primitives (#3124) we'll likely remove this and run a proper UV loop to service these tests.
=> Do snapshot `fsync` on UV threadpool

src/host/snapshots.h, src/host/test/ledger.cpp
- [Do snapshot `fsync` on UV threadpool (#7035)](https://github.com/microsoft/CCF/pull/7035)
=> [release/5.x] Cherry pick: Do snapshot `fsync` on UV threadpool (#7035)

python/pyproject.toml, scripts/extract-release-notes.py
Also tweak for a nicer error:
```
First version in CHANGELOG must match version in pyproject.toml: 6.0.4
vs
First version in CHANGELOG (6.0.5) must match version in pyproject.toml (6.0.4)
```
=> Bump `pyproject.toml` version

include/ccf/ds/nonstd.h, include/ccf/pal/snp_ioctl5.h, include/ccf/pal/snp_ioctl6.h
This PR uses a unique_ptr to ensure that the file descriptor cannot leak when we do the ioctls to /dev/guest-sev.
=> Ensure fds are closed after exiting ioctl

CMakeLists.txt, python/src/ccf/ledger.py, tests/e2e_operations.py, tests/schema.py
Includes a small fix to `ledger.py` to support early (1.x) ledger files that do not include a cert in their signatures.
=> Add test to validate historical ledgers and snapshots

doc/build_apps/migration_5_x_to_6_0.rst
Closing #7002.
Following discussion there, we've confirmed that interop between 5.latest and 6.0.2 is possible, so the docs now recommend that users skip 6.0.0 and 6.0.1.
=> Update 5-to-6 migration docs to recommend going directly to 6.0.2

doc/index.rst, doc/reproduce_app/index.rst
This PR updates the documentation to include how to reproduce and verify CCF packages.
Depends on #7069
=> Add reproducible build documentation

doc/reproduce_app/index.rst, reproduce/reproduce_rpm.sh, reproduce/start_container_and_reproduce_rpm.sh
This PR adds a temporary fix for an embedded file path mismatch between the GitHub Actions produced package and the locally produced package. It also fixes file bind syntax in docker.
=>  Add path prefix to reproduce script

src/endpoints/authentication/jwt_auth.cpp
Resolves #7084.
Making sure misleading error messages don't leak through when auth succeeds. Also adding a consistent pattern of `error_reason = ...; continue;`, to try and prevent future code flow bugs.
=> Clear error messages when JWT auth succeeds

CMakeLists.txt, reproduce/start_container_and_reproduce_rpm.sh
Maps absolute path to project dir name to avoid embedding local paths in build output
=> Make embedded path reproducible

samples/apps/logging/logging.cpp, samples/apps/programmability/programmability.cpp, src/endpoints/json_handler.cpp
The non-controversial bit of #7082 - use a common helper function rather than this multi-stage call everywhere. Then _if_ we ever add a way to request pretty-printed responses, it should be uniformly handled.
=> Use `set_response_json` rather than re-implementing

.github/workflows/ci.yml
Since large SKUs are not readily available for CI on Genoa, run minimal tests that cover architecture-specific differences to avoid slow and flaky test runs.
=> Restrict tests on Genoa

scripts/notice-check.py
Previously:
```
notice-check.py:64: SyntaxWarning: invalid escape sequence '\{'
cmd = f"git ls-files | grep -E -v \"{'|'.join('^' + prefix for prefix in EXCLUDED)}\" | grep -e '\{suffix}$'"
```
=> Fix escaping warning in notice script

src/consensus/aft/test/driver.cpp, src/consensus/aft/test/main.cpp, src/ds/thread_messaging.h, src/enclave/main.cpp, src/indexing/test/indexing.cpp, src/node/rpc/test/frontend_test.cpp, src/node/test/channels.cpp, src/node/test/historical_queries.cpp, src/node/test/history.cpp, src/node/test/history_bench.cpp, src/node/test/snapshot.cpp, src/node/test/snapshotter.cpp
Inspired by discussion from #7118 about removing unnecessary initialisers, and noticed in passing.
=> Remove unnecessarily public + repeated singleton initialisation

.github/workflows/release.yml
Fix for https://github.com/microsoft/CCF/actions/runs/16463458106/job/46537926845, we want to download "pkg" and "pkg-devel", and so we need "pkg*", not "pkg-*".
=> Fix download action

CMakeLists.txt
Seems like [#7106](https://github.com/microsoft/CCF/pull/7106/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR858) accidentally removed e2e tests in DEBUG mode.
We have not been running LONG_TESTS + hardening (libc) since then 😿 
In belief that the intention was to only avoid running picobench for libc, here's the change to resurrect missing tests.
=> Bring back e2e debug tests

include/ccf/threading/thread_ids.h, src/enclave/thread_local.cpp, src/host/run.cpp
Closes #7165 
The issue was that a host side `ledger.h` thread logged between when the thread counters were reset and the first enclave thread was created giving it thread id 1 rather than 0, causing the enclave side task system to crash.
This PR instead explicitly passes a thread id into each enclave thread, which then updates the thread_local storage as soon as it starts to reflect this.
The result is that if we want to change the way the task system interacts with thread ids, at least for enclave threads, this will now be deterministic and relatively simple to update.
=> Use a deterministic thread numbering scheme

cmake/ccf_app.cmake
_There's no ~smoke~ new/delete without ~fire~ malloc/free, they say._
Came out of https://github.com/microsoft/CCF/issues/7172.
snmalloc's cmake:
```
set(MALLOC src/snmalloc/override/malloc.cc)
set(NEW src/snmalloc/override/new.cc)
set(MEMCPY src/snmalloc/override/memcpy.cc)
set(ALLOC ${MALLOC} ${NEW})
set(ALL ${ALLOC} ${MEMCPY})
if (SNMALLOC_STATIC_LIBRARY)
compile(snmallocshim-static STATIC ${ALLOC})
target_compile_definitions(snmallocshim-static PRIVATE
SNMALLOC_STATIC_LIBRARY_PREFIX=${SNMALLOC_STATIC_LIBRARY_PREFIX})
endif ()
compile(snmalloc-new-override STATIC ${NEW})
```
Confirmed by @mjp41, linking `snmallocshim-static` if just fine.
Will check bencher after merge to make sure no regression happened.
=> Remove unnecessary double-linking

.github/workflows/long-test.yml, CMakeLists.txt
Various failures in the Long Tests job seemingly stemming from the switch to broader use of `snmalloc`. This is a broad hammer fix - forbid both options being set at once.
=> Fix long tests: Forbid SAN or TSAN alongside snmalloc

CHANGELOG.md, js/ccf-app/package.json, js/ccf-app/src/converters.ts, js/ccf-app/src/polyfill.ts, js/ccf-app/src/utils.ts, js/ccf-app/test/polyfill.test.ts, js/ccf-app/test/utils.test.ts, tests/js-interpreter-reuse/package.json, tests/npm-app/package.json, tests/npm-app/src/endpoints/crypto.ts, tests/npm-app/src/endpoints/snp_attestation.ts
Typescript 5.9 made `ArrayBufferLike = ArrayBuffer | SharedArrayBuffer`, which causes typescript to output many errors as our code has previously assumed that the input is always an ArrayBuffer.
This PR removes the pins, and by adding `toArrayBuffer(b : ArrayBufferLike | Uint8Array | Buffer) : ArrayBuffer` and `toUint8ArrayBuffer(b : Uint8Array<ArrayBufferLike>) : Uint8Array<ArrayBuffer>` to a `utils.ts` module in ccf-app, fixes the corresponding errors with typescript 5.9.
These in theory could live in maybe `converters.ts`, however that would add an import on `converters.ts` to both `polyfill.ts` and `crypto.ts` which seems inadvisable, instead of a direct import of just `utils.ts`.
=> Compatibility with TypeScript 5.9

js/ccf-app/package.json, js/ccf-app/src/converters.ts, js/ccf-app/src/polyfill.ts, js/ccf-app/src/utils.ts, js/ccf-app/test/polyfill.test.ts, js/ccf-app/test/utils.test.ts, tests/js-interpreter-reuse/package.json, tests/npm-app/package.json, tests/npm-app/src/endpoints/crypto.ts, tests/npm-app/src/endpoints/snp_attestation.ts
Backports the following commits to `release/6.x`:
- [Compatibility with TypeScript 5.9 (#7171)](https://github.com/microsoft/CCF/pull/7171)
=> [release/6.x] Cherry pick: Compatibility with TypeScript 5.9 (#7171)

.github/workflows/release.yml
`7.0.0-dev1` contains no non-devel `.rpm`, because we created build artifacts called `pkg` and `pkg-devel`, and then downloaded `pkg-*`. That pattern should now be `pkg*`.
Same as #7129, broken since we removed `COMPILE_TARGET` from builds.
=> Upload non-devel RPM in releases

src/kv/store.h
Resolves a part of #7201.
Read https://github.com/microsoft/CCF/issues/7201#issuecomment-3210630730. Results:
```
Running tests 10 times...
Command: ./tests.sh -VV -L partitions -C partitions
----------------------------------------
Run 1/10...
-> out1.txt does not contain ThreadSanitizer
Run 2/10...
-> out2.txt does not contain ThreadSanitizer
Run 3/10...
-> out3.txt does not contain ThreadSanitizer
Run 4/10...
-> out4.txt does not contain ThreadSanitizer
Run 5/10...
-> out5.txt does not contain ThreadSanitizer
Run 6/10...
-> out6.txt does not contain ThreadSanitizer
Run 7/10...
-> out7.txt does not contain ThreadSanitizer
Run 8/10...
-> out8.txt does not contain ThreadSanitizer
Run 9/10...
-> out9.txt does not contain ThreadSanitizer
Run 10/10...
-> out10.txt does not contain …
```
=> Fix commit/rollback race on last_replicated

tests/governance_js.py, tests/infra/clients.py
Small spin-off from #7133: make replay detection test more robust/general by replaying the exact request, rather than re-sign and depend on the signing algorithm being deterministic.
=> Make replay detection test more robust

include/ccf/ds/logger.h
Gradually working up the stack of simplifications from remove ringbuffer logging path.
=> Remove unused LogLine constructor path

python/tests/test_cose_sign.py
Flagged in https://github.com/microsoft/CCF/security/code-scanning/970 - this is just test cert duration, 30 days is plenty.
=> Address CodeQL SM04546 comment

.clang-tidy, samples/apps/programmability/programmability.cpp, src/crypto/openssl/hash.cpp, src/crypto/openssl/key_pair.cpp, src/crypto/sharing.cpp, src/enclave/main.cpp, src/enclave/thread_local.cpp, src/js/core/context.cpp, src/js/extensions/snp_attestation.cpp, src/node/historical_queries_utils.cpp, src/node/uvm_endorsements.cpp
Previously, there were a number of:
```
main.cpp:16:24: error: variable 'create_lock' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace,-warnings-as-errors]
16 | static ccf::pal::Mutex create_lock;
```
=> One less clang-tidy exception

CHANGELOG.md, python/pyproject.toml, src/node/node_state.h
=> Log initial node attestation (#7256)

src/crypto/openssl/verifier.cpp, src/crypto/test/crypto.cpp, tests/npm_tests.py
Replacement for #7236 
We should validate that all trusted certs are CAs and therefore can endorse the certificate we are testing.
=> CA should be set in all trusted certs

tests/requirements.txt
Dependency fun - a recent release of Python cryptography is not compatible with recent `python-cwt`, so we installed cwt @ 1.something and got broken imports on all of our test runs. We need recent `python-cwt`, so add a minimum version here and accept whatever `cryptography` _it_ pulls in.
=> Require a recent version of Python CWT

python/src/ccf/receipt.py, tests/e2e_logging.py, tests/recovery.py, tests/requirements.txt
No longer needed - `cryptography` can do the same.
~~I believe I've extended `receipt.check_endorsements` to do the equivalent checks via `cryptography`. Please check [the docs](https://cryptography.io/en/latest/x509/verification/) and see if there's anything you'd add/remove.~~
~~If this works, it should be preferable to #7296.~~
See discussion in comments for more accurate description. A new `receipt.check_cert_chain` function does roughly what PyOpenSSL was doing.
=> Remove `pyopenssl`
